### ISSUE TITLE
Using method references to constructors can cause false positive: Unsafe null type conversion (type annotations)

### ISSUE THREAD

**Issue by krallus** [eclipse-jdt/eclipse.jdt.core#1009]
### Using method references to constructors can cause false positive: Unsafe null type conversion (type annotations)

**Environment**
Eclipse IDE for Enterprise Java and Web Developers
Version: 2023-03 (4.27.0)
Build id: 20230309-1520

OS: Linux Mint 21.1 Cinnamon

Project is set to compile using Java 1.8, although I'm not sure it matters.

**Issue**
Just as the title says.  Most easily demonstrated in code (my apologies that I have not taken the time to come up with an example more basic than one that uses Stream Collectors).

```java
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.jdt.annotation.NonNull;

public class UnsafeNullTypeConversionFalsePositive {

	public static void main(final String[] args) {
		final List<@NonNull StringBuffer> someList = new ArrayList<>();
		List<@NonNull String> results;

		results = someList.stream().map(String::new).collect(Collectors.toList());

		// In the above, "Collectors.toList" is flagged with:

		/*
		 * Unsafe null type conversion (type annotations): The value of type '@NonNull Collector<@NonNull
		 * String,capture#of ?,@NonNull List<@NonNull String>>' is made accessible using the
		 * less-annotated type '@NonNull Collector<? super String,@NonNull Object,@NonNull List<@NonNull
		 * String>>'
		 */

		// However, the following two lines are both warning free, one that uses a lambda instead
		// of a method reference for the constructor in the map method, and the second where the
		// return value of the map method is given via an explicit generic parameter.

		results = someList.stream().map(buff -> new String(buff)).collect(Collectors.toList());
		results = someList.stream().<@NonNull String>map(String::new).collect(Collectors.toList());
	}
}
```

Note that this warning is generated when the following Java compiler warning is enabled: **Unsafe conversion of annotated parameterized type to a less-annotated type**

**Comment by stephan-herrmann** [comment]
Yes, when annotation based null analysis is enabled, type inference should do a better job in also inferring (non-)nullness. I cannot promise "perfect" inference in this regard, but I'll give it a try.
