### ISSUE TITLE
SourceField.isRecordComponent() returns false for record component

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#1035]
Seen with the fix for https://github.com/eclipse-jdt/eclipse.jdt.ui/issue/571, https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/572.

To reproduce, use that fix in JDT UI. Create 2 source files:

```
public record Car(int wheels) {}
```
```
public class Foo {
    void foo(Car c) {
        var wheels = c.wheels();
    }
}
```

Select `wheels` in `Foo.java`, compute call hierarchy, observe that the code added for https://github.com/eclipse-jdt/eclipse.jdt.ui/issue/571 evaluates `SourceField.isRecordComponent()` to `false`, while in `CallerMethodWrapper.getAccurateSearchScope()`. So the next block (that checks if the parent type is a record) is required to ensure a correct call hierarchy.

Selecting `wheels` in `Car.java` doesn't run into this problem, `isRecordCompoent()` returns the expected `true`.

The member that returns false for `isRecordComponent()` is of type `SourceField`. The member that returns the expected true is of an anonymous type and is created here: `CompilationUnitStructureRequestor.createRecordComponent()`

**Comment by iloveeclipse** [comment]
This seem to be regression from [bug 565211](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565211) / commit 7f0b7a275edf8d5988fd058f6d1144e100d714e0 that changed code added for [bug 562637](https://bugs.eclipse.org/bugs/show_bug.cgi?id=562637) / commit aa930daf6545d757b7e55d1cfef67c6ba4fa3e4f.

The 7f0b7a275edf8d5988fd058f6d1144e100d714e0 removed `notifySourceElementRequestor(RecordComponent)` that called `requestor.exitRecordComponent` where `SourceFieldElementInfo.isRecordComponent = true;` was set, and the code uses now only `notifySourceElementRequestor(FieldDeclaration)`. In this one, the `SourceFieldElementInfo.isRecordComponent` is not changed.

I will push a fix in a moment.

**Comment by iloveeclipse** [comment]
Note: same issue happens also with BinaryField elements, see #1059 tests.
