### ISSUE TITLE
AIOOBE when compiling method reference expression

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1054]
Compiling the following code, ECJ crashes with an AIOBE exception:

```
import java.lang.invoke.MethodHandle;
interface FI {
    Object invokeMethodReference(String s, char c1, char c2) throws Throwable;
}
public class X {
    private static MethodHandle createMethodHandle() {
    	return null;
    }
    public static void run() throws Throwable {
        MethodHandle ms = createMethodHandle(); 
        FI fi = ms::invoke;
        fi.invokeMethodReference("", (char)0, (char)0);
    }
}
```

The exception is at this line:
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.isDirectCodeGenPossible(ReferenceExpression.java:311)
	at org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.shouldGenerateImplicitLambda(ReferenceExpression.java:284)
	at org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.generateCode(ReferenceExpression.java:332)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.generateCode(LocalDeclaration.java:162)

This code was recently added via #1041

**Comment by srikanth-sankaran** [comment]
This is not a regression per se: Just that the fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=577466 made via PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1041 makes it more likely for the preexisting defect to surface itself.

To see this, backout the changed introduced by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1041 and then compile this program:

```
import java.lang.invoke.MethodHandle;
interface FI {
    <T extends Object & Runnable> Object invokeMethodReference(Object o, T t2) throws Throwable;
}
public class X {
    private static MethodHandle createMethodHandle() {
    	return null;
    }
    public static void run() throws Throwable {
        MethodHandle ms = createMethodHandle(); 
        FI fi = ms::invoke;
        fi.invokeMethodReference(null, ()-> {}); 
    }
}  
```

You get a:

```
Internal compiler error: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 at 
org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.isDirectCodeGenPossible(ReferenceExpression.java:311)
```
