### ISSUE TITLE
text search should find unicode literals

### ISSUE THREAD

**Issue by weberjn** [eclipse-jdt/eclipse.jdt.core#1055]
When searching for prüfen File search should find
new JButton("pr\u00FCfen");

**Comment by iloveeclipse** [comment]
This is not directly possible, but with the regex search for `G(ü|\\u00fc)nter` you can do that:

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/67fd296c-c20b-47fb-88c8-21f1732342e2)

```
String Guenter1 = "G\u00fcnter";
String Guenter2 = "Günter";
```

Note, there are multiple ways to encode non-ascii characters (for example, in html you would also expect `G&uuml;nter` to match here) and "basic" search doesn't support them all - here regex to help.

This tracker is for JDT related bugs, text search isn't handled by JDT.
If you want the feature to be implemented, please open issue at https://github.com/eclipse-platform/eclipse.platform.text/issues.
