### ISSUE TITLE
NPE when inspecting scrapbook expression that uses Java 8 features

### ISSUE THREAD

**Issue by twwwt** [eclipse-jdt/eclipse.jdt.core#1060]
From time to time, I'm using Eclipse's scrapbook pages (*.jpage). Using **Eclipse 2023-03 (4.27.0)**, I tried to *inspect* the following expression:

```java
return java.time.format.DateTimeFormatter
	.ofPattern("yyyyMMddHHmmss.SSS000")
	.format(java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy HHmmss").parse("30.03.2021 112430", java.time.LocalDateTime::from));
```

This results in the following error:

```
Internal compiler error: java.lang.NullPointerException: Cannot read field "parameters" because "this.descriptor" is null at org.eclipse.jdt.internal.compiler.ast.ReferenceExpression.analyseCode(ReferenceExpression.java:516)
```

Note, this is an older issue that has been reported originally in March 2021. I have transferred it over from https://bugs.eclipse.org/bugs/show_bug.cgi?id=572449 because I think it should still be fixed.

**Comment by srikanth-sankaran** [comment]
Reproduced on master. I will work on this.
