### ISSUE TITLE
Regression in code generation for try with resources with the fix for Issue # 934

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#1063]
Reported by @iloveeclipse in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/934 

The fix for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/934  causes several Advantest internal tests to fail.

A simple test case here:

```
import java.io.Closeable;
import java.io.IOException;

public class X {
	public static void main(String[] args) throws IOException {
		try (DummyClosable closable = new DummyClosable()) {
			throw new IOException("OMG!!!");
		} catch (IOException e) {
			throw e;
		}
	}

	static class DummyClosable implements Closeable {
		@Override
		public void close() throws IOException {
			System.out.println("Closed!");
		}
	}
}
```

Executed with ecj from master it throws IllegalArgumentException:

```
Closed!
Exception in thread "main" java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1072)
	at X.main(X.java:8)
Caused by: java.io.IOException: OMG!!!
	at X.main(X.java:7)
```

With commit https://github.com/eclipse-jdt/eclipse.jdt.core/commit/2bac9e436e1bbd143006f0d0b062655853565bc2 reverted, it prints what is expected to print:

```
Closed!
Exception in thread "main" java.io.IOException: OMG!!!
	at X.main(X.java:7)
```

**Comment by srikanth-sankaran** [comment]
Sorry about that! I will for the time being use this issue to revert the change made in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/934 and leave that ticket open for a refix in due course.

**Comment by iloveeclipse** [comment]
OK, thanks.
