### ISSUE TITLE
ECJ accepts invalid Java code `instanceof final Type`

### ISSUE THREAD

**Issue by SimplyDanny** [eclipse-jdt/eclipse.jdt.core#1076]
The class `Test.java` with the content

```java
package org.eclipse.test;

class Test {
    void check() {
        Number n = Integer.valueOf(1);
        if (n instanceof final Integer) {}
    }
}
```

can be compiled with the Eclipse Compiler (version 4.27), but `javac` errors with

```
Test.java:6: error: modifier final not allowed here
        if (n instanceof final Integer) {}
                               ^
1 error
```

The problem is the modifier in front of the type in the `instanceof` comparison which is just meaningless and (more importantly) not allowed at this location by the specification.

I wonder if there is a specific reason why ECJ allows this kind of syntax.

We are currently facing issues with Checkstyle in Eclipse (see [reported issue](https://github.com/checkstyle/checkstyle/issues/13071)) which behaves according to `javac` and just breaks.

**Comment by srikanth-sankaran** [comment]
A first pass through JLS 20 14.30.1 Kinds of Patterns which spells out the grammar and rules for type patterns does not seem to rule out final modifiers. 

Also 4.12.4 final Variables has this passage:

```
...
Certain variables that are not declared final are instead considered effectively
final:
• A local variable declared by a statement and whose declarator has an initializer
(§14.4), or a local variable declared by a pattern (§14.30.1), is effectively final
if all of the following are true:
– It is not declared final.
...
```

**Comment by srikanth-sankaran** [comment]
So in a first glance, it would appear ECJ is right in accepting final modifier there.

**Comment by srikanth-sankaran** [comment]
You are most welcome 🙏
