### ISSUE TITLE
Add name recommendation function for renaming

### ISSUE THREAD

**Issue by DongChunhao** [eclipse-jdt/eclipse.jdt.core#1083]
While using Eclipse, I noticed that there is no recommended algorithm for renaming fields. However, recommending a more suitable name can greatly improve a programmer's development efficiency. Therefore, I hope that Eclipse can provide this feature in future versions.
![1684806618140](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/77560508/6156a155-e750-4634-a524-2fbd1be327f5)

**Comment by mpalat** [comment]
I don't see bandwidth for anyone working on this - if you are interested please reopen and submit a patch. else won;tfix for now
