### ISSUE TITLE
Null analysis break compilation

### ISSUE THREAD

**Issue by cdietrich** [eclipse-jdt/eclipse.jdt.core#1093]
Given the sample code in https://github.com/cdietrich/jdt-nullanalysis-compiler-bug

when in `/b/.settings/org.eclipse.jdt.core.prefs` null analysis is enabled `org.eclipse.jdt.core.compiler.annotation.nullanalysis=enabled`
then compile errors are shown on the `MyDslValidator` class

![Screenshot 2023-05-26 061207](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/238736/5cc3a313-0220-4e79-8f91-c7302f71f1ec)
![Screenshot 2023-05-26 061154](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/238736/de0576b6-597e-48fb-936a-b3f8148b7b61)

The problems are not shown in problems view, but also appear in the tycho build

(tested with Eclipse 2023-03 DSL package, Eclipse 2023-06 DSL package, Tycho 3.0.4)

**Comment by iloveeclipse** [comment]
@cdietrich : please try latest SDK nightly, this should have been fixed recently. 
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1007

**Comment by cdietrich** [comment]
i can confirm the problem is not visible in 

```
Version: 2023-06 (4.28)
Build id: I20230525-0350
```
