### ISSUE TITLE
Content assist does not propose overrides in records

### ISSUE THREAD

**Issue by robertvazan** [eclipse-jdt/eclipse.jdt.core#1095]
I have the following interface:

```java
public interface BaseInterface {
    void implementMe();
}
```

Content assist in implementing record does not offer implementation of the `implementMe()` method:

![Screenshot from 2023-05-26 08-09-40](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/3514517/eb205fc5-6012-49e5-839d-de04a0f974d1)

Whereas in classes it works just fine:

![Screenshot from 2023-05-26 08-09-14](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/3514517/687b0327-3e76-4577-bd1f-6386f525f192)

I am observing the above behavior in Eclipse 2023-03. In 2022-12, completion in records works better:

![Screenshot from 2023-05-26 08-33-45](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/3514517/3608ade4-9910-4941-9303-cf1699ad45d1)

But as you can see, even in 2022-12, content assist fails to propose overrides for equals, hashCode, and toString.

**Comment by robertvazan** [comment]
This regression is still reproducible in Eclipse 2023-09. It's an upgrade blocker for me, because I have a mountain of records implementing interfaces.

**Comment by robertvazan** [comment]
Still reproducible in 2023-12.

**Comment by srikanth-sankaran** [comment]
Originates as a side effect of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/667

**Comment by srikanth-sankaran** [comment]
@robertvazan - Thanks for the report. Fix merged into master. Thanks for confirming with the next integration build or milestone build.

**Comment by robertvazan** [comment]
Thanks. This finally works in Eclipse 2024-03.
