### ISSUE TITLE
[21] JEP 446: Scoped Values (Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1113]
Ref: https://openjdk.org/jeps/446
Summary
Introduce scoped values, which enable the sharing of immutable data within and across threads. They are preferred to thread-local variables, especially when using large numbers of virtual threads. This is a [preview API](https://openjdk.org/jeps/12).

**Comment by mpalat** [comment]
no action required from language pov

**Comment by hohwille** [comment]
I disagree that nothing needs to be done.
I have enabled language level 21 and preview-features:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1923119/b4c11536-a8bb-4729-bc2c-f467eb920e24)
However, usage of `ScopedValue` is not possible in Eclipse:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1923119/16161b52-8911-4d7d-9765-44c18d34ebf3)

**Comment by akurtakov** [comment]
Have you configured the JRE in Eclipse to be Java 21? The ScopedValue class itself is added in Java 21 so this is a prereq.

**Comment by hohwille** [comment]
> Have you configured the JRE in Eclipse to be Java 21? The ScopedValue class itself is added in Java 21 so this is a prereq.

Sure:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1923119/8287a5f7-3952-4f24-aec0-bfffbc3b59dc)

**Comment by hohwille** [comment]
> Have you configured the JRE in Eclipse to be Java 21? The ScopedValue class itself is added in Java 21 so this is a prereq.

If you mean the default in "Installed JREs" also yes - how could I have set the "Compiler compliance level" to 21 as you can see in my earlier screenshot. Also all projects are using the default JRE. There is not other Java JDK/JRE involved at all.
