### ISSUE TITLE
[17] compiler.ast.CaseStatement.ResolvedCase.intValue not initialized for Strings

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1126]
@jarthana 
The return value of ` c.stringValue().hashCode();` is not used. Was it meant to be assigned to this.intValue ?

https://github.com/eclipse-jdt/eclipse.jdt.core/blame/28cc628fdc35aef58a2321cf603f7ccc63e0ee56/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/CaseStatement.java#LL207C3-L207C31

**Comment by jarthana** [comment]
At a glance, your observation looks to be correct. Let me take a closer look soon.

**Comment by jarthana** [comment]
OK, I see that I meant to capture that intValue but didn't. The reason it works is because, down the line, in SwitchStatement (line 981), we do a String comparison anyway instead of intValue().

					`return c2.stringValue().equals(con.stringValue());`

I think it makes sense to avoid the String comparison and compare the intValue() and if we do, then tests will fail.

And good catch. I will shortly propose a fix.

**Comment by iloveeclipse** [comment]
> And good catch. I will shortly propose a fix.

Jay, I see a commit but don't see a PR. Missed to create one?

**Comment by jarthana** [comment]
> > And good catch. I will shortly propose a fix.
> 
> Jay, I see a commit but don't see a PR. Missed to create one?

It's already here - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1128

**Comment by iloveeclipse** [comment]
> It's already here - #1128

Jay, for github automation / better traceability it is needed to refer to the issue in the commit message with the keyword `Fixes` following by the issue hash or (better) full issue url, like:
```
[17] compiler.ast.CaseStatement.ResolvedCase.intValue not initialized for Strings


Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1126
```

This way 
- the PR will be linked to issue automatically
- if PR is merged, issue will be automatically fixed
- From the Git history in IDE you can directly jump to the issue

**Comment by jarthana** [comment]
> > It's already here - #1128
> 
> Jay, for github automation / better traceability it is needed to refer to the issue in the commit message with the keyword `Fixes` following by the issue hash or (better) full issue url, like:
> 
> ```
> [17] compiler.ast.CaseStatement.ResolvedCase.intValue not initialized for Strings
> 
> 
> Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1126
> ```
> 
> This way
> 
>     * the PR will be linked to issue automatically
> 
>     * if PR is merged, issue will be automatically fixed
> 
>     * From the Git history in IDE you can directly jump to the issue

Ah, that explains why I didn't see the automatic linking. I thought just using them on the title was enough. Thanks for the tip, it helps.
