### ISSUE TITLE
Null constraint mismatch Regression in 4.28:

### ISSUE THREAD

**Issue by ewillink** [eclipse-jdt/eclipse.jdt.core#1152]
The following code compiles fine in 4.27

`	package bug;
	
	import org.eclipse.jdt.annotation.NonNull;
	
	public class NonNullBug
	{
		interface Interface<@NonNull T>
		{
		}
	
		class Class<T> implements Interface<@NonNull T> // 4.28 Null constraint mismatch: The type 'T' is not a valid substitute for the type parameter '@NonNull T'
		{
		}
	}
`

but, as commented, reports a @NonNull mismatch in 4.28.

**Comment by iloveeclipse** [comment]
I can reproduce on master. Here simple project to play with: 
[issue_1152_project.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/11803198/issue_1152_project.zip)

**Comment by iloveeclipse** [comment]
@stephan-herrmann : do you want to look at this may be?
