### ISSUE TITLE
Version 3.34.0 built against JDK 17 and throws java.lang.IllegalArgumentException: Unsupported class file major version 61

### ISSUE THREAD

**Issue by alex-korobko** [eclipse-jdt/eclipse.jdt.core#1153]
Guys, 

Since version 3.34.0 switched to JDK 17 any project that is still on JDK 11 or earlier that uses transitive dependencies throws an error `java.lang.IllegalArgumentException: Unsupported class file major version 61`
Maybe it would be better to increment the major version for such a change, like, starting with 4.*? 
Workarounds:
Users to define explicitly lib version [3.33.0](https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core/3.33.0) as the latest which still on JDK 11

**Comment by ascopes** [comment]
Can confirm this has broken my builds as well, unfortunately.

**Comment by Ulchie** [comment]
This also affects us. In our case, it broke a benchmark that uses a lombok version that doesn't support Java 17.

**Comment by codersinthestorm** [comment]
This also broke one of our Java 11 specific builds, and we were using version 3.31.0. Somehow that too has been compiled against 17. Thanks @alex-korobko, 3.33.0 works still, for now.

**Comment by iloveeclipse** [comment]
Anyone who needs latest Java versions support in JDT please move to Java 17 runtime. If you can't, stay at Java 11 and old compiler versions. Major version bump is not done, as we don't do this if moving to other Java runtimes.

There is nothing to fix here, closing.
