### ISSUE TITLE
APIDocumentationTests#testTestDefaultCompliance() fails with tycho 3.0.0

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#12]
See https://github.com/eclipse/tycho/issues/879#issuecomment-1095446252

Additionally to OOM errors (they disappear after bumping max heap to 2 GB), there is one test that is now **always** failing with tycho 3.0.0: `org.eclipse.jdt.core.tests.dom.APIDocumentationTests#testTestDefaultCompliance()`
```
junit.framework.ComparisonFailure: 
Tests should run at default compliance 1.8.
----------- Expected ------------
1.8
------------ but was ------------
1.4
--------- Difference is ----------
 expected:<1.[8]> but was:<1.[4]>
```

I haven't had time to analyze this failure yet.

**Comment by iloveeclipse** [comment]
@laeubi: This code seem to be broken now: 
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/5d6c0fab0f6f7c256117a677f1c5751ba9d1d86c/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModelManager.java#L2202

it uses
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/5d6c0fab0f6f7c256117a677f1c5751ba9d1d86c/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModelManager.java#L3285

and it is the only code used in the test:
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/7eeb9b4342d4d83f3a5a1d078a4e4dff0ab83bb2/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/APIDocumentationTests.java#L309

So looks like something with Eclipse preferences init is broken.

**Comment by iloveeclipse** [comment]
Strike that, I've messed up the pom xml. Only good there is no validation for stupid user input in maven / tycho.

**Comment by iloveeclipse** [comment]
I naively assumed that "argline" in the configuration allows to have *many* elements (many lines) but obviously only the last one was taken. That was very surprising, I would expect it would stop immediately.

**Comment by laeubi** [comment]
You mean https://www.eclipse.org/tycho/sitedocs/tycho-surefire-plugin/test-mojo.html#argLine ? I don't see a compelling reason not supporting many lines so if thats an issue, feel free to open a ticket at tycho so we can simply squash everything into one long line.
