### ISSUE TITLE
CombinedBinaryExpression.buildStringForConcatation() produces unexpected bytecode

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1201]
We see 3 new fails on jenkins (and locally), but not in SDK build.
I couldn't find how to "fix" the tests, reverting jdt.core back to I20230623-1800 does not help.

[org.eclipse.jdt.core.tests.model.CompletionTests_1_5.test482775](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-1200/1/testReport/junit/org.eclipse.jdt.core.tests.model/CompletionTests_1_5/test482775/)
[org.eclipse.jdt.core.tests.model.CompletionTests18.testBug473654](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-1200/1/testReport/junit/org.eclipse.jdt.core.tests.model/CompletionTests18/testBug473654/)
[org.eclipse.jdt.core.tests.model.CompletionTests18.testBug537679](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-1200/1/testReport/junit/org.eclipse.jdt.core.tests.model/CompletionTests18/testBug537679/)

**Comment by iloveeclipse** [comment]
OK, after we built SDK with latest ecj version, we see fails on SDK build too.
So this is direct side effect of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1139

See
- https://download.eclipse.org/eclipse/downloads/drops4/I20230630-1800/testResults.php
- https://download.eclipse.org/eclipse/downloads/drops4/I20230630-1800/testresults/html/org.eclipse.jdt.core.tests.model_ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html

**Comment by iloveeclipse** [comment]
Yep. One can grab the SDK build from https://download.eclipse.org/eclipse/downloads/drops4/I20230629-0130/ and the tests will be green if executed locally, on same (latest) commit on master.

Starting with the build https://download.eclipse.org/eclipse/downloads/drops4/I20230629-1200/ (where the https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1139 was merged), tests fail in the IDE.

What I don't understand is how code completion tests are affected by the https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1139 change. I would rather expect they should be affected by recent changes in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1038 and https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1192 that actually touch CompletionEngine ?!

**Comment by iloveeclipse** [comment]
OMG. 
I've missed that because one must carefully look at what is actually expected by the test and what is complained by the test!!!

The **compiled** test **bytecode** does NOT match the actual test source code!!!
There is obviously a bug that **duplicates** parts of the concatenated string passed as expectation argument to the test.

So actual test result and actual test expectation are both fine, but the expectation value compiled to the bytecode of the test class is wrong!!!

Look at this: the highlighted extra expectation part that was "missing" in the test result doesn't exist in source code of the expectation:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/5c933db1-68e5-4651-a73f-644f7341d97e)

@jarthana , @srikanth-sankaran : this must be fixed for M1, as the compiler obviously produces wrong bytecode.

**Comment by iloveeclipse** [comment]
It looks like the generated code is totally confused if there are multiple variables involved in string concatenation.

```
public class X {

	public static void main(String[] args) {
		int first = 11;
		int second = 42;
		String expected = """
			X 0
			a 11
			a 11
			X 1
			b 42
			b 42
			b 42
			b 42""";
		String actual =
				"X " + 0 + "\n" +
				"a " + first + "\n" +
				"a " + first + "\n" +
				"X " + 1 + "\n" +
				"b " + second + "\n" +
				"b " + second + "\n" +
				"b " + second + "\n" +
				"b " + second + "\n";

		System.out.println("### expected ###");
		System.out.println(expected);
		System.out.println("### actual ###");
		System.out.println(actual);
	}
}
```

Produces:

```
### expected ###
X 0
a 11
a 11
X 1
b 42
b 42
b 42
b 42
### actual ###
X 0
a 11
a 11
X 1
b 42
b 42
b 42
b 11
a 11
X 1
b 42
b 42
b 42
b 42
```

**Comment by iloveeclipse** [comment]
OK, I believe I nailed the root cause. `CombinedBinaryExpression.buildStringForConcatation()` produces too much by calling `super.buildStringForConcatation()` inside the for loop here:

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/4c983903d12a95e98aab9b77b478015b1c354840/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/CombinedBinaryExpression.java#L261

This call goes to `BinaryExpression.buildStringForConcatation()` where it sees that `this.constant == Constant.NotAConstant` and builds code for **both** left and right sides of the expression.

I believe it is supposed to be `cursor.buildStringForConcatation()`.

**Comment by jarthana** [comment]
My bad. Looking at the original generateOptimizedStringConcatenationCreation() that the new method was cloned from, it was an oversight that super was called.

Thanks for taking care of this, @iloveeclipse

**Comment by iloveeclipse** [comment]
@jarthana , could you please review  https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1202

**Comment by iloveeclipse** [comment]
OK, after re-deploying fixed ecj and re-building SDK with it we have no related fails anymore:
https://download.eclipse.org/eclipse/downloads/drops4/I20230702-1800/testResults.php
