### ISSUE TITLE
Pending metaindex job makes tests fail when run in specific order

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#1203]
I have stripped down RunCompletionModelTests to just a very specific set of 28 test methods from two test classes.

In this setting, some of the tests don't even try to search for types in working copies, because an index search job aborts with OperationCanceledException. As a result fewer completions are proposed than expected.

OperationCanceledException is thrown, because the index manager has a waiting job that was never triggered.

From a test we indirectly create a PatternSearchJob, which below ensureReadyToRun() calls IndexSelector.initializeIndexLocations(). At this point the IndexManager is in this call stack:
```
IndexManager.scheduleForMetaIndexUpdate(Index) line: 1750	
IndexManager.updateMetaIndex(Index) line: 1680	
IndexManager.saveIndex(Index) line: 1155	
IndexManager.saveIndexes() line: 1198	
IndexManager.notifyIdle(long) line: 836	
IndexManager(JobManager).indexerLoop() line: 487	
```
I believe that problem results from creating a request from within the indexerLoop(): the job is added to awaitingJobs but down in indexerLoop we will just run into this.wait() with nobody to ever notify us, that we have an awaitingJob. All subsequent search jobs with policy IJob.CancelIfNotReady will get OperationCanceledException.

**Comment by stephan-herrmann** [comment]
As a proof of my theory I replaced JobManager.awaitingJobsCount() with the following kludge:

```
public synchronized int awaitingJobsCount() {
	if (this.activated) {
		int count = 0;
		for (IJob iJob : this.awaitingJobs) {
			if (iJob.getClass().getName().equals("org.eclipse.jdt.internal.core.search.indexing.IndexManager$MetaIndexUpdateRequest"))
				continue; // skip
			count++;
		}
		return count;
	}
	return 1;
}
```

With this the test set that previously failed runs green.

**Comment by stephan-herrmann** [comment]
@gayanper  I'd appreciate if you take a look :)

Here's a recipe for reproduction:

First create a manageable subset of tests, which are sufficient to show interference, which should ensure we have the exact same environment:
* In RunCompletionModelTests comment all tests except for CompletionTests2 and CompletionTests
* In CompletionTests2:
  * in the static initializer set `TESTS_NAMES = new String[]{"testChangeInternal"};`
  * inside `testChangeInternalJar()` replace the buggy finally block with `removeLibrary(this.currentProject, jarName, sourceZipName);`
* in CompletionTests add the following at the top of `suite()` (not in the static initializer):
   * `TESTS_NAMES = new String[] { "testBug2", "testBug20", "testBug28", "testBug29", "testBug9", "testCamelCaseType1", "testCatchClauseExceptionRef04" };`
   * next line change `BYTECODE_DECLARATION_ORDER` to `ALPHABETICAL_SORT`

Now launch RunCompletionModelTests. 

Useful breakpoints:
* IndexManager.scheduleForMetaIndexUpdate() last line, mark as TriggerPoint with hit count 15
* CompletionTest.testCamelCaseType1() line of `codeComplete()`, mark as TriggerPoint, too
* OperationCanceledException: exception breakpoint

Breakpoints should trigger in that exact order. After the second hit, ensure that no trigger breakpoints are enabled any more. The exception breakpoint will signal the point where BasicSearchEngine.searchAllTypeNames() aborts prematurely.

**Comment by stephan-herrmann** [comment]
Here's another change I have in my workbench, sorry, I was in the middle of fixing all kinds of test instabilities :)

in `org.eclipse.jdt.core.tests.model.CompletionTests.setUpSuite()` add with the else block:
* `this.currentProject = COMPLETION_PROJECT;`

**Comment by stephan-herrmann** [comment]
Without the reduced set of tests we seem to be lucky that subsequent index requests actually unblock the `MetaIndexUpdateRequest`, but such dependence on test order will likely cause much head scratching time and again.

**Comment by gayanper** [comment]
I will check on it

**Comment by gayanper** [comment]
Unfortunately I don't get a hit for `OperationCanceledException` ?

**Comment by stephan-herrmann** [comment]
> Unfortunately I don't get a hit for `OperationCanceledException` @stephan-herrmann , any more tweaks to reproduce this ?

Did you check that after the second hit both trigger points where disabled?

**Comment by gayanper** [comment]
> > Unfortunately I don't get a hit for `OperationCanceledException` @stephan-herrmann , any more tweaks to reproduce this ?
> 
> Did you check that after the second hit both trigger points where disabled?

The first trigger point get enabled after the second trigger point is hit, I manually disable it before continuing. So basically after the second trigger point is hit, only enabled breakpoint is the exception breakpoint.

**Comment by gayanper** [comment]
I was wondering if we move the meta index update into post job step, like the `saveIndexes`, Of course that will then get execute in the main loop, which I think will not be a big issue since the meta update operation is much faster than actual indexing operations. 

Then we will not need the `requestIfNotWaiting(new MetaIndexUpdateRequest())` at `scheduleForMetaIndexUpdate`

**Comment by gayanper** [comment]
If you can reproduce the issue still in workspace.

You could do the following changes in IndexManager and see if it fixes.

- Remove line `requestIfNotWaiting(new MetaIndexUpdateRequest()) from scheduleForMetaIndexUpdate`
-  Add the following line `(new MetaIndexUpdateRequest()).execute(new NullProgressMonitor())` as the first line of `saveIndexes`

**Comment by stephan-herrmann** [comment]
I understand that my "reproducer" is quite fragile. I'll try to come up with an easier story, once I'm done with #1077

If you want to do one more experiment in the meanwhile, you could try to step into `CompletionTest.testCamelCaseType1()` until the point where `CompletionEngine.findTypesAndPackages()` should invoke `this.nameEnvironment.findTypes()` and down into where `BasicSearchEngine` is invoked. In my case it went into the branch with `CANCEL_IF_NOT_READY_TO_SEARCH` where `indexManager.performConcurrentJob()` would then throw `indexManager.performConcurrentJob` - but surely whether or not the `MetaIndexUpdateRequest` is still waiting at that point is fragile.

**Comment by gayanper** [comment]
I try an experiment with what I mentioned above in a PR and see if any tests fails, If it doesn't you can try to do the same tests in your workspace with the branch. That might save time for both of us, WDYT ?

**Comment by stephan-herrmann** [comment]
Found a tweak missing from my steps: swap order of CompletionTests and CompletionTests2 :-/

**Comment by stephan-herrmann** [comment]
I could re-create the problem, then applied the suggested changes in IndexManager, which let tests run green again :)

**Comment by stephan-herrmann** [comment]
For the "fun" of it I created #1204 for remaining(?) issues. As you can see your proposed fix seems to improve more than just this one scenario.

**Comment by gayanper** [comment]
> Found a tweak missing from my steps: swap order of CompletionTests and CompletionTests2 :-/

This is the recipe :)

**Comment by stephan-herrmann** [comment]
I wasn't happy about the crude reproducer, in particular the set of tests needed in `CompletionTests` looked weird, *until* I managed to reduce it to
* just one test in CompletionTests: `testCamelCaseType1`
* a `Thread.sleep(1000)` as the first statement of that test

During that time period, `IndexManager.notifyIdle()` puts a `MetaIndexUpdateRequest` into `awaitingJobs` while no client is waiting for the index, and hence the subsequent `wait()` doesn't complete, and subsequent search jobs with policy `IJob.CancelIfNotReady` will get `OperationCanceledException`, and now `Thread.sleep()` will make it ready.

Maybe all this is already obvious to @gayanper ? :)

**Comment by stephan-herrmann** [comment]
@jukzi in case you'll pick it up from here, feel free to use https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1215 for your investigation.

**Comment by stephan-herrmann** [comment]
Using the above tweaks for reproduction, I can no longer observe the problem after #1283. `OperationCanceledException` no longer occurs.
