### ISSUE TITLE
Lack of test isolation between CompletionTests and CompletionTests2

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#1204]
The following tweaks in `RunCompletionModelTests` will cause failures:
* add `CompletionTests2` to the suite before `CompletionTests`
* comment all other test classes
* run `RunCompletionModelTests`
* 2 failures:
  * CompletionTests2.testBug410207c() (that's an instance of #1190)
  * CompletionTests.test270436a() unexpected proposal

Now change `CompletionTests.suite()` from using `BYTECODE_DECLARATION_ORDER` to `ALPHABETICAL_SORT`:
* number of failures goes up to **20**!  I haven't even started to analyze this.

**Comment by stephan-herrmann** [comment]
Note, that above observations were on top of other pending fixes:
* [#1077](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1077) where I already fixed the broken cleanup of CompletionTests2.testChangeInternalJar().
* proposed fix for [#1203](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1203), without that results are:
  * ALPHABETICAL_SORT -> a complete freeze in CompletionTests.testBug351444() 
  * BYTECODE_DECLARATION_ORDER -> 14 failures instead of 2

**Comment by jarthana** [comment]
Here's another experiment: Just take `CompletionTest` and comment out all tests but `testDeprecationCheck15()` and run only to see the lonely test failing!
