### ISSUE TITLE
Eclipse formatter(Java) doesn't work if code contain errors

### ISSUE THREAD

**Issue by igornem1** [eclipse-jdt/eclipse.jdt.core#1208]
Eclipse version info is:
Version: 2023-06 (4.28.0)
Build id: 20230608-1333

Bug description:

If code has compilation error then formatter(manually by Ctrl+Shift+F either automatically by setting actions on save) doesn't work.
It's very problematic because if write code and save it uncompleted(containing errors) during work, then when I finish and file compiles without issues then saved before lines is not considered as edited line by settings in Java->Editor->Save Actions- "Format edited lines" and remains unformatted.
How to reproduce:

Put below code into java editor and save
Select all text and choose in menu Source->Format
Expected bechaviour: code formatted accordingly to current formatter settings
Actual resuult: Code didn't change

Code samlple being tested:

`package test;

public class Test {
public static void main(String[] args) {
int i=0;
formatter breaker line
}
}
`

**Comment by jukzi** [comment]
Unless you provide a patch that can magically guesss the right format for an invalid content this can't be solved.

**Comment by igornem1** [comment]
Sorry, I not understand, what a problem to format a code which locates before not-compiling code?

**Comment by igornem1** [comment]
@jukzi moreover, I don't understand what a problem to format even code which locating after non-compiling lines? The wrong code can be considered as a code block and to get defined indent and code which is after to be formatted as usual. At the bottom line the formatter should format the sentences, but not compile, I don't see relation between compiling and formatting at all.

**Comment by jukzi** [comment]
In case of a syntax error the parser can in general not know which part of the code is correct and which is not.
For example if there is a brace too much it can't know if the brace is too much or another brace is missing. And where it is missing. So he can not know the indent.

**Comment by igornem1** [comment]
@jukzi Ok, lets begin from simplest part. What a problem to format a code which is before an errored line?

**Comment by jukzi** [comment]
Contribute a solution please if you know how todo it.

**Comment by igornem1** [comment]
@jukzi I guess myself is not a subject to discuss can I do it or not, there are few significant reasons why I didn't do it yet, but I guess in this community exists enough persons who know how and able do it and its looks very strange you closed this ticket with reason you personally don't know how to do it or just don't like this or I again not clearly undersand what a reason for a ticket reject

**Comment by jukzi** [comment]
Feel free to pay someone to implement that miracle for you or hope for a wonder. The community is damn small.

**Comment by igornem1** [comment]
@jukzi well, you're a boor, buddy. I don't remember that I spat at your lunch)))
