### ISSUE TITLE
AIOOB exception for invalid code with records and generics

### ISSUE THREAD

**Issue by brychcy** [eclipse-jdt/eclipse.jdt.core#1218]
The following (invalid) code leads to an AIOOB exception in SourceTypeBinding#components  (in the finally block)

```
package test;

class Test<T> {
	record R(T x);
}
```

From a quick look: in the if-block with condition failed > 0, the array of components is shortened, but then a few lines below the length of smb.parameters doesn't match anymore.

**Comment by iloveeclipse** [comment]
Hi Till, do you mind to provide a PR?

**Comment by brychcy** [comment]
Maybe @mpalat can have a look? He added the code where the exception happens for [Bug 570399](https://bugs.eclipse.org/bugs/show_bug.cgi?id=570399)

**Comment by srikanth-sankaran** [comment]
I'll take a look.

**Comment by mpalat** [comment]
hit upon this while looking at "mentions  me" filter- 
@srikanth-sankaran - I have a trivial patch for this - creating a PR [with apologies for hijacking this issue]
