### ISSUE TITLE
ECJ handles multiline strings with Unicode codepoint escapes incorrectly

### ISSUE THREAD

**Issue by markozajc** [eclipse-jdt/eclipse.jdt.core#1237]
Example code:
```java
System.out.println("""
    a\u0020a
    a \
    a""");
```
---
Running the example code in Eclipse produces the following erroneous output:
```
a a
a \    a
```
Compiling it with javac and running it on the command line by hand produces the correct output:
```
a a
a a
```
Software used:
- Eclipse IDE 2023-06 (4.28.0), build id 20230608-1333
- Eclipse Java Development Tools 3.19.100.v20230605-0440

Note to self: change ChatbotCommand.java once this is fixed

**Comment by jarthana** [comment]
@jjohnstn Is this something you can take it up?

**Comment by jukzi** [comment]
fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2316
