### ISSUE TITLE
Get rid of org.eclipse.jdt.annotation_v1 ?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#1255]
org.eclipse.jdt.annotation_v1 is a Java-8 compatible bundle, and newer version supports newer Java. As JDT doesn't target running on Java 8 anymore, shouldn't we remove this bundle from the source tree to make things a bit simpler and faster?

**Comment by iloveeclipse** [comment]
Not sure I understood what exactly should be faster.

The annotation library is not meant to be "running" on Java 8, it is just a library for those clients that want use JDT annotations **version 1**, because it is not compatible to version 2.

**Comment by stephan-herrmann** [comment]
I believe the proper way of deprecating the _v1 bundle, telling people where they can still get previous versions etc pp causes more churn, than keeping the bundle. Or is there any significant maintenance cost which it incurs?

**Comment by mickaelistria** [comment]
OK, thanks for your insights. I was asking this as an opportunity to make things slightly easier (ie build wouldn't require Java 8 any more for safe build), but it doesn't seem profitable at the moment. Let's close.
