### ISSUE TITLE
[regression] Record methods are not recognized

### ISSUE THREAD

**Issue by snjeza** [eclipse-jdt/eclipse.jdt.core#1258]
A related issue - https://github.com/redhat-developer/vscode-java/issues/3233

Steps to reproduce:

- create the following classes
```
public class Main {
    public static void main(String[] args) {
        MyRecord test = new MyRecord(0, 0);
        System.out.println(test.field1());
    }
}

@Deprecated(since = MyRecord.STATIC_VALUE)
record MyRecord(int field1, int field2) {
    public static final String STATIC_VALUE = "test";
}
```
You will get `The method field1() is undefined for the type MyRecord`.
The issue can be reproduced in jdt.core >= https://github.com/eclipse-jdt/eclipse.jdt.core/commit/32961cfe47d06434b73a05f44e81fb6b94d9f87f

**Comment by iloveeclipse** [comment]
@stephan-herrmann : could you please take a look?

**Comment by stephan-herrmann** [comment]
Thanks for catching. That's exactly the kind stuff why I was keen on pushing #1077 early in the cycle :)
