### ISSUE TITLE
Eclipse compiler not inferring lambda parameter type in Eclipse EE 2023-09 M1

### ISSUE THREAD

**Issue by garretwilson** [eclipse-jdt/eclipse.jdt.core#1261]
I'm using OpenJDK 17, although this code is set to use Java 8. I upgraded to Eclipse EE 2023-09 M1, and suddenly the Eclipse compiler doesn't like Java 8 code that has been working for a long time.

The code is in the https://github.com/globalmentor/globalmentor-base project. It relies on the https://github.com/globalmentor/globalmentor-root POM. You can install both of those with Maven simply by cloning them from the repository and running `mvn install`. (Install the `globalmentor-root` project first.)

The code that is breaking is [`MediaTypeTest`](https://github.com/globalmentor/globalmentor-base/blob/main/core/src/test/java/com/globalmentor/net/MediaTypeTest.java) in the method `testParameterAppendValueTo()`:

```java
/** @see MediaType.Parameter#appendValueTo(Appendable, String) */
@Test
public void testParameterAppendValueTo() throws IOException {
  PARAMETER_VALUE_STRINGS_BY_VALUE.forEach(throwingBiConsumer((value, valueString) -> {
    assertThat(MediaType.Parameter.appendValueTo(new StringBuilder(), value).toString(), is(valueString));
  }));
}
```

This tests the [`MediaType`](https://github.com/globalmentor/globalmentor-base/blob/main/core/src/main/java/com/globalmentor/net/MediaType.java) class.

`PARAMETER_VALUE_STRINGS_BY_VALUE` is a simple `Map<String, String>`. `throwingBiConsumer` is part of the [Faux Pas](https://github.com/zalando/faux-pas) library, which we discussed in #1162. It uses "sneaky throws" to allow exceptions to propagate even though they are not declared.

`MediaType.Parameter.appendValueTo()` looks like this:

```java
public static <A extends Appendable> A appendValueTo(@Nonnull final A appendable, @Nonnull CharSequence parameterValue) throws IOException
```

Thus in the code above, we know that `value` is the key in the `Map<String, String>`. We know that `new StringBuilder()` is of course an `Appendable`. Thus `(StringBuilder, String)` should be fine to pass to `(Appenable, CharSequence`). And in fact this worked fine in Eclipse EE 2023-06 and for many, many versions before that. But in Eclipse EE 2023-09 we get>

> `The method appendValueTo(A, CharSequence) in the type MediaType.Parameter is not applicable for the arguments (StringBuilder, Object) MediaTypeTest.java /globalmentor-core/src/test/java/com/globalmentor/net line 485`

I can work around this by manually casting `value` to e.g. a `String`:

```java
    assertThat(MediaType.Parameter.appendValueTo(new StringBuilder(), (String)value).toString(), is(valueString));
```

But we shouldn't have to, because we already know that `value` is a `String`, because it comes from the key in the `Map<String, String>` constant `PARAMETER_VALUE_STRINGS_BY_VALUE`. And as I mentioned, this has been working fine for ages, both in Eclipse and in OpenJDK 17.

You might investigate whether this bug is related to the fix for #1162. I only say that because they both use Faux Pas; otherwise I don't have any idea what might be causing this, as this is pretty basic lambda parameter type inference.

**Comment by srikanth-sankaran** [comment]
> You might investigate whether this bug is related to the fix for #1162. I only say that because they both use Faux Pas; otherwise I don't have any idea what might be causing this, as this is pretty basic lambda parameter type inference.

No. This is not from there. I verified by backing out that change.

**Comment by srikanth-sankaran** [comment]
@stephan-herrmann @testforstephen - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/524 seems to result in this issue - Can you please take a look ? TIA

**Comment by stephan-herrmann** [comment]
This is how I tried to simulate the problem in a single Java file:
```
import org.eclipse.jdt.annotation.*;
import java.io.*;
import java.util.*;
import java.util.function.*;

@FunctionalInterface
interface ThrowingBiConsumer<T,U, X extends Throwable> extends BiConsumer<T,U> {

    void tryAccept(T t, U u) throws X;

    @Override
    default void accept(final T t, final U u) {
        tryAccept(t, u);
    }

}
public class GH1261 {
	public static <T,U, X extends Throwable> ThrowingBiConsumer<T,U,X> throwingBiConsumer(
            final ThrowingBiConsumer<T,U,X> consumer) {
        return consumer;
    }
    Map<String, String> PARAMETER_VALUE_STRINGS_BY_VALUE;
    public void testParameterAppendValueTo() throws IOException {
        PARAMETER_VALUE_STRINGS_BY_VALUE.forEach(throwingBiConsumer((value, valueString) -> {
            assertThat(appendValueTo(new StringBuilder(), value).toString(), is(valueString));
        }));
    }
    boolean is(String s) { return false; }
    void assertThat(String msg, boolean b) {}
    public static <A extends Appendable> A appendValueTo(@NonNull final A appendable, @NonNull CharSequence parameterValue) throws IOException { return null; }
}
```
This fails like this:
```
----------
1. ERROR in /tmp/GH1261.java (at line 13)
        tryAccept(t, u);
        ^^^^^^^^^^^^^^^
Unhandled exception type X
----------
```

Now @garretwilson will complain that I left out the `@SneakyThrow`, but according to JLS an annotation cannot influence compiler behavior in a way that it would accept this code.

A sneaky look into https://projectlombok.org/features/SneakyThrows let's me think the point of contention is, that Lombok uses this annotation to _transform_ the code before it is handled by the compiler.

If that's correct, then we need a version of the Java code **as it will be piped into the compiler**.  The lombok page gives some hints at how the code will be transformed. Anyone able to manually apply that transformation to my snippet above, so we have a test case that we can work on without any lombok black magic?

**Comment by jarthana** [comment]
I am attaching a simple Java project with just the test code the hamcrest jar dependency. Hope this helps.
[Issue1261.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12302075/Issue1261.zip)

**Comment by garretwilson** [comment]
> Now @garretwilson will complain that I left out the @SneakyThrow, but according to JLS an annotation cannot influence compiler behavior in a way that it would accept this code.

> A sneaky look into https://projectlombok.org/features/SneakyThrows let's me think the point of contention is, that Lombok uses this annotation to _transform_ the code before it is handled by the compiler.

There seems to be some misunderstanding here.

* I am not using any relevant annotations—only things like `@Test` and `@Nonnull`.
* I am not using Lambok. I don't get anywhere near Lambok unless someone drags me there (e.g. a client is paying me).
* There is no transformation of the code occurring.
* "Sneaky throws" is a term for a particular technique that, as I understand it, is 100% compliant with the JLS. I merely referenced the Lambok as documentation explaining the technique.
* The library I am using is [Paux Pas](https://github.com/zalando/faux-pas), mentioned in the description. It is a normal Java library.

I confess that I have not tested whether this error occurs removing the intermediate sneaky throws lambda wrapper from Faux Pa, but I have little extra time and I've already switched back to Eclipse EE 2023-06. I had believed the full Maven projects I provided would serve as a sufficient case to reproduce without ambiguities.

**Comment by stephan-herrmann** [comment]
> There seems to be some misunderstanding here.

I'm not sure how you get around using lombok since Faux Pas seems to rely on lombok's `@SneakyThrow`, which from my brief look appears to require on-the-fly code transformation.

Anyway, since @jarthana managed to reproduce without SneakyThrow we can drop that topic.

**Comment by stephan-herrmann** [comment]
Srikanth:
> Sorry, I should have mentioned that Jay has a reproducer eclipse project that shows the exact same message reported by @garretwilson

Now you are telling me :)

Jay:
> I am attaching a simple Java project with just the test code the hamcrest jar dependency. Hope this helps. P.S: Sorry, I didn't bother to clean up. The test code contains lot of commented out stuff. [Issue1261.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12302075/Issue1261.zip)

I can reproduce using that project, still something is weird: I stubbed the required classes from hamcrest, using the exact signatures as found in .class, but even if I pack my stubs in a new jar and use that for compilation, the error does not occur. 

As a first step, I checked if the assert from #524  fires when run with `-ea`: it doesn't.

to be continued later.

**Comment by garretwilson** [comment]
> I'm not sure how you get around using lombok since Faux Pas seems to rely on lombok's @SneakyThrow, which from my brief look appears to require on-the-fly code transformation.

@stephan-herrmann it appears I was mistaken in a lot of what I [mentioned above](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1261#issuecomment-1671216582). (I've edited the comment.) I had never realized that Faux Pas had part of Lombok as a dependency, and I had never realized that in the source code Faux Pas actually uses the Lombok `@SneakyThrow` annotation. So now I'm unsure whether there is code generation happening under the covers with Faux Pas—it would be a surprise and slightly disappointing. How sneaky throws works is still 30% of a mystery to me.

In any case thanks for pointing that out and correcting my assumption.

Nevertheless this seems to be a new problem in Eclipse EE 2023-09 M1. Thanks for @jarthana and @srikanth-sankaran for finding a test case that I understand separates the issue from sneaky throws.

**Comment by jarthana** [comment]
> Jay:
> 
> > I am attaching a simple Java project with just the test code the hamcrest jar dependency. Hope this helps. P.S: Sorry, I didn't bother to clean up. The test code contains lot of commented out stuff. [Issue1261.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/12302075/Issue1261.zip)
> 
> I can reproduce using that project, still something is weird: I stubbed the required classes from hamcrest, using the exact signatures as found in .class, but even if I pack my stubs in a new jar and use that for compilation, the error does not occur.

Yes, I found the same behavior, which I shared with Srikanth as well. Hence, I had to include the library.

**Comment by stephan-herrmann** [comment]
In the bad case I see inference picking the wrong candidate among these:
```
    public static <T extends java.lang.Object> org.hamcrest.Matcher<T> is(org.hamcrest.Matcher<T>)
    public static <T extends java.lang.Object> Matcher<T> is(T)
```
this could be the core problem from where inference goes bad.

At least adding the above overloads lets me reproduce in a single file:
```
import java.io.IOException;
import java.util.AbstractMap;
import java.util.function.BiConsumer;
import java.util.Collections;
import java.util.Map;

class Matcher<T extends Object> {}

public class GH1261 {
	private static final Map<String, String> PARAMETER_VALUE_STRINGS_BY_VALUE = Collections.emptyMap();

	public void testParameterAppendValueTo() throws IOException {
		PARAMETER_VALUE_STRINGS_BY_VALUE.forEach(throwingBiConsumer((value, valueString) -> {
			assertThat(Parameter.appendValueTo(new StringBuilder(), value).toString(), is(valueString));
		}));
	}
    public static <T, R, X extends Throwable> ThrowingBiConsumer<T, R, X> throwingBiConsumer(
            final ThrowingBiConsumer<T, R, X> consumer) {
        return consumer;
    }
    public static <T extends java.lang.Object> Matcher<T> is(Matcher<T> m) { return null; }
    public static <T extends java.lang.Object> Matcher<T> is(T t) { return null; }

    public static <T extends java.lang.Object> void assertThat(T t, Matcher<? super T> m) { }
    // original has overloads of assertThat, which are not relevant here
}
interface ThrowingBiConsumer<T, U, X extends Throwable> extends BiConsumer<T, U> {
    void tryAccept(T t, U u) throws X;
    default void accept(final T t, final U u) { }
}
@SuppressWarnings("serial")
final class Parameter extends AbstractMap.SimpleImmutableEntry<String, String> {
    public static <A extends Appendable> A appendValueTo(final A appendable, CharSequence parameterValue) throws IOException {
        return appendable;
    }
    public Parameter(final String name, final String value) {
        super("", "");
    }
}
```

**Comment by stephan-herrmann** [comment]
Thanks, @garretwilson, for reporting this regression in time for it to be fixed for 2023-09 (hopefully). PR #1281 lists a bit of the colorful history of this code, where implementing JLS true to the letter is not sufficient to arrived at the desired behavior. For that reason we can only hope that our opportunistic fixes converge towards a point where regressions will become fewer over time.

**Comment by garretwilson** [comment]
> Thanks, @garretwilson, for reporting this regression in time for it to be fixed for 2023-09 (hopefully).

Good morning, @stephan-herrmann . I appreciate your taking the time to send me that note. So often the first thing I get in my email inbox are notices of more hurdles to confront during the day; or comments on my many bug reports (on other projects) practically criticizing me for filing them or flat-out telling me I should fix them myself. You helped start the day on a positive note. Thank you.

Have a great weekend.

**Comment by garretwilson** [comment]
Does anyone know if this got into Eclipse 2023-09 M3 (supposed to be released today), or will be in RC 1 (due next week)?

I'm not rushing anyone; I just wanted to know whether to go ahead and upgrade or hold off. Thanks.

**Comment by iloveeclipse** [comment]
> or will be in RC 1

It is in RC1.

**Comment by garretwilson** [comment]
This indeed seems to be fixed in Eclipse 2023-09 RC1 and Eclipse 2023-09 final release. Sincere thanks for investigating and addressing this.
