### ISSUE TITLE
Parameter assignment warning in record constructor should be disabled or optional

### ISSUE THREAD

**Issue by hjohn** [eclipse-jdt/eclipse.jdt.core#1279]
Parameter assignment is generally not a great practice, and the Code Style "parameter assignment" warning serves a useful purpose to avoid accidentally changing parameters that might result in confusing code.

However, with records, Eclipse flags this code as parameter assignment:

```java
   public record Xyx(Map<String, Object> unmappedProperties) {
        public Xyz {
            unmappedProperties = unmappedProperties == null ? new HashMap<>() : unmappedProperties;
        }
   }
```

You can't write `this.unmappedProperties` here as you are not allowed to assign a final field twice (the record constructor will assign it "again" after this constructor code completes).

I think there are two ways this can be fixed:

1. Make the parameter assignment warning ignore parameter assignment in the record constructor.  Especially in the short constructor where there is no need to specify the parameters the warning does not make much sense.
2. Make this an option that can be turned on/off

**Comment by srikanth-sankaran** [comment]
This is already fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1173

In future, always make sure to submit full test case: i.e. include imports.
Also note the mispelt `Xyz `
