### ISSUE TITLE
 The import a.b.c.AType cannot be resolved in parallel builds

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#1299]
It seems there is another reincarnation of 
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/183

I have upgraded one of my builds to Tycho4 (ECJ 3.34.0) and see this error again but this time not for a JDK class but for a user type class (even though the type is on the classpath and it often succeeds to build the project), that *sometimes* it fails with the error "The import a.b.c.AType cannot be resolved" (even though the project has not changed compared to the last successful build).

It often helps to perform a complete clean (what probably changes the timing enough) to succeed, then it works, maybe for a few builds, sometimes for many days, also the build is quite large and complex to reproduce the problem.

So I hope that maybe with the findings of #183 someone has an idea or can suggest some flag to pass to the compiler to get some more details why the type cannot be found. Also maybe someone has encountered a similar issue and can share some more ideas how to reproduce this.

**Comment by iloveeclipse** [comment]
Any chance for some simple reproducer project?

**Comment by laeubi** [comment]
> Any chance for some simple reproducer project?

Not yet, so if anyone has an idea what might be the cause here I can try to narrow it down, but at the moment it is quite random.

**Comment by laeubi** [comment]
The only think I can see is that it strange enough is always related to types from one third party jar... the only maybe "unusual" thing I can see is that the build contains projects that use different versions of the library, could it be that types are cached by class-name somewhere and then things get confused between those versions?

The both jars in question are:

- https://mvnrepository.com/artifact/edu.ucar/cdm/4.5.5
- https://mvnrepository.com/artifact/edu.ucar/cdm-core/5.4.0

I'll now run a debug build to see what classpath is passed to Tycho ...

**Comment by laeubi** [comment]
I think I tracked this down to the jar being modified while the build is running, because it is quite large jar it then could happen that JDT already is working on the jar while content is still written in a parallel build.

As I can't find any other evidence that this a compiler bug (beside from that its a bit strange that I don't see any error printout), I'll close this for now.
