### ISSUE TITLE
Null analysis - Record synthetic accessor methods cannot implement interfaces with null constraints

### ISSUE THREAD

**Issue by agentgt** [eclipse-jdt/eclipse.jdt.core#1302]
@stephan-herrmann 

# Behavior

Assume we have `@NonNullByDefault` on a package. The package contains:

```java
public interface Parent {
  Map<String, String> model();
}
```

*Now a separate file (this important):*

```java
public record Child(Map<String, String> model) implements Parent {
}
```

We get an error on `Child`:

```
The method @NonNull Map<String,String> model() from Child cannot implement the corresponding method from Parent due to incompatible nullness constraints
```

# Work around

```java
public record Child(Map<String, String> model) implements Parent {
  Map<String,String> model() { return this.model }
}
```

**The reason this was probably not found earlier is if the interface and record are in the same file this issue disappears.**

For example this is fine:

```java
public interface Parent {
  Map<String, String> model();
  public record Child(Map<String, String> model) implements Parent {
  }
}
```

**Comment by agentgt** [comment]
BTW I have to praise how much the null analysis has improved for Eclipse these days! 

I have my project checking with both Eclipse and Checkerframework: https://github.com/jstachio/jstachio/actions/runs/5930238466

It is so much easier to annotate existing stuff with Eclipse that I found checkers annotations on the JDK lacking and far more painful to go fix.

Way more praise should be given to Eclipse null analysis so I am happy to help in anyway @stephan-herrmann and appreciate all the hard work!

**Comment by stephan-herrmann** [comment]
Thanks for your feedback! Both the praise and the bug report are appreciated :smile:
