### ISSUE TITLE
Gerrit build fails with some baseline errors

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#132]
See #131 gerrit build that is failed allthough there shouldn't be any problem:

https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-131/1/consoleFull

Gerrit complains about some errors which I don't understand:
```
10:25:23  [INFO] Adding repository https://download.eclipse.org/eclipse/updates/4.24-I-builds/I20220607-0700
10:25:29  [ERROR] Baseline and reactor have same fully qualified version, but with different content
10:25:29  different
10:25:29     .api_description: not present in baseline
10:25:29     .options: not present in baseline
10:25:29     META-INF/ECLIPSE_.RSA: different
10:25:29     META-INF/ECLIPSE_.SF: different
10:25:29     META-INF/MANIFEST.MF: different
```

Not sure why I20220607-0700 build is used at all, the last stable should be [I20220607-1940](https://download.eclipse.org/eclipse/downloads/drops4/I20220607-1940/).

@sravanlakkimsetti , @SDawley : do you have an idea what is missing?

**Comment by iloveeclipse** [comment]
Moment. Why is this still **4.24**-I-builds? **That** is the issue

**Comment by sravanlakkimsetti** [comment]
I checked the parent pom but could not find any obvious problems need to dig deeper here. Will continue tomorrow

**Comment by iloveeclipse** [comment]
@sravanlakkimsetti : obviously this works now, but could you please explain **why**?

**Comment by sravanlakkimsetti** [comment]
I am still investigating it. I just unblocked every one by disabling baseline check. Once I get a fix I will reenable baseline check

**Comment by iloveeclipse** [comment]
Is this issue related to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/148 may be?

**Comment by iloveeclipse** [comment]
OK, looks like at least two entries 
```
10:25:29     META-INF/ECLIPSE_.RSA: different
10:25:29     META-INF/ECLIPSE_.SF: different
```
are related to this bug: https://github.com/eclipse/tycho/issues/1053
