### ISSUE TITLE
Improve type compatibility checks in pattern resolution

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#134]
Pattern matching can be complicated when involving super/sub types, sealed classes etc.. A simple isCompatibleWith() we are doing now in RecordPattern is not good enough. This needs to be improved. Also to be looked at is, making use of MatchException that is being introduced in Java 19.

**Comment by srikanth-sankaran** [comment]
@jarthana is this still open ? If you point me to some symptom I can take over this one and work on it - TIA

**Comment by jarthana** [comment]
> @jarthana is this still open ? If you point me to some symptom I can take over this one and work on it - TIA

I see that fix for #1336 took care of the concerns. This can be closed now.
