### ISSUE TITLE
[21][dom] APIs deprecation and cleanup

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1340]
20 -> 21
cleanups

**Comment by mpalat** [comment]
@jarthana  - in case this is not covered in move to 21, created this issue

**Comment by jarthana** [comment]
I covered quite a few of these during #1316. But didn't bother with API upgrades/deprecation and such. Let me do a check later and see what it takes.

**Comment by jarthana** [comment]
OK, some of the tests were disabled, so I missed out on an important detail. In Java 21, record patterns don't have pattern variable names. I am planning to remove this new DOM property from RecordPattern and adjust tests accordingly.

@noopur2507  I will post a patch shortly. Please go through the API changes and let me know if you have any comments.

**Comment by noopur2507** [comment]
@jarthana Please release the attached UI patch after the Core patch.

**Comment by jarthana** [comment]
Both core and corresponding UI changes have been merged now.
