### ISSUE TITLE
Confusing "Type mismatch: cannot convert from Optional<Object> to Optional<String>" with type inference

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#1342]
I have this very simple example:

```
public Optional<String> notWorking() {
    return CompletableFuture.completedFuture(Optional.empty()).join();
}
```

but JDT complain:

```
Description	Resource	Path	Location	Type
Type mismatch: cannot convert from Optional<Object> to Optional<String>	TestMe.java	Java Problem
```

changing this to
```
public Optional<String> working1() {
    return CompletableFuture.completedFuture(Optional. <String>empty()).join();
}
```

works as well as

```
public Optional<String> working2() {
    return CompletableFuture.<Optional<String>> completedFuture(Optional.empty()).join();
}
```

but from the return type of the function I would assume it should work in the first place as it is clear that the type must be of the specified return type as it works for the following example:

```
public Optional<String> ok() {
   return Optional.empty();
}
```

This is a very simplified example (and maybe not even very useful ones) but this behavior is making work with streams/lamdas sometimes a nightmare because Eclipse suddenly "lost" the type and gives extremely hard to understand errors where one needs to decompile a more complex expression into individual parts to find out whats wrong, or its working by just introduce an intermediate local variable with a named type like in the following case:

```
public Optional<String> inlineme() {
    CompletableFuture<Optional<String>> future = CompletableFuture.completedFuture(Optional.empty());
    return future.join();
}
```

if one uses this snippet and chooses the quickfix to **inline** `future` this results in the initial error case, so inlining makes my code "suddenly" fail there.

**Comment by stephan-herrmann** [comment]
I agree with @szarnekow  and here's why inference for `completedFuture` cannot use `String`: the expression `CompletableFuture.completedFuture(Optional.empty())` is a _standalone_ expression, which is inferred without any target type. The information from the method return `Optional<String>` cannot travel right-to-left across the dot of `.join()`.

Thus the confusion is caused by JLS not ecj :)

**Comment by stephan-herrmann** [comment]
> if one uses this snippet and chooses the quickfix to inline future this results in the initial error case, so inlining makes my code "suddenly" fail there.

You might consider filing an issue against JDT/UI, but making the inline-quickfix aware of this subtle semantic issue might be quite a hard nut to crack.

**Comment by laeubi** [comment]
@stephan-herrmann then still the inline feature is broken as it produces wrong code.

Beside that the JLS for sure does not specify the error message an IDE has to emit or Quickfixes to offer, if you try this out in eclipse JDT offers for example to change this to en empty optional **as the first choice (!)** what makes no sense at all as it deletes all of my code and replace it with `Optional.empty()` ... instead i would like to get the suggestion to add a type hint of `<String>`  (or whatever this is called).

**Comment by laeubi** [comment]
> making the inline-quickfix aware of this subtle semantic issue might be quite a hard nut to crack

While this might be true I think it could boost the usefulness of JDT/Eclipse/Java Development, Stream/Optional and JDT(UI) often barks with strange error messages and quick fixes that almost never help to resolve the issue, instead one is forced back to manual typing/parsing java code :-\

**Comment by stephan-herrmann** [comment]
> > Thus the confusion is caused by JLS not ecj :)
> 
> @stephan-herrmann then still the inline feature is broken as it produces wrong code.

Yes, but inline feature is implemented in a different component, not ecj - JDT/Core.
 
> Beside that the JLS for sure does not specify the error message an IDE has to emit

Sure, within certain limits the compiler is free to choose the exact phrasing for the errors mandated by JLS. Do you see anything amiss with ecj's message?

> ... or Quickfixes to offer, ...

Again: different issue, not a compiler bug.

**Comment by stephan-herrmann** [comment]
>>    making the inline-quickfix aware of this subtle semantic issue might be quite a hard nut to crack
>
> While this might be true I think it could boost ...

True.

Emphasis is on _could_, which requires that there is a contributor/committer who is willing & **able** to make this change.  Frankly, I don't see such a person, but everybody is invited to prove me wrong.

> ... often barks with strange error messages ...

... now we're back at blaming the compiler? Please provide examples of error messages that you think need to be rephrased.

BTW, don't forget to link your new JDT/UI issue to this one :)

**Comment by laeubi** [comment]
See:

- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/757
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/758
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/759
