### ISSUE TITLE
instanceof pattern matching should reject supertypes

### ISSUE THREAD

**Issue by DasBrain** [eclipse-jdt/eclipse.jdt.core#1356]
The following snippet should be rejected by the compler:

```java
String str = "foo";
if (str instanceof String s) {}
```

because `String` is a the same (or a supertype) of the type of the variable `str`, so this check would always succeed (if `str != null`).

This is mandated by [JLS §15.20.2](https://docs.oracle.com/javase/specs/jls/se20/html/jls-15.html#jls-15.20.2):

>  If the type of the RelationalExpression is a subtype of the type of the Pattern, then a compile-time error occurs.

**Comment by srikanth-sankaran** [comment]
Reproduced. I'll take a look. Thanks

**Comment by srikanth-sankaran** [comment]
JDK21 javac accepts the code above while upto JDK20, it was rejected.

**Comment by srikanth-sankaran** [comment]
JLS21 15.20.2 is missing the said clause - however there are phantom bullets: See https://bugs.openjdk.org/browse/JDK-8317695

**Comment by srikanth-sankaran** [comment]
Closing with no change for reasons cited - latest JLS and latest javac don't call for or enforce this. Should there be a change in future, we will revisit
