### ISSUE TITLE
The method apply(capture#15-of ? extends Type) ... is not applicable for the arguments (Type)

### ISSUE THREAD

**Issue by dpetroff** [eclipse-jdt/eclipse.jdt.core#1369]
I got this error message in Eclipse. It looks like nonsense to me but I want to double check that it isn't somehow a legal interpretation of the JLS before I spend any time extracting a MRE.

```
The method apply(capture#15-of ? extends EObject) in the type Function<capture#15-of ? extends EObject,QualifiedName> is not applicable for the arguments (EObject)
```

**Comment by stevenschlansker** [comment]
I think the `capture#15` type means that you need to provide a subtype of `EObject` that matches the captured type. Just an `EObject` isn't specific enough.

**Comment by stephan-herrmann** [comment]
The signature `apply(capture#15-of ? extends EObject)` requires you to pass a value that is a specific subtype of `EObject`, but the actual required type is unknown, so you can never comply, other then passing smth that has that exact same type `capture#15-of ? extends EObject`.

Likely the declaration of the enclosing `Function<capture#15-of ? extends EObject,QualifiedName>` (perhaps some lambda) wasn't typed the way it should be. 

Feel free to re-open if you can show a self-contained reproducer that demonstrates, e.g., that the compiler should actually infer a different signature.
