### ISSUE TITLE
Deprecation warnings are not suppressed in lambdas of deprecated methods

### ISSUE THREAD

**Issue by Madjosz** [eclipse-jdt/eclipse.jdt.core#1370]
Transfer of [Bug 562113](https://bugs.eclipse.org/bugs/show_bug.cgi?id=562113)

# Problem

Adding `@Deprecated` to a method normally tells the compiler to ignore all deprecation warnings in that method. This fails for calls to deprecated methods in a lambda in the deprecated method.

# Example
```java
public class IamDeprecated {
  @Deprecated
  static void deprecatedMethod(Object o) {}
}

public class DeprecationWarning {
  @Deprecated
  void callDeprecated() {
    IamDeprecated.deprecatedMethod(null);                   // no warning
    List.of().forEach(IamDeprecated::deprecatedMethod);     // no warning
    List.of().forEach(o -> IamDeprecated.deprecatedMethod(o)); // warning
  }
}
```
# Expected behaviour
`javac -Xlint:deprecation` shows no deprecation warnings in all 3 cases.

Additional: `@SuppressWarnings("deprecation")` will suppress all 3 warnings when `callDeprecated()` is not `@Deprecated` (and also when it is)

# System information
Eclipse SDK
Version: 2023-12 (4.30)
Build id: I20230911-1800

openjdk version "20.0.2" 2023-07-18
OpenJDK Runtime Environment Temurin-20.0.2+9 (build 20.0.2+9)
OpenJDK 64-Bit Server VM Temurin-20.0.2+9 (build 20.0.2+9, mixed mode, sharing)

Microsoft Windows 10 Pro 10.0.19045

**Comment by srikanth-sankaran** [comment]
I'll take a look

**Comment by Madjosz** [comment]
Confirmed works in I20231004-0320.
