### ISSUE TITLE
Generate reference to classes holding constants used in the code

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#1382]
Originally https://bugs.eclipse.org/bugs/show_bug.cgi?id=549455

We learned that https://bugs.openjdk.org/browse/JDK-7153958 deliberately made javac emit unnecessary CONSTANT_Class entries in class files, to record "dependencies" on classes of which constants have been inlined in the code.

This creates a hidden contract between javac and tools consuming that entry for their analysis, so it should have been driven by a spec change rather than an unannounced implementation change, but given that the change is close to trivial, ecj might as well follow suit.

**Comment by stephan-herrmann** [comment]
In [bug 549455](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549455) it was argued that this extra constant pool entry could also help search in the IDE, but it seems the constant itself still isn't mentioned in the class file. So, https://bugs.openjdk.org/browse/JDK-7153958 fixed only one particular aspect of inlining, without providing a general solution.

**Comment by dct** [comment]
There is also this long-running bug where Eclipse couldn't search for inlined constants defined in jar dependencies: https://bugs.eclipse.org/bugs/show_bug.cgi?id=12044
Do you know if this change that can help fixing that bug?

**Comment by iloveeclipse** [comment]
> Do you know if this change can help fixing that bug?

It depends, assuming the problem is not yet fixed. At least classes "know" now where they are taking constants. The open question if the JDT **search** can use that.

> There is also this long-running bug where Eclipse couldn't search for inlined constants defined in jar dependencies: https://bugs.eclipse.org/bugs/show_bug.cgi?id=12044 

Please check if this is still the case for latest Eclipse build from https://download.eclipse.org/eclipse/downloads/drops4/I20240416-0300/

**Comment by stephan-herrmann** [comment]
> There is also this long-running bug where Eclipse couldn't search for inlined constants defined in jar dependencies: https://bugs.eclipse.org/bugs/show_bug.cgi?id=12044 Do you know if this change can help fixing that bug?

For that to work smoothly https://bugs.openjdk.org/browse/JDK-7153958 was insufficient.

@iloveeclipse is right in that search _could_ now be told to invest extra efforts, to search the sources of all classes that at least mention the class holding the constant. I feel that in many cases this would be an unacceptable performance penalty, but of course we don't know before someone tried. Note that access to the library's sources would indeed be a prerequisite for such a feature.
