### ISSUE TITLE
Problem Marker does not mention finalize() is "for removal"

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1393]
If a method is annotated for removal, the warning should say that. But it does not work for Object.finalize()
**@Deprecated(since="9", forRemoval=true)** 

```
public class A {
@Override
protected void finalize() throws Throwable {
	super.finalize();
}
}
```
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/05b8dc53-5553-479a-9a43-90af761fb313)

for other methods it works:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/cbce3b73-1402-49a1-b882-be105707ce95)

**Comment by jukzi** [comment]
it seem like it depends on the selected Execution environment: 
with 17 (but using jdk20) "removal" is not warned,
but with EE 20 "removal" is detected.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/58c30456-4553-4ec2-b3a2-b445f69717f5)

Feels a bit odd, because using JDK 20 could see the removal even if executed on 17.

**Comment by stephan-herrmann** [comment]
Are you per chance using a `--release` option to set a target version different from the actual JDK found during compilation? If so, then you should indeed see the API as of version 17, where `forRemoval` wasn't yet specified.

**Comment by jukzi** [comment]
i don't know what --release option is - i just created a new java project with the IDE UI, the project is configured to Execution environment 17,  created a class, i have a jdk 20 installed and used. 
So even when executing/building for 17 it could know from the used jdk 20 that the method is already deprecated for removal.

**Comment by jukzi** [comment]
indeed, unchecking "--release" option produces the wanted warning. strange that such option is on by default for jdt but not for javac
