### ISSUE TITLE
[22] Top level JDT.Core Issue for Java 22 support

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1397]
Umbrella bug for Java 22 activities - Ref :
https://openjdk.org/projects/jdk/22/ 
https://openjdk.org/projects/jdk/22/spec/

for updates on 22

Features for Java 22 release:

Batch Compiler:
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1633
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1637
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1596
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1595
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1634
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1636
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1594
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1638
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1896
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1639
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1640
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1758

IDE Support for the relevant above features #2162  (Umbrella bug Targeted for 4.32)

Additional Tracking for Issues
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1703
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2073

And track the JSR 397
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1843

Release Activities captured in:

- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2163

**Comment by snjeza** [comment]
[461: Stream Gatherers (Preview)](https://openjdk.org/jeps/461)

**Comment by srikanth-sankaran** [comment]
Having delivered unnamed patterns and variables I will exclude myself from being an assignee simply to declutter my issues list.

**Comment by mpalat** [comment]
Please note that Java 22 IDE support umbrella bug is targeted for 4.32 although some of the features will be available in P-Build. For the detailed info please take a look at #2162  (Umbrella bug ).
