### ISSUE TITLE
Java 21: "RestrictedIdentifierWhen" with a method starting with a statically imported "when()"

### ISSUE THREAD

**Issue by qtxo** [eclipse-jdt/eclipse.jdt.core#1404]
Given this class

```
package qtxo;
public class WhenMethod {
	static void when(String x) {}
}
```
```
package qtxo;

import static qtxo.WhenMethod.when;

class WhenTokenTest {

    public void whenIsNotFirstToken() {
	    System.currentTimeMillis();
    	    when(null);
    }
	
    public void whenIsFirstToken() {
    	when(null); // <--- ERROR HERE
    }
    
}
```

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/9822844/3bb6d9a9-c32b-4f35-8b0c-6cffc2cdc822)

There is an error: "Syntax error on token "RestrictedIdentifierWhen", while expected"

**Comment by Madjosz** [comment]
Probably related issues: #1209, #456, #609, #59

**Comment by srikanth-sankaran** [comment]
Anything special I need to do to reproduce ? Settings ??

Just creating a project by copy pasting the snippets above doesn't show a problem for me...

**Comment by iloveeclipse** [comment]
I see the error on master. Project should have Java 21 configured.

**Comment by qtxo** [comment]
Duplicate of #456

**Comment by srikanth-sankaran** [comment]
> I see the error on master. Project should have Java 21 configured.

Duh. 

Thanks.
