### ISSUE TITLE
[Patterns] Bizarre code generation for type test patterns

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#1406]
The code generated for type test patterns looks bizarre with and without java 21 change:

Given:
```
public class X {
	public static void main(String[] args) {
		Object o = null;
		if (o instanceof String x) {
			
		}
	}
}
```
We used to generate:
```
public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=2, locals=5, args_size=1
         0: aconst_null
         1: astore_1
         2: aload_1
         3: astore        4
         5: aload         4
         7: instanceof    #16                 // class java/lang/String
        10: ifeq          26
        13: aload         4
        15: checkcast     #16                 // class java/lang/String
        18: dup
        19: astore_2
        20: aload         4
        22: checkcast     #16                 // class java/lang/String
        25: pop2
        26: return
```
but now with Java 21 work merged in we generate:
```
public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=2, locals=4, args_size=1
         0: aconst_null
         1: astore_1
         2: aload_1
         3: astore_3
         4: aload_3
         5: instanceof    #16                 // class java/lang/String
         8: ifeq          22
        11: aload_3
        12: checkcast     #16                 // class java/lang/String
        15: dup
        16: astore_2
        17: aload_3
        18: checkcast     #16                 // class java/lang/String
        21: pop2
        22: return
```

This is suboptimal - what necessitates two checkcasts and the associated loads and stores, I don't yet know.

See what javac generates which is concise and clearly understandable:
```
  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=3, args_size=1
         0: aconst_null
         1: astore_1
         2: aload_1
         3: instanceof    #7                  // class java/lang/String
         6: ifeq          14
         9: aload_1
        10: checkcast     #7                  // class java/lang/String
        13: astore_2
        14: return
```

**Comment by srikanth-sankaran** [comment]
> The code generated for type test patterns looks bizarre with and without java 21 change:

[...]

> See what javac generates which is concise and clearly understandable:

[...]

With https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1963 in place, we generate identical code to javac for this construct. Record patterns continue to have various weirdness and oddities - that is a subject of a follow up ticket.
> 
> ```
>   public static void main(java.lang.String[]);
>     descriptor: ([Ljava/lang/String;)V
>     flags: (0x0009) ACC_PUBLIC, ACC_STATIC
>     Code:
>       stack=1, locals=3, args_size=1
>          0: aconst_null
>          1: astore_1
>          2: aload_1
>          3: instanceof    #7                  // class java/lang/String
>          6: ifeq          14
>          9: aload_1
>         10: checkcast     #7                  // class java/lang/String
>         13: astore_2
>         14: return
> ```

**Comment by srikanth-sankaran** [comment]
@iloveeclipse - This will result in comparator errors for every bundle that uses instanceof pattern matching. FYI - I am happy yo help with any analysis needed. 

The observed effects could be:
1. More compact code that eliminates some `dup` + `aload + checkcast + pop2` sequences.
2. Fewer locals in some methods
3. Change of local variable slot numbers etc

**Comment by iloveeclipse** [comment]
@srikanth-sankaran: thanks for heads up, I've started new I Build to detect & fix issues.

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1781 for the progress.

**Comment by laeubi** [comment]
@srikanth-sankaran you can already see baseline changes as part of the PR here:
- https://github.com/eclipse-jdt/eclipse.jdt.core/runs/21305715442

it might be easier to use this as a basis for analysis in the future instead of waiting for bull aggregator builds, look how PDE collects these information as part of its build:

https://github.com/eclipse-pde/eclipse.pde/blob/9aaa8241609c08733ad33263a9cb28f19f4213e3/Jenkinsfile#L38
https://github.com/eclipse-pde/eclipse.pde/blob/9aaa8241609c08733ad33263a9cb28f19f4213e3/Jenkinsfile#L26-L27

**Comment by iloveeclipse** [comment]
> This will result in comparator errors for every bundle that uses instanceof pattern matching. FYI - I am happy yo help with any analysis needed.
> 
> The observed effects could be:
> 
> 1. More compact code that eliminates some `dup` + `aload + checkcast + pop2` sequences.
> 2. Fewer locals in some methods
> 3. Change of local variable slot numbers etc

From ~50 affected bundles I've picked randomly ~10 class files and all changes I saw were matching exactly your expectation, all points above - less duplicated code, less local variables, cleaner code.

https://download.eclipse.org/eclipse/downloads/drops4/I20240207-0610/ is OK now.
