### ISSUE TITLE
compiler.regression LookupTest.test075 fails on java 21

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1421]
See https://download.eclipse.org/eclipse/downloads/drops4/I20230922-0140/testresults/html/org.eclipse.jdt.core.tests.compiler_ep430I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html#org.eclipse.jdt.core.tests.compiler.regression

test075 - 1.3 | Failure | Unexpected failure. ----------- Expected ------------ ------------ but was ------------ ----------\n 1. ERROR in package2\MyList.java (at line 4)\n public class MyList extends AbstractList implements List {\n ^^^^^^\n The return types are incompatible for the inherited methods List.reversed()\n ----------\n ---------------------- ---------- expected:<[]> but was:<[----------\n 1. ERROR in package2\MyList.java (at line 4)\n public class MyList extends AbstractList implements List {\n ^^^^^^\n The return types are incompatible for the inherited methods List.reversed()\n ----------\n ]>junit.framework.ComparisonFailure: Unexpected failure.----------- Expected ------------------------ but was ----------------------\n1. ERROR in package2\MyList.java (at line 4)\npublic class MyList extends AbstractList implements List {\n^^^^^^\nThe return types are incompatible for the inherited methods List.reversed()\n----------\n---------------------- ----------expected:<[]> but was:<[----------\n1. ERROR in package2\MyList.java (at line 4)\npublic class MyList extends AbstractList implements List {\n^^^^^^\nThe return types are incompatible for the inherited methods List.reversed()\n----------\n]>at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3562)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3252)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1973)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1970)at org.eclipse.jdt.core.tests.compiler.regression.LookupTest.test075(LookupTest.java:2568)at java.base/java.lang.reflect.Method.invoke(Method.java:580)at junit.framework.TestCase.runTest(TestCase.java:177)at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:975)at junit.framework.TestCase.runBare(TestCase.java:142)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at org.eclipse.jdt.core.tests.util.CompilerTestSetup.run(CompilerTestSetup.java:59)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)
-- | -- | --

test075 - 1.4 | Failure | Unexpected failure. ----------- Expected ------------ ------------ but was ------------ ----------\n 1. ERROR in package2\MyList.java (at line 4)\n public class MyList extends AbstractList implements List {\n ^^^^^^\n The return types are incompatible for the inherited methods List.reversed()\n ----------\n ---------------------- ---------- expected:<[]> but was:<[----------\n 1. ERROR in package2\MyList.java (at line 4)\n public class MyList extends AbstractList implements List {\n ^^^^^^\n The return types are incompatible for the inherited methods List.reversed()\n ----------\n ]>junit.framework.ComparisonFailure: Unexpected failure.----------- Expected ------------------------ but was ----------------------\n1. ERROR in package2\MyList.java (at line 4)\npublic class MyList extends AbstractList implements List {\n^^^^^^\nThe return types are incompatible for the inherited methods List.reversed()\n----------\n---------------------- ----------expected:<[]> but was:<[----------\n1. ERROR in package2\MyList.java (at line 4)\npublic class MyList extends AbstractList implements List {\n^^^^^^\nThe return types are incompatible for the inherited methods List.reversed()\n----------\n]>at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3562)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3252)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1973)at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1970)at org.eclipse.jdt.core.tests.compiler.regression.LookupTest.test075(LookupTest.java:2568)at java.base/java.lang.reflect.Method.invoke(Method.java:580)at junit.framework.TestCase.runTest(TestCase.java:177)at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:975)at junit.framework.TestCase.runBare(TestCase.java:142)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at org.eclipse.jdt.core.tests.util.CompilerTestSetup.run(CompilerTestSetup.java:59)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)
-- | -- | --

**Comment by iloveeclipse** [comment]
@jarthana : could you please check?

**Comment by jarthana** [comment]
Looks like this is same as issue #1310

**Comment by jarthana** [comment]
OK, I don't know much about generics and method overriding much, but I am staring by comparing the tests between 1.3/1.4 and 1.5 and here's what I found. The inherited method for a given selector `reversed` are

1.3/1.4:
```
public volatile default SequencedCollection#RAW reversed() , 
public abstract SequencedCollection#RAW reversed()
```

1.5 and above:
```
public default List#RAW reversed() , 
public abstract SequencedCollection#RAW reversed()
```

To me, it looks wrong that we end up with `SequencedCollection#RAW reversed()` while it is declared as `List<E> reversed()` in `java.util.List`

@srikanth-sankaran Can you tell me if I am on the right path here?

**Comment by jarthana** [comment]
Inspecting further, I see that the TypeBinding for List contains two reversed methods:

public volatile default SequencedCollection#RAW reversed() , 
public default List#RAW reversed() 

Looking at the .class of the java.util.List, I see that the first may correspond to a bridge/synthetic method. I don't yet know why we don't have this method in Java 1.5 and above.

**Comment by jarthana** [comment]
We can disregard my earlier point about the bridge method. I see this finally boils down to the following code:

`org.eclipse.jdt.internal.compiler.lookup.MethodVerifier.areReturnTypesCompatible(MethodBinding, MethodBinding, LookupEnvironment)`

Essentially, it's the different check that we use for levels 1.5+ and otherwise:

`return one.returnType.isCompatibleWith(two.returnType);`
vs
`return areTypesEqual(one.returnType.erasure(), two.returnType.erasure());`

My question is, why can't we use `isCompatibleWith()` for compliance 1.4 and below? Is that method not capable of handling it for pre-generic code?

Other interesting factor we should consider is, the JDK in question is unlikely to contain binaries for --release for 1.3 and 1.4.

@srikanth-sankaran I see you added this code. Can you share your thoughts please?

**Comment by stephan-herrmann** [comment]
> My question is, why can't we use `isCompatibleWith()` for compliance 1.4 and below? Is that method not capable of handling it for pre-generic code?

I seem to recall that covariant return types are allowed only since 1.5. In 1.4- different return types would produce independent methods.

**Comment by iloveeclipse** [comment]
Seem to be fixed meanwhile

**Comment by stephan-herrmann** [comment]
> Seem to be fixed meanwhile

probably by stopping to test at 1.3 / 1.4? 

From https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.tests.compiler/pom.xml I would think that tests still run at 1.4, but [current test results](https://download.eclipse.org/eclipse/downloads/drops4/I20240414-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep432I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html) show no match for "test075 - 1.3" nor "test075 - 1.4".

What defines the final set of compliance levels in SDK builds?

Don't get me wrong, I'm not complaining that these levels are dropped, just trying to understand.

**Comment by iloveeclipse** [comment]
See 47bb6022608d9c4cff8254e4529ca82566b9f9b4 & https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1605

**Comment by stephan-herrmann** [comment]
> See [47bb602](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/47bb6022608d9c4cff8254e4529ca82566b9f9b4) & #1605

Aha! PR builds use the list in pom.xml and SDK builds the corresponding list in test.xml :+1:
