### ISSUE TITLE
Field "cannot be resolved or is not a field" when referenced from parent class within annotation

### ISSUE THREAD

**Issue by moikeygraham** [eclipse-jdt/eclipse.jdt.core#1431]
```java
@Deprecated(since = AbstractChild.TEST_CONSTANT) // this now fails
public class Parent extends AbstractChild {
    private static final String REF_OK = AbstractChild.TEST_CONSTANT; // this compiles OK
}

public abstract class AbstractChild implements Constants {
    // redacted for brevity
}

public interface Constants {
    public static final String TEST_CONSTANT = "this is a test";
}
```

The above code sample previously compiled fine with 0 errors, but now causes compilation errors in the latest release of eclipse. The line in question is marked with a comment:  `@Deprecated(since = AbstractChild.TEST_CONSTANT) // this now fails`

Bug seems to be introduced with latest Eclipse release:
Version: 2023-09 (4.29.0)
Build id: 20230907-1323

This issue **does not exist** in the previous Eclipse release:
Version: 2023-06 (4.28.0)
Build id: 20230608-1333

I am using `@Deprecated` in the scenario above for reproduction purposes, but in my real code sample I am using hibernate entity annotations to define a discriminator value which is defined on an `interface` implemented by a child `abstract class`.

**Comment by iloveeclipse** [comment]
I still see this on master / I20230924-0600.
