### ISSUE TITLE
Status of ClasspathJmodTests is unclear

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#1457]
It seems that `org.eclipse.jdt.core.tests.compiler.regression.ClasspathJmodTests` is never executed during builds?

It's not mentioned in any `TestAll` suite.

Unfortunately, it is not possible to search the actual test results for this file, because test results only list the toplevel `TestAll` suite, not individual test classes :(, and test names `test001` - `test005` don't help either.

@jarthana according to history you're the only one who ever actually worked on this test class. Is it (still) of any value and should be fixed (I see 2 failures when running locally), or is it time to retire that class?

**Comment by jukzi** [comment]
locally for me the test fails. Also it seems to be the only thing that uses the undocumented system property `modules.to.load`. Moreover the method org.eclipse.jdt.internal.compiler.util.JRTUtil.reset() seems to be unreferenced and is not needed anymore
![image](https://github.com/user-attachments/assets/350da2d6-ad54-42f6-838e-585890ca5dd5)

**Comment by jarthana** [comment]
This can be removed. I worked on this when the JRT was in a state of flux and we expected jmod entries to become common, which never happened. I will remove this.

**Comment by jukzi** [comment]
> undocumented system property `modules.to.load`.

@jarthana can that property also be removed?

**Comment by jarthana** [comment]
> > undocumented system property `modules.to.load`.
> 
> @jarthana can that property also be removed?

This was meant for tests to limit the modules being loaded into the compiler. I think there's still value in it that tests can use. Having said that, I am surprised to see none of the other tests using it.
