### ISSUE TITLE
Ambiguous method compiling a Java class against Java 11 with Scala 2.13

### ISSUE THREAD

**Issue by vpinna80** [eclipse-jdt/eclipse.jdt.core#1463]
Eclipse Version:
Version: 2023-09 (4.29.0)
Build id: 20230907-1323
Eclipse Java Development Tools 3.19.200.v20230903-1000

The following snippet doesn't compile in Eclipse, but does with Maven 3.84 and OpenJDK 11:

```java
if (newV instanceof Seq) {
    Object[] result = asJava((Seq<?>) newV).toArray(new Object[((Seq<?>) newV).length()]);
}
```

The error given by eclipse is:
```
The method length() is ambiguous for the type Seq<capture#196-of ?>
```

The following instead works, but gives a "Raw type" warning:
```java
Object[] result = asJava((Seq<?>) newV).toArray(new Object[((Seq) newV).length()]);
```

Expected result:
compile normally

**Comment by iloveeclipse** [comment]
> The following snippet 

Could you please provide self containing, compilable Java example, not a snippet?

**Comment by jukzi** [comment]
not enough information provided
