### ISSUE TITLE
Java formatter setting for switch arror opening brace position

### ISSUE THREAD

**Issue by garretwilson** [eclipse-jdt/eclipse.jdt.core#1473]
Here's a snippet from [Java 20 Language Updates § 6 Switch Expressions](https://docs.oracle.com/en/java/javase/20/language/switch-expressions.html) direct from Oracle:

```java
int numLetters = switch (day) {
  case MONDAY, FRIDAY, SUNDAY -> {
    System.out.println(6);
    yield 6;
  }
  …
  default -> {
    throw new IllegalStateException("Invalid day: " + day);
  }
};
```

Eclipse 2023-09 that formats correctly, leaving the opening brace on the same line after the `case` error. But watch what happens when I make it a statement instead of an expression:

```java
switch(day) {
  case MONDAY, FRIDAY, SUNDAY ->
    {
      System.out.println(6);
    }
  …
  default ->
    {
      throw new IllegalStateException("Invalid day: " + day);
    }
}
```

It turns out this is because I had "Brace positions: Blocks in case statement" set to "Next line indented". And I may actually want to keep that for the old-style `case 123:` form, because the braces mean subtly different things in the old style. They don't delimit the logic—they just create a new scope. Thus I might want to keep my `break` outside the block, like this:

```
case 123:
  {
    //TODO stuff
  }
  break;
```

However with the arrow syntax, the braces represent the entire logic, such as the body of a method, so I would want to keep the opening brace on the same line:

```
case 123 -> {
    //TODO stuff
  }
```

Thus it might be useful to have a separate setting "Brace positions: Blocks in case statement after arrow". Or maybe after the arrow simply follow the formatting rule that you use above in a case expression.

This is an extremely low priority request. For the meantime I will change my format setting back to "Brace positions: Blocks in case statement" set to "Same line" and live with it, although as explained above for old-style case blocks I would prefer that opening braces be formatted differently than after an arrow.

**Comment by mateusz-matela** [comment]
Setting added. Thanks for the suggestion, Garret.
