### ISSUE TITLE
Erroneous "Cannot infer type arguments" error

### ISSUE THREAD

**Issue by JackPGreen** [eclipse-jdt/eclipse.jdt.core#1475]
With generics, the `Cannot infer type arguments` error is shown erroneously.

Take the following (simplified, so slightly bizarre) example:
```
public class CannotInferTypeArguments<V extends java.util.concurrent.Semaphore> {
    class Fish {
        public V getFlavour() {
            return null;
        }
    }

    class Shark<E extends Fish> {
    }

    <E extends Fish> Shark<E> fish() {
        // This compiles fine with javac, but will only work in Eclipse with new Shark<E>();
        return new Shark<>();
    }
}
```

This compiles fine with `javac`, but not in Eclipse.
When `new Shark<>()` is changed to `new Shark<E>()`, Eclipse is then happy as well.

This _may_ be related to [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=566989) which the same symptom but with a slightly different scenario.

I've reproduced this in Eclipse 2023-09 (4.29.0) on Windows (Java 19) & OSX (Java 17).

**Comment by stephan-herrmann** [comment]
This is not specify to return statements, also this assignment shows the same problem:
```
Shark<E> s = new Shark<>();
```

Tentatively putting this into my backlog. @srikanth-sankaran feel free to grab, if you have the time :)

**Comment by JackPGreen** [comment]
> This is not specific to return statements, also this assignment shows the same problem:
> 
> ```
> Shark<E> s = new Shark<>();
> ```
> 
> Tentatively putting this into my backlog. @srikanth-sankaran feel free to grab, if you have the time :)

@stephan-herrmann it's good to know I'm not alone on this. Have you been able to make any progress?

**Comment by JackPGreen** [comment]
@stephan-herrmann thanks so much for this!

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann thanks so much for this!

Thanks for reporting this (long-standing) bug :)
