### ISSUE TITLE
Missing modifiers in record bindings

### ISSUE THREAD

**Issue by cart-before-horse** [eclipse-jdt/eclipse.jdt.core#1497]
It seems like there is a bug in [BinaryTypeBinding](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/BinaryTypeBinding.java#L521-L528) class - this code is supposed to add `AccRecord` modifier if target type is `record`. But for some reason this code is inside
```
char[] typeSignature = binaryType.getGenericSignature();
...
if (typeSignature == null)
```
condition branch, which is true as long as the record does not implement any generic interfaces. Otherwise we're getting record binding but without actual record modifier, which causes wrong behaviour later (lack of accessor methods, even NPE).

[Example repo](https://github.com/cart-before-horse/eclipse-jdt-issue-demo) with mapstruct NPE crash

<details>
<summary>stacktrace</summary>

> Internal error in the mapping processor: java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.Element.getKind()" because "element" is null  
>  at org.eclipse.jdt.internal.compiler.apt.model.TypesImpl.asMemberOf(TypesImpl.java:91)     
>  at org.mapstruct.ap.internal.util.AbstractTypeUtilsDecorator.asMemberOf(AbstractTypeUtilsDecorator.java:129)   
>  at org.mapstruct.ap.internal.util.Filters.getWithinContext(Filters.java:142)   
>  at org.mapstruct.ap.internal.util.Filters.getReturnType(Filters.java:114)  
>  at org.mapstruct.ap.internal.util.Filters.recordAccessorsIn(Filters.java:102)  
>  at org.mapstruct.ap.internal.model.common.Type.getPropertyReadAccessors(Type.java:674)     
>  at org.mapstruct.ap.internal.model.common.Type.getAlternativeTargetAccessors(Type.java:1006)   
>  at org.mapstruct.ap.internal.model.common.Type.getPropertyWriteAccessors(Type.java:756)    
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:226)     
>  at org.mapstruct.ap.internal.model.AbstractBaseBuilder.createForgedAssignment(AbstractBaseBuilder.java:98)     
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapping(PropertyMapping.java:824)   
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapping(PropertyMapping.java:788)   
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forge(PropertyMapping.java:319)  
>  at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:326)     
>  at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:169)  
>  at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:145)  
>  at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:256)  
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1418)    
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1382)    
>  at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:294)     
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:418)     
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:181)     
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:135)   
>  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:82)    
>  at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)    
>  at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)   
>  at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)  
>  at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)    
>  at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)    
>  at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)  
>  at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)   
>  at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)   
>  at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:953)    
>  at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)   
>  at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)   
>  at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:406)   
>  at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:371)     
>  at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:338)   
>  at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.incrementalBuildLoop(IncrementalImageBuilder.java:190)    
>  at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:147)   
>  at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:290)     
>  at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:213)   
>  at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)     
>  at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)     
>  at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)  
>  at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)     
>  at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)     
>  at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)  
>  at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)    
>  at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)    
>  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

</details>

Same record bindings:

without implementing generic interface
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/147742748/49a53cf7-7696-41ab-8eac-e962c485e3cf)

with generic interface
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/147742748/8ac19b65-0161-4ab6-9bb2-ee4359edc067)

tried with jre17, jre21, both project compiler and vm in eclipse.ini

**Comment by cart-before-horse** [comment]
@iloveeclipse hi, i have created a pr with unit test & possible fix, as well as some investigation info, please take a look if its ok

**Comment by srikanth-sankaran** [comment]
> @iloveeclipse hi, i have created a pr with unit test & possible fix, as well as some investigation info, please take a look if its ok

I offer to review this and take it forward.

Looks like you haven't signed Eclipse Contributor agreement - Can you look into signing it please ?

Information should be available here: https://www.eclipse.org/legal/ECA.php and here: https://www.eclipse.org/legal/committer_process/re-sign/

**Comment by srikanth-sankaran** [comment]
Problem only shows up when the concerned record class is an inner class.

`BinaryTypeBinding`'s constructor picks up the modifier bits from the `IBinaryType`'s modifiers - and this includes the AccRecord bit computed by ClassFileReader's ctor (CFR is a IBinaryType)

For an inner class, `org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.getModifiers()` drops the AccRecord bit set by `org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.ClassFileReader(byte[], char[], boolean)` in preference for `innerInfo.getModifiers()` - which don't contain any indication of record'ness of inner class (javac and ecj align here)
