### ISSUE TITLE
Code snippets: In Javadoc view code snippets referring to classes or files miss @highlight, @replace, and @link modifications

### ISSUE THREAD

**Issue by howlger** [eclipse-jdt/eclipse.jdt.core#150]
The _Javadoc_ view shows the preview of the code snippets that refer to a class or file, but without the modifications via `@highlight`, `@replace` and `@link`. The `@highlight`/`@replace`/`@link` comments are correctly removed, but not applied. In contrast, including the content directly inside the snippet tag (`{@snippet : ... }`) works as expected.

**Java 18 code to reproduce the issue:**
`Sample.java`:
```java
/**
 * {@snippet class="Other" region="r1"}
 */
public class Sample { }
```
`Other.java` (contained in the source folder to which `--snippet-path` refers when generating Javadoc):
```java
// @start region="r1"
public class Other {
	int field = 42; // @replace substring="42" replacement="1"
}
// @end region="r1"
```

**Result:**
In the Javadoc view and in the hover, 42 should be replaced by 1, but it is not, as the following screenshot shows:
![code_snippets](https://user-images.githubusercontent.com/5197918/174327135-b8ccd840-a916-4cc9-854f-b2eca852a47e.png)

In addition, if the snippet refers to a whole class or file (without `region="..."`), the start, end and modification comments will not be removed in the _Javadoc_ view and in the hover in contrast to the HTML generated by Javadoc.

**Comment by ktatavarthi** [comment]
Created a separate issue for supporting `@link` in external snippets https://github.com/eclipse-jdt/eclipse.jdt.core/issues/302. This bug mainly fixes the `@highlight` and `@replace` support  in external snippets
