### ISSUE TITLE
Completion for unimported types doesn't work

### ISSUE THREAD

**Issue by snjeza** [eclipse-jdt/eclipse.jdt.core#1502]
The related issue - https://github.com/redhat-developer/vscode-java/issues/1123

Steps to reproduce:
- create the following class
```
public class X {
	void foo() {
		new ArrayList<>().|
	}
}
```
- call CA

**Comment by stephan-herrmann** [comment]
As @fbricon mentioned in https://github.com/redhat-developer/vscode-java/issues/1123: an interesting feature :)

@snjeza could you specify what exactly you expect JDT to do? 

When you observed that other tools give meaningful proposals, does this work for any type, or are well-known classes (e.g., in `java.util`) treated specially?

What should JDT do, if the simple type name has multiple candidates in the workspace?

Another question is about the relevance of such feature? Is it common practice to manually type expressions like "new ArrayList<>()" (using completion already at that level would have inserted the import), and only then invoking content assist?

**Comment by snjeza** [comment]
> @snjeza could you specify what exactly you expect JDT to do?

without the PR

![withoutpr](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/388609/05839543-43bd-4570-853a-1f5e7d5feb93)

with the PR

![withpr](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/388609/2c8d216a-027d-470d-ba56-a4919ab1480f)

**Comment by snjeza** [comment]
> When you observed that other tools give meaningful proposals, does this work for any type, or are well-known classes (e.g., in java.util) treated specially?
What should JDT do, if the simple type name has multiple candidates in the workspace?
Another question is about the relevance of such feature? Is it common practice to manually type expressions like "new ArrayList<>()" (using completion already at that level would have inserted the import), and only then invoking content assist?

You may want to take a look at https://github.com/eclipse-jdt/eclipse.jdt.core/blob/d1cf644d0e66878b5c2d56d4d2aad3ad302cf17b/org.eclipse.jdt.core/codeassist/org/eclipse/jdt/internal/codeassist/MissingTypesGuesser.java#L522

**Comment by stephan-herrmann** [comment]
@snjeza  your screencasts show the behavior for one very specific situation, not the general story.

> You may want to take a look at ...

sure the code is the ultimate truth, but perhaps a reviewer (not necessarily me) may want to compare the implementation against the intention. That's why I asked about your expectations / intentions.

**Comment by snjeza** [comment]
> sure the code is the ultimate truth, but perhaps a reviewer (not necessarily me) may want to compare the implementation against the intention. That's why I asked about your expectations / intentions.

> What should JDT do, if the simple type name has multiple candidates in the workspace?

`MissingTypesGuesser` selects the first missing type and offers its completion.

**Comment by snjeza** [comment]
> When you observed that other tools give meaningful proposals, does this work for any type, or are well-known classes (e.g., in java.util) treated specially?

I have tried Netbeans 19 and IntelliJ IDEA 2022.2.5. Please see https://github.com/redhat-developer/vscode-java/issues/1123#issuecomment-1784164367
