### ISSUE TITLE
Recommendation from compiler to drop type arguments leads to compile error

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1506]
Original state: 
Enable "warning" severity for compiler option "Redundant type arguments" like here:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/95152857-516f-4286-8879-0adce74a8f11)

With that option enabled on Java 17 project ecj reports 

```
Description	Resource	Path	Location	Type
Redundant specification of type arguments <File>	X.java	/A/src	line 8	Java Problem
```
on the code below:
```
import java.io.File;
import java.util.Arrays;
import java.util.Iterator;

public class X {

	public Iterable<File> getStackFramesClassesLocations(Object element) {
		return new Iterable<File>() {
			@Override
			public Iterator<File> iterator() {
				return Arrays.stream(new Object[0]) //
						.map(frame -> getClassesLocation(frame)) //
						.iterator();
			}
			
			File getClassesLocation(Object frame) {
				return null;
			}
		};
	}
}
```

So far so good. If we fix that warning by removing type argument from `return new Iterable<File>()`, ecj reports an **error** 

```
Description	Resource	Path	Location	Type
The method getClassesLocation(Object) of type new Iterable<File>(){} must override or implement a supertype method	X.java	/A/src	line 16	Java Problem
```

so the code below is not compilable anymore:

```
import java.io.File;
import java.util.Arrays;
import java.util.Iterator;

public class X {

	public Iterable<File> getStackFramesClassesLocations(Object element) {
		return new Iterable<>() {
			@Override
			public Iterator<File> iterator() {
				return Arrays.stream(new Object[0]) //
						.map(frame -> getClassesLocation(frame)) //
						.iterator();
			}
			
			File getClassesLocation(Object frame) {
				return null;
			}
		};
	}
}
```

The error ecj reports is clearly wrong. It looks like compiler is unable to properly resolve super type and reports some garbage.

Found by occasion, trying to fix org.eclipse.jdt.internal.launching.sourcelookup.advanced.JDIHelpers - on save, the save action automatically removes redundant type argument and the code doesn't compile anymore...

Here is a reduced example that doesn't compile anymore after changing `new Generic<Object>` to `new Generic<>`:

```
public class X {
	public Generic<Object> doSomething(Object element) {
		return new Generic<Object>() {
			void hello() {
			}			
			@Override
			public Object call() {
				return null;
			}			
		};
	}
}
interface Generic<T> {
	T call();
}
```

**Comment by srikanth-sankaran** [comment]
See plausible duplicates:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=576002
https://bugs.eclipse.org/bugs/show_bug.cgi?id=579314

**Comment by stephan-herrmann** [comment]
Look at this error from ecj:
```
The method getClassesLocation(Object) of type new Iterable<File>(){} must override or implement a supertype method	X.java	/A/src	line 16	Java Problem
```

vs this answer from javac 20:
```
X.java:16: error: method does not override or implement a method from a supertype
                        File getClassesLocation(Object frame) {
                             ^
  (due to <>, every non-private method declared in this anonymous class must override or implement a method from a supertype)
1 error
```

ups? I've never heard of this error. When was it introduced? Where specified?

At the bottom line: other then more informative wording in javac's message, ecj and javac are fully in sync in this matter. Cool, huh? :)

**Comment by stephan-herrmann** [comment]
The entire thing is supported since javac 9 (JDT 4.8), where diamonds for anonymous classes were introduced. Any one have the JEP at hand?

**Comment by iloveeclipse** [comment]
> (due to <>, every non-private method declared in this anonymous class must override or implement a method from a supertype)

I'm really surprised to see that! Would be really interesting to read the reasoning behind.

**Comment by srikanth-sankaran** [comment]
From JLS 15.9.5 Anonymous Class Declarations:

```
If a class instance creation expression with a ClassBody uses a diamond (<>) for the
type arguments of the class to be instantiated, then for all non-private methods
declared in the ClassBody, it is as if the method declaration is annotated with
@Override (§9.6.4.4).
When <> is used, the inferred type arguments may not be as anticipated by the programmer.
Consequently, the supertype of the anonymous class may not be as anticipated, and methods
declared in the anonymous class may not override supertype methods as intended. Treating
such methods as if annotated with @Override (if they are not explicitly annotated with
@Override) helps avoid silently incorrect programs.
```

**Comment by srikanth-sankaran** [comment]
https://bugs.openjdk.org/browse/JDK-8062373 made me :)

**Comment by srikanth-sankaran** [comment]
> The entire thing is supported since javac 9 (JDT 4.8), where diamonds for anonymous classes were introduced. Any one have the JEP at hand?

https://openjdk.org/jeps/213
https://bugs.openjdk.org/browse/JDK-8073593

**Comment by srikanth-sankaran** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=551913 - It would appear the fix there is problematic in three ways:

1. It is a partial fix i.e. does not address all scenarios: For the problem snippet in this bug report, we should not have concluded the type arguments are redundant at all.
2. Also the method name introduced there is backwards: `org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.checkDiamondOperatorCanbeRemoved(BlockScope)` is misnamed. We are actually checking whether the *type arguments* can be removed so that diamond operator can be *inserted* (deployed into service)
3. Also `org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.checkDiamondOperatorCanbeRemoved(BlockScope)` is checking whether *every* method in the anonymous class is overriding a super method - *not just whether every non-private method* is overriding a super method. As a result, we don't warn about redundant type arguments in this scenario where we should: 
```
class Foo {
    void foo() {
        var a = new java.util.HashSet<String>();
        var b = new java.util.HashSet<String>(a) {
            public String toString() {
            	return "";
            }
            private void foo() {
            	
            }
        };
    }
}
```

**Comment by srikanth-sankaran** [comment]
Given 

```
public class X<E> {
	static class AX<T>{}
    X(E e) {}
    X() {}
    public static void main(String[] args) {
    	X<? extends AX> x5 = new X<AX<String>>(new AX<String>() { private void foo() {} });
	}
} 
```

javac reports:
```
X.java:11: warning: Redundant type arguments in new expression (use diamond operator instead).
    	X<? extends AX> x5 = new X<AX<String>>(new AX<String>() { private void foo() {} });
    	                                             ^
1 warning
```

while ecj is silent
