### ISSUE TITLE
NLS not supporting Java text-blocks

### ISSUE THREAD

**Issue by frankbenoit** [eclipse-jdt/eclipse.jdt.core#1510]
### Marker

With having the "non-externalized strings" set to INFO, and place the // NON-NLS-1$ at the end of the last line, this is flagged with a marker

````
return """
    some content
    """;  // $NON-NLS-1$
````

Markers information:
Multiple markers at this line
	- Non-externalized string literal; it should be followed by //$NON-NLS-<n>$
	- Non-externalized string literal; it should be followed by //$NON-NLS-<n>$

### Formatter
If the formatter is enabled, "Enable line comment formatting"

````
return """
    some content
    """;  // $NON-NLS-1$
````
The formatter inserts the space after `//`. This does not happen for lines with a simple string literal.

### Quickfix
Quickfix to "Add missing  // '\$NON-NLS-1\$" results in 2 times the comment:
````
return """
    some content
    """; // $NON-NLS-1$ //$NON-NLS-1$
````

### Externalize String Dialog
If I use the dialog to add a Java text block as externalized string, it puts the string literal including 2 double-quotes at the beginning and end, all the indentation of the literal, the \r\n from the source file.
Instead I expect that it only puts in the real string content only.

Generated value:
````
mykey=""\r\n    some content\r\n    ""
````

I expect the value to be:
````
mykey=some content\n
````

**Comment by jjohnstn** [comment]
Remove the space in your NLS comment //$NON-NLS-1$ instead of // $NON-NLS-1$

**Comment by frankbenoit** [comment]
@jjohnstn good catch...

Here we have another problem with the Eclipse formatter.
If the space is not there, on save the formatter add the space. This does not happen with normal strings.

**Comment by frankbenoit** [comment]
Thanks for the fix @jjohnstn 
In this bug description, the last problem description with the Externalize String Dialog is not yet addressed? Should I create a bug in jdt.ui for this? Or re-open this one?

I searched in the code and found that the implementation 
`org.eclipse.jdt.internal.corext.refactoring.nls.NLSHint.stripQuotes(String)`
is not good enough for text block. But I have no idea where I can find a method in Eclipse which can extract this value properly.
