### ISSUE TITLE
No constructor completions for records or parameter info for record constructors

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#1519]
```
public class Main {
public record StringResponse(java.util.List<String> values) {}

public static void main(String[] args) {
   var s = new StringResponse(|

   List.of().stream().map(s -> new StringResponse(|)).toArray()
}

}
```

No constructor completions behind `(`, nor behind `new  ` in both normal and inside lambda

But

```
public class Main {
public record StringResponse(java.util.List<String> values) {}

public static void main(String[] args) {
   StringResponse s = new StringResponse(|

   List.of().stream().map(s -> new StringResponse(|)).toArray()
}

}
```
constructor completions behind `(`, nor behind `new  ` in both normal statements but no inside lambda

Eclipse Release : 4.29

**Comment by snjeza** [comment]
The following code works fine in the jdt master
```
var s = new StringResponse(|
```
and
```
import java.util.List; // <--
public class Main {
public record StringResponse(java.util.List<String> values) {}
public static void main(String[] args) {
   // var s = new StringResponse(
   List.of().stream().map(sr -> new StringResponse(|)).toArray();
}
}
```

**Comment by gayanper** [comment]
It's not about the completions inside the constructer, Its about the constructor it self. We only get documentation when the constructors are provided as part of the completions at the first argument, so that you can choose in case there are overloaded constructors.

But for records this doesn't work in above scenarios.

**Comment by gayanper** [comment]
I think the issue is with the logic which resolves constructors after `new` keyword when there are no expected type binding available. It works for classes and anonymous classes based on interfaces, but not records. I can have a look at this issue

**Comment by gayanper** [comment]
Found out that this was because the record constructors are implicit and they are not tracked by the indexer.
