### ISSUE TITLE
Javadoc tag completion fails when source level is 21

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdt/eclipse.jdt.core#1524]
eg. perform completion at the `|` in a project where the source level is set to 21

```java
package io.github.datho7561;

/**
 * @|
 */
public class MyClass {}
```

Only `@author` appears.

With unit tests, if you make the following change: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1517/files#diff-9c200e3b57583d32dc4efc792a7b796415867270a8ecdaab020967f79b618c07 (but leaving out the new test added in that PR) they will fail

**Comment by jjohnstn** [comment]
This has already been reported with: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/879  @akurtakov has a solution posted to here (jdt.core) which fixes the problem https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1523

**Comment by iloveeclipse** [comment]
> has a solution posted to here (jdt.core) which fixes the problem #1523

Would be good if you could help adding regression tests there

**Comment by jjohnstn** [comment]
Ok

**Comment by datho7561** [comment]
I opened a PR onto @akurtakov 's branch with the test change that Rob made in the PR I referenced
