### ISSUE TITLE
Enhance resource leak analysis with additional annotation(s)

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#1530]
In https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1447#issuecomment-1760403838 I was reminded that resource leak analysis is inherently incomplete when a resource is passed to a method invocation (either as receiver or argument).

This could be improved by supporting one or more additional annotations.

Some references re annotations for resource leak analysis:
* https://stackoverflow.com/questions/75871642/can-jsr-305s-willclose-et-al-annotation-or-one-to-the-same-effect-be-imp
* The above links to https://checkerframework.org/manual/#resource-leak-checker

Their pair of annotations @MustCall and @CalledMethods is actually more general then the issue of resource analysis: in our case we are interested in calls to exactly one method only: `close()`.

In an attempt to generalize in a different direction, I'm thinking of adding a variant of `@Owning`, plus possible `@NotOwning` with the following semantics:
* ~~I'd design these annotations as `TYPE_USE` annotations.~~ No, that would be overselling the idea. This annotation doesn't play well with generics (_also the folks of the Checker Framework came to the same conclusion_).
* passing a resource into a method invocation where the corresponding parameter has an `@Owning` type delegates the responsibility to close the argument resource to the body of the target method.
* invoking a method on a resource instance, where the method has an `@Owning` `this`-parameter delegates the responsibility to close the receiver to the body of the target method.
* returning a value from a method that has an `@Owning` return type, delegates responsibility to close the returned resource to the caller.

In https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1447#issuecomment-1760426031 I imagined a pair of annotations to support the parameter and the receiver scenario, which can be avoided by the above approach as `TYPE_USE` annotation, which will be applicable also to a `this`-parameter.

While we should always be careful with introducing our own annotations with JDT-specific semantics, I think the above approach should be future proof (e.g., in case some day jspecify will specify similar annotations):
* We would again apply the dual strategy of supplying a default annotation type via `org.eclipse.jdt.annotation` (v2) plus an option to specify a custom annotation type via its FQN.
* We would start with minimal semantic evaluation as outlined above, but hopefully other ownership-related evaluation could follow, should such become mainstream in a (distant) future.

Even only an `@Owning` annotation will help to significantly improve analysis, where currently the analysis applies a lot of hand-waiving as to say "may", "potentially" etc.:
* avoid false positives at the origin of a data flow
* strengthen potential problems to errors at the receiving end

Additionally supported `@NotOwning` would improve in the inverse direction:
* avoid false positives at the receiving end
* strengthen some potential problems at the origin of a data flow to error.

**Comment by stephan-herrmann** [comment]
Inviting specifically @srikanth-sankaran, @iloveeclipse, @szarnekow, @brychcy to join the discussion.

I could imagine to present a prototype soon after 2023-12.

Let me know, if you'd like to see some test cases even earlier, as a means to trigger discussion on semantic details.

**Comment by stephan-herrmann** [comment]
Example: In https://github.com/eclipse-jdt/eclipse.jdt.core/commit/e95b184e57e9427d20496ad32ab26342fec7da3b#diff-684993aca2f0ff8f2bdbd5f272e40916d1844f3135ca361ef3eceac8daeb3554 significant complexity is added to coerce resource handling into try-with-resources.  While the changes are well done, nothing of this is strictly necessary: if an `InputStream` is allocated it will always be passed to `new ExternalAnnotationProvider(input, binaryTypeName)`.

Following the proposal in this issue, we'd only need to add `@Owning` to the first parameter of that constructor to indicate: responsibility for closing the input stream is delegated to that constructor and finally to `initialize()`. Inside that method, the input stream is wrapped at 2 levels and the outer resource is governed by try-with-resources. This ensures that also the nested input stream will always be closed.

Obviously, there's a bit too much indirection for the compiler to detect all this as is, but with the help of that one new annotation it could faithfully perform all necessary checks. IOW, we could use that very code example to validate the enhanced analysis.

@jukzi fyi.

**Comment by jukzi** [comment]
Sounds interesting. And there is plenty code left in eclipse platform where it could be used. However such annotation has some drawbacks.
1. `@Owning` is incomplete - often resources are only stored in a class and it is required to call another method thereafter. A `@MustCall("close")` could express that but comes with the drawback, that it involves a string literal which will easy go wrong when the method is renamed.
2. it's not Java Standard which makes it less used.
3. It's wrong to let the programmer add such annotations, as the programmer could get it wrong and declare `@Owning` where in fact the code is not safe. =>`@Owning` is like an inverse `@SupressWarnings`. When i want to have my code verified the verifyer must not trust such annotation,. As far as i read https://checkerframework.org/manual/#resource-leak-checker already offers such analysis.

To me it sound's better to refactor code to be autoclosable with try-with-resource.  Or to pass a `Supplier<Resource>` to the new Owner instead of constructing the resource before and passing the resource instance.

**Comment by stephan-herrmann** [comment]
> 3\. It's wrong to let the programmer add such annotations, as the programmer could get it wrong and declare `@Owning` where in fact the code is not safe.

You should know me better :smile: : I would of course implement as one part of the analysis the following rule:
* if a method receives a resource via a parameter marked `@Owning` then this method must ensure that this resource will be closed on all paths. Otherwise an error is raised.

IOW, it's just a variant of design by contract. API must settle responsibility to either caller or callee. That's all it needs to be as safe as anything (_provide the code with `@Owning` annotations is actually checked by this rules, but for every analysis tool there are plenty of options to fool the tool if you are determined to do so ..._).

**Comment by stephan-herrmann** [comment]
> Or to pass a `Supplier<Resource>` to the new Owner instead of constructing the resource before and passing the resource instance.

That's an interesting option. I wonder why I haven't yet seen this pattern in real code? Perhaps nobody ever thought of it, or perhaps, it's difficult to apply in real world scenarios, or perhaps the API cannot be changed, or I just haven't looked in the right places ...

I imagine that adding a few annotations here and there would be less invasive and in well-written code this could express the exact intention behind the code, and help the compiler to see where existing code *is* in fact safe already (like in the example linked above).

**Comment by jukzi** [comment]
> * if a method receives a resource via a parameter marked `@Owning` then this method must ensure that this resource will be closed on all paths. Otherwise an error is raised.

1. i guess you wont check that on binaries.
2. if the checker does this analysis then we don't need @Owning, because the checker knows it better anyway

**Comment by stephan-herrmann** [comment]
> > * if a method receives a resource via a parameter marked `@Owning` then this method must ensure that this resource will be closed on all paths. Otherwise an error is raised.
> 1. i guess you wont check that on binaries.

The same rule would apply as we already have for null annotations: when compiling a method `m()` the compiler checks if the method adheres to the implementation contract; when compiling a _call_ to method `m()` the compiler checks adherence the the client part of the contract. Nothing more needed.

Shipping binaries that promise to fulfill a contract that has not been checked at build time is just one of infinite ways of intentionally or carelessly causing harm. I don't see preventing such nonsense as a priority.
 
> 2. if the checker does this analysis then we don't need @owning, because the checker knows it better anyway

Which checker do you mean? Where does it say that that particular checker evaluates all this on binaries?

**Comment by jukzi** [comment]
> Which checker do you mean?

The checker you are going to write.

**Comment by stephan-herrmann** [comment]
> > Which checker do you mean?
> 
> The checker you are going to write.

Thanks for clarifying.

So, _in theory_ a checker that can detect whether a method will close a resource it receives as an argument, does not need further help when checking a call site that allocated the resource.

That's what I call "whole system analysis", because for checking one method the analysis must be able to do a full analysis of any call paths that start at this method (those can be very, very huge call graphs). For batch compilation of all sources of an application this could perhaps be made to work if you have unlimited memory and lots of time. For an incremental compiler this is not feasible.

Another reason for wanting an annotation: blame assignment. By marking a parameter as `@Owning` a developer expresses the _intention_ to let the receiving method take responsibility. Now, if there's any path within that method, where the resource is _not closed_, it is the annotation that tells us that we should blame the method implementation, not the caller for this failure to close. If conversely we had a `@NotOwning` (or just absence of `@Owning`) then failure to close would be a bug at the side of the caller.

Design by contract, made explicit ...

**Comment by jukzi** [comment]
> That's an interesting option. I wonder why I haven't yet seen this pattern in real code?

see  for example https://github.com/eclipse-platform/eclipse.platform.ui/pull/1373

**Comment by jukzi** [comment]
> For an incremental compiler this is not feasible.

Why should an incremental compiler be unable to store its results? 
The memory required is very low: just one Bit more per argument. Given that most arguments are not resources it would be feasible to use a sparse representation.

**Comment by stephan-herrmann** [comment]
> Why should an incremental compiler be unable to store its results?

Store where? It would have to be persisted on disk, so the only option I see would be to write this information into the produced .class files, but the format of those is specified by JVMS, not JDT :)

If not in .class files we would be inventing something like .eea files :) -- but I would do that on top of a solution using explicit annotations, not instead.

Next we would need a new mechanism for change propagation: assume `m()` calls `n()` calls `o()`, passing a resource `r` all the way. 
* Initially `n()` always passes the resource to `o()` and `o()` always closes the resource.
* A change is made in the body of `o()` such that closing or `r` is no longer guaranteed.
* The incremental compiler will need to now that now it has to re-compile also `n()` and `m()`, because at this point `m()` has to be flagged as having a resource leak.

No, incremental compilation and whole-system analysis just don't match.

Anyway, I strongly believe explicit design by contract is significantly _better_ than non-local inference, better for the developer to figure out what to do, see, e.g., the topic of blame assignment above.

**Comment by stephan-herrmann** [comment]
It's almost ridiculous how little code changes suffice to give real meaning to an `@Owning` annotation in conjunction with the existing resource analysis. (Just the scaffolding for introducing new options, and detecting the annotation make the change look big).

The real brave can already play with this, the less brave may want to wait a few more days, or ask my help :smile:

**Comment by stephan-herrmann** [comment]
> Inviting specifically @srikanth-sankaran, @iloveeclipse, @szarnekow, @brychcy to join the discussion.
> 
> I could imagine to present a prototype soon after 2023-12.

Yes, PR #1716 is in advanced draft status, and everyone is invited to take a look and play with the new analysis.

Conceptually, all this very seamlessly extends our existing analysis, and also the implementation either uses or copies existing approaches. Actually, the new analysis is much clearer than the existing solution which needed to apply various heuristics in order to give useful results. I've started to disable some of these heuristics, when opting-in to annotation based analysis.

I still wonder, whether the single new annotation is already enough, or if perhaps the inverse annotation `@NotOwning` should be supported at the same time.  Specifically this annotation would enable us to define `@Owning` as the default in certain locations, with opt-out using `@NotOwning`.

I'm curious to hear what people think.

**Comment by stephan-herrmann** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1716#issuecomment-1887874994 for a status summary.
