### ISSUE TITLE
[21] DOM Changes for String Template

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1537]
String template will require new API/changes in DOM models. This can be taken up along with #544 or after completion of it.

**Comment by jarthana** [comment]
I propose two new DOM nodes:

```
1. StringTemplate
       ChildListPropertyDescriptor STRING_TEMPLATE_COMPONENTS =
			new ChildListPropertyDescriptor(StringTemplate.class, "components", Expression.class, CYCLE_RISK);

2. StringTemplateExpression
	ChildPropertyDescriptor TEMPLATE_PROCESSOR =
			new ChildPropertyDescriptor(StringTemplateExpression.class, "processor", Expression.class, MANDATORY, 
CYCLE_RISK);
	ChildPropertyDescriptor STRING_TEMPLATE_PROPERTY =
		new ChildPropertyDescriptor(StringTemplateExpression.class, "template", StringTemplate.class, MANDATORY, CYCLE_RISK);
```

Here are two points that need some discussion:
1. The source range verifier doesn't allow us to put the fragments and embedded expressions in different lists. So, I am of the opinion that we should put them both in a single list. The `STRING_TEMPLATE_COMPONENTS `property mentioned above embodies that.
2. I am tempted to come up with new node for the string fragments, as the current ones (`StringLiteral `and `TextBlock`) fail some of the validation that we have in `getLiteralValue()`. Similarly, reconstructing them will also be a problem as only the first and last fragments get the delimiters.

**Comment by jarthana** [comment]
We should also find a neat way to handle the string fragments that may not have the opening/closing or both delimiters at all. Since we decided to use the StringLiteral compiler AST node for string fragments, that will include the quotes, we have to find a way to provide the escaped value and literal value from the fragments. StringLIteral and TextBlock DOM nodes achieve this with Scanner.getNextToken(). But that's not going to work here.

**Comment by jarthana** [comment]
The proposed PR has different APIs than the ones I initially proposed:
1. `StringFragment` - Same as `StringLiteral` , but does not include the delimiters such as " or """. This way, we will be able to represent all string fragments in a template regardless of where they appear (beginning, middle or end) and whether they are part of a simple string or text block.
2. `StringTemplateComponent` - a pair of embedded expression (`Expression`) and a `StringFragment` (both mandatory).
3. `StringTemplateExpression` - contains a mandatory `FIRST_STRING_FRAGMENT `(`StringFragment`) and optional list of `StringTemplateComponent`. Also includes the delimiters and a boolean property that indicates whether this is a single line string or text block.

**Comment by srikanth-sankaran** [comment]
Please verify this duplicate ticket's scenario is addressed before merging in: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1736
