### ISSUE TITLE
Some build flag/profile to regenerate the parser from Maven build

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#1562]
I'd like to be able to fully rebuild and test jdt.compiler.batch just after a change in the grammar, without need to touch other files. To achieve that, it would be convenient to setup a Maven profile or a flag to trigger the parser generation when building org.eclipse.jdt.compiler.batch. I suspect it's more or less a matter of calling antrun.

**Comment by iloveeclipse** [comment]
Stupid question: wouldn't the project content change after grammar change? Or what's the point of changing grammar without updating the rest of the code?

**Comment by mickaelistria** [comment]
The files generated by the grammar would change, and sometimes the Parser class too; but in enough cases, no code needs to be touched when grammar changes for the change to be effective.
For more context, one goal is also to allow forks to more easily combine pending PRs as part of their build and to more easily produce the combined parser as part of the build. Running the GenerateParser.java as a preliminary step before the whole build can easily work, but it seems more consistent if we can encapsulate that step in the build of the module that requires it.

**Comment by iloveeclipse** [comment]
Not looking into code: should we simply ship grammar in the binary build, so any change there will cause bundle change?

**Comment by mickaelistria** [comment]
The grammar file is a generator file, and the generated parser files have to be manually generated and committed together with changes to the grammar for those to take effect. What I'd like to allow is an alternative to make this less manual and more orchestrated by Maven during regular build, when a flag such as `-Pgenerate-parser` is set.

**Comment by mickaelistria** [comment]
I'm not planning to work further on ECJ, so we can close this issue as I don't have interest in it any more.
