### ISSUE TITLE
Javadoc @value doesnt work as expected (also @implSpec and @implNote)

### ISSUE THREAD

**Issue by Nightenom** [eclipse-jdt/eclipse.jdt.core#1586]
Downstream issue: https://github.com/redhat-developer/vscode-java/issues/3385
Was asked to report it also here

**Comment by jukzi** [comment]
There is no such issue in JDT UI:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/8bcd8cac-fe78-4613-9987-37a10710a1b0)

**Comment by jukzi** [comment]
If you can provide additional information what the problem in JDT should be please reopen with additional information
