### ISSUE TITLE
[22] JEP 456: Unnamed Variables & Patterns

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1595]
Ref: [JEP 456](https://openjdk.org/jeps/456)
Earlier JEP: [JEP 443](https://openjdk.org/jeps/443)

earlier issue: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/893 

Latest Spec Changes : [https://cr.openjdk.org/~abimpoudis/unnamed/latest](https://cr.openjdk.org/~abimpoudis/unnamed/latest)

no changes from earlier  - https://cr.openjdk.org/~abimpoudis/unnamed/jep443-20230322/specs/unnamed-jls.html

**Comment by srikanth-sankaran** [comment]
> Ref: https://openjdk.org/jeps/456 no changes from earlier - https://cr.openjdk.org/~abimpoudis/unnamed/jep443-20230322/specs/unnamed-jls.html
> 
> earlier issue: #893

https://cr.openjdk.org/~abimpoudis/unnamed/jep456-20231017/specs/unnamed-jls.html - This looks like the matching JLS diff ??

**Comment by mpalat** [comment]
> > Ref: https://openjdk.org/jeps/456 no changes from earlier - https://cr.openjdk.org/~abimpoudis/unnamed/jep443-20230322/specs/unnamed-jls.html

This is the spec for Java 21
> 
> https://cr.openjdk.org/~abimpoudis/unnamed/jep456-20231017/specs/unnamed-jls.html - This looks like the matching JLS diff ??

https://cr.openjdk.org/~abimpoudis/unnamed/jep456-20231017/specs/unnamed-jls.html is Java 22 spec - unchanged from the last one  [at the time of writing this]

**Comment by srikanth-sankaran** [comment]
I offer to own and manage this for 22
