### ISSUE TITLE
--enable-preview works only on latest java SDK

### ISSUE THREAD

**Issue by EdoardoPanfili** [eclipse-jdt/eclipse.jdt.core#160]
I need to use "--enable-preview" with java 17 but I can't

It seems that I can use it only with the latest java release. I wont to stay on latest stable versione (17) but with [Pattern Matching for switch](https://openjdk.org/jeps/406) it seems it is not possible now with Eclipse.

Edoardo

**Comment by sravanlakkimsetti** [comment]
That was the decision we have taken to avoid complications of modified or rewritten preview feature in the subsequent releases. It will be quite difficult for us to implement/support different versions of the same feature.

If you have a requirement to use preview features of java 17. Please use Eclipse version 2021-12 (4.22). If you prefer ECJ use ecj version 3.28.0 from [maven central](https://search.maven.org/artifact/org.eclipse.jdt/ecj/3.28.0/jar)
