### ISSUE TITLE
[21] Code completion doesn't work inside String template expressions

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1601]
This should be tried on top of pull #1513 

Any completion inside embedded expressions doesn't work. For e.g. this code:

        String s = STR."""
            \{  |  }
            """;

Initial investigation shows that jdt.ui doesn't recognize the location as valid place for Java constructs (i..e part of a string literal. Not sure if this needs to be fixed in the UI or core yet.

**Comment by jarthana** [comment]
This was fixed via pull #1712. I will just move the tests to compliance 23 in beta branch and close the issue.

**Comment by srikanth-sankaran** [comment]
> This was fixed via pull #1712. I will just move the tests to compliance 23 in beta branch and close the issue.

Just a caution that that PR may only have fixed the problem for string templates and left the text block templates case as future work

**Comment by jarthana** [comment]
> Just a caution that that PR may only have fixed the problem for string templates and left the text block templates case as future work
Pull #1803 covered that.

**Comment by jarthana** [comment]
String templates have been removed and this is no longer relevant.
