### ISSUE TITLE
RFE: warn if equals compares the same values

### ISSUE THREAD

**Issue by xerces8** [eclipse-jdt/eclipse.jdt.core#1609]
This warning would help detect some errors.

Example:

		Date x = new Date();
		if(x.getClass().equals(x.getClass()))
			System.out.println("hello");

This gives no warning, even if the condition is always true.

**Comment by xerces8** [comment]
I case the above is vague:
I'm suggesting a new warning for Java projects , as in under Project Properties / Java Compiler / Errors/Warnings.

In the example above or in general, when the expression involves a get method, theoretically the two invocations of it could return different results, so the code is not always a programming error. If Eclipse would inspect the called method, the the certainty could be higher. For example if it is a simple getter of a bean (like a simple return memberVariable;)

**Comment by iloveeclipse** [comment]
In general this is a domain of static code analysis, so please consider to use spotbugs and report this rfe there.
See https://github.com/spotbugs/spotbugs/issues

**Comment by xerces8** [comment]
FYI:

if(x.getClass()==x.getClass())   also does not trigger a warning

if(x.equals(x))   also not

if(x==x)   does
