### ISSUE TITLE
Full-Builds even on minor changes

### ISSUE THREAD

**Issue by AlBundy33** [eclipse-jdt/eclipse.jdt.core#161]
I think this is a regression at least since Eclipse 2022-03 (and still exists in 2022-06)

For example I've added a `System.out.println("foo")` to a class an existing class and saved it.

The result was an "cleaning output folder for project XYZ"...

I'm not sure but maybe this happens only once in a project after start from Eclipse.
But because I have multiple projects (some are really large) I'm not 100% sure - maybe this also happens multiple times.

This is very anoing because a full build of large projects takes some time... :-(

Feel free to ask if you need more informations.

**Comment by iloveeclipse** [comment]
> Feel free to ask if you need more informations.

Please provide minimal reproducible example. Just changing a random java file & save doesn't trigger a full build for me.

**Comment by AlBundy33** [comment]
The full build is not started everytime I change a file - for example in my large project I've added the System.out again and only the change file was compiled (as expected).

I have no idea when this happens - I only know that this happens every(?) day.

It seems that this happens only in large projects.
Are there some options log when/why a full build is triggered?

**Comment by jukzi** [comment]
This issue misses steps to reproduce. Feel free to reopen with reproducer or provide a PR that fixes your issue.
