### ISSUE TITLE
last step after clean takes very long and ends sometimes in OutOfMemoryException

### ISSUE THREAD

**Issue by AlBundy33** [eclipse-jdt/eclipse.jdt.core#1610]
I don't have that much informations - but I'll add more if needed.

I have some projects in my workspace including a large one with ~140 src-folders and ~36000 java-files.
If a full build is started (triggered by some change or manually by cleaning the project the progess is always

- cleanup project
- compiling source-folder1
- compiling source-folder2
- ...
- compiling last source-folder

after the last step the progress does not update for a very long time where the heap (displayed in statusbar) is maxed out.
during the compilation phases the heap usages goes up and down (usual gc-activity).

Then the result of the build is different from time to time
- eclipse hangs "forever" -> needs to be killed (this happens most of the time - may because I'm to impatient)
- build ends with an OutOfMemoryException
- build comes to end after waiting several minutes (to be ones never measured but I would say ~15min)

According to the progress and memory usage it seems that "something" is done after the build the consumes a lot of memory.

The OutOfMemoryException often happens if all a full build was automatically started (e.g.  after I had to kill eclipse).
Workaround: kill eclipse, start eclipse, disable autobuild, build the small projects one by one, restart eclipse, build the large project.

Can I enable some logging to find out what is done in the last phase?

Eclipse version is 2023-09 on Windows 10, started with -Xmx3.5G

**Comment by jukzi** [comment]
> * eclipse hangs "forever" -

that is probably caused by excessive GC  when memory get's low. try to increase Heap Size by 1GB. If that does not help please provide a downloadable heapdump which can be created with options `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=yourpath`

**Comment by AlBundy33** [comment]
this is excessive GC - but this is always at the end of the compilation-phases.
during the compilation memory and cpu goes up and down.
After the progress-output "compiling ...." of the last folder cpu und memory are maxed out.

So I think that there is something memory intensive at the end but I have no idea how to track it down.

**Comment by iloveeclipse** [comment]
@AlBundy33 :  please follow steps proposed above.

**Comment by jukzi** [comment]
not enough information provided
