### ISSUE TITLE
error in compiling Stanford CoreNLP with the most recent eclipse environment:

### ISSUE THREAD

**Issue by scasadei** [eclipse-jdt/eclipse.jdt.core#1616]
Please refer to the following discussion for more details:
https://github.com/stanfordnlp/CoreNLP/issues/1399
<img width="855" alt="tree_Screenshot 2023-11-22 at 4 44 43 PM" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/484137/49febd8d-1346-4216-8964-53eb9c901f9c">

**Comment by jukzi** [comment]
@scasadei please post a selfcontained minimal reproducer javasource for the error

**Comment by jukzi** [comment]
no information provided
