### ISSUE TITLE
API documentation of GuardedPattern should be corrected

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#1618]
API documentation of GuardedPattern should be corrected. The pattern switch is being a standard feature in Java 21.

**Comment by akurtakov** [comment]
Noise with milestones is due to recreation of the milestone for release tasks automation via GHA.  https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1557

**Comment by akurtakov** [comment]
Yes, it is an explanation why you see my name ^^^ modifying the milestone.

**Comment by subyssurendran666** [comment]
The documentation is already been modified as part of a different ticket. So this issue is being closed
