### ISSUE TITLE
[22] JEP 457: Class-File API (Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1634]
Provide a standard API for parsing, generating, and transforming Java class files. This is a [preview API].
https://openjdk.org/jeps/457

**Comment by stephan-herrmann** [comment]
It looks like JEP 457 will be implemented as an addition to the system libraries. What should JDT do here?

**Comment by mpalat** [comment]
> It looks like JEP 457 will be implemented as an addition to the system libraries. What should JDT do here?

@stephan-herrmann  Nothing to be done here, atleast for now. The only possibility is about using this in JDT's disassembler sometime later in the future (or should we?). Will close this - unless you have some other thoughts.
