### ISSUE TITLE
[22] JEP 458: Launch Multi-File Source-Code Programs

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1636]
Enhance the java application launcher to be able to run a program supplied as multiple files of Java source code. This will make the transition from small programs to larger ones more gradual, enabling developers to choose whether and when to go to the trouble of configuring a build tool.

https://openjdk.org/jeps/458

**Comment by mpalat** [comment]
@jarthana - can you please investigate this? I don't expect any changes in ecj though.

**Comment by jarthana** [comment]
This is not relevant to JDT. Closing the issue.
