### ISSUE TITLE
[22] JEP 462: Structured Concurrency (Second Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1639]
https://openjdk.org/jeps/462
Simplify concurrent programming by introducing an API for structured concurrency. Structured concurrency treats groups of related tasks running in different threads as a single unit of work, thereby streamlining error handling and cancellation, improving reliability, and enhancing observability. 

Investigate for any possible impacts

**Comment by mpalat** [comment]
@subyssurendran666 Could you please investigate this?

**Comment by subyssurendran666** [comment]
> @subyssurendran666 Could you please investigate this?

Sure @mpalat

**Comment by mpalat** [comment]
This is the re-preview discussed in #1114 - same analysis - no changes envisage in jdt.core
