### ISSUE TITLE
[19] 4.25 Y-Build: Y20220623-0600 - BUILD FAILED

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.core#165]
16:17:30  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:validate-classpath (default-validate-classpath) on project org.eclipse.help.webapp: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:validate-classpath failed: org.osgi.framework.BundleException: Bundle org.eclipse.help.webapp cannot be resolved:org.eclipse.help.webapp [36]
16:17:30  [ERROR]   Unresolved requirement: Import-Package: org.eclipse.jdt.core.compiler
16:17:30  [ERROR]     -> Export-Package: org.eclipse.jdt.core.compiler; bundle-symbolic-name="org.eclipse.jdt.core"; bundle-version="3.30.50.qualifier"; version="0.0.0"
16:17:30  [ERROR]        org.eclipse.jdt.core [37]
16:17:30  [ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.core.resources; bundle-version="[3.17.0,4.0.0)"

**Comment by SarikaSinha** [comment]
Now we have different set of errors:
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) on project org.eclipse.equinox.console.ssh.tests: Compilation failure: Compilation failure: 
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[49] 
21:22:36  [ERROR] 	import org.osgi.service.cm.ManagedService;
21:22:36  [ERROR] 	       ^^^^^^^^^^^^^^^^^^^
21:22:36  [ERROR] The import org.osgi.service.cm cannot be resolved
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[70] 
21:22:36  [ERROR] 	private ManagedService configurator;
21:22:36  [ERROR] 	        ^^^^^^^^^^^^^^
21:22:36  [ERROR] ManagedService cannot be resolved to a type
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[97] 
21:22:36  [ERROR] 	when(context.registerService(any(String.class), any(ManagedService.class), any(Dictionary.class)))
21:22:36  [ERROR] 	             ^^^^^^^^^^^^^^^
21:22:36  [ERROR] The method registerService(String[], Object, Dictionary<String,?>) in the type BundleContext is not applicable for the arguments (String, any(ManagedService.class), Dictionary)
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[97] 
21:22:36  [ERROR] 	when(context.registerService(any(String.class), any(ManagedService.class), any(Dictionary.class)))
21:22:36  [ERROR] 	                             ^^^^^^^^^^^^^^^^^
21:22:36  [ERROR] Type mismatch: cannot convert from String to String[]
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[97] 
21:22:36  [ERROR] 	when(context.registerService(any(String.class), any(ManagedService.class), any(Dictionary.class)))
21:22:36  [ERROR] 	                                                ^^^
21:22:36  [ERROR] The method any(Class<ManagedService>) from the type ArgumentMatchers refers to the missing type ManagedService
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[97] 
21:22:36  [ERROR] 	when(context.registerService(any(String.class), any(ManagedService.class), any(Dictionary.class)))
21:22:36  [ERROR] 	                                                    ^^^^^^^^^^^^^^
21:22:36  [ERROR] ManagedService cannot be resolved to a type
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[112] 
21:22:36  [ERROR] 	configurator.updated(props);
21:22:36  [ERROR] 	^^^^^^^^^^^^
21:22:36  [ERROR] ManagedService cannot be resolved to a type
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[178] 
21:22:36  [ERROR] 	configurator = (ManagedService) invocation.getArguments()[1];
21:22:36  [ERROR] 	^^^^^^^^^^^^
21:22:36  [ERROR] ManagedService cannot be resolved to a type
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[178] 
21:22:36  [ERROR] 	configurator = (ManagedService) invocation.getArguments()[1];
21:22:36  [ERROR] 	                ^^^^^^^^^^^^^^
21:22:36  [ERROR] ManagedService cannot be resolved to a type
21:22:36  [ERROR] /home/jenkins/agent/workspace/Y-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.console.ssh.tests/src/org/eclipse/equinox/console/ssh/SshCommandWithConfigAdminTests.java:[196] 
21:22:36  [ERROR] 	configurator.updated(props);
21:22:36  [ERROR] 	^^^^^^^^^^^^
21:22:36  [ERROR] ManagedService cannot be resolved to a type
21:22:36  [ERROR] 10 problems (10 errors)
21:22:36  [ERROR] -> [Help 1]
21:22:36  [ERROR] 
21:22:36  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
21:22:36  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
21:22:36  [ERROR] 
21:22:36  [ERROR] For more information about the errors and possible solutions, please read the following articles:
21:22:36  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
21:22:36  [ERROR] 
21:22:36  [ERROR] After correcting the problems, you can resume the build with the command
21:22:36  [ERROR]   mvn <args> -rf :org.eclipse.equinox.console.ssh.tests

**Comment by sravanlakkimsetti** [comment]
@SarikaSinha Can this be closed now?
