### ISSUE TITLE
False positive "Dead code" compiler error reported on org.eclipse.pde.internal.core.util.PDEJavaHelper.getExternalPackageFragment(String, String)

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1667]
In `org.eclipse.pde.internal.core.util.PDEJavaHelper.getExternalPackageFragment(String, String)` compiler reports now "Dead code" error, the analysis is however not correct.

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/8662b350-32e3-41f0-8729-3986d2d17a07)

@stephan-herrmann : this is regression from commit 4dc7b558f82274580170553b52bd47da43729c9b, could you please check?

**Comment by stephan-herrmann** [comment]
Reduced test case:
```
class EPD {
	public String getModel() { return null; }
}
class IPS {
	public EPD getSupplier() { return null; }
}
public class Foo {
	void m(String packageName, IPS[] packages) {
		String base = null;
		for (IPS spec : packages) {
			EPD desc = spec.getSupplier();
			if (desc != null) {
				base = desc.getModel();
			}
			break;
		}
		if (base != null) {
			System.out.println(); // dead code warning here
		}
	}
}
```

**Comment by iloveeclipse** [comment]
Two other examples I see of same error (looks like same pattern, reporting here just in case) are:
* org.eclipse.jgit.internal.storage.file.Pack.load(WindowCursor, long)
* org.eclipse.jgit.internal.storage.dfs.DfsPackFile.load(DfsReader, long)
