### ISSUE TITLE
Switch statement with `yield` in `synchronized` and try-catch blocks results in `ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by sbrannen** [eclipse-jdt/eclipse.jdt.core#1686]
## Overview

This is potentially related to #1394 but slightly different in that an `ArrayIndexOutOfBoundsException` is thrown instead of an `EmptyStackException`. In addition, the examples here fail with a `yield` statement within a try-catch block in the `default` case and a `yield` statement within a `synchronized` block in a non-default case.

## Version Info

- Eclipse IDE for Java Developers
- Version: 2023-09 (4.29.0)
- Build id: 20230907-1323

## Examples

❌ The following class fails to compile. See `Error` section below for details.

```java
package demo;

public class SwitchExpressionFailure {

	public String demo(String input) {
		return switch (input) {
			case "red" -> {
				synchronized (this) {
					yield "apple";
				}
			}
			default -> {
				try {
					yield "banana";
				}
				catch (Exception ex) {
					throw new IllegalStateException(ex);
				}
			}
		};
	}

}
```

✅ If I leave the `default` case unmodified but move `yield "apple";` outside the `synchronized` block as follows, the class compiles.

```java
public String demo(String input) {
	return switch (input) {
		case "red" -> {
			synchronized (this) {
			}
			yield "apple";
		}
		default -> {
			try {
				yield "banana";
			}
			catch (Exception ex) {
				throw new IllegalStateException(ex);
			}
		}
	};
}
```

✅ If I leave `yield "apple";` in the `synchronized` block but remove the try-catch block from the `default` case as follows, the class compiles.

```java
public String demo(String input) {
	return switch (input) {
		case "red" -> {
			synchronized (this) {
				yield "apple";
			}
		}
		default -> {
			yield "banana";
		}
	};
}
```

## Errors

```
Internal compiler error: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2 at org.eclipse.jdt.internal.compiler.codegen.ExceptionLabel.placeEnd(ExceptionLabel.java:58)	SwitchExpressionFailure.java	/demo/src/main/java/demo	line 0	Java Problem
```

```
Errors occurred during the build.
Errors running builder 'Java Builder' on project 'demo'.
Index 2 out of bounds for length 2
```

```
A save participant caused problems.
  The save participant 'Code Clean Up' caused an exception: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2. See the error log for details.
```

## Related Issues

- #1394

**Comment by srikanth-sankaran** [comment]
I'll take a look tomorrow. If it is overly complicated will identify and assign to original author.

**Comment by srikanth-sankaran** [comment]
Problem arises from the differences between `org.eclipse.jdt.internal.compiler.ast.YieldStatement.generateCode(BlockScope, CodeStream)` and `org.eclipse.jdt.internal.compiler.ast.YieldStatement.generateExpressionResultCodeExpanded(BlockScope, CodeStream)` in how they deal with generation of code responsible for invoking the finally blocks.

The latter is used when a yield statement occurs inside a switch expression that contains a try statement. It seems to be a coarse grain determination - the try statement need not enclose the yield statement - this is puzzling that code generated for a yield statement would be impacted by a non enclosing try block at a distance. Perhaps @mpalat can shed some light on why this is so.

Compare the code between `org.eclipse.jdt.internal.compiler.ast.YieldStatement.generateCode` which reads:

```
	// generation of code responsible for invoking the finally
	// blocks in sequence
	if (this.subroutines != null){
		for (int i = 0, max = this.subroutines.length; i < max; i++){
			SubRoutineStatement sub = this.subroutines[i];
			sub.exitAnyExceptionHandler();
			sub.exitDeclaredExceptionHandlers(codeStream);
                       /* some common identical code not shown here */
                       boolean didEscape = sub.generateSubRoutineInvocation(currentScope, codeStream, this.targetLabel, this.initStateIndex, null);
```


```
        // generation of code responsible for invoking the finally
	// blocks in sequence
	if (this.subroutines != null){
		for (int i = 0, max = this.subroutines.length; i < max; i++){
			SubRoutineStatement sub = this.subroutines[i];
			/* some common identical code not shown here */
			boolean didEscape = sub.generateSubRoutineInvocation(currentScope, codeStream, this.targetLabel, this.initStateIndex, null);
```

It is the _seemingly extra_ calls to 
```
                        sub.exitAnyExceptionHandler();
			sub.exitDeclaredExceptionHandlers(codeStream);
```

that cause the problem. They close the exception table range, which is again attempted to be closed by the call to `sub.generateSubRoutineInvocation` resulting in the AIOOB

**Comment by sbrannen** [comment]
Thanks for addressing this, @srikanth-sankaran! 👍 

Looking forward to the 4.31 release.
