### ISSUE TITLE
[memory] reduce PerProjectInfo.options duplicate strings

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1692]
org.eclipse.jdt.internal.core.JavaModelManager.PerProjectInfo.options contains a lot of duplicate string
example:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/d5b051d8-611f-45a8-bf05-5c5e71cc35d2)

**Comment by iloveeclipse** [comment]
There should be inline() method in JavaModelManager, if I remember it right.
