### ISSUE TITLE
ECJ crashes when an embedded expression contains broken code

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1701]
Given the code:

```
		String s = STR."Hello \{
				foo() + name)
				}!";
```
the compiler throws the following exception:
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.jdt.internal.compiler.parser.Parser.getMethodBodies(Parser.java:12235)

Initial investigation shows that the parseExpression() call inadvertently resets the CompilationUnitDeclaration.types[].

**Comment by srikanth-sankaran** [comment]
Hmm. Two questions: 

(1) I don't see a crash without this PR being pulled into my workspace. I get only:

```
String literal is not properly closed by a double-quote
Syntax error on token ")", delete this token
```

(2) I doubt if the changes to printExpression suffice to reproduce the text block with fidelity. (I am not even sure if it is possible to do so). For instance in test03 of EmbeddedExpressionSelectionTest.java, the expected output string doesn't resemble the program text.

**Comment by jarthana** [comment]
> Hmm. Two questions:
> 
> (1) I don't see a crash without this PR being pulled into my workspace. I get only:
> 
> ```
> String literal is not properly closed by a double-quote
> Syntax error on token ")", delete this token
> ```

My bad. The testcase has to have a redundant type, which I removed during clean-up. Sigh. PR #1705 adds a new test.

> (2) I doubt if the changes to printExpression suffice to reproduce the text block with fidelity. (I am not even sure if it is possible to do so). For instance in test03 of EmbeddedExpressionSelectionTest.java, the expected output string doesn't resemble the program text.

Are you talking about the indentation or the escapes? The latter, I have no idea about. But I find the indentation to be as expected.
