### ISSUE TITLE
[22] Create Java 22 constants and test framework changes

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1703]
Java 22 related constants and tests to be created. The following wiki page outlines the changes required for every such revision:

https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/Adding-support-for-new-Java-version-and-Features-in-JDT

Note: If something found missing, please feel free to update the document.

**Comment by jarthana** [comment]
> Can we get the constants (and only them!) in master branch? That would allow to reuse them in other places (e.g. jdt.ls, jdt.ui,pde, ..) . As long as these are not supported as e.g. target by the compiler (in master branch) there should be no legal concern. 

Agreed, we can and should put the API constants and even the test framework changes that test the 22 Java Runtime. Only thing we can't add is the Java Language feature changes themselves.

**Comment by mpalat** [comment]
> https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/Adding-support-for-new-Java-version-and-Features-in-JDT

Sure @jarthana - will look at this

**Comment by mpalat** [comment]
refer PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1841

**Comment by mpalat** [comment]
I don't see any more changes under this issue - resolving. Any new/related constant additions can be taken via new issue(s).
