### ISSUE TITLE
[21][Formatter] Formatter changes for Pattern Switches

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1709]
ref the feature here : https://github.com/eclipse-jdt/eclipse.jdt.core/issues/891 - Formatter changes as "deemed appropriate".
@mateusz-matela could you please take a look? Thanks

**Comment by mateusz-matela** [comment]
As far as I can tell, changes in JEP 441 do not require updates in the formatter. Of course, please reopen if I missed something.
