### ISSUE TITLE
[21][Formatter] Formatter changes for Record Patterns

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1710]
Please see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/892 for Record Patterns feature - This issue is about formatter changes as deemed fit for Record Patterns @mateusz-matela could you please take a look? Thanks

**Comment by mateusz-matela** [comment]
As far as I can tell, changes in JEP 440 do not require updates in the formatter. Of course, please reopen if I missed something.
