### ISSUE TITLE
[21] Processed string templates falsely contain backslash characters

### ISSUE THREAD

**Issue by kriegaex** [eclipse-jdt/eclipse.jdt.core#1719]
@jarthana, @mpalat, @srikanth-sankaran

Tested with _ecj-3.37.0-20231209.011330-8.jar_, i.e. probably with a build based on commit a476dd1a7f83a3a56332d9e9e17456801e54c983.

This works as expected:

```java
/**
 * Examples taken from <a href="https://openjdk.org/jeps/430">JEP 430</a>
 */
public class StringPatternsPreview1 {
  public static void main(String[] args) {
    // Embedded expressions can be strings
    String firstName = "Bill", lastName = "Duck";
    System.out.println(STR."\{firstName} \{lastName}");

    // Embedded expressions can be used in multi-line strings
    String title = "My Web Page";
    String text = "Hello, world";
/*
    String html = STR."""
      <html>
        <head>
          <title>\{title}</title>
        </head>
        <body>
          <p>\{text}</p>
        </body>
      </html>
      """;
    System.out.println(html);
*/
  }
}
```

```text
$ java -jar 'c:\Users\Alexa\.m2\repository\org\eclipse\jdt\ecj\3.37.0-SNAPSHOT\ecj-3.37.0-SNAPSHOT.jar' --enable-preview --release 21 src/main/java/StringPatternsPreview1.java
(...)

$ java --enable-preview -cp src/main/java StringPatternsPreview1
Bill Duck
```

Now activate the commented-out section and try again:

```text
$ java -jar 'c:\Users\Alexa\.m2\repository\org\eclipse\jdt\ecj\3.37.0-SNAPSHOT\ecj-3.37.0-SNAPSHOT.jar' --enable-preview --release 21 src/main/java/StringPatternsPreview1.java
(...)

$ java --enable-preview -cp src/main/java StringPatternsPreview1
\Bill \Duck
<html>
  <head>
    <title>My Web Page</title>
  </head>
  <body>
    <p>Hello, world</p>
  </body>
</html>
```

See? Suddenly, there is a side effect of the second string template interpolation on the result of the first! Instead of `Bill Duck` it unexpectedly prints `\Bill \Duck`. I noticed this by chance when preparing a smoke test for the upcoming AspectJ version and immediately tested with upstream ECJ.

**Comment by kriegaex** [comment]
BTW, if you are interested in a longer version of my test, it is [here](https://github.com/eclipse-aspectj/aspectj/blob/0cdc5cfa5ca270a610517aa3117f1d679717eaf7/tests/features1921/java21/StringPatternsPreview1.java). The declarative version of my assertions on the expected output can be found in [this file](https://github.com/eclipse-aspectj/aspectj/blob/0cdc5cfa5ca270a610517aa3117f1d679717eaf7/tests/src/test/resources/org/aspectj/systemtest/ajc1921/ajc1921.xml#L194-L223). There is also a TODO comment for the one line rendered incorrectly, pointing to this issue.

**Comment by srikanth-sankaran** [comment]
Thanks for the report. Reproduced. Bizarre to say the least. Investigating

**Comment by srikanth-sankaran** [comment]
Smallest test case that shows the problem:

```
public class X {
  public static void main(String[] args) {
    String name = "Bill";
    System.out.println(STR."\{name}");
    
    String html = STR."""
         \{name}
      """;
   
  }
}
```

Scanner seems to return wrong text fragments. Jay please take a look. TIA

**Comment by srikanth-sankaran** [comment]
As I mentioned here: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1517#issuecomment-1818157439 : , it is a good practice to grab all the code snippets in the JEP document into a regression test. So we know there is basic coverage. Not late even now.

**Comment by jarthana** [comment]
The problem is the stale `Scanner#textBlockOffset` left by the previous calls to `scanForTextBlock()` via `jumpOverBody()`. Perhaps, we can avoid lot of things that we do for templates and embedded expressions if  scanner#diet is true. But for this issue (and #1722), just resetting just as we enter `scanForStringLiteral()` seems sufficient.



> As I mentioned here: [#1517 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1517#issuecomment-1818157439) : , it is a good practice to grab all the code snippets in the JEP document into a regression test. So we know there is basic coverage. Not late even now.

Most of the current tests in `StringTemplateTest `were taken from the JEP. I will do another pass if something is missing. In this case, it was the combination of two tests that caused the issue.

**Comment by kriegaex** [comment]
> As I mentioned here: [#1517 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1517#issuecomment-1818157439) : , it is a good practice to grab all the code snippets in the JEP document into a regression test. So we know there is basic coverage.

I agree with you. I mentioned that several times before, e.g. in a comment on a JDK 19 issue more than a year ago , see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/450#issuecomment-1271445356:

>> Another potentially helpful idea is to always try to incorporate code examples from the corresponding JEPs into the test bed and compare the behaviour to Javac. Of course, that does not in any way replace implementing the JEP based on the JVM spec, but having a few obvious test cases might help to drive design and implementation and gain additional confidence before merging a beta branch into main.
