### ISSUE TITLE
[21] Pattern-matching in `instanceof` doesn't work

### ISSUE THREAD

**Issue by boris-petrov** [eclipse-jdt/eclipse.jdt.core#1726]
```java
class Main {
	record A(int x) {
	}

	public int foo(Object a) {
		return a instanceof A(int x) ? x : 1;
	}
}
```

This leads to an error: `This method must return a result of type int` which is wrong.

**Comment by srikanth-sankaran** [comment]
Reproduced, I'll take a look. Initial investigation shows parse tree looks bad: has a return statement with no expression.

**Comment by srikanth-sankaran** [comment]
Problem arises since we leave the optional modifiers for the `RecordPattern `s `ReferenceType` unclaimed.

RecordPattern ::= **Modifiersopt** ReferenceType PushLPAREN PatternListopt PushRPAREN

This messes up the `expressionLengthStack` and bad things happen from then on

**Comment by boris-petrov** [comment]
@srikanth-sankaran thanks for so quickly handling the issues I opened! As I'm not familiar with the release process here, can I expect these issues to be fixed some time for Eclipse 2023-12 or do I have to wait for the next major release (2024-03)?

**Comment by akurtakov** [comment]
2023-12 is done deal and all work goes against 2024-03 which you can try (and even use as your main IDE) if you get the I-build from https://download.eclipse.org/eclipse/downloads/index.html .
Note that commits make it to the builds after a successful build, usually on the next day.

**Comment by Madjosz** [comment]
Confirmed works in Eclipse SDK build I20231212-0120.
