### ISSUE TITLE
[Sealed types][Switch] Pattern switch - ECJ accepts code rejected by javac 

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#1735]
```
class X {
		void foo(I<X> ix) {
			switch(ix) {
			case A<Y> ay -> System.out.println();
			case B<X> bx -> System.out.println();
			}
		}
}
class Y extends X {}
class Z extends X {}

sealed interface I<T> permits A, B {
}

final class B<T> implements I<X> {
}


final class A<T> implements I<X> {
}
```

ECJ 4.30 compiles this code while, javac 21 complains:

```
X.java:7: error: I<X> cannot be safely cast to A<Y>
			case A<Y> ay -> System.out.println();
			     ^
X.java:9: error: I<X> cannot be safely cast to B<X>
			case B<X> bx -> System.out.println();
			     ^
2 errors

```

**Comment by srikanth-sankaran** [comment]
@mpalat Let us discuss.

Separately, can we construct a test case for each of these bullets of 14.11.1.1 ??

```
A set of case elements, P, covers a type T if one of the following cases applies:

...

• The type T names an abstract sealed class or sealed interface C and for
every permitted direct subclass or subinterface D of C, one of the following two
conditions holds:
1. There is no type that both names D and is a subtype of T, or
2. There is a type U that both names D and is a subtype of T, and P covers U.
```

**Comment by srikanth-sankaran** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/587 and
https://bugs.eclipse.org/bugs/show_bug.cgi?id=579360 may relate to that part of JLS

**Comment by mpalat** [comment]
> #587 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=579360 may relate to that part of JLS

@srikanth-sankaran the snippet  in the issue above is from next para of JLS. And that's how I was thinking that must be the we need to construct the test case.

**Comment by srikanth-sankaran** [comment]
> > #587 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=579360 may relate to that part of JLS
> 
> @srikanth-sankaran the snippet in the issue above is from next para of JLS. And that's how I was thinking that must be the we need to construct the test case.

Thanks it was useful to decode the meaning of those two bullets.

**Comment by mpalat** [comment]
> @mpalat Let us discuss.
> 
> Separately, can we construct a test case for each of these bullets of 14.11.1.1 ??
> 
> ```
> A set of case elements, P, covers a type T if one of the following cases applies:
> 
> ...
> 
> • The type T names an abstract sealed class or sealed interface C and for
> every permitted direct subclass or subinterface D of C, one of the following two
> conditions holds:
> 1. There is no type that both names D and is a subtype of T, or
> 2. There is a type U that both names D and is a subtype of T, and P covers U.
> ```

@srikanth-sankaran coming to think of it I believe the next code snippet has the answer to it:
`sealed interface J<X> permits D, E {}
final class D<Y> implements J<String> {}
final class E<X> implements J<X> {}
static int testExhaustive2(J<Integer> ji) {
return switch(ji) { // Exhaustive!
case E<Integer> e -> 42;
};
}`

Let us iterate through the permitted types of J<X> which are D and E. However, our type is J<Integer>. 
a) For D, the first condition "There is no type that both names D and is a subtype of T," is met -> Though there is D, D<Y> implements J<String> and  hence it cannot be a subtype of T, where the T here is J<Integer>.  So we don't go beyond for D
b)Now for E, there indeed is a type that names E, which E<X> , and in P we do have a type U that names E, which is E<Integer> , and P covers U [why? -> because of first condition: "P covers a type U where T and U have the same erasure."] - so this would be an example of second condition being met. wdyt?

**Comment by srikanth-sankaran** [comment]
JLS 14.11.1 Switch Blocks: 

```
The switch block of a switch statement or a switch expression is switch
compatible with the type of the selector expression, T, if all of the following are
true:
• If a null literal is associated with the switch block, then T is a reference type.
• For every case constant associated with the switch block that names an enum
constant, the type of the case constant is assignment compatible with T (§5.2).
• For each case constant associated with the switch block that is a constant
expression, the constant is assignment compatible with T, and T is one of char,
byte, short, int, Character, Byte, Short, Integer, or String.
• Every pattern p associated with the switch block is applicable at type T
(§14.30.3).
Switch blocks are not designed to work with the types boolean, long, float, and double.
The selector expression of a switch statement or switch expression can not have one of
these types.
The switch block of a switch statement or a switch expression must be switch
compatible with the type of the selector expression, or a compile-time error occurs.
```

JLS 14.30.3 Properties of Patterns
```
A pattern p is said to be applicable at a type T if one of the following rules apply:
• A type pattern that declares a pattern variable of a reference type U is applicable
at a reference type T if T is checked cast convertible to U (§5.5).
```

And JLS 5.5 Casting Contexts: 

```
If a casting context makes use of a narrowing reference conversion that is checked
or partially unchecked (§5.1.6.2, §5.1.6.3), then a run time check will be performed
on the class of the expression's value, possibly causing a ClassCastException.
Otherwise, no run time check is performed.
If an expression can be converted to a reference type by a casting conversion other
than a narrowing reference conversion which is unchecked, we say the expression
(or its value) is checked cast compatible with the reference type.
If an expression of reference type S is checked cast compatible with another
reference type T, we say that the type S is checked cast convertible to type T.
```

**Comment by srikanth-sankaran** [comment]
This snippet compiles with no unchecked conversions using ECJ:

```
class X {
		void foo(I<X> ix) {
			A<Y> ay = (A<Y>) ix;
			B<X> bx = (B<X>) ix;
		}
}
class Y extends X {}
class Z extends X {}

sealed interface I<T> permits A, B {
}

final class B<T> implements I<X> {
}


final class A<T> implements I<X> {
}
```

javac says: 
```
X.java:3: warning: [unchecked] unchecked cast
			A<Y> ay = (A<Y>) ix;
			                 ^
  required: A<Y>
  found:    I<X>
X.java:4: warning: [unchecked] unchecked cast
			B<X> bx = (B<X>) ix;
			                 ^
  required: B<X>
  found:    I<X>

```

**Comment by srikanth-sankaran** [comment]
While playing around with some snippets, I ran into this which is rejected by javac but accepted by ECJ: 

```
public record X<T>(int x) {
	public static void main(String[] args) {
		Object o = new Object();
		switch (o) {
		case X<String>(int x):
		default:
		}
	}
}
```
