### ISSUE TITLE
Performance : getMainTypeName in CompilationUnitDeclaration is called very often

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-jdt/eclipse.jdt.core#1747]
getMainTypeName in CompilationUnitDeclaration is called very often
add a cash to increase performance

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/3462260/c8d907fe-6943-4660-b96e-27e057ae272b)

**Comment by jukzi** [comment]
my sampling says getMainTypeName is irrelevant compared to other things:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/441a9e4f-03b7-4122-a835-ad93536dfafd)

but maybe you have a special usecase?
