### ISSUE TITLE
Incorrect type inference leads to ambiguous method resolution

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#1753]
The following code example gives a compilation error.

```java
import org.junit.jupiter.api.Assertions;

public class StateTestHelper {

    interface Data {}

    @SuppressWarnings("unchecked")
    public <T extends Data> T getData() {
        return (T) new Data() {};
    }

    public void testData() {
        // hover over getData to see that the return type is Data
        getData();
        // d is correctly inferred as Data and hovering is same as above
        var d = getData();
        // hover over getData to see that the return type is Short!
        Assertions.assertEquals(getData(), getData()); // error: The method assertEquals(short, short) is ambiguous for the type Assertions
    }
}
```

While method resolution is complex, I don't see how inferring `Short` is viable since it's not a subtype or a supertype of `Data` and erasure should erase `T` to `Data`. It seems to me that it should work like the following snippet:

```java
var d1 = getData(); // Data
var d2 = getData(); // Data
Assertions.assertEquals(d1, d2); // assertEquals(Object expected, Object actual) - good
```

If the types of `d1` and `d2` are inferred correctly, inlining them should not cause ambiguities.

Note also that if I add a method to `Data`:
```java
interface Data {

    int getid();
}
```
then inference works well again even inlined:
```java
// hover over getData to see that the return type is Data
Assertions.assertEquals(getData().getid(), getData().getid()); // assertEquals(int expected, int actual) - good
```

Using:
Version: 2023-09 (4.29)
Build id: I20230903-1000
Java 21

**Comment by srikanth-sankaran** [comment]
Two questions: 

1. Do you actually get the message `error: The method assertEquals(short, short) is ambiguous for the type Assertions` ? I get `The method assertEquals(Short, Short) is ambiguous for the type X` - see the use of Boxed type vs primitive in messages,
2. Did you compile with javac ? I get the following error when I try:
```
X.java:35: error: reference to assertEquals is ambiguous
        Assertions.assertEquals(getData(), getData());
                  ^
  both method assertEquals(Double,Double) in Assertions and method assertEquals(Character,Character) in Assertions match
1 error
```

**Comment by srikanth-sankaran** [comment]
```
var d1 = getData(); // Data
var d2 = getData(); // Data
Assertions.assertEquals(d1, d2); // assertEquals(Object expected, Object actual) - good
```

It is not surprising that this works. In these scenario, getData() is invoked with no expected type from expression context and so return type is inferred to be Data and Data being a subtype of only Object and none of the other parameter types of assertEquals - there is only one method applicable candidate to choose from all the overloads.

```Assertions.assertEquals(getData().getid(), getData().getid()); // assertEquals(int expected, int actual) - good
```
It is not surprising that this works either. In this case, the call to `getData()` is not featuring in an invocation context. It is the chained call to ` getData().getid()` that is featuring in an invocation context. Thus there is no expected type from the context to `getData()` invocation and so the inferred return type defaults to `Data`

**Comment by srikanth-sankaran** [comment]
Here is a short version that **does not** compile with **both JDK21 and Eclipse** master:

```
public class X {

    interface Data {}

    @SuppressWarnings("unchecked")
    public <T extends Data> T getData() {
        return (T) new Data() {};
    }
    
	public static void assertEquals(Short expected, Short actual) {}

	public static void assertEquals(Byte expected, Byte actual) {}

	public static void assertEquals(Object expected, Object actual) {}

    public void testData() {
       assertEquals(getData(), getData());
    }
}
```

Eclipse says: `The method assertEquals(Short, Short) is ambiguous for the type X`
Javac says: `error: reference to assertEquals is ambiguous
       assertEquals(getData(), getData());
       ^
  both method assertEquals(Short,Short) in X and method assertEquals(Byte,Byte) in X match`

**Comment by srikanth-sankaran** [comment]
JLS 18.5.2 Invocation Type Inference reads:
```
Given a method invocation expression that provides no explicit type arguments,
and a corresponding most specific applicable generic method m, the process to
infer the invocation type (§15.12.2.6) of the chosen method may require resolving
additional constraints, both to assert compatibility with a target type and to assert
validity of the method invocation's argument expressions.
It is important to note that multiple "rounds" of inference are involved in finding the type of
a method invocation. This is necessary, for example, to allow a target type to influence the
type of the invocation without allowing it to influence the choice of an applicable method.
The first round (§18.5.1) produces a bound set and tests that a resolution exists, but does
not commit to that resolution. Subsequent rounds reduce additional constraints until a final
resolution step determines the "real" type of the expression.
```

The operative sentence is ` This is necessary, for example, to allow a target type to influence the
type of the invocation without allowing it to influence the choice of an applicable method.`

So `assertEquals(Short expected, Short actual) {}` and `public static void assertEquals(Byte expected, Byte actual) {}` are both very much applicable method and we have trouble picking the most specific one among them. 

Ergo: I don't see a defect here. I will wait for you to confirm the behavior against javac and unless it compiles for you (it doesn't with javac for me per above), I will close this as Won't Fix

**Comment by srikanth-sankaran** [comment]
Inserting a cast thusly: `assertEquals((Data) getData(), (Data) getData());` eliminates the ambiguity but now results in a warning: ` Unnecessary cast from X.Data to X.Data` - The warning is wrong obviously and needs to be fxed

**Comment by nlisker** [comment]
> Two questions:
> 
> 1. Do you actually get the message `error: The method assertEquals(short, short) is ambiguous for the type Assertions` ? I get `The method assertEquals(Short, Short) is ambiguous for the type X` - see the use of Boxed type vs primitive in messages,

Yes, when using the Junit Jupiter dependency as in my initial example. Here's a screenshot:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/37422899/f58b8afb-9f09-48f2-b181-cac5c0978550)

> 2. Did you compile with javac ? I get the following error when I try:
> 
> ```
> X.java:35: error: reference to assertEquals is ambiguous
>         Assertions.assertEquals(getData(), getData());
>                   ^
>   both method assertEquals(Double,Double) in Assertions and method assertEquals(Character,Character) in Assertions match
> 1 error
> ```

Same.

**Comment by nlisker** [comment]
> So `assertEquals(Short expected, Short actual) {}` and `public static void assertEquals(Byte expected, Byte actual) {}` are both very much applicable methods and we have trouble picking the most specific one among them.

I understand, but the only method out of the 3 in your example that should be valid is the `Object` overload since `Data` is a subtype of `Object` and nothing else. There is no way `Short` or `Byte` could match.

**Comment by nlisker** [comment]
Even without the method resolution issue, if you hover over `getData()`, the tooltip shows:
```
<Short> Short StateTestHelper.getData()
```
But this can never be correct as `Short` is not a valid replacement for the bounded type `T extends Data`.

**Comment by srikanth-sankaran** [comment]
> Even without the method resolution issue, if you hover over `getData()` (in the method argument position), the tooltip shows:
> 
> ```
> <Short> Short StateTestHelper.getData()
> ```
> 
> But this can never be correct as `Short` is not a valid replacement for the bounded type `T extends Data`.

This is just a red herring. Eclipse compiler computes the _binding_ associated with the `getData()` method invocation to be `ProblemMethodBinding` with the problem type to `Ambiguous` - In such cases for further processing  one among the applicable choices is chosen as the _closest match_ - this is what you are seeing.

**Comment by srikanth-sankaran** [comment]
> > So `assertEquals(Short expected, Short actual) {}` and `public static void assertEquals(Byte expected, Byte actual) {}` are both very much applicable methods and we have trouble picking the most specific one among them.
> 
> I understand, but the only method out of the 3 in your example that should be valid is the `Object` overload since `Data` is a subtype of `Object` and nothing else. There is no way `Short` or `Byte` could match as the method returns `T extends Data`.

True. But method overload resolution works in a certain way in Java - JLS 15.12 Method Invocation Expressions documents this in excruciating detail.  First the applicable methods are chosen, then the most specific method is chosen and if the most specific method is generic mentioning a type variable in its return type, its invocation type is computed - all in that order. Where we have multiple applicable methods but are not able to determine the most specific method - we declare ambiguity and stop.

It is very much conceivable that the most specific applicable method may not be the  appropriate method - see JLS 15.12.3

I don't see an ECJ bug here. It is just a case of your running into what is seemingly confusing. See the javac message mentioning `both method assertEquals(Double,Double) in Assertions and method assertEquals(Character,Character) in Assertions match` - neither Double nor Character implements Data - same head scratching situation as the tool tip situation you call out,
