### ISSUE TITLE
[22] JEP 464: Scoped Values (Second Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1758]
Introduce scoped values, which enable the safe and efficient sharing of immutable data within and across threads. They are preferred to thread-local variables, especially when using large numbers of virtual threads.

ref: https://openjdk.org/jeps/464

**Comment by mpalat** [comment]
@subyssurendran666  Could you please take a look at this? Thanks!
Also, check the comment https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1113#issuecomment-1826174630?

**Comment by subyssurendran666** [comment]
@mpalatI have investigated this matter, and it appears that no action is required.

**Comment by mpalat** [comment]
Thanks @subyssurendran666  - closing
