### ISSUE TITLE
Bogus warning for unassigned resource in ternary expression

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#1762]
With resource leak enabled, the following snippet is marked inconsistently:
```java
void m(String path, ClassLoader loader) throws IOException {
	try (InputStream input = loader == null ? new FileInputStream(path) : loader.getResourceAsStream(path)) {
		// read
	}
}
```

The allocation expression is understood well, but at the else branch of the ternary we see a bogus:
```
Potential resource leak: '<unassigned Closeable value>' may not be closed
```

**Comment by stephan-herrmann** [comment]
While working on a fix I noticed, that switch expressions are integrated with this analysis on poorly:
```java
import java.io.*;
class A {
	void a(int i) throws Exception {
		FileInputStream in = switch (i) {
			case 1 -> new FileInputStream("a");
			case 2 -> open("b");
			case 3 -> { yield new FileInputStream("c"); }
			case 4 -> { yield open("d"); }
			default -> open("e");
		};
	}
	FileInputStream open(String fn) throws Exception { return new FileInputStream(fn); }
}
```
Here we raise warnings against `in` and all `open()` calls, but not against the allocation expressions.
In fact, the warning against `in` should suffice. Ergo, during analysis we fail to associate the `open()` calls to the local variable.

**Comment by basilevs** [comment]
Is this the same as https://bugs.eclipse.org/bugs/show_bug.cgi?id=434065 ?

```
public OutputStream testA(boolean condition) throws FileNotFoundException {
    return condition ? null : new FileOutputStream("test.txt");
}
```

**Comment by srikanth-sankaran** [comment]
> Is this the same as https://bugs.eclipse.org/bugs/show_bug.cgi?id=434065 ?
> 
> ```
> public OutputStream testA(boolean condition) throws FileNotFoundException {
>     return condition ? null : new FileOutputStream("test.txt");
> }
> ```

Looks very likely
