### ISSUE TITLE
NPE in switch with case null 

### ISSUE THREAD

**Issue by urferr** [eclipse-jdt/eclipse.jdt.core#1767]
With Eclipse 2023-12 and JDK 21 i found the following behaviour in a switch with an enum:

`
public static enum TestEnum {
		E1,
		E2
	}
`

The first try uses the following test method:

`
private void testSwitchWithNull(TestEnum theEnum) {
    switch (theEnum) {
      case TestEnum e when e == TestEnum.E1 -> System.out.println(e);
      case null -> System.out.println("Enum: null");
      default -> System.out.println("Enum: default -> " + theEnum);
   }
}
`

if i call the method with the switch statement in the 3 following ways everything works fine

`
new TestPatternMatchingInSwitch().testSwitchWithNull(TestEnum.E1);
new TestPatternMatchingInSwitch().testSwitchWithNull(TestEnum.E2);
new TestPatternMatchingInSwitch().testSwitchWithNull((TestEnum) null);
`

if i modify the test method containing the switch and call it again in the 3 different ways from above still everything works fine.

`
private void testSwitchWithNull(TestEnum theEnum) {
   switch (theEnum) {
      case TestEnum e -> System.out.println(e);
      case null -> System.out.println("Enum: null");
   }
}
`

but if i change the method as follows and execute the 3 test cases again, the third one with the null value passed throws the following exception:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "TestPatternMatchingInSwitch$TestEnum.ordinal()" because "theEnum" is null

`
private void testSwitchWithNull(TestEnum theEnum) {
   switch (theEnum) {
      case TestEnum.E1 -> System.out.println(theEnum);
      case null -> System.out.println("Enum: null");
      default -> System.out.println("Enum: default -> " + theEnum);
   }
}
`

For any reason now the null case is now not handled properly and the exception is already thrown on the line with the switch(theEnum)! I have added the whole test app to reproduce in the TestPatternMatchingInSwitch.zip.
[TestPatternMatchingInSwitch.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13714010/TestPatternMatchingInSwitch.zip)

**Comment by iloveeclipse** [comment]
Please try latest nightly, I believe there was a fix for similar issue recently
https://download.eclipse.org/eclipse/downloads/drops4/I20231218-1800/

**Comment by srikanth-sankaran** [comment]
I can reproduce on top of master. Will investigate.

**Comment by srikanth-sankaran** [comment]
Simpler test case:

```
public class X {
   public static void main(String[] args) {
	   Integer o = null;
	   switch (o) {
	     case null:
	       System.out.println("NULL"); 
	       break;
	     default : System.out.println(o);
	   }
 }
}
```

javac compiled version prints `NULL` while ECJ compiled version crashes with `Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "o" is null`

**Comment by srikanth-sankaran** [comment]
Reduced test case that still shows the problem:

```
public class X {
	enum E {
		E
	}

	public static void main(String[] args) {
		E e = null;
		switch(e) {
		case E.E -> {}
		case null -> {}
		}
	}
}
```

**Comment by urferr** [comment]
@srikanth-sankaran you have to qualify the case constant i.e if the switch handles constants from different enums and the variable used in the switch statement is of type Object

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran you have to qualify the case constant i.e if the switch handles constants from different enums and the variable used in the switch statement is of type Object

That is true, but it is not the case in the example snippet you used to open the ticket. Anyways, my question is one of academic curiosity. I hope your issues are resolved. If any persist, please open a ticket, Thanks.
