### ISSUE TITLE
[Java 21][switch] - switch with null case throw NullPointerException on null Enum

### ISSUE THREAD

**Issue by farrault** [eclipse-jdt/eclipse.jdt.core#1778]
Since https://openjdk.org/jeps/441, switch allows "case null", but ECJ seems to fail to generate the correct bytecode in case of switching on an enum : 

The following program throws this NPE after being compiled with ECJ : 
java.lang.NullPointerException: Cannot invoke "TestCaseNPEEnum$Foo.ordinal()" because "< local1 >" is null

While it does returns the "NULL" string with Temurin 21 compiler 

```
class TestCaseNPEEnum {
    enum Foo {
       ONE,
       TWO; 
    }
    public static void main(String[] args) {
        Foo foo = null;
        var str = switch(foo) {
            case null -> "NULL";
            case ONE -> "one";
            case TWO -> "two";
        };
        System.out.println(str);
    }
}
```

Tested with ECJ 4.30 : 
```
> java -jar ecj-4.30.jar -proc:none -21 TestCaseNPEEnum.java
> java TestCaseNPEEnum
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "TestCaseNPEEnum$Foo.ordinal()" because "<local1>" is null
        at TestCaseNPEEnum.main(TestCaseNPEEnum.java:17)
```

Also tested with ecj-I20231221-0400.jar => same behaviour

**Comment by srikanth-sankaran** [comment]
Wow. You just managed to pick up very last build with the problem :)
eclipse-SDK-I20231221-1800 has a fix for this problem.

See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1773
