### ISSUE TITLE
The conditional expression for an `if` does not have a target type of `boolean`

### ISSUE THREAD

**Issue by DasBrain** [eclipse-jdt/eclipse.jdt.core#178]
Given this method:

    static <T> T uncheckedCast(Object o) {
        return (T) o;
    }

The following code compiles in javac, but not with eclipse:

    if (uncheckedCast(false)) {}

Eclipse shows the error "Type mismatch: cannot convert from Object to boolean".

In contrast, this line compiles fine with both javac and eclipse:

    boolean b = uncheckedCast(false);

(The code where I discovered that issue uses this feature like this: `if (config.get("someopt")) {...}`.)

**Comment by brychcy** [comment]
This has already been discussed here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=513766

Summary: It's actually a bug in javac (according to the current Java Language Specification):
https://bugs.openjdk.org/browse/JDK-8179483

As seen in a comment to that ticket, changing the JLS is being considered.

**Comment by trancexpress** [comment]
Closing as per last comment.
