### ISSUE TITLE
ElementsImpl9#getTypeElement is very slow

### ISSUE THREAD

**Issue by nakamura-to** [eclipse-jdt/eclipse.jdt.core#1785]
`org.eclipse.jdt.internal.compiler.apt.model.ElementsImpl9#getTypeElement` is significantly slower compared to `org.eclipse.jdt.internal.compiler.apt.model.ElementsImpl#getTypeElement`. As a result, in my Annotation Processor, I have addressed this issue by caching the execution results. Could you consider making improvements to its performance?

#### Eclipse
Version: 2023-09 (4.29.0)
Build id: 20230907-1323

#### OS
Mac OS X 12.6 x86_64

**Comment by nakamura-to** [comment]
Please allow me to share some additional information. The performance depends on the version of JRE specified in the Eclipse project. It is fast when using JavaSE-1.8. However, it becomes slower when using JavaSE-9 or higher.

**Comment by jukzi** [comment]
Feel free to suggest an improvement as PR but don't expect someone else to solve your issue.

**Comment by jukzi** [comment]
closing as not planned without contribution
