### ISSUE TITLE
Start position and length of Dimension node lost when cloned

### ISSUE THREAD

**Issue by ptziegler** [eclipse-jdt/eclipse.jdt.core#1786]
We recently raised the api level of the JDT parser we use for the WindowBuilder project from JSL3 to JSL21 and as a result, we're currently having roughly 130 test cases that now fail because of the check `assertTrue(begin >= parent_begin)`:

```
@Override
public void preVisit(ASTNode node) {
	assertSame(editorAST, node.getAST());
	// check positions for parent/child
	{	ASTNode parent = node.getParent();
		if (parent != null) {
			int begin = AstNodeUtils.getSourceBegin(node);
			int end = AstNodeUtils.getSourceEnd(node);
			int parent_begin = AstNodeUtils.getSourceBegin(parent);
			int parent_end = AstNodeUtils.getSourceEnd(parent);
			assertTrue(begin >= parent_begin);
			assertTrue(end <= parent_end);
		}
	}
}
```

Instead of the actual position, both the start position and length of the node are set to `-1`.
Note that this problem only shows up when arrays are used.  For example in this test class:

```
public class Test extends JPanel {
	public Test() {
		addButtons(new JButton[]{});
		JButton button = new JButton();
		addButtons( new JButton[] { button, new JButton() } );
	}

	public void addButtons(JButton[] buttons) {
	}
}
```

The reason it didn't happen previously is because with JSL8, JDT switched from a ComponentType to an ElementType when dealing with arrays. ElementTypes have an additional Dimension attribute, which is what's causing problems now.

Normally, the position and length of the Dimension node is set while parsing. However, this information gets lots when it is cloned via `ASTNode.copySubtree(...)`. So I believe this information simply has to be set when `clone0()` is called.

**Comment by srikanth-sankaran** [comment]
Thanks for the patch. I offer to review it.

**Comment by ptziegler** [comment]
> Thanks for the patch. I offer to review it.

That would be great :) I've already created #1787, which should fix this problem. I hope with such a small changes, there are no regressions that were overlooked while testing it.

**Comment by srikanth-sankaran** [comment]
Missed it this week, will review and test next week and help wrap it up
