### ISSUE TITLE
[Patterns][records] Error in JDT Core during AST creation: info cannot be null

### ISSUE THREAD

**Issue by Madjosz** [eclipse-jdt/eclipse.jdt.core#1792]
With the following code multiple error messages in the Error Log View pop up
```java
package mwe;

public class NullInfo {
    private record R(Object o) {}
    void f() {
        R r = new R(new Object());
        while (r instanceof R(Object o)) {
            o.toString();
        }
    }
}
```
> Error in JDT Core during AST creation

> Problems occurred when invoking code from plug-in: "org.eclipse.jdt.core.manipulation".

```stacktrace
java.lang.IllegalArgumentException: info cannot be null
	at org.eclipse.jdt.internal.compiler.codegen.StackMapFrame.addStackItem(StackMapFrame.java:90)
	at org.eclipse.jdt.internal.compiler.ClassFile.traverse(ClassFile.java:7037)
	at org.eclipse.jdt.internal.compiler.ClassFile.generateStackMapTableAttribute(ClassFile.java:5473)
	at org.eclipse.jdt.internal.compiler.ClassFile.completeCodeAttribute(ClassFile.java:1703)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:376)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:292)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:759)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:829)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:414)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1327)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:790)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1242)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1120)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5821)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1120)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:166)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.run(SelectionListenerWithASTManager.java:151)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Problem does not occurr with `if` instead of `while`.

It also messes with code cleanup save actions.

# System information
Eclipse SDK
Version: 2024-03 (4.31)
Build id: I20231228-1800

openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

**Comment by srikanth-sankaran** [comment]
Reproducible. Thanks for the report and test case.

**Comment by Madjosz** [comment]
Bytecode for comparison:
| actually parsed by ejc | instruction | expected (modified from code with `if`, compiled with ejc) |
| --- | --- | --- |
| bb 00 0f | new | 0: new           #7                  // class mwe/NullInfo$R |
| 59 | dup | 3: dup |
| 01 | aconst_null | 4: aconst_null |
| b7 00 11 | invokespecial | 5: invokespecial #9                  // Method mwe/NullInfo$R."<init>":(Ljava/lang/Object;)V |
| 4c | astore_1 | 8: astore_1 |
| a7 00 08 | goto |  |
| 2d | aload_3 | <---- exception occurs here |
| b6 00 14 | invokevirtual |  |
| 57 | pop |  |
| 2b | aload_1 | 9: aload_1 |
| 3a 04 | astore | 10: astore        4 |
| 19 04 | aload | 12: aload         4 |
| c1 00 0f | instanceof | 14: instanceof    #7                  // class mwe/NullInfo$R |
| 99 00 2d | ifeq | 17: ifeq          67 |
| 19 04 | aload | 20: aload         4 |
| 4d | astore_2 | 22: astore_2 |
| 2c | aload_2 | 23: aload_2 |
| c0 00 0f | checkcast | 24: checkcast     #7                  // class mwe/NullInfo$R |
| b6 00 18 | invokevirtual | 27: invokevirtual #12                 // Method mwe/NullInfo$R.o:()Ljava/lang/Object; |
| 4e | astore_3 | 30: astore_3 |
| 19 04 | aload | 31: aload         4 |
| c0 00 0f | checkcast | 33: checkcast     #7                  // class mwe/NullInfo$R |
| 19 04 | aload | 36: aload         4 |
| c0 00 0f | checkcast | 38: checkcast     #7                  // class mwe/NullInfo$R |
| 58 | pop2 | 41: pop2 |
|  |  | 42: aload_3 |
|  |  | 43: invokevirtual #16                 // Method java/lang/Object.toString:()Ljava/lang/String; |
|  |  | 46: pop |
|  |  | 47: goto          12
| a7 ff da | goto | 50: goto          70 |
| 3a 05 | astore | 53: astore        5 |
| bb 00 1c | new | 55: new           #22                 // class java/lang/MatchException |
| 59 | dup | 58: dup |
| 19 05 | aload | 59: aload         5 |
| b6 00 1e | invokevirtual | 61: invokevirtual #24                 // Method java/lang/Throwable.toString:()Ljava/lang/String; |
| 19 05 | aload | 64: aload         5 |
| b7 00 21 | invokespecial | 67: invokespecial #25                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V |
| bf | athrow | 69: athrow |
| b1 | return | 70: return |

**Comment by srikanth-sankaran** [comment]
The warning ECJ issues viz `The expression of type X.R is already an instance of type X.R` needs to be suppressed, as deconstruction could be the intent.

**Comment by srikanth-sankaran** [comment]
Code generated by ECJ for `f()` is:

```
         0: new           #15                 // class X$R
         3: dup
         4: new           #3                  // class java/lang/Object
         7: dup
         8: invokespecial #8                  // Method java/lang/Object."<init>":()V
        11: invokespecial #17                 // Method X$R."<init>":(Ljava/lang/Object;)V
        14: astore_1
        15: goto          23
        18: aload_2
        19: invokevirtual #20                 // Method java/lang/Object.toString:()Ljava/lang/String;
        22: pop
        23: aload_1
        24: instanceof    #15                 // class X$R
        27: ifeq          62
        30: aload_1
        31: astore        4
        33: aload         4
        35: checkcast     #15                 // class X$R
        38: invokevirtual #24                 // Method X$R.o:()Ljava/lang/Object;
        41: astore_2
        42: goto          18
        45: astore        5
        47: new           #28                 // class java/lang/MatchException
        50: dup
        51: aload         5
        53: invokevirtual #30                 // Method java/lang/Throwable.toString:()Ljava/lang/String;
        56: aload         5
        58: invokespecial #33                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
        61: athrow
        62: return
```

while the reference compiler generates:
```
         0: new           #7                  // class X$R
         3: dup
         4: new           #2                  // class java/lang/Object
         7: dup
         8: invokespecial #1                  // Method java/lang/Object."<init>":()V
        11: invokespecial #9                  // Method X$R."<init>":(Ljava/lang/Object;)V
        14: astore_1
        15: aload_1
        16: instanceof    #7                  // class X$R
        19: ifeq          41
        22: aload_1
        23: astore_2
        24: aload_2
        25: invokevirtual #12                 // Method X$R.o:()Ljava/lang/Object;
        28: astore        4
        30: aload         4
        32: astore_3
        33: aload_3
        34: invokevirtual #16                 // Method java/lang/Object.toString:()Ljava/lang/String;
        37: pop
        38: goto          15
        41: goto          58
        44: astore_2
        45: new           #22                 // class java/lang/MatchException
        48: dup
        49: aload_2
        50: invokevirtual #24                 // Method java/lang/Throwable.toString:()Ljava/lang/String;
        53: aload_2
        54: invokespecial #25                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
        57: athrow
        58: return
```

**Comment by srikanth-sankaran** [comment]
Problem arises from code generation for `while` loop's body preceding `while` loop's condition. This was fine as long as `while`'s condition would not introduce any variables - which was the case until pattern matching entered the picture. Now with pattern matching, an expression could introduce a variable and we are not prepared for it.

(See the `15: goto          23` into ECJ generated class file which jumps over the body into condition evaluation which is emitted after the body; `42: goto          18` jumps into the body if the condition is true. This is irregular but valid code generation which we could get away with all this while (pun intended :) )

**Comment by srikanth-sankaran** [comment]
At first inspection, it looks like we could do better than javac's code generation - let us see.

**Comment by srikanth-sankaran** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1966 provides a valid but stop gap fix. The entire area of patterns code generation is being overhauled and the idiosyncrasies with code generation for while loop where body precedes the condition will be addressed via https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1889

A comment there says `The recursive descent as it reaches the local declaration should add the variable.` but the `while` loop is descended into in "wrong" order causing the problem.

**Comment by Madjosz** [comment]
Confirmed works in I20240207-0610
