### ISSUE TITLE
Removing type arguments reported to be redundant leads to type mismatch error

### ISSUE THREAD

**Issue by PyvesB** [eclipse-jdt/eclipse.jdt.core#1794]
Originally reported as https://bugs.eclipse.org/bugs/show_bug.cgi?id=579314.

Consider the following code sample:

```
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class TypeArgumentsTest {
	public static void main(String[] args) {
		List<String> strings = List.of("string1", "string2");
		ArrayList<ArrayList<String>> collectedStrings = strings.stream()
				.map(s -> new ArrayList<String>())
				.collect(Collectors.toCollection(() -> new ArrayList<>(strings.size())));
		System.out.println(collectedStrings);
	}
}
```

Eclipse considers that the type argument `<String>` is redundant on line `.map(s -> new ArrayList<String>())`, and suggests removing it. However, doing so leads to a type mismatch error:
> cannot convert from ArrayList<ArrayList<Object>> to ArrayList<ArrayList<String>>

**Comment by srikanth-sankaran** [comment]
The verification in `org.eclipse.jdt.internal.compiler.ast.AllocationExpression.checkTypeArgumentRedundancy(ParameterizedTypeBinding, BlockScope)` that the express type arguments match the expected type arguments is too localized. It fails to consider the cases that the expected type was influenced by the express type (as I suspected was the case here)

Perhaps if `org.eclipse.jdt.internal.compiler.ast.ASTNode.resolvePolyExpressionArguments(Invocation, MethodBinding, TypeBinding[], BlockScope)` is up in the call stack we should suppress the redundant type arguments warning. More sophisticated implementation would call for comparing the bindings on a more global basis than just the allocation expression's type arguments.

@stephan-herrmann - what do you think ?
