### ISSUE TITLE
[22] Add AST rewrite support for new String Template DOM nodes

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#1800]
Issue #1537 introduced new nodes to represent String templates. To be able to provide UI support, we will have to update the AST Rewrite components accordingly.  The above mentioned issue added some rudimentary support for the flatteners and some in `ASTRewriteAnalyzer`, but there's more to be done.

@mpalat this might be a good one for anyone trying to take up DOM ast.

- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2026

**Comment by mpalat** [comment]
@subyssurendran666 - please have a look

**Comment by subyssurendran666** [comment]
Okay @mpalat I'll take it.

**Comment by mpalat** [comment]
Changed the title to reflect 22 instead of earlier preview version

**Comment by mpalat** [comment]
done via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2026
