### ISSUE TITLE
Record pattern matching with `null` gives wrong result

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdt/eclipse.jdt.core#1804]
Spotted by Jay in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1517#issuecomment-1859821498

Given the following code:
```java
public class BooleanVariable {
	record Paper(int color) {}
	record Box<T>(T a) {}
	public static void main(String[] args) {
		Box<?> b = new Box<>(null);
		boolean res = b instanceof Box(Paper a);
		if (res) {
			System.out.println("res is true");
		} else {
			System.out.println("res is false");
		}
	}
}
```

ECJ prints "res is true" while javac prints "res is false".

**Comment by datho7561** [comment]
I planning on working on this

**Comment by datho7561** [comment]
If you instead do:

```java
boolean res = b instanceof Box(Paper a) && a == null;
```

It will print "res is false", since a completely different method is used to generate boolean methods when a part of an `&&` expression. I'll try to repurpose that method so that it will work without `&&`.

**Comment by datho7561** [comment]
This example from Jay's comment also doesn't work:

```java
public class X {
	record Paper(int color) {}
	record Box<T>(T a) {}
	public static void main(String argv[]) {
		foo(null, null);
	}
	public static void foo(String abc, String def) {
		Box<?> p = new Box<>(new Paper(0));
		boolean b = false;
		switch (p) {
			case Box(Paper a) -> {
				b = true;
				break;
			}
			default -> {
				b = false;
				break;
			}
		}
		System.out.println(b);
	}
}
```

**Comment by srikanth-sankaran** [comment]
@datho7561 - This is my plan for this ticket - I have assigned myself as a joint owner of this ticket. As mentioned in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1517#issuecomment-1911691090 I am investigating and possibly undertaking a overhaul of code generation for patterns. If you don't mind, I would subsume this PR as a part of the larger work. Let us not rush this please. What do you say ?

**Comment by datho7561** [comment]
Okay. Just as a heads up, this issue is a blocker for code generation in lists of patterns in case statements: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1742

I've figured out how to get code generation working in https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/9, but I'll probably need to rewrite the code after your overhaul of pattern code generation.

**Comment by srikanth-sankaran** [comment]
> This example from Jay's comment also doesn't work:
> 
> ```java
> public class X {
> 	record Paper(int color) {}
> 	record Box<T>(T a) {}
> 	public static void main(String argv[]) {
> 		foo(null, null);
> 	}
> 	public static void foo(String abc, String def) {
> 		Box<?> p = new Box<>(new Paper(0));
> 		boolean b = false;
> 		switch (p) {
> 			case Box(Paper a) -> {
> 				b = true;
> 				break;
> 			}
> 			default -> {
> 				b = false;
> 				break;
> 			}
> 		}
> 		System.out.println(b);
> 	}
> }
> ```
> 
> However, it gives a VerifyError in the generated bytecode instead of the wrong result.

Happy to report that this one works fine on master, I'll push a regression test
