### ISSUE TITLE
Parameters of compact canonical constructor are not marked as mandated

### ISSUE THREAD

**Issue by SirYwell** [eclipse-jdt/eclipse.jdt.core#1806]
Consider the following record:

```java
public record MyRecord(int a) {
	
	public static void main(String[] args) {
		var ctor = MyRecord.class.getConstructors()[0];
		System.out.println(ctor.getParameters()[0].isImplicit());
	}
	
	public MyRecord {
		
	}

}
```

Compiling this with javac 21 and running it yields `true`. Compiling with Eclipse and running it yields `false`.

The JLS says (https://docs.oracle.com/javase/specs/jls/se20/html/jls-13.html#jls-13.1):

> A binary representation for a class or interface must also contain all of the following: 
> [...]
> 12. A construct emitted by a Java compiler must be marked as mandated if it corresponds to a formal parameter declared implicitly in source code ([§8.8.1](https://docs.oracle.com/javase/specs/jls/se20/html/jls-8.html#jls-8.8.1), [§8.8.9](https://docs.oracle.com/javase/specs/jls/se20/html/jls-8.html#jls-8.8.9), [§8.9.3](https://docs.oracle.com/javase/specs/jls/se20/html/jls-8.html#jls-8.9.3), [§15.9.5.1](https://docs.oracle.com/javase/specs/jls/se20/html/jls-15.html#jls-15.9.5.1)).

It further says:

> The following formal parameters are declared implicitly in source code: 
> [...]
> - The formal parameters of a compact constructor of a record class ([§8.10.4](https://docs.oracle.com/javase/specs/jls/se20/html/jls-8.html#jls-8.10.4)).

Using `javap`, you can also see that a classfile compiled with javac 21 will contain the mandated flag in the MethodParameters attribute of the constructor, while that's not the case when compiling with eclipse.

Note that older javac versions were wrong here too, see <https://bugs.openjdk.org/browse/JDK-8292275>.

**Comment by srikanth-sankaran** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=572203 - I will for the time being provide a fix for just what is reported here.
