### ISSUE TITLE
Extract ECJ compiler code from jdt.core to ecj bundle and make ecj a real plug-in

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#181]
Follow up on https://github.com/eclipse-platform/eclipse.platform.ua/issues/18#issuecomment-1164373052.

Currently JDT has LOT of hacks around compiler part (dedicated source folders, dedicated build files, dedicated deployment steps, dedicated validation bundle) - all because the standalone Eclipse Compiler for Java (ECJ) code is located inside the jdt.core project that contains additionally all the IDE specific extensions.

Ideally ECJ could be just extracted from the jdt.core bundle so it can be used by jdt.core and other bundles as a regular bundle.

This would remove most of the custom hacks around building, testing and shipping ecj we have today.

I will provide a draft idea, but I have no enough time/knowledge to perform all the build/maven magic required to get that working.
Technically **I believe** this should work without breaking existing jdt.core clients.

**Comment by stephan-herrmann** [comment]
> Do you have any idea why `org.eclipse.jdt.compiler.apt` and `org.eclipse.jdt.compiler.tool` are _fragments_ of jdt.core? Just a hack to get the standalone part compiled separately?

I can only guess / infer from what I see in our history. Both fragments implement additional capabilities connected to the compiler that were introduced around Java 6 (JSR 269 and JSR 199), right? As such the had to set BREE 1.6, while the rest of JDT/Core was still at 1.4 (!). That's why the implementation *had* to be kept separate.

*If* that was the only reason, then the reason is gone in times where JDT/Core requires 11.

For authoritative answers you'd have to ask Walter Harley or Olivier Thomann, I believe. I haven't heard from Walter for ages, but Olivier might still respond?

**Comment by guw** [comment]
+1 for merging the fragments into a new ECJ bundle. They make ECJ a better offering in the Java ecosystem.

My hypothesis is that they are separate because they have been created long time ago while JDT was much more strict with who and what goes into jdt.core.

**Comment by stephan-herrmann** [comment]
> My hypothesis ...

The JDK 6 dependency was a sufficient reason to keep those fragments separate (see my previous comment). I just wasn't sure if that was the only reason.

As of today I cannot think of any reason against merging.

**Comment by jarthana** [comment]
> @stephan-herrmann , @jarthana : WDYT about #182 ?

I am not sure I understand the changes in `org.eclipse.jdt.core/.classpath`. What does this mean to org.eclipse.jdt.core as a Java Project in the IDE?

> Do you have any idea why `org.eclipse.jdt.compiler.apt` and `org.eclipse.jdt.compiler.tool` are _fragments_ of jdt.core? Just a hack to get the standalone part compiled separately?
I concur with Stephan. 

> Would there be any issue if we just merge all three code bases together (ecj + org.eclipse.jdt.compiler.apt + org.eclipse.jdt.compiler.tool) in one real bundle? At the end that is what ecj.jar does?

I can't think of a reason why this will be a big problem. Except that org.eclipse.jdt.core, when shipped with IDE, will contain some code that won't be useful. Or are you suggesting that we continue to make two bundles?

**Comment by iloveeclipse** [comment]
> are you suggesting that we continue to make two bundles?

Yes. One "ecj" bundle for batch compiler (and apt) and one "core" bundle for the rest of jdt, that depends on ecj.

**Comment by jarthana** [comment]
> > org.eclipse.jdt.core, when shipped with IDE, will contain some code that won't be useful.
> 
> This seems to refer to code from source folder `antadapter`, right?

I had that and "batch" in my mind. But just checked the jdt.core bundle and to my surprise found all those classes already in there. We really don't need them, do we? Perhaps there's some history I don't remember.

**Comment by stephan-herrmann** [comment]
> > > org.eclipse.jdt.core, when shipped with IDE, will contain some code that won't be useful.
> > 
> > 
> > This seems to refer to code from source folder `antadapter`, right?
> 
> I had that and "batch" in my mind. But just checked the jdt.core bundle and to my surprise found all those classes already in there. We really don't need them, do we? Perhaps there's some history I don't remember.

Well, who remembers the decisions from 2001 or earlier :)

Just two small observations:
* org.eclipse.jdt.core.compiler.batch.BatchCompiler is API, so if it's in jdt.core now, it must remain there. It then pulls in all the rest from "batch".
* lot's of our tests use "batch", so they need a way to depend on it

**Comment by jarthana** [comment]
Thanks Stephan. So, that looks like it's only the antadapter then. In that case, then my previous concern of adding redundant code to jdt.core is no longer a big deal.

**Comment by iloveeclipse** [comment]
> * org.eclipse.jdt.core.compiler.batch.BatchCompiler is API, so if it's in jdt.core now, it must remain there.

Why? It can be re-exported from JDT core. Do I miss something?

I've updated draft patch to actually move all the code to the final place, rename bundle etc.

Main point: we don't have 3 different jars now (ecj.jar / org.eclipse.jdt.compiler.apt / org.eclipse.jdt.compiler.tool), we don't need to "merge" them, we have everything inside org.eclipse.jdt.core.compiler.batch bundle. 

jdt.core reexports API from org.eclipse.jdt.core.compiler.batch.

Note: I've used "org.eclipse.jdt.core.compiler.batch" name because that was used in MANIFEST.MF of the ecj.jar.

See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/182

With this code I have no compile errors in my SDK workspace (with PDE,JDT UI etc) and I can start Eclipse from Eclipse and everything still works.

Here are current TODO's:

1) What I did NOT tried is to re-write all the magic scripts that build
and package separated ecj library out of jdt.core. I have no idea about maven and current JDT build magic.
2) The 3 antadapter classes are now split over ecj and jdt core, because
BuildJarIndex.java and CheckDebugAttributes.java depend on JDT core
code.
3) ecj.1 and build_ecj.xml aren't touched yet. ecj.1 was touched last
time 2017, it seem to be used for man pages.
4) pom from jdt core will need an adoption.
5) org.eclipse.jdt-feature need to be updated (trivial)
6) Current maven build fails with "chicken and egg" problem: jdt core needs ecj bundle, but the bundle isn't there yet, I have no idea how that is supposed to be done: `Missing requirement: org.eclipse.jdt.core 3.32.0.qualifier requires 'osgi.bundle; org.eclipse.jdt.core.compiler.batch 3.32.0' but it could not be found`.
7) TBC

@akurtakov , @sravanlakkimsetti , @jarthana , @mpalat : I need your help:

1) It would be great if people who know some of the magic behind **building compiler** could help to update scripts logic. I believe I've heard that we build some grammar somehow manually - that script/artifacts, if in jdt core, must be probebly moved to org.eclipse.jdt.core.compiler.batch bundle.
2) It would be great if people who know some of the magic behind **building maven artifacts** could check what needed for org.eclipse.jdt.core.compiler.batch module. I've copied pom.xml from jdt.core and adopted that a bit, but I guess there is lot more work need to be done.
3) I guess there must be something done for platform aggregator once jdt can be built. 
4) SDK Download page lists "JDT Core Batch Compiler" - that need to be updated to include "org.eclipse.jdt.core.compiler.batch" bundle and its source.

Ideally we could get that in 4.26 M1.

**Comment by stephan-herrmann** [comment]
> > * org.eclipse.jdt.core.compiler.batch.BatchCompiler is API, so if it's in jdt.core now, it must remain there.
> 
> Why? It can be re-exported from JDT core. Do I miss something?

No objection. My comment was only trying to argue that clients of jdt.core must be able to use BatchCompiler (vs. Jay's worry that we're stuffing jdt.core with classes that don't belong there). This doesn't affect the question whether jdt.core *directly* contains that class, or _pulls it in_ (and re-exports) from a new ecj plugin.

**Comment by stephan-herrmann** [comment]
> Note: I've used "org.eclipse.jdt.core.compiler.batch" name because that was used in MANIFEST.MF of the ecj.jar.

Frankly, I don't know who needs that plugin name. If we keep it, then publish-to-maven-central will have to continue to translate this into the GA org.eclipse.jdt:ecj. But since 'ecj' is an exceptional artifactName anyway, that translation is probably OK / unavoidable.

**Comment by stephan-herrmann** [comment]
> could something be wrong with the version of the compiler.batch bundle? I see that we replace the placeholders with actual version on the fly from the "prepare-package" phase in the jdt.core's pom.xml.

To check we're on the same page: This is about patching the version into `org/eclipse/jdt/internal/compiler/batch/messages.properties`, right? Which is for the benefit of `java -jar ecj.jar -version`.

Are you saying that part is still missing in #182? Or is your point about the confusion / duplication(?) between `build_ecj.xml` and `pom.xml`?

**Comment by iloveeclipse** [comment]
**Update**

With the help from @laeubi I was able to fix first round of maven errors.

**Something** was built, so that even (all gerrit?) tests were executed.

So far only 24 failures in [org.eclipse.jdt.apt.pluggable.tests](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-182/11/testReport/org.eclipse.jdt.apt.pluggable.tests/).

The same tests run fine in the IDE, and I don't see clear pointer why don't they run in maven.
If anyone has an idea, what is special about org.eclipse.jdt.apt.pluggable.tests, don't hesitate to leave a comment.

**Comment by stephan-herrmann** [comment]
> I guess something in https://github.com/eclipse-jdt/eclipse.jdt/blob/master/org.eclipse.jdt-feature/feature.xml ???

Sure, any changes in the set of plugins/fragments must be reflected in the feature. In addition to removing fragments that no longer exist you probably need to also add the new plugin.

**Comment by iloveeclipse** [comment]
> Sure, any changes in the set of plugins/fragments must be reflected in the feature. In addition to removing fragments that no longer exist you probably need to also add the new plugin.

Thanks, I haven't found this feature in jdt core repo, so my surprise to see it elsewhere.
See https://github.com/eclipse-jdt/eclipse.jdt/pull/45

**Comment by iloveeclipse** [comment]
Next error is:
```
18:29:59  [ERROR] Cannot resolve project dependencies:
18:29:59  [ERROR]   You requested to install 'osgi.bundle; org.eclipse.jdt.compiler.apt 0.0.0' but it could not be found
18:29:59  [ERROR] 
18:29:59  [ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
18:29:59  [ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.jdt:org.eclipse.jdt.compiler.apt.tests:1.2.300-SNAPSHOT @ 
 ```

**Comment by akurtakov** [comment]
Sounds like this should require the new bundle name, no?

**Comment by iloveeclipse** [comment]
> Sounds like this should require the new bundle name, no?

Should be done without extre config, because new bundle is not a fragment anymore.
Let see if https://github.com/eclipse-jdt/eclipse.jdt.core/pull/572 works.

**Comment by iloveeclipse** [comment]
OK, finally failed in SDK build, see https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/8/console

```
21:59:37  ~/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/mbscripts
21:59:37  + set +x
21:59:37  ~/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.jdt.core/org.eclipse.jdt.core/target ~/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/mbscripts
21:59:37  cp: cannot stat 'org.eclipse.jdt.core-*-SNAPSHOT-batch-compiler.jar': No such file or directory
```

@sravanlakkimsetti, I assume batch compiler location is not chnaged, but I have no idea where it is?

**Comment by iloveeclipse** [comment]
Guess instead of 
eclipse.platform.releng.aggregator/eclipse.jdt.core/org.eclipse.jdt.core/target 
it will be in
eclipse.platform.releng.aggregator/eclipse.jdt.core/org.eclipse.jdt.core.compiler.batch/target ?

```
21:01:33  [INFO] Building jar: /home/jenkins/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.jdt.core/org.eclipse.jdt.core.compiler.batch/target/org.eclipse.jdt.core.compiler.batch-3.33.0-SNAPSHOT-sources.jar
21:01:33  [INFO] 
21:01:33  [INFO] --- maven-antrun-plugin:3.1.0:run (default) @ org.eclipse.jdt.core.compiler.batch ---
21:01:33  [INFO] Executing tasks
21:01:33  [INFO] Executed tasks
21:01:33  [INFO] 
21:01:33  [INFO] --- tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin (default-package-plugin) @ org.eclipse.jdt.core.compiler.batch ---
21:01:33  [INFO] Building jar: /home/jenkins/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.jdt.core/org.eclipse.jdt.core.compiler.batch/target/org.eclipse.jdt.core.compiler.batch-3.33.0-SNAPSHOT.jar
```

**Comment by iloveeclipse** [comment]
I've pushed https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/735.

I will not trigger SDK build now (going to sleep), it will be triggered soon anyway, but if anyone wants, feel free to continue: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/

Will see tomorrow what else is broken...

**Comment by vik-chand** [comment]
Is pde.build failures related? https://download.eclipse.org/eclipse/downloads/drops4/I20221201-1800/testresults/html/org.eclipse.pde.build.tests_ep427I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by iloveeclipse** [comment]
> Is pde.build failures related? https://download.eclipse.org/eclipse/downloads/drops4/I20221201-1800/testresults/html/org.eclipse.pde.build.tests_ep427I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

Sure. I plan follow up later today.

**Comment by iloveeclipse** [comment]
@merks : I believe the Oomph setup in jdt should be changed.
We have new jdt project now, and three jdt projects are removed (see https://github.com/eclipse-jdt/eclipse.jdt.core/pull/182).

Added: org.eclipse.jdt.core.compiler.batch
Removed:
- org.eclipse.jdt.core.ecj.validation
- org.eclipse.jdt.compiler.apt 
- org.eclipse.jdt.compiler.tool

I don't use Oomph, so I could try to simply search / replace something without testing - or you would check that?

**Comment by iloveeclipse** [comment]
I consider the main task to be fixed now.

**Remains**
- Add N&N entry (I will do that)
- send a mail to cross-projects list, I think it is worth to do in case someone hacked around JDT core/compiler
- Find & fix possible leftovers in build scripts or elsewhere => in dedicated bugs please.
- Possible regressions etc should also be handled by dedicated bugs.
- Anything else I forgot?

**Comment by iloveeclipse** [comment]
Please review N&N entry https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/pull/74.
Should we add something like this to release notes?

**Comment by stephan-herrmann** [comment]
Does anyone know, why github failed to link the follow-up #578 and https://github.com/eclipse-pde/eclipse.pde/issues/419 (which has a fix in jdt.core, not pde: #592) ? Without those issues its impossible to fully understand the story of this refactoring.

**Comment by laeubi** [comment]
What do you mean by 

> github failed to link the follow-up

e.g. none of those seem to mention the issue directly (except now as you mentioned them here) and also the commit message do not have a reference, so how do you suppose github to know about this issue?

In general there are two options:

1. You mention the issue number or link in the PR/isuue
2. You have the issue number or link in the commit message

**Comment by stephan-herrmann** [comment]
> What do you mean by
> 
> > github failed to link the follow-up
> 
> e.g. none of those seem to mention the issue directly

I just saw #578 mentioning this `#181` right in its description, likewise https://github.com/eclipse-pde/eclipse.pde/issues/419 saying `eclipse-jdt/eclipse.jdt.core#181` - still I found neither by scanning this issue.

**Comment by iloveeclipse** [comment]
Will do. And yes, maven is a PITA for me.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : please check. I hope this is a bit more clear now.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann : please check. I hope this is a bit more clear now.

Thanks @iloveeclipse . This helps (_and I still hope, I'll never have to edit pom.xml in this regard ..._).

Still I added one change on top as I felt confusion between **creation** and **use** of jdtCompilerAdapter. Well, this happens in true dogfooding situations, like exporting jdt.core w/ jdtCompilerAdapter using jdt.core and jdtCompilerAdapter :)
