### ISSUE TITLE
[21] Enums cause issues in Record Pattern exhaustiveness checks

### ISSUE THREAD

**Issue by eNBeWe** [eclipse-jdt/eclipse.jdt.core#1813]
Consider this code

```
public sealed interface ExhaustiveCheck {

    sealed interface SubInterface1 extends ExhaustiveCheck permits Impl1 {}
    enum Impl1 implements SubInterface1 {}
    
    sealed interface SubInterface2 extends ExhaustiveCheck permits Impl2{}
    record Impl2() implements SubInterface2 {}

    default String format() {
        return switch (this) {
            case SubInterface1 e -> "1";
            case Impl2 e -> "2";
        };
    }
}
```

This should be detected as exhaustive, but Eclipse still requires a default case.

In builing the example it turned out that the enum is actually required to break it.

**Comment by iloveeclipse** [comment]
Have you tested your example with latest SDK build? There were few fixes in this area recently.

**Comment by eNBeWe** [comment]
Actually, no. We got these issues in some training on Java 21 features, using Eclipse 2023-12 (20231201-2043).
Sadly, I can't test on latest builds easily (due to company policies)

**Comment by snjeza** [comment]
@eNBeWe @iloveeclipse It works fine in the master branch.

**Comment by iloveeclipse** [comment]
> It works fine in the master branch.

Thanks @snjeza !
