### ISSUE TITLE
[Switch][patterns][record] AssertionError at org.eclipse.jdt.internal.compiler.ast.YieldStatement.addSecretYieldResultValue(YieldStatement.java:120)

### ISSUE THREAD

**Issue by KostiantynDenysiuk** [eclipse-jdt/eclipse.jdt.core#1835]
It seems that expression String s = switch(...) should take a value in any case unless the control flow is not broken. 
When we throw exception in default block, we got an error when parse this example. 

[error]: Unexpected exception: java.lang.AssertionError
java.lang.AssertionError: null
at org.eclipse.jdt.internal.compiler.ast.YieldStatement.addSecretYieldResultValue(YieldStatement.java:120) ~[ecj-3.36.0-20231107.jar:?]....

Reproducer: 

public class Reproducer {

   public class DataX {
         String data;
    }

   public class DataY {
        String data;
   }

   record X (DataX data) {}
   record Y (DataY data) {}

   Reproducer() {
        DataX dataX = new DataX();
        DataY dataY = new DataY();

        X x = new X(dataX);
        Y y = new Y(dataY);

        foo(x);
    }

    void foo(Object obj) {
           String s = switch(obj) {
                  case X(var x) -> x.data;
                  case Y(var y) -> y.data;
        
                 default -> {
                          try {
                                   throw new Exception();
                               } catch (Exception e) {
                                     throw new RuntimeException();
                               }
                 }
          };
    }

}

**Comment by iloveeclipse** [comment]
Two things: 
1) something in your snippet is missing.
2) please try with latest nightly SDK build from https://download.eclipse.org/eclipse/downloads/drops4/I20240109-1800/ , there were few fixes in switch area.

**Comment by KostiantynDenysiuk** [comment]
I've just tried new fixes but nothing has changed.

**Comment by iloveeclipse** [comment]
> I've just tried new fixes but nothing has changed.

OK. Please then provide full self contained java file showing the problem.

**Comment by KostiantynDenysiuk** [comment]
[Reproducer.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/13888571/Reproducer.zip)

**Comment by srikanth-sankaran** [comment]
I'll take a look.

**Comment by srikanth-sankaran** [comment]
Hello @KostiantynDenysiuk - On master, I don't see the problem. This program:

```
public class Reproducer {

	public class DataX {
		String data = "DataX";
	}

	public class DataY {
		String data1 = "DataY";
	}

	record X(DataX data) {
	}

	record Y(DataY data) {
	}

	Reproducer() {
		DataX dataX = new DataX();
		DataY dataY = new DataY();
		X x = new X(dataX);
		Y y = new Y(dataY);

		foo(x);
		foo(y);
		foo(null);
		foo("");
	}

	void foo(Object obj) {
		String s = switch (obj) {
		case X(var x) when x != null -> x.data;
		case Y(var x) when x != null -> x.data1;
		case null, default -> {
			try {
				if (obj == null)
					yield "switch on null";
				throw new Exception();
			} catch (Exception e) {
				yield "default threw exception";
			}
		}
		};
		System.out.println("s = " + s);
	}

	public static void main(String[] args) {
		new Reproducer();
	}

}
```

compiles fine and produces the output:

```
s = DataX
s = DataY
s = switch on null
s = default threw exception
```

which matches what one would expect and what JDK21 compiler produces. 

I tried doing some time travel using git to go back to earlier states of source - I see other problems when compiling this code with past versions but never the assertion failure you report.

Can you confirm you are able to see the problem with the snippet I have produced here ??

Also what is the version of Eclipse SDK you are on - I know you cited the plugin version, but it helps to know the SDK version too.

**Comment by srikanth-sankaran** [comment]
> Two things:
> 
> 1. something in your snippet is missing.

As far as I can tell, it seems to be just a markup problem. The code is just above the segment bracketed by the triple backquote pairs.

The zip file he has attached subsequently essentially has the same code.

> 2. please try with latest nightly SDK build from https://download.eclipse.org/eclipse/downloads/drops4/I20240109-1800/ , there were few fixes in switch area.

Not reproducible on HEAD on origin/master

**Comment by srikanth-sankaran** [comment]
> I tried doing some time travel using git to go back to earlier states of source - I see other problems when compiling this code with past versions but never the assertion failure you report.

For the record, when I reset to commit 52c1af8db2b3533e139f5c558391eb319687083f which as far as I can tell corresponds to the 
20231107 version id, I get this error:

```
Internal compiler error: java.util.EmptyStackException at java.base/java.util.Stack.peek(Stack.java:103)
```

not what you report. 

That problem itself was fixed as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1727 (or its variant https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394)


> Can you confirm you are able to see the problem with the snippet I have produced here ??
> 
> Also what is the version of Eclipse SDK you are on - I know you cited the plugin version, but it helps to know the SDK version too.

**Comment by srikanth-sankaran** [comment]
OK, since you mention `ecj-3.36.0-20231107.jar` I assume you are using Eclipse SDK but just the batch compiler. In this case can you try the ecj available from https://download.eclipse.org/eclipse/downloads/drops4/I20240109-1800/  - that would be `ecj-I20240109-1800.jar`

The reproducer runs fine on this jar.

**Comment by srikanth-sankaran** [comment]
Interestingly, https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1840 fails with 

```
java.lang.AssertionError
	at org.eclipse.jdt.internal.compiler.ast.YieldStatement.addSecretYieldResultValue(YieldStatement.java:120)
```

I'll see what is going on.

**Comment by srikanth-sankaran** [comment]
OK, locally reproduced too by supplying -ea to run/debug configuration

**Comment by srikanth-sankaran** [comment]
Smallest and simplest test case that shows the problem:

```
public class X {
	public static void main(String[] args) {
		String s = switch (new Object()) {
		case Integer i  -> "";
		case String y  -> "";
		default -> {
			try {
				throw new Exception();
			} catch (Exception e) {
				throw new RuntimeException();
			}
		}
		};
	}
}
```

**Comment by KostiantynDenysiuk** [comment]
Yes, You were absolutely right! With Your snippet I've got the same trouble here: 

[error]: Unexpected exception: java.lang.AssertionError
java.lang.AssertionError: null
	at org.eclipse.jdt.internal.compiler.ast.YieldStatement.addSecretYieldResultValue(YieldStatement.java:120) ~[ecj-3.36.0-20231107.jar:?]

**Comment by srikanth-sankaran** [comment]
PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1840 has been input for review. There are 3 possible fixes and I have opted for one. I would wait for comments from the original author (@mpalat) and figure out how best to take it forward.
