### ISSUE TITLE
[19] Code completion completely broken following a record pattern

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#185]
Put the following code in a class and try completing after the 'syso':

	 	boolean b = switch (o) {
	 		case Pair(Student s, Student s1) p1 -> true;
	 		default -> false;
	 	};
    	syso|

Nothing comes up on invoking code completion. There could be a several other case like this, but this is most basic and having a valid record pattern should not affect code completion in the surrounding code.

**Comment by vik-chand** [comment]
I tested some more and found these issues

- in RecordPatternTests::test10 ,  control-space on System.out.println("lr.p().y()= " + lr.p().^); gives
```
- java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.ast.SingleTypeReference cannot be cast to class org.eclipse.jdt.internal.compiler.ast.AbstractVariableDeclaration (org.eclipse.jdt.internal.compiler.ast.SingleTypeReference and org.eclipse.jdt.internal.compiler.ast.AbstractVariableDeclaration are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @4678fd33)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeExitVariableWithInitialization(Parser.java:4189)
	at org.eclipse.jdt.internal.codeassist.complete.CompletionParser.consumeExitVariableWithInitialization(CompletionParser.jav
```
- in test15(),  permi^ should prompt permits
- in test22(), wh^ should show when
- ase Rectangle(ColoredPoint(Point(int x, int y), Color c), ColoredPoint lr) r1 when x <= 0 && r1.^toString()==null -> 
  in the case when 'when' clause is used, one should be able to use content assist on r1.^

**Comment by vik-chand** [comment]
Any bug found during testing will be taken up via a new issue
