### ISSUE TITLE
3 new compiler test fails on I20240112-0200

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#1855]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240112-0200/testresults/html/org.eclipse.jdt.core.tests.compiler_ep431I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
testConsumingMethod_nok
testConsumingMethodUse_binary
testConsumingMethodUse
```

Most likely regression from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1716

**Comment by iloveeclipse** [comment]
@stephan-herrmann : could you please check?

**Comment by stephan-herrmann** [comment]
Spooky. 
All three tests are new indeed, but locally and in the PR build they succeeded.
I'll wait for results from other platforms ...

**Comment by stephan-herrmann** [comment]
Got it: it fails at compliance 1.7. Will disable below 1.8.
