### ISSUE TITLE
[switch][record patterns] NPE: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.MethodBinding.isStatic()"

### ISSUE THREAD

**Issue by KostiantynDenysiuk** [eclipse-jdt/eclipse.jdt.core#1856]
Snippet: 

package com.fortify.rp.testSwitch;

public class X1 {

    public class Data {
        String name;
    }

    record WrapperRec(ExhaustiveSwitch.Data data) {}

    public static void main(String[] args) {
        switch (new Object()) {
            case WrapperRec(var data) when data.name.isEmpty() -> { }
            default -> {}
        }
    }
}

Error when parsing: 
[error]: Unexpected exception while parsing file testSwitch/X1.java
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.MethodBinding.isStatic()" because "this.binding" is null
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:149) ~[ecj-3.36.0-20231107.jar:?]

**Comment by srikanth-sankaran** [comment]
Most JDT compiler engineers are on a 4 day long break - I will study this next week upon my return, Reproduced. Thanks for the report,

**Comment by srikanth-sankaran** [comment]
Problem is that we shouldn't be proceeding into code generation at all, given that there is a missing type.

**Comment by srikanth-sankaran** [comment]
@KostiantynDenysiuk I don't see any error with:

```
public class X1 {

public class Data {
String name;
}

record WrapperRec(Data data) {}

public static void main(String[] args) {
switch (new Object()) {
case WrapperRec(var data) when data.name.isEmpty() -> { }
default -> {}
}
}

}
```

JDT does not crash on this snippet as it did with the original snippet you posted.

But your comment says `ERROR still exists` - I am unable to see this

**Comment by KostiantynDenysiuk** [comment]
Yes, I found the mentioned mistake locally. Sorry for that.

**Comment by srikanth-sankaran** [comment]
That the compiler crashes on the original snippet is a problem that needs to be fixed, so closing is premature :)

Just to confirm, on this snippet:

```
public class X1 {

public class Data {
String name;
}

record WrapperRec(Data data) {}

public static void main(String[] args) {
switch (new Object()) {
case WrapperRec(var data) when data.name.isEmpty() -> { }
default -> {}
}
}

}
```

there is no problem - right ?

**Comment by KostiantynDenysiuk** [comment]
Right. It works well. I've made a mistake using unresolved class 

record WrapperRec(ExhaustiveSwitch.Data data) {}

when I changed it to 
record WrapperRec(Data data) {}

It works well. Sorry for disturb You. ``

**Comment by srikanth-sankaran** [comment]
No problem at all. You did report a genuine problem. Compilers should not crash on invalid input - that ecj does with the missing type is a bug. 

Thank you for reporting that! 😄

**Comment by KostiantynDenysiuk** [comment]
Thank You! Have a nice day!
