### ISSUE TITLE
[Spec Conformance] Annotations shouldn't be able to access private constants

### ISSUE THREAD

**Issue by danthe1st** [eclipse-jdt/eclipse.jdt.core#1861]
According to [Example 6.6-5. Access to private Fields, Methods, and Constructors](https://docs.oracle.com/javase/specs/jls/se21/html/jls-6.html#d5e11140) of the JLS (emphasis mine):
> A private class member or constructor is accessible only **within the body of the top level class** ([§7.6](https://docs.oracle.com/javase/specs/jls/se21/html/jls-7.html#jls-7.6)) that encloses the declaration of the member or constructor. It is not inherited by subclasses. [...]

For demonstration, take a look at the following class:
```java
@MyAnnotation(Test.ANNOTATION_TEXT)
public class Test{
    private static final String ANNOTATION_TEXT = "Hello World";
}
@interface MyAnnotation{
	String value();
}
```
This seems to compile with EJC but doesn't with `javac`.

**Comment by srikanth-sankaran** [comment]
Closing as duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1216

**Comment by srikanth-sankaran** [comment]
PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4828 addresses the problem
