### ISSUE TITLE
[22][test] JavaSearchBugs to be modified for running with JDK 22

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1871]
Following tests fail on Java 22 - atleast some of them are failing due to StackWalker class

org.eclipse.jdt.core.tests.model.JavaSearchTests.testAnonymousTypeMethodReferenceSearchGh432
org.eclipse.jdt.core.tests.model.JavaSearchBugs9Tests.testMethodReferenceForTypeFromJREModuleBugGh740
org.eclipse.jdt.core.tests.model.JavaSearchBugs9Tests.testGH902_whenTypeReferenceIsUnknownButQualified_expectToBeFound
org.eclipse.jdt.core.tests.model.JavaSearchBugs9Tests.testGH902_whenTypeReferenceIsUnknownButQualifiedNested_expectToBeFound
org.eclipse.jdt.core.tests.model.JavaSearchBugs9Tests.testGH902_whenTypeReferenceIsUnknownButNested_expectToBeFound
org.eclipse.jdt.core.tests.model.JavaSearchBugs16Tests.testAIOOBEForRecordClassGh790

@gayanper - I have assigned this to you..please let know in case you cannot take this up..
Anyway, please wait until https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1841 is merged before taking this up

**Comment by gayanper** [comment]
@mpalat i will be able to have a look at this next week since i'm busy with some other work. But if i get some extra time i will have a look at it during this week. But if someone else have time please pick this up.

**Comment by gayanper** [comment]
I will assign this to my self next week when i start work on it if it is not picked up by then by someone else.

**Comment by mpalat** [comment]
Thanks @gayanper !

**Comment by iloveeclipse** [comment]
Should be fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2286
