### ISSUE TITLE
[22][test] ModuleBuilderTests to be modified for JDK22

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#1874]
These tests are failing once pr #1841  is used.

- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testConvertToModule
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testConvertToModuleWithRelease9
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testBug512053
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testBug527569c
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption1
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption4
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption5
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption8
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption9
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption11
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption12
- org.eclipse.jdt.core.tests.model.ModuleBuilderTests.testReleaseOption13

would return if jre22 in the pr - need to re-enable after fixing

**Comment by jarthana** [comment]
I see something weird going on with the ct.sym of the JDK 22. I see that the classes not being loaded when --release is specified. I suspect they messed up the paths inside the ct.sym file.

@iloveeclipse Is this something you can look at?

**Comment by iloveeclipse** [comment]
@jarthana : I can. Which exact JDK 22 build have you tried?

**Comment by iloveeclipse** [comment]
I've tried to run ModuleBuilderTests locally on `openjdk-22-ea+32` build and commit 31ef12dd145f22210d90dc53596f0799d420482b (the latest one I see on BETA_JAVA22 branch) and everything is fine, I see no fails.

I've also briefly checked if the ct.sym structure / content looks different, but couldn't spot any major change (except new content for older releases). I'm using my very basic "JRT Browser" view which you can get importing project from 
https://github.com/iloveeclipse/jrtbrowser repo into workspace and run debugger IDE with that.

**Comment by iloveeclipse** [comment]
@jarthana, note: I saw the fails above while running tests on **master** branch. So I guess that was your mistake by using wrong branch?

**Comment by jarthana** [comment]
> I've tried to run ModuleBuilderTests locally on `openjdk-22-ea+32` build and commit [31ef12d](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/31ef12dd145f22210d90dc53596f0799d420482b) (the latest one I see on BETA_JAVA22 branch) and everything is fine, I see no fails.
> 
> I've also briefly checked if the ct.sym structure / content looks different, but couldn't spot any major change (except new content for older releases). I'm using my very basic "JRT Browser" view which you can get importing project from https://github.com/iloveeclipse/jrtbrowser repo into workspace and run debugger IDE with that.

That looks interesting. Let me try that. 
I am certain I tried with the right branch. In fact, Manoj reported it against his PR that he released in BETA_JAVA22 branch. Anyway, here's something else I tried:

1. Launch Eclipse from JDT workspace (I think it doesn't matter whether JDT is from master or BETA branch, but I tried from both)
2. Create a new project with JDK 22 in build path (I have the latest - EA 32)
3. Use compliance 16 and enable the --release option
4. Notice a build path error and another one saying "The type java.lang.Object cannot be resolved..."

The error doesn't occur with JDK 21.

**Comment by jarthana** [comment]
Something I noticed looking at the ct.cym through the JRT browser: I see that JDK 22 has two additional versions in JDK 22 (L and M). The L is supposed to be present in JDK 21, right?

**Comment by jarthana** [comment]
> Something I noticed looking at the ct.cym through the JRT browser: I see that JDK 22 has two additional versions in JDK 22 (L and M). The L is supposed to be present in JDK 21, right? Or is it the other way around?

Actually, ignore this. I dug bit deeper and found that in JDK 22, we are missing the `M\system-modules. This is expected by the code in `CtSym#isCurrentRelease12plus()`. The same is present in JDK 21 under `L\system-modules`

**Comment by jarthana** [comment]
Just to confirm my above theory, I removed the second condition in the following code in `CtSym.java` and the problem went away.

`if (releaseCode > JAVA_11 && Files.exists(this.fs.getPath(rel, "system-modules"))) {`

@iloveeclipse Can you try this and let me know what you find. I am surprised you are not seeing the test failures. Anyway, the scenario I mentioned two comments above eliminates other factors.

**Comment by iloveeclipse** [comment]
> Just to confirm my above theory, I removed the second condition in the following code in `CtSym.java` and the problem went away.
> 
> `if (releaseCode > JAVA_11 && Files.exists(this.fs.getPath(rel, "system-modules"))) {`
> 
> Can you try this and let me know what you find. I am surprised you are not seeing the test failures. Anyway, the scenario I mentioned two comments above eliminates other factors.

Correct, I still don't see test fails but I see that the condition is not OK anymore as Java 22 seem to have changed internal structure of that file and highest `M` folder contains again all ??? modules and no `system-modules`. In Java 21 the highest folder was `L` and it had a single `system-modules` child entry.

@srikanth-sankaran : not sure if you were ever involved in the ct.sym file structure, but do you know may be why the "inofficial" structure of it was changed in java 22?
