### ISSUE TITLE
Include JDT Groovy completion in JavaFX project

### ISSUE THREAD

**Issue by wise-coders** [eclipse-jdt/eclipse.jdt.core#1881]
I want to add Java Groovy text completion to a custom editor, written in JavaFX.
I need help for this. I can compensate this work.

A simplified version of the editor is [here](https://github.com/wise-coders/javafx-gradle.git).

The requirement is to pass a text ( some code ) to the Eclipse plugin, and with the caret position, and get back a list of completions. I expect Eclipse already has something like this build-in, and probably the Eclipse text editor is implementing some interfaces. I would implement the interface in my text editor as well, and bind it to the Eclipse plugin. Some guidance/consulting about how to do this would be fine.

**Comment by laeubi** [comment]
@wise-coders I think you should elaborate a bit more what exactly are your requirements, your environment and what issues are you facing, if you just need some guidance/consulting or want to outsource the development completely.

**Comment by laeubi** [comment]
You probably want to use a https://github.com/GroovyLanguageServer/groovy-language-server for such purpose ... as what you have "in eclipse" is more a feature of the editor (mostly). You can for example look into lsp4j/lsp4e project how language servers work, espcially how they implement the completion processor.

**Comment by wise-coders** [comment]
Thank you very much! This looks great. I will need time to read. 
We can close this issue. 
If I will have questions later, can I contact you back - help as consultancy?

**Comment by laeubi** [comment]
> If I will have questions later, can I contact you back - help as consultancy?

Sure feel free to contact me.

**Comment by wise-coders** [comment]
One more question, if I am allowed: 
I found a Java application called Install4j (for creating launchers) which also has build-in auto-completion. But from the libraries they use it seems they have a different approach. Do you have any idea?
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/60284259/2f1f4bc9-9c97-4cdd-a7b4-e8f52375a67a)

**Comment by laeubi** [comment]
JFace contains an autocomplete text field, but this is really a bit more low level than an editor:

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjface%2Ffieldassist%2FAutoCompleteField.html

**Comment by wise-coders** [comment]
Here is a screenshot of their code editor. They are using a CodeEditor, so probably they call the completion in a different way?
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/60284259/0285619d-17fb-4e24-bfb4-3bcc14bf0ac9)
