### ISSUE TITLE
unnecessary "Potential resource leak" warning

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1892]
in org.eclipse.ui.internal.wizards.datatransfer.TarFile.TarFile(File):61

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/86465be6-4081-488b-b9a7-cf31cf258a6d)
@stephan-herrmann

**Comment by stephan-herrmann** [comment]
Yea, this is BS, obviously. I already saw this when playing with the new feature, and reduced the example into #1848.
Unfortunately, this one has significant complexity, since we need to keep track of different resources that may be assigned to the same variable :(
