### ISSUE TITLE
Instanceof: "Duplicate local variable" 

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#1904]
This code Compiles in the IDE but fails to compile with batch compiler:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/222905c2-5cce-48d8-af68-f566efb63acb)

```
		switch (structSel.size()){
			case 1:
				file1 = getCurrentFileRevision();
				if (objArray[0] instanceof IFileRevision f2) {
					file2 = f2;
				} else {
					return;
				}
			break;

			case 2:
				if (objArray[0] instanceof IFileRevision f1 && objArray[1] instanceof IFileRevision f2) {
					file1 = f1;
					file2 = f2;
				} else {
					return;
				}
			break;
		default:
			break;
		}
```

```
12:11:50.637 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.5-SNAPSHOT:compile (default-compile) on project org.eclipse.team.ui: Compilation failure: Compilation failure: 
12:11:50.637 [ERROR] /home/jenkins/agent/workspace/eclipse.platform_PR-1143/team/bundles/org.eclipse.team.ui/src/org/eclipse/team/internal/ui/actions/CompareRevisionAction.java:[81] 
12:11:50.637 [ERROR] 	if (objArray[0] instanceof IFileRevision f1 && objArray[1] instanceof IFileRevision f2) {
12:11:50.637 [ERROR] 	                                                                                    ^^
12:11:50.638 [ERROR] Duplicate local variable f2
```
from https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1143/1/console

**Comment by iloveeclipse** [comment]
The code was using this version: `Compiling 345 source files to /home/jenkins/agent/workspace/eclipse.platform_PR-1143/team/bundles/org.eclipse.team.ui/target/classes using Eclipse Compiler for Java(TM) 3.37.0.v20240115-1036` and I assume it corresponds to this commit: e04852bf615e3f30f31a82a04bd30c99bdf5ea41.

At this commit I also see error in the IDE.
Switching IDE to 35bf3605e3a1fba5c0864479d04fef13452f9046 commit error disappears, and commit message explains the reason why.

With that, we can close this issue.

**Comment by akurtakov** [comment]
@jukzi In order to fix the console build one has to deploy latest ecj via (https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/) and then switch to it in eclipse-platform-parent (https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/6791247801f0e71bc476222858ff5cad51bc9eb4/eclipse-platform-parent/pom.xml#L89). Completing these should really fix the issue.
