### ISSUE TITLE
NoSuchFieldError RELEASE_17 in org.eclipse.jdt.core 1.9.21.RC1

### ISSUE THREAD

**Issue by dhsmith1001** [eclipse-jdt/eclipse.jdt.core#1912]
When I upgraded my aspectj compiler from 1.9.20 to 1.9.21 I got a compile error:

[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.14.0:compile (default) on project server: AJC compiler errors:
[ERROR] abort ABORT -- (NoSuchFieldError) RELEASE_17
[ERROR] RELEASE_17
[ERROR] java.lang.NoSuchFieldError: RELEASE_17
[ERROR]         at org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.BaseProcessingEnvImpl.<clinit>(BaseProcessingEnvImpl.java:49)

Version 1.9.21 of aspectj depends on version 1.9.21.RC1 of org.eclipse.jdt.core.

[aspectj-build-error.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14057813/aspectj-build-error.txt)
[ajcore.20240125.160119.952.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14057826/ajcore.20240125.160119.952.txt)

**Comment by iloveeclipse** [comment]
Don't get me wrong - shouldn't you report this issue at aspectj?

**Comment by dhsmith1001** [comment]
> Don't get me wrong - shouldn't you report this issue at aspectj?

Yes, sorry! I didn't realize aspectj had forked the module.
