### ISSUE TITLE
ECJ 3.35 and newer: Gennerated inner classes cannot be imported in the same package.

### ISSUE THREAD

**Issue by jchalou** [eclipse-jdt/eclipse.jdt.core#1923]
```
import org.example.GenerateInnerClassTriggerGen.Inner;

public class GenerateInnerClassTrigger {
    @GenerateInnerClassAnnotation
    private int x;

    {
        Inner inner = new Inner();
    }
}
```
ECJ 3.35 and newer cannot resolve the import `import org.example.GenerateInnerClassTriggerGen.Inner`.

Small maven project that reproduces the bug:
https://github.com/jchalou/jdtbug2/

**Comment by srikanth-sankaran** [comment]
Demonstrating the problem as a stand-alone Java test case will elicit faster response in general.

**Comment by jukzi** [comment]
sound like https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1654#issuecomment-1841261160

did you check it's not already fixed in current build?
https://download.eclipse.org/eclipse/downloads/drops4/I20240128-1800/

**Comment by srikanth-sankaran** [comment]
> sound like https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1654#issuecomment-1841261160
> 
> 
> 
> did you check it's not already fixed in current build?


That one is still open ??

> 
> https://download.eclipse.org/eclipse/downloads/drops4/I20240128-1800/
> 
>

**Comment by jukzi** [comment]
> That one is still open ??

the APT part was fixed.

**Comment by jchalou** [comment]
I can confirm that "ecj-I20240128-1800.jar" has this issue fixed.
