### ISSUE TITLE
Caching Compiler Threads?

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#1937]
While debugging an Eclipse Instance I noticed that when many projects are rebuild I see a lot of "Compiler Processing Thread" come and go in the Debugger. Maybe it would be good to have a (cached) Threadpool instead of creating and destroying Threads instead?

**Comment by jukzi** [comment]
i worked on such pool in https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/177563
