### ISSUE TITLE
[content assist] Duplicate constructor completion

### ISSUE THREAD

**Issue by snjeza** [eclipse-jdt/eclipse.jdt.core#195]
Version: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/ba0944dbadfa1fbfd5927e80084ffe03718c43d4

Steps to reproduce:
![constructor](https://user-images.githubusercontent.com/388609/177638483-c5cae8b2-2b1d-4c6b-b308-a177d5208e1d.gif)

A related issue -https://github.com/eclipse/eclipse.jdt.ls/issues/2147

**Comment by rgrunber** [comment]
Just saw this as well while trying the PR referenced.
