### ISSUE TITLE
Migration of JDT wiki pages 

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.core#1989]
Does the JDT project wants to migrate some of their wiki pages to mark-down in the repos? If yes, please list them here.

cc @jarthana @akurtakov

**Comment by iloveeclipse** [comment]
Did you have noticed https://github.com/eclipse-jdt/eclipse.jdt.core/wiki ?
AFAIK we've done here.

**Comment by vogella** [comment]
To make this discoverable for others, I suggest to add links to the new content in the old wiki pages At least https://wiki.eclipse.org/JDT/ or https://wiki.eclipse.org/JDT/FAQ 

I leave that to the JDT team to decided if that is worthy their effort, ticket can remain closed.
