### ISSUE TITLE
Missing resource leak warning for FileInputStream

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.core#1990]
In Eclipse 2023-12 the following code
```
public class EclipseMissingWarningAutoCloseable {

    public static void main(String[] args) throws Exception {
	int foo = test();
	System.out.println(foo);

    }

    public static int test() throws Exception {
	FileInputStream fis = new FileInputStream(new File("."));
	return fis.available();
    }

}
```
does not show any warnings about the resource leak. I turned on both "resource leak" and "potential resource leak" warnings.

**Comment by jukzi** [comment]
can not reproduce on master
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/16c20deb-1af9-48fb-b005-c7317c962b10)
