### ISSUE TITLE
ECJ produces redundant bytecode for instanceof pattern matching

### ISSUE THREAD

**Issue by gtoison** [eclipse-jdt/eclipse.jdt.core#2003]
As noted in https://github.com/spotbugs/spotbugs/issues/1992#issuecomment-1225443082 ECJ seems to produce redundant bytecode compared for javac for instanceof pattern matching: 

When compiling the following example
```
public static void main(String[] args) {
    Number n = Integer.valueOf("0");
    if (n instanceof Integer i) {
        System.out.println("int " + i);
    }
}
```
Compiles to this with ECJ:
```
         0: ldc           #16                 // String 0
         2: invokestatic  #18                 // Method java/lang/Integer.valueOf:(Ljava/lang/String;)Ljava/lang/Integer;
         5: astore_1
         6: aload_1
         7: astore_3
         8: aload_3
         9: instanceof    #19                 // class java/lang/Integer
        12: ifeq          50
        15: aload_3
        16: checkcast     #19                 // class java/lang/Integer
        19: dup
        20: astore_2
        21: aload_3
        22: checkcast     #19                 // class java/lang/Integer
        25: if_acmpne     50
        28: getstatic     #24                 // Field java/lang/System.out:Ljava/io/PrintStream;
...
        50: return
```
While javac produces:
```
         0: ldc           #7                  // String 0
         2: invokestatic  #9                  // Method java/lang/Integer.valueOf:(Ljava/lang/String;)Ljava/lang/Integer;
         5: astore_1
         6: aload_1
         7: instanceof    #10                 // class java/lang/Integer
        10: ifeq          30
        13: aload_1
        14: checkcast     #10                 // class java/lang/Integer
        17: astore_2
        18: getstatic     #15                 // Field java/lang/System.out:Ljava/io/PrintStream;
...
        30: return
```

Note that ECJ produces two checkcast and the if_acmpne triggers SpotBugs' SA_LOCAL_SELF_COMPARISON

**Comment by iloveeclipse** [comment]
Please try latest build from https://download.eclipse.org/eclipse/downloads/
There was recently a major rewritein this area.

**Comment by srikanth-sankaran** [comment]
> Please try latest build from https://download.eclipse.org/eclipse/downloads/ There was recently a major rewritein this area.

Yes, this is addressed via https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1406. 

And once https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2000 - proposed for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/300 is merged in (expected today), we produce very compact code for record patterns also.
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2000#issuecomment-1937405686

**Comment by gtoison** [comment]
Thank you very much for the improvements and answers!
