### ISSUE TITLE
[Patterns][unnamed] Support for identifier '_' for old compile source/target versions

### ISSUE THREAD

**Issue by kriegaex** [eclipse-jdt/eclipse.jdt.core#2008]
This issue was first mentioned on the _jdt-dev_ mailing list. @iloveeclipse asked me to create an issue.

I noticed after the latest merge of `3.37.0-SNAPSHOT` into the AspectJ fork, that some old tests compiling to source/target 1.5 started failing. Those tests used `_` as class or method names on purpose, because before 1.8 it was still allowed to do so. After recent changes, probably with the intention to support `_` for unnamed classes/patterns, probably JDT Core is prepared for the latter, but breaks for the former, even if explicitly targeting 1.5. IMO, that is a regression bug. But I could be wrong. Maybe, you have plans to drop pre-1.8 source/target versions completely in 3.37.0. Can you please enlighten me?

**Comment by kriegaex** [comment]
Thanks for the swift reaction and the fix, @srikanth-sankaran. 🙂 I have re-tested it and merged it into the AspectJ fork, where it is working as expected, too.

**Comment by srikanth-sankaran** [comment]
You are welcome.
