### ISSUE TITLE
Pattern matching instanceof expression with bit-wise-and doesn't report a parser error but doesn't recognize pattern variable

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-jdt/eclipse.jdt.core#2039]
The following code:

```
public class BadInstanceOfExpression {
	public void func(boolean exp, boolean useStrikethroughForCompleted, Object data) {
		if (data instanceof Long task  & useStrikethroughForCompleted) {
			if (task.intValue() == 0) {
				int i = 0;
			}
		}
	}
}
```

Marks that the task variable is unknown at the point of task.intValue().  While the code is an invalid use of bit-wise-and, the question is whether the bit-wise-and should have been flagged or if the original reference to task should have been flagged or whether this should have passed.

part of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1197

**Comment by srikanth-sankaran** [comment]
I don't see a defect here. ECJ behavior matches javac and the spec.

```
15.22.2 Boolean Logical Operators &, ^, and |
When both operands of a &, ^, or | operator are of type boolean or Boolean, then
the type of the bitwise operator expression is boolean. In all cases, the operands
are subject to unboxing conversion (§5.1.8) as necessary.
For &, the result value is true if both operand values are true; otherwise, the result
is false.
For ^, the result value is true if the operand values are different; otherwise, the
result is false.
For |, the result value is false if both operand values are false; otherwise, the
result is true
```

**Comment by srikanth-sankaran** [comment]
However, flow scoping of pattern binding is defined only for logical && operator - hence the error about task being undefined by both javac and ECJ. So there is no defect here.
