### ISSUE TITLE
ResourceLeakTests & ResourceLeakAnnotatedTests fail in some compliance levels when run locally via RunJDTCoreTests

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2041]
testGH1762 - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakTests)
test056l - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testBug411098_comment19_annotated - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testBug440282_annotated - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testCustomWrapperResource - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testCustomWrapperResource_binary - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testGH1762 - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testInheritance - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testNotOwningCloseableClass - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testNotOwningCloseableClass_binary - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testNotOwning_return - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK1 - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK2 - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_OK - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit2 - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_binaryCall - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_call - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_return - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testSharedField - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testSubclassingWrapperResource - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testUnannotated_return - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testWrappingTwoResources - 1.3(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testGH1762 - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakTests)
test056l - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testBug411098_comment19_annotated - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testBug440282_annotated - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testCustomWrapperResource - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testCustomWrapperResource_binary - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testGH1762 - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testInheritance - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testNotOwningCloseableClass - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testNotOwningCloseableClass_binary - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testNotOwning_return - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK1 - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK2 - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_OK - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit2 - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_binaryCall - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_call - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_return - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testSharedField - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testSubclassingWrapperResource - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testUnannotated_return - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testWrappingTwoResources - 1.4(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testGH1762 - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakTests)
test056l - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testBug440282_annotated - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testCustomWrapperResource - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testGH1762 - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK1 - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK2 - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit2 - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_binaryCall - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_call - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testSubclassingWrapperResource - 1.5(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testGH1762 - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakTests)
test056l - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testBug440282_annotated - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testCustomWrapperResource - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testGH1762 - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK1 - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_NOK2 - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwningField_binaryField_lazyInit2 - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_binaryCall - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testOwning_receiving_from_call - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)
testSubclassingWrapperResource - 1.6(org.eclipse.jdt.core.tests.compiler.regression.ResourceLeakAnnotatedTests)

**Comment by srikanth-sankaran** [comment]
@stephan-herrmann - Thanks for taking a look.

**Comment by stephan-herrmann** [comment]
Thanks!

None of these tests are intended for those compliance levels:
* ResourceLeakTests.testGH1762 needs individual inclusion
* for ResourceLeakAnnotatedTests declaring minimal compliance 1.7 was half-baked (only in the test class, not where it's integrated in TestAll)

**Comment by stephan-herrmann** [comment]
BTW, for me also org.eclipse.jdt.core.tests.compiler.regression.LookupTest.test075() failed below 1.5. Did you observe the same?

**Comment by srikanth-sankaran** [comment]
> BTW, for me also org.eclipse.jdt.core.tests.compiler.regression.LookupTest.test075() failed below 1.5. Did you observe the same?

Yes, there is an open ticket for it. Has been there for a while.
