### ISSUE TITLE
Enumerations incompatible with "javac"

### ISSUE THREAD

**Issue by ilhikki** [eclipse-jdt/eclipse.jdt.core#205]
For example, complire the follow code by eclipse complier, obtain a class, the problem is javac can not read it.
```java
pakcage com.xxx;
enum MyEnum {
    ;
    MyEnum(@NotNull String a, @NotNull String b, @NotNull String c) {
        
    }
}
```

Because the output of JDT and javac are different, where the result code of javac has attr `Sigature` but eclipse complier not (only has `RuntimeInvisibleParameterAnnotations`)

**Comment by ilhikki** [comment]
![image](https://user-images.githubusercontent.com/29532519/178253951-7f4f2492-6977-4c5e-aec1-754726aae18f.png)
![image](https://user-images.githubusercontent.com/29532519/178254119-d0b41f7e-580a-4ef4-9b2f-53c851b75b33.png)

**Comment by ilhikki** [comment]
[jdt-issue-205.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14381734/jdt-issue-205.zip)

Hello! I have uploaded an example to show my issue, hope it helps to explain the issue. The file structure looks like
- javac-classes (include class files which were compiled by `javac`(openjdk21))
- jdt-classes  (include class files which were compiled by `jdt`)
- src (include srouce files )

Now compile `Main.java` with `javac-classes`
`javac src/com/xxx/Main.java -cp ./javac-classes/`
it works.
Then execute the command to compile `Main.java` with `jdt-classes`
`javac src/com/xxx/Main.java -cp ./jdt-classes/`
Then print error
```
 src\com\xxx\Main.java:5: error: cannot access MyEnum
        System.out.println(MyEnum.class);
                           ^
  bad class file: .\jdt-classes\com\xxx\MyEnum.class
    class file is invalid for class com.xxx.MyEnum
    Please remove or make sure it appears in the correct subdirectory of the classpath.
src\com\xxx\Main.java:5: error: cannot access System
        System.out.println(MyEnum.class);
        ^
  bad class file: /modules/java.base/java/lang/System.class
    bad RuntimeInvisibleParameterAnnotations attribute: registerNatives()
    Please remove or make sure it appears in the correct subdirectory of the classpath.
2 errors
```
Actually, no mistakes occur when we run with java:
`
java -cp ./src;javac-classes/ com.xxx.Main
java -cp ./src;jdt-classes/ com.xxx.Main
`
both OK.  But when we compile using javac while importing from a library compiled by JDT, the issue appears

I guess it matters with The Signature Attribute, but I am not sure ECJ or Javac which is incorrect.

**Comment by srikanth-sankaran** [comment]
This is very likely the same as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1964

**Comment by stephan-herrmann** [comment]
> So at the outset it looks correct that ECJ does not emit Signature attribute for the constructor. There are no type variables or parameterized types in the constructor signature - ??

The only type parameter is in the implicit `extends java.lang.Enum<MyEnum>` in the class header.

But for the constructor this looks bogus. This can be shown also by comparing signature and descriptor emitted by javac: they are identical, i.e, the signature adds no value and hence it cannot be mandatory.

**Comment by ilhikki** [comment]
I seem to have pinpointed the cause of the problem. When we compile use javac, The exception causing this issue：`java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3`
And the array at
```
setParameters(Symbol$MethodSymbol, Type):2376, ClassReader (com.sun.tools.javac.jvm), ClassReader.java
```
We and debugger at here
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/29532519/f7fc1550-7cd5-418b-9117-b079f202a6e1)
In the image, when javac iterates over `sym.type.getParameterTypes()`, get accesses value in the `parameterAnnotations` by index. However, in this example,  when classes are compiled by JDT,  `parameterAnnotations.length` is 3 and  `sym.type.getParameterTypes().size()` is 5. I believe the first and second parameters represent the enum name and its ordinal, respectively. (extends the constructor `protected Enum(String name, int ordinal)` ).

The following image shows classes compiled by javac, where the difference lies in sym.type.getParameterTypes().size(), which is 3 instead of 5.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/29532519/4fd43cb2-3342-4a03-8671-7829d2196674)

**Comment by stephan-herrmann** [comment]
@ilhikki  those are interesting results.

At a quick look it seems that `javac` does not respect these sentences from [JVMS 4.7.19](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-4.html#jvms-4.7.19)

> [num_parameters] ... There is no assurance that this number is the same as the number of parameter descriptors in the method descriptor. 

and then 
> The i'th entry in the parameter_annotations table may, but is not required to, correspond to the i'th parameter descriptor in the method descriptor ([§4.3.3](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-4.html#jvms-4.3.3)).

Whenever a compiler inserts synthetic method parameters (for which there are several reasons) then it doesn't make a lot of sense to allocate a slot for annotations on this parameter, which doesn't exist is source and hence cannot be annotated.

The AIOOBE in javac seems to relate to ecj making use of the above snippets of specification.

Maybe @srikanth-sankaran has already heard of such a bug in javac?

**Comment by srikanth-sankaran** [comment]
Past spec update here: https://bugs.openjdk.org/browse/JDK-8067975 - closed

Javac issue: https://bugs.openjdk.org/browse/JDK-8213329

Also see https://bugs.openjdk.org/browse/JDK-8062582

@ilhikki - Have you reported a defect against javac ? If it encounts an AIOOB and swallows that and exposes that as a bad class file - that is problematic.

**Comment by srikanth-sankaran** [comment]
Any regression test added here should also capture the scenario from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1964

**Comment by ilhikki** [comment]
> @ilhikki - Have you reported a defect against javac ? If it encounts an AIOOB and swallows that and exposes that as a bad class file - that is problematic.

No, because I don't know whose responsibility it was at that time

**Comment by srikanth-sankaran** [comment]
I have tracked it down to an existing javac defect https://bugs.openjdk.org/browse/JDK-8024694 that references https://bugs.eclipse.org/bugs/show_bug.cgi?id=388314. 

Interestingly the fix is repeatedly deferred for behavioral compatibility impact - but they can continue to emit what they do while still handling what ECJ emits (which is JLS compliant) - Not sure why that is not undertaken. 

Closing this defect as it is not a problem in ECJ. It is unfortunate that javac traps an AIOOB and reports it as a bad class file - this raises unnecessary suspicion on innocent parties :)

**Comment by stephan-herrmann** [comment]
> I have tracked it down to an existing javac defect https://bugs.openjdk.org/browse/JDK-8024694 that references https://bugs.eclipse.org/bugs/show_bug.cgi?id=388314.
> 
> Interestingly the fix is repeatedly deferred for behavioral compatibility impact - but they can continue to emit what they do while still handling what ECJ emits (which is JLS compliant) - Not sure why that is not undertaken.

I asked again at https://mail.openjdk.org/pipermail/compiler-dev/2024-June/026996.html to the effect that https://bugs.openjdk.org/browse/JDK-8024694 now says: "Fix Version/s: 24".
