### ISSUE TITLE
[memory] deduplicate ResolvedBinaryType.uniqueKey

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2054]
Resolved*Type.uniqueKey contains a lot of duplicate Strings after open quicktypehierarchy as shown in heapdump:

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/d0697cf6-a51c-4905-ab5e-46a81c381c59)
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/540a604f-a4e4-45ff-9fcb-4a2c10189366)
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/f04b1b77-f959-4d7c-b93e-85ae0ec73563)
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/8ccc664f-94d6-4469-be8c-9d07cb4d9f02)

**Comment by mickaelistria** [comment]
This has caused a subtle regression: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4389
