### ISSUE TITLE
Incorrect  sourceStart  values coming from the ECJ for String template

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#2061]
I have two scenarios:

```
package test1;
public class X {
  void foo(Object o) {
    String name = "Jay";
    String s = STR."hello ";
  }
}
```

```
package test1;
public class X {
  void foo(Object o) {
    String name = "Jay";
    String s = STR."hello \{name}";
  }
}
```
The only difference is that in the second scenario, there is a template expression along with the first fragment.

So the **sourceStart** should be the same for both scenarios. 
<img width="499" alt="without-component-start-position" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/117082823/72b69b59-a0ea-4ea3-a44c-ab121551f2d4"> => without a template expression

<img width="517" alt="with-component-start-position" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/117082823/517b433e-02b1-4fe7-aad6-a12200fd4c37"> => with a template expression

However, two different values are coming from the org.eclipse.jdt.internal.compiler.ast.StringTemplate class for the **sourceStart**.

<img width="476" alt="without-component-source" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/117082823/e74a8b28-44cd-4132-a1cb-12d178dcaba4"> => without a template expression

<img width="501" alt="with-component-source" src="https://github.com/eclipse-jdt/eclipse.jdt.core/assets/117082823/0126f106-92a4-4dee-aa37-f04f5312072c"> => with a template expression

Because of the incorrect **sourceStart**, dom ASTConverter, calculates the value based on this. Therefore this leads issues in the ASTRewriter process.

**Comment by subyssurendran666** [comment]
@mpalat, could you please assign this ticket to me.

**Comment by mpalat** [comment]
@jarthana I have assigned this issue to you as well as discussed.

**Comment by mpalat** [comment]
I believe this is a non-issue now since String Template is not there. closing
