### ISSUE TITLE
Tab characters at the end of each multi line string are omitted  

### ISSUE THREAD

**Issue by kasim-ba** [eclipse-jdt/eclipse.jdt.core#2067]
When reading multi line string either from a text block: like
```
		var data = """
one	two	three			
one	two	three	four	five	six
one						
				""";
```
the tab characters (\t) before the new line are ignored. The same thing happens if the data is saved in a text (i,e, csv) file and read with a `InputStreamReader`, 

I'm currently working with STS 4.21.

**Comment by iloveeclipse** [comment]
> tab characters (\t) before the new line are ignored

Ignored **where**, or by **whom**? Can you please also check with Eclipse 4.31 latest build from https://download.eclipse.org/eclipse/downloads/drops4/I20240225-1800 ?

**Comment by kasim-ba** [comment]
Sorry for not being precise enough.
This is the representation of the string in debug mode: `one\ttwo\tthree\none\ttwo\tthree\tfour\tfive\tsix\none\n`
If I call `data.toCharArray()` directly after the string is created the tab characters are missing from the char array. I looked into the byte code of the string and the tab character was also missing there.
Byte representation: 
`[111, 110, 101, 9, 116, 119, 111, 9, 116, 104, 114, 101, 101, 10, 111, 110, 101, 9, 116, 119, 111, 9, 116, 104, 114, 101, 101, 9, 102, 111, 117, 114, 9, 102, 105, 118, 101, 9, 115, 105, 120, 10, 111, 110, 101, 10]`
While using a regular string the tab characters are not omitted: `one\ttwo\tthree\t\t\t`

I will also check this behavior with the newest release.
