### ISSUE TITLE
[22][search] Search support for JEP 447 Statements before super

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2079]
Investigate (and testcases definitely) for Search. Not expecting any dom change here.
This is for issue https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2083

**Comment by mpalat** [comment]
@subyssurendran666 can you please take this up?

**Comment by subyssurendran666** [comment]
Sure @mpalat
