### ISSUE TITLE
[22] IDE Support for JEP 459: String Templates - Second Preview 

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2084]
Refer the batch compiler issue #1594 

- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1800
- [ ]  https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2274
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1601

**Comment by mpalat** [comment]
@subyssurendran666 please take a look at the search as well

**Comment by subyssurendran666** [comment]
@mpalat Sure.

**Comment by mpalat** [comment]
> @mpalat Sure.

@subyssurendran666  please mention search bug number here

**Comment by subyssurendran666** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2274

**Comment by subyssurendran666** [comment]
> > @mpalat Sure.
> 
> @subyssurendran666 please mention search bug number here

This is the issue for Java search support for String Templates(JEP-459) https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2274

**Comment by mpalat** [comment]
no longer relevant as this feature is removed
