### ISSUE TITLE
[22][dom ast][rewrite] Add ASTRewrite support for EitherOrMultiPattern nodes

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2087]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2069 introduces new DOM AST node `EitherOrMultiPattern` ASTRewrite support is lacking as of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2011 which defines the node and hooks it into `ASTConverter`

@mpalat - could this be assigned to someone ? Perhaps @subyssurendran666 ? Thanks

**Comment by mpalat** [comment]
@subyssurendran666 can you help with this?

**Comment by subyssurendran666** [comment]
@mpalat Sure Manoj. Could you please assign this ticket to me ?

**Comment by mpalat** [comment]
moving this out of 4.32
