### ISSUE TITLE
Deploy the ecj.jar to the eclipse-maven-respository

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#209]
ECJ is already deployed [here](https://download.eclipse.org/eclipse/downloads/drops4/I20220712-1800/download.php?dropFile=ecj-I20220712-1800.jar).

It would be useful if a SNAPHSOT would also be deployed [to the eclipse-maven-repository](https://repo.eclipse.org/content/repositories/) e.g. with a command line call like described in:

https://maven.apache.org/guides/mini/guide-3rd-party-jars-remote.html

**Comment by laeubi** [comment]
@merks I think you mentioned somewhere that IBuilds are already deployed, would something similar work here as well I and Tycho is doing snapshot deploys already (@akurtakov @mickaelistria) so I don't see a reason to not do it (for the single jar) here as well.

**Comment by merks** [comment]
This does the Maven publishing:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/

The platform publishing failed two days in a row.  I the past this ends up correcting itself so I think just a network problem actually deploying to repo.eclipse.org...

In any case, JDT is not failing and there are snapshots of ecj here:

https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/jdt/ecj/3.36.0-SNAPSHOT/

**Comment by laeubi** [comment]
> In any case, JDT is not failing and there are snapshots of ecj here

Then I think this can be closed...
