### ISSUE TITLE
[Sealed classes] Inconsistent type hierarchy on sealed interface when used with other from different level in class hierarchy

### ISSUE THREAD

**Issue by RedeemerSK** [eclipse-jdt/eclipse.jdt.core#2108]
It seems that JDT wrongly reports problem on interface that is a member of sealed class hierarchy when implemented by class that also implements other interface from same sealed class hierarchy but from different "level" = depth in hierarchy tree.

However I may be tottaly wrong that class hierarchy level (depth) of an used interface may be a factor in this behavior.

Quick summary of reproducer:

```
// BaseInterface.java
public sealed interface BaseInterface permits SubInterfaceA, SubInterfaceB {}

// SubInterfaceA.java
public sealed interface SubInterfaceA extends BaseInterface permits TestClassA, SubSubInterfaceA {}

// SubInterfaceB.java
public sealed interface SubInterfaceB extends BaseInterface permits TestClassB {}

// SubSubInterfaceA.java - show errors
public sealed interface SubSubInterfaceA extends SubInterfaceA permits TestClassB {}

// TestClassA.java
public final class TestClassA implements SubInterfaceA {}

// TestClassB.java
public final class TestClassB implements SubSubInterfaceA, SubInterfaceB {}
```

Full reproducer with 2 other examples where things (surprisingly) works fine :
https://github.com/RedeemerSK/sealed-classes-reproducer

**Comment by RedeemerSK** [comment]
fyi @srikanth-sankaran : maybe the suspected 'different level in class hierarchy' may help to pinpoint some weak spots in JDT code.

**Comment by srikanth-sankaran** [comment]
@mpalat @jarthana - I plan to work on this in the 4.32 M3 time frame - if you have cycles ahead of it, please grab and take over. Thanks

**Comment by srikanth-sankaran** [comment]
This problem is already resolved by the fix pushed for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2093 - I will add a regression test and close this soon
