### ISSUE TITLE
[22] VerifyError when String template expression is used as part of condition

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2121]
```
interface TemplateProcessor extends java.lang.StringTemplate.Processor<Boolean, RuntimeException> {
    Boolean process(StringTemplate st);
}

public class X {
    public static void main(String argv[]) {
        TemplateProcessor STR = st -> st.interpolate().equals("abc");
        if (STR."abc") {
        	System.out.println("hello");
        }
    } 
}
```
This is supposed to print "hello, but we get this error:

```
Error: Unable to initialize main class X
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    X.main([Ljava/lang/String;)V @20: ifeq
  Reason:
    Type 'java/lang/Boolean' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @20
    flags: { }
    locals: { '[Ljava/lang/String;', 'TemplateProcessor' }
    stack: { 'java/lang/Boolean' }
```

I suspect this will be a problem with other statements like 'for' and 'while' as well.

**Comment by mpalat** [comment]
@jarthana I see that we are not calling booleanValue() before  ifeq. That should fix the issue
ie
ecj generates only
        12: invokeinterface #23,  2           // InterfaceMethod TemplateProcessor.process:(Ljava/lang/StringTemplate;)Ljava/lang/Boolean;
        17: checkcast     #28                 // class java/lang/Boolean
        20: ifeq          31

If we take a normal (read non-string template code), we see the following:
    X(Boolean i) {
        super();
    	if (i) 
    		System.out.println("hee");
    }

translates to:
         0: aload_0
         1: invokespecial #8                  // Method java/lang/Object."<init>":()V
         4: aload_1
         5: invokevirtual #11                 // Method java/lang/Boolean.booleanValue:()Z
         8: ifeq          19
        11: getstatic     #17                 // Field java/lang/System.out:Ljava/io/PrintStream;
...

the relevant part being:
         5: invokevirtual #11                 // Method java/lang/Boolean.booleanValue:()Z
         8: ifeq          19

essentially Boolean.booleanValue:() should fix the same.

**Comment by jarthana** [comment]
When I was looking at the code, I wondered if we should override generateOptimizedBoolean() and/or resolveTypeExpectingWithBindings() in TemplateExpression. I certainly see the patch works for this case, but just wondering if there will ever be a case where this won't be sufficient. Just thinking aloud.

Tagging @srikanth-sankaran as he also reviewed the original string template code.

@mpalat since you are taking up this, can you also add tests for other statements like for and while?

**Comment by mpalat** [comment]
> @mpalat since you are taking up this, can you also add tests for other statements like for and while?
sure - added the tests

**Comment by mpalat** [comment]
merged via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2126
