### ISSUE TITLE
Circular dependency error when using JPMS

### ISSUE THREAD

**Issue by newmangreen** [eclipse-jdt/eclipse.jdt.core#2122]
Hi,
We are on a project to migrate a big Java application containing multiple modules. We decided to use Java module system in compile-time only(since Jakarta EE Web Projects) but when using Eclipse it is not possible to use circular dependency in module-info.java. To fix this dependency problem in our application is "impossible".

Let's say we have 2 modules depends each other; X -> Y and Y -> X
During defining this relationship in module-info.java,
Eclipse gives this error "Cycle exists in module dependencies, Module X requires itself via Y"

Yes, circular dependency is a bad thing but before JPMS(Java 9) we can bypass this control by changing this setting to "Warning". Preferences>Java>Compiler>Build Path Problems>Circular dependencies = Error -> Warning

What I suggest is, same setting or a new setting should provide this bypass as before. So, what I expect is if it is set to "Warning",
then compiler should not complain about circular dependency in module-info as well.

Thank you.

**Comment by jukzi** [comment]
Since circular dependencies should and can be avoided in general [1] there will be probably not much use of such feature.
If you still think you need it is best if you provide a PR.

[1] https://opus.ch/modularity-patterns-with-jpms-acyclic-dependencies/

**Comment by iloveeclipse** [comment]
See also good answer on https://stackoverflow.com/questions/35688995/will-cyclic-module-dependencies-be-possible-in-java-9 pointing to  https://openjdk.org/projects/jigsaw/spec/issues/#CyclicDependences 

> Resolution Cyclic dependences will not be supported at this time. They could be supported in a later revision, if necessary, after a thorough analysis of the impact of this change on both the specification and the implementation.

So you are asking to add an option to allow ecj compile something that is currently not supported by JPMS => closing.

Once that would be supported by Java, feel free to reopen.

**Comment by newmangreen** [comment]
OK, thank you for your attention.
