### ISSUE TITLE
[22][dom ast][rewrite] DOM AST Rewrite Support for JEP 447 Super After Statement

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2131]
rewrite part of issue #2078 
Essentially expecting only test case changes as I don't anticipate any rewrite change.

**Comment by mpalat** [comment]
@subyssurendran666 please address this as well

**Comment by mpalat** [comment]
Done with pr #2132 merge. Thanks @subyssurendran666

**Comment by subyssurendran666** [comment]
Done.
