### ISSUE TITLE
bug class nor found 

### ISSUE THREAD

**Issue by appt2** [eclipse-jdt/eclipse.jdt.core#2134]
https://github.com/eclipse-jdt/eclipse.jdt.core/assets/143449333/1322f071-aaea-479e-9ccd-acfdbc2fcba2

I use your code formatter arranger, it works fine on Android 14 but not below that
(NoClassDefFoundError ..... StackWalker)
https://github.com/appt2/Ghost-web-ide/blob/main/app/src/main/java/io/github/rosemoe/sora/langs/java/JavaLanguage.java#L180

Just don't pay attention to the class name, it's a typo

**Comment by jukzi** [comment]
```
Is Java compatible with Android?
Each version of Android supports a specific version of the JDK and a subset of its available Java APIs

```
Please note that android is not supported. JDT requires a full JDK 17 to run.
If you can reproduce with most recent version and on JDK 17 Please create a standalone example how to reproduce. Preferably as JUnit Test. And please post the stacktrace.
