### ISSUE TITLE
[Release notes] Show fixed bugs in release notes

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.core#2136]
With the upcoming 2024-03 release I realized again that I would like to have a "release notes" document which shows the fixed bugs which made it into that release. For the features I tend to look at https://github.com/howlger/Eclipse-IDE-improvements-videos. However, for me the fixed bugs are often much more important than the new features.

But I guess there already exists something like this and I just didn't find it?

Thank you

**Comment by jukzi** [comment]
You can look in the commits here:
https://github.com/eclipse-jdt/eclipse.jdt.core/commits/master/
or a subset: the closed pull request, or even less: closed issues:
https://github.com/eclipse-jdt/eclipse.jdt.core/issues?q=is%3Aissue+is%3Aclosed

**Comment by jubax** [comment]
Thank you, this helped a lot! I was hoping for a more summarized/grouped high-level overview, but those two links are certainly very useful.

**Comment by jukzi** [comment]
If you could contribute by extracting a summarized log i guess other people would enjoy it too .
Also take note that the Eclipse IDE consists of a lot interconnected libraries which cause bugs on each other. 
On Github you can filter multiple projects at once by enlisting them all in the query like:  `user:eclipse-platform user:eclipse-jdt ` (and others)
https://github.com/issues?q=is%3Aissue++is%3Aclosed+user%3Aeclipse-platform+user%3Aeclipse-jdt
