### ISSUE TITLE
An (optional) p2 repo built with this repo

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#2138]
As we're experimenting a lot about Eclipse JDT, we very often want to inject our experiments in experimental JDT-LS to see how they behave in practice. At the moment, we find that adding a p2 repo build in JDT Core directly would make the "experimental" work much more convenient; and we didn't find a productive alternative to that. We basically have added a module in some fork that creates a p2 repo with the local build of JDT Core, which then can be referenced by a product build or a target platform for testing.
Such feature would most likely be interesting for more JDT contributors who want to test their (whichever) changes in their consuming applications.

As a p2 repo build can take some extra time, the p2 repo build could be guarded by a profile.

**Comment by iloveeclipse** [comment]
Why not, I don't think building p2 repo takes longer then few seconds.
Do you mean an "official" location at SDK or just as part of any jenkins/maven build for PR's?
Please provide a PR.

**Comment by mickaelistria** [comment]
For the moment, it's more for local testoing, so no official location where to deploy it. Making it possible to have it locally or to reference it under Jenkins URL would already be great.
