### ISSUE TITLE
[22][dom ast] Converter Test setup

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2150]
DOM AST Test setup to be upgraded with 22

**Comment by mpalat** [comment]
@subyssurendran666 - please work with @jarthana in this

**Comment by subyssurendran666** [comment]
Sure @mpalat

**Comment by mpalat** [comment]
done via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2081 - thanks @subyssurendran666
