### ISSUE TITLE
Null-Analysis - The interface ... cannot be implemented more than once with different arguments ...

### ISSUE THREAD

**Issue by jan-reidemeister-valantic** [eclipse-jdt/eclipse.jdt.core#2158]
Version: 2024-03 (4.31.0)
Build id: 20240307-1437

Import the attached Gradle project. 
(in case the .settings are not picked up) Enable annotation-based null analysis using the jspecify annotations.

Incorrect error on DMessageHandlerRegistryImpl:
> The interface MessageHandlerRegistry cannot be implemented more than once with different arguments: MessageHandlerRegistry<C,CharSequence,DIncomingMessageData> and MessageHandlerRegistry<C,CharSequence,DIncomingMessageData>.

Disabling the null analysis removes the error. Last working version was 2023-06.

[sample.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14601943/sample.zip)

**Comment by stephan-herrmann** [comment]
I can reproduce the problem.

**Comment by stephan-herrmann** [comment]
> Last working version was 2023-06.

Also using ecj 4.29 (v20230814-2020, 3.35.0) it still passes.

**Comment by stephan-herrmann** [comment]
Broken since #1413
