### ISSUE TITLE
Cleanup JrtFileSystem init  code

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#216]
Biggest part of the https://github.com/eclipse-jdt/eclipse.jdt.core/pull/194 is not the actual change of classpath behavior in presence of `--release` argument, but generic cleanup of the JrtFileSystem init  code.

- There is code only required if JDT would run on Java 8 and not needed anymore because we run only on 11
- Some code duplication
- Really unnecessary complicated init sequence

So the plan is to extract most of the refactoring from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/194 and apply to JDT without changing any compiler behavior.

**Comment by akurtakov** [comment]
There are some new warnings in I-build which seem related to work here:
* https://download.eclipse.org/eclipse/downloads/drops4/I20220718-1800/compilelogs/plugins/org.eclipse.jdt.compiler.apt_1.4.200.v20220718-1549/@dot.html#OTHER_WARNINGS
* https://download.eclipse.org/eclipse/downloads/drops4/I20220718-1800/compilelogs/plugins/org.eclipse.jdt.compiler.tool_1.3.200.v20220718-1549/@dot.html

**Comment by iloveeclipse** [comment]
Warnings fixed, closing.
