### ISSUE TITLE
[22] Merge BETA_JAVA22 to master

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2167]
After MPE for 22 and release activities  in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2163 merge

**Comment by jarthana** [comment]
The UI and Debug merge PRs ran into some bundle dependency issue that I don't know much about. Both seem to be the same problem.
@noopur2507 Can you please take a look at?

**Comment by jarthana** [comment]
Thanks @akurtakov for the review. I have removed the Y build references and updating the PRs.
