### ISSUE TITLE
ASTParser doesn't parse task tags

### ISSUE THREAD

**Issue by snjeza** [eclipse-jdt/eclipse.jdt.core#2179]
ASTParser never parses task tags. See https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/ASTParser.java#L381

Can we relax this restriction?
The https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator project uses ASTParser in https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/blob/dom-based-operations/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java#L195 and need to parse task tags.

I have commented ASTParser.java, line 381 and all tests pass locally.

A related issue - https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/84
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/160/commits/b2e311daa3ebc2c4d9472078d3ca1b63de3fe450#diff-5155d744fdf221c04316cc2e0751b9ed207740927ccb1a36d82f85ca4e2bee5cR382

**Comment by mickaelistria** [comment]
This seems like a pretty correct analysis here. Would you be willing to submit a PR to fix it?

**Comment by snjeza** [comment]
> Would you be willing to submit a PR to fix it?

I have submitted it - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2200
