### ISSUE TITLE
[Enhanced switch] Case null disallowed when switching on arrays

### ISSUE THREAD

**Issue by uhoefel** [eclipse-jdt/eclipse.jdt.core#2190]
Using jshell I can do
```java
int[] aa = {1};
switch (aa) {
    case null -> System.out.println("A");
    default -> System.out.println("B");
}

int[] cc = null;
switch (cc) {
    case null -> System.out.println("A");
    default -> System.out.println("B");
}
```
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/4885222/825f7265-7a86-4b10-82f5-b8e2f1731b86)

However, in eclipse I get
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/4885222/8d74ca11-2f29-45fa-bc4c-fee288f05356)
with
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/4885222/51f7058c-e881-4f2f-999f-418ee9ab82d2)

**Comment by srikanth-sankaran** [comment]
I'll take a look.
