### ISSUE TITLE
Eclipse 2024-03 reports unclosed closeable for whitelisted StreamEx

### ISSUE THREAD

**Issue by szarnekow** [eclipse-jdt/eclipse.jdt.core#2191]
Similar to regular streams, one.util.streamex.StreamEx is whitelisted for (parts of) the unclosed closable check:

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ReferenceBinding.java#L2207

With 2024-03 a previously clean codebase now has new warnings about resource leaks. A simple reproducer is
```
StreamEx<Object> streamEx = StreamEx.of(new Object()).flatMap(obj->StreamEx.of(obj));
```
which reports the unclosed resource on the stream that is made within the lambda.

**Comment by szarnekow** [comment]
@stephan-herrmann Do you have a hunch? Is there a hidden flag that I could configure to make the errors disappear? Or maybe an idea about a code-path that doesn't use the whitelist-bit for closeables as expected?

Note that the same statement with java.util.stream.Stream doesn't show a warning
```
Stream<Object> stream = Stream.of(new Object()).flatMap(obj->Stream.of(obj));
```

**Comment by stephan-herrmann** [comment]
> Similar to regular streams, one.util.streamex.StreamEx is whitelisted for (parts of) the unclosed closable check:

I completely forgot about this, thanks for the reference :)

I don't have a quick answer but I'll take a look soonish.

**Comment by szarnekow** [comment]
> I don't have a quick answer but I'll take a look soonish.

Much appreciated!
