### ISSUE TITLE
ASTStructuralPropertyTest needs an update after bug 578608

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#22]
AST node types introduced via https://bugs.eclipse.org/578608 are outside the range that is tested in `org.eclipse.jdt.core.tests.dom.ASTStructuralPropertyTest.testNodeClassForType()`.

I suggest to simply increase the loop limit (now `nodeType < 110`) by a larger step, say 10 or even more. Then you will see that the assert also needs adjusting - to correspond to the last constant in ASTNode.

**Comment by SarikaSinha** [comment]
Thanks @stephan-herrmann
