### ISSUE TITLE
Failing test on master build

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.core#2215]
Issue can be seen at https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/121/testReport/org.eclipse.jdt.core.tests.dom/ASTConverterSuperAfterStatements/test004/  . 
@jarthana @mpalat  Can you take a look at this one? It's a feature coming from Java 22 support.

**Comment by srikanth-sankaran** [comment]
Already tracked here: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2215
