### ISSUE TITLE
Use "Implicitly declared class" instead of unnamed class consistently

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdt/eclipse.jdt.core#2219]
Throughout the codebase, we use both names interchangeably. It would be nice to stick to one. I think we should use "implicitly declared class", since that's the name from the newest JEP for the feature.

I am interested in making a PR for this

**Comment by jarthana** [comment]
Keep in mind that there is a chance that the specs might change the terms again. It is nice and in fact, we should have used a single term consistently. But I won't mind waiting until it becomes a standard feature.
