### ISSUE TITLE
Internal compiler error using Vertx in Quarkus

### ISSUE THREAD

**Issue by mavina** [eclipse-jdt/eclipse.jdt.core#2223]
Hi team,

I'm experiencing an issue with Eclipse 2024.03. I'm getting following error message : 
_Errors occurred during the build.
Errors running builder 'Java Builder' on project 'services'.
Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.getSingleAbstractMethod(org.eclipse.jdt.internal.compiler.lookup.Scope, boolean)" because "targetType" is null_

This is the part of the code that is actually triggering this (removing / commenting it is removing the error) : 

```
	@BeforeEach 
	public void beforeTests() {
		System.out.println(); 
		VertxContextSupport.subscribeAndAwait(() -> Panache.withTransaction(()->
		User.deleteAll()
		.chain(()->	User.add("testUser", "test", "test", "user")
		.onItem().invoke(item->{userTest=item;}))
		.chain(()-> User.add("adminUser", "admin", "admin", "admin")
		.onItem().invoke(item->{userAdmin=item;}))
			)
		);
		
	}
```

More specifically, it seems like it's the VertxContextSupport class usage that is triggering the issue. I tried multiple things, including re-installing a fresh eclipse, changing versions of Java (now is 17), refreshing maven project, deleting and re-importing project in eclipse. Nothing worked. Any tip ?

Thank you

**Comment by srikanth-sankaran** [comment]
Attaching a reproducible test case as a plain vanilla SDK project would help us reproduce, investigate and recommend a suitable course of action.

**Comment by mavina** [comment]
Hi,

I'm attaching the project that is triggering the issue. It is a 100% reproductible issue in my environment, even on fresh eclipse installation. You just need to import the project as a maven project, and the issue appears at build time.
See the beforeTests method in UserTest class  that is triggering the issue for me.

Thank you

[services.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14754701/services.zip)

**Comment by mavina** [comment]
I switched to IntelliJ
