### ISSUE TITLE
Drop of Java 11 compatibility?

### ISSUE THREAD

**Issue by alexandrebouchard** [eclipse-jdt/eclipse.jdt.core#2252]
Our gradle CI started failing recently due to `org/eclipse/core/runtime/OperationCanceledException` in a gradle build which used to be compatible with Java 11 but is not longer (despite not changing the build script). Unfortunately, we have a system pinned at Java 11 for the foreseeable future. 

The error message is:

```
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException 
has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

We have not changed our build script dependencies, so I suspect a jar file on maven central might have been re-generated recently using a newer version of Java, losing compatibility with Java 11 as a side effect. The new one uses class version 61.0, making it incompatible with Java 11. If that's the case, would it be possible to regenerate to maintain support for Java 11? Thank you in advance for your help!

To reproduce:

```
git clone https://github.com/UBC-Stat-ML/blangSDK.git 
cd blangSDK
./gradlew build
```

**Comment by iloveeclipse** [comment]
> would it be possible to regenerate to maintain support for Java 11? Thank you in advance for your help!

No. JDT and rest of SDK require Java 17. If you need support of older Java runtimes, don't update your build tooling and pin all SDK dependencies to Java 11 compatible versions.
