### ISSUE TITLE
Bug561287Test fails when run on Java 22

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.core#2284]
Details:
```
junit.framework.ComparisonFailure: Unexpected problem(s)!!!.
----------- Expected ------------

------------ but was ------------
Problem : The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project [ resource : </Bug561287Test> range : <-1,-1> category : <10> severity : <2>]
Problem : The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files [ resource : </Bug561287Test/src/bug561287/A0.java> range : <0,1> category : <10> severity : <2>]

---------------------- ----------
expected:<[]> but was:<[Problem : The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project [ resource : </Bug561287Test> range : <-1,-1> category : <10> severity : <2>]
Problem : The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files [ resource : </Bug561287Test/src/bug561287/A0.java> range : <0,1> category : <10> severity : <2>]
]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assumeEquals(TestCase.java:287)
at org.eclipse.jdt.core.tests.builder.BuilderTests.expectingNoProblemsFor(BuilderTests.java:255)
at org.eclipse.jdt.core.tests.builder.BuilderTests.expectingNoProblemsFor(BuilderTests.java:241)
at org.eclipse.jdt.core.tests.builder.BuilderTests.expectingNoProblems(BuilderTests.java:235)
at org.eclipse.jdt.core.tests.builder.Bug561287Test.testBuilderRegression(Bug561287Test.java:66)
at java.base/java.lang.reflect.Method.invoke(Method.java:580) 
``` 
and visible at https://download.eclipse.org/eclipse/downloads/drops4/I20240404-1800/testresults/html/org.eclipse.jdt.core.tests.builder_ep432I-unit-cen64-gtk3-java22_linux.gtk.x86_64_22.html .

**Comment by akurtakov** [comment]
If I change compliance level to 22 (TestingEnvironments modified to add support for it) test works so this makes me look in the ctsym direction. Any pointers are more than welcome.

**Comment by akurtakov** [comment]
Commenting env.getJavaProject(projectPath).setOption(JavaCore.COMPILER_RELEASE, JavaCore.ENABLED); in the test makes it pass even with 1.8 target so now I'm quite sure that JDT fails to read jvm 22 proper.

**Comment by iloveeclipse** [comment]
Alex, I see there are **lot** of possibly related test fails on Java 22 build (debugger, PDE), I just had no time to look into yet.
Could it be we are seeing this problem: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1874#issuecomment-1914065526

**Comment by iloveeclipse** [comment]
> Alex, I see there are **lot** of possibly related test fails on Java 22 build (debugger, PDE), I just had no time to look into yet. Could it be we are seeing this problem: [#1874 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1874#issuecomment-1914065526)

I've checked that and yes, it is the case. I will push a fix in a moment.

**Comment by akurtakov** [comment]
Thanks! It looked like smth that others should have experienced already.

**Comment by iloveeclipse** [comment]
Actually that was since day one on Java 22 branch, however most failing tests were simply disabled :-( 
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1872. 
Few inked issues should be fixed now with the https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2286.

**Comment by akurtakov** [comment]
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2287/1/ makes tests fail on the PR (prior to your patch). I'll rebase now for confirmation that even tests will run from now on.
