### ISSUE TITLE
[22] DOM support for Unnammed Variables and Patterns (Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2291]
ref https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2086

**Comment by mpalat** [comment]
@subyssurendran666 can you please take a look at this?

**Comment by subyssurendran666** [comment]
Sure @mpalat, could you please assign this ticket to me?

**Comment by subyssurendran666** [comment]
@mpalat after investigating this matter, no further action is required.
