### ISSUE TITLE
[22] Search Support for Unnamed variables and patterns

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2292]
ref https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2086

**Comment by mpalat** [comment]
@subyssurendran666 can you take this up?

**Comment by subyssurendran666** [comment]
Yes, Would you mind assigning this ticket to me, please?

**Comment by srikanth-sankaran** [comment]
There is nothing to do here - unnamed variables may not referred to in the program. So there is no search for uses, declarations etc.
