### ISSUE TITLE
[22]DOM Support for implicitly declared classes

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2294]
ref https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2085

**Comment by mpalat** [comment]
@subyssurendran666 - please have a look

**Comment by subyssurendran666** [comment]
Sure @mpalat , could you please assign this one to me ?

**Comment by mpalat** [comment]
addressed in 23 - closing
