### ISSUE TITLE
RecordPattern variables are not resolved in Completions

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#2299]
Given the code with Java 21

```
public interface Named {}
public record Person(String name) implements Named {}

public foo(Named n) {
     switch(n) {
        case Person(var name) -> {
            n
        }
     }
} 
```

Completions after `n` inside the case statement show the local variable n as `Object` instead of string. But the compiler do resolve type which compiles fine.

**Comment by gayanper** [comment]
@mpalat @stephan-herrmann Any pointers ? I try to see if the RecordPattern in the case statement output by CompletionParser do have type bindings, but what I found was the the Type reference of the local variable is `var`

**Comment by gayanper** [comment]
The problem seems to be when we extract the local variables from scope, the method scope in this case, they are not resolved, not sure how the compiler resolved them though

**Comment by gayanper** [comment]
Now I did some digging,

if I change the code at completion like this

```
     switch(n) {
        case Person(var name) -> {
            n
        }
     }
```
The resolved CU is this
```
import static java.util.AbstractMap.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.stream.Stream;
public class GH902 {
  public sealed interface Range {
  }
  public record LessThan(String attr) implements Range {
/* Implicit */    private final String attr;
    public LessThan(String attr) {
      .attr = attr;
    }
  }
  public GH902() {
  }
  public void foo() {
  }
  private void makeSureNotNull(Entry entry1, int i, String tag, Range r) {
    switch (r) {
    case LessThan(var attr) ->
        {
          <CompleteOnName:System.ou>.println();
        }
    }
  }
}

```

otherwise it is this

```
import static java.util.AbstractMap.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.stream.Stream;
public class GH902 {
  public sealed interface Range {
  }
  public record LessThan(String attr) implements Range {
/* Implicit */    private final String attr;
    public LessThan(String attr) {
      .attr = attr;
    }
  }
  public GH902() {
  }
  public void foo() {
  }
  private void makeSureNotNull(Entry entry1, int i, String tag, Range r) {
    {
      var attr;
      case LessThan(var attr) ->
      {
        <CompleteOnName:at>;
      }
    }
  }
}

```

the issue is CompletionParser is spitting different AST in different scenarios.

**Comment by gayanper** [comment]
I think I found the issue in the parser, I will investigate more and provide a PR

**Comment by srikanth-sankaran** [comment]
> I think I found the issue in the parser, I will investigate more and provide a PR

Any changes in the compiler for patterns, please mark me for review. I recently rewrote significant parts of pattern matching and so can help review and make sure the changes are harmonious. TIA
