### ISSUE TITLE
Cleanup: "Convert String to TextBlock" changes newlines!

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2315]
found by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2282/checks?check_run_id=23479604578
the source of org.eclipse.jdt.core.tests.compiler.regression.ScannerTest.test034() is changed:
```
	public void test034_() {
	String original=
				"public class Test {\n" +
				"  static String C = \"\u0043\\n\\u0043\";\n" +
				"  \n" +
				"  public static void main(String[] args) {\n" +
				"  	System.out.print(C.length());\n" +
				"  	System.out.print(C.charAt(1) == \'\\n\');\n" +
				"  }\n" +
				"}";
	String cleaned=
					"""
						public class Test {
						  static String C = "\u0043\\n\\u0043";
						 \s
						  public static void main(String[] args) {
						  	System.out.print(C.length());
						  	System.out.print(C.charAt(1) == '\\n');
						  }
						}""";
	assertEquals(original, cleaned);
	}
```

```
junit.framework.ComparisonFailure: 
----------- Expected ------------
public class Test {\n
  static String C = "C\n\u0043";\n
  \n
  public static void main(String[] args) {\n
  	System.out.print(C.length());\n
  	System.out.print(C.charAt(1) == '\n');\n
  }\n
}
------------ but was ------------
public class Test {\n
  static String C = "C\n
\u0043";\n
  \n
  public static void main(String[] args) {\n
  	System.out.print(C.length());\n
  	System.out.print(C.charAt(1) == '\n
');\n
  }\n
}
```

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/3ac34660-64ec-4ce2-9594-f28821d308f8)

**Comment by jjohnstn** [comment]
@jukzi This is not a failure of the cleanup but a failure from jdt.core to parse the Text Block.  Note the following test code:

```
public class TestTextBlock2 {
    
    public static void main(String[] args) {
        String x= 
                """
            public class Test {
              static String C = "\u0043\\n\\u0043";
             \s
              public static void main(String[] args) {
               System.out.print(C.length());
               System.out.print(C.charAt(1) == '\\n');
              }
            }""";
        System.out.println(x);
        String y = """
            class Test {
              char  C = "\\n";
            }""";
        System.out.println(y);
    }

}
```

When run under Eclipse, it prints the following:

```
public class Test {
  static String C = "C
\u0043";
  
  public static void main(String[] args) {
   System.out.print(C.length());
   System.out.print(C.charAt(1) == '
');
  }
}
class Test {
  char  C = "\n";
}
```

When compiled with javac and run from the command line:

```
[jjohnstn@localhost experiment]$ java TestTextBlock2
public class Test {
  static String C = "C\n\u0043";
  
  public static void main(String[] args) {
   System.out.print(C.length());
   System.out.print(C.charAt(1) == '\n');
  }
}
class Test {
  char  C = "\n";
}

```

The escaped character which is "C" causes problems thereafter.  Remove it and the code prints as expected.

**Comment by jjohnstn** [comment]
@jukzi I found the problem.  When a unicode character is found, there is a separate buffer populated.  In the case of double-backslashes it was storing just the single back-slash.  This was then passed to create the TextBlock which parsed the lines and converted "\n" to a newline.  In the case where no unicode is used, the original lines are passed to the TextBlock and the "\\n" sequences were treated properly and not converted to newlines.

**Comment by jukzi** [comment]
Thanks for analysis. @iloveeclipse To my understanding a Compiler Fix will intentionally lead to comparator error on any affected Plugin - if any

Jörg Kubitz

**Comment by jjohnstn** [comment]
@jukzi Are you intending on converting ScannerTest to use text blocks?  I don't think you want to do this as the scanning logic path changes.  If not, I will add a new test for the unicode text block example that caused the issue in the first place.

**Comment by jukzi** [comment]
I have not thought about that. i just applied the cleanup on all tests to test the cleanup. I guess that it would be a welcome cleanup on all tests though. if any test has to be excluded please let me now.

**Comment by jjohnstn** [comment]
I guess it would fine to convert all.  It might be useful to add a new test with string concat that uses unicode to ensure that the compiler gets tested for that somehow.
