### ISSUE TITLE
JDT null annotation for records

### ISSUE THREAD

**Issue by frankbenoit** [eclipse-jdt/eclipse.jdt.core#233]
Given a record with null annotation:
````
record A( @NonNull String value1, @Nullable String value2, String value3 ) {}

@NonNullByDefault
record B( @NonNull String value1, @Nullable String value2, String value3 ) {}
````
For the ctor arguments, the processing seems to be fine. But for the getters, the ctor annotations are not taken into account.

The getters should have the same null-ness like the ctor args. (JavaDoc is also propagated to the getters)
E.g. if value2 is nullable, the getter `value2()` return value should be nullable as well.
If I want to change this, the getter can always be overridden and annotated.

**Comment by stephan-herrmann** [comment]
As I was pondering the use of `@NonNullByDefault` concerning records, I filed #701.

**Comment by frankbenoit** [comment]
@stephan-herrmann Thanks you Stephan, for the solution!

**Comment by stephan-herrmann** [comment]
My pleasure, thanks for the report @frankbenoit  :)

Also feel free to chime in on https://github.com/eclipse-jdt/eclipse.jdt.core/issues/701.
