### ISSUE TITLE
[23] JEP 466: Class-File API (Second Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2331]
Ref https://openjdk.org/jeps/466

Summary
Provide a standard API for parsing, generating, and transforming Java class files. This is a [preview API](https://openjdk.org/jeps/12).

**Comment by stephan-herrmann** [comment]
Two plug-ins in JDT-land will eventually have to make a decision, whether / when to migrate from ASM to the new API:
* org.eclipse.jdt.launching.javaagent (jdt.debug)
* org.eclipse.jdt.bcoview (jdt.ui)

@iloveeclipse are you aware of any plans to migrate one or the other?

Other than that I see no impact on JDT, right?

**Comment by iloveeclipse** [comment]
> any plans to migrate one or the other?

As long as Eclipse minimum required JDK is 17 or 21 no, as we wouldn't be able to use it.
In general, if ASM will continue supporting new JDK features, I see no real motivation to rewrite everything.

**Comment by stephan-herrmann** [comment]
> In general, if ASM will continue supporting new JDK features, I see no real motivation to rewrite everything.

that is a big interesting IF ... let's see ...

**Comment by mpalat** [comment]
Thanks @stephan-herrmann for the analysis. closing as no impact (atleast for now)
