### ISSUE TITLE
[23] JEP 469: Vector API (Eighth Incubator)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2332]
https://openjdk.org/jeps/469

Summary
Introduce an API to express vector computations that reliably compile at runtime to optimal vector instructions on supported CPU architectures, thus achieving performance superior to equivalent scalar computations.

**Comment by mpalat** [comment]
@subyssurendran666  - please investigate

**Comment by subyssurendran666** [comment]
Sure @mpalat. Could you please assign this ticket to me ?

**Comment by mpalat** [comment]
@subyssurendran666 - I checked this feature - looks like no changes.
JDT not affected. closing
