### ISSUE TITLE
Add -proc:full to batch compiler

### ISSUE THREAD

**Issue by cpfeiffer** [eclipse-jdt/eclipse.jdt.core#2347]
https://bugs.openjdk.org/browse/JDK-8308245 adds the `-proc:full` option value to javac for versions 8, 11 and 17, and 21. maven-compiler-plugin already [supports this value as well](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#proc).

It would be nice if JDT's batch compiler would also support this.

See https://github.com/openjdk/jdk/pull/14432 for the discussion around this.

**Comment by jukzi** [comment]
Do you miss the function to annotation processing/compilation or do you just want ecj not to complain about the parameter?

**Comment by cpfeiffer** [comment]
I would expect no functional changes other than accepting the new `full` value, which is supposed to reflect the current behavior wrt annotation processing.
