### ISSUE TITLE
[23] Remove String Template preview feature

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2353]
Java 23 will likely drop the String Template. There's no clarity on the way forward, whether this will be added back again in future. The following jdk issue tracks it for the JDK:

https://bugs.openjdk.org/browse/JDK-8329949

ECJ should remove the feature too, obviously. But I would like to start a discussion on whether we should simply turn-off the feature (we have no way yet to do that) or remove the all the relevant code.

**Comment by srikanth-sankaran** [comment]
My preference is that we remove every trace of it. When it gets reintroduced if some portion of code is leveragable we can do so. All it calls for is organizational memory of the PR that rolled back things.

**Comment by jarthana** [comment]
This is going to be messy. I wish they had done on the 2nd iteration. We just added quite a bit of stuff for the AST rewrite.

> My preference is that we remove every trace of it. When it gets reintroduced if some portion of code is leveragable we can do so. All it calls for is organizational memory of the PR that rolled back things.

This is going to be messy, but agree that the resulting code will be lot cleaner. I wish they had this done on the 2nd iteration. We just added quite a bit of stuff for the AST rewrite :(

**Comment by jukzi** [comment]
I assume 21/22 template preview features will also be removed. right?

**Comment by jarthana** [comment]
> I assume 21/22 template preview features will also be removed. right?

If we go the "remove all code related" route, certainly yes.

**Comment by iloveeclipse** [comment]
Note, while reading the [original mail on the JDK list](https://mail.openjdk.org/pipermail/amber-spec-experts/2024-April/004106.html), I have an impression that the removal from Java 23 doesn't mean complete stop of efforts in the direction of templates in Java, just the current design seem to be questioned and so the effort will go on.

I see also the original [JEP 459](https://openjdk.org/jeps/459) is replaced with a new one in [JEP 465](https://openjdk.org/jeps/465) but that one was added two weeks before the [dropping feature announcement](https://mail.openjdk.org/pipermail/amber-spec-experts/2024-April/004106.html) and still says `We here propose to finalize the feature with no further changes.`

This all is confusing... May be we should wait few weeks more to see where it all goes :-)

**Comment by jarthana** [comment]
> This all is confusing... May be we should wait few weeks more to see where it all goes :-)

Yes, we can wait and watch and take this up in the BETA branch that gives us few months time.

**Comment by srikanth-sankaran** [comment]
Note that https://bugs.openjdk.org/browse/JDK-8329948 is merged in. Perusing the commit here https://github.com/openjdk/jdk/commit/03e84178ebfd2ca48b89d65d8f3c291e0c622fb5#diff-1fa76229dfd36a4b7f96a49c14157c3eac397346221b159f82c9963df8903fb5 I see javac as well core-libs are stripped of any trace of it. 

What is sauce for the goose is sauce for gander :)

**Comment by stephan-herrmann** [comment]
Should this issue be assigned to milestone BETA_JAVA23?

**Comment by jarthana** [comment]
> Should this issue be assigned to milestone BETA_JAVA23?

Yes, updated the issue accordingly.

**Comment by jarthana** [comment]
I still see some code related to the string templates in JavaFeature and CUScope#getDefaultImports(). Not sure if it's wise to do it in RC2. Will do it during M1.

**Comment by stephan-herrmann** [comment]
It looks like this issue remains open only due to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2586, correct?

**Comment by stephan-herrmann** [comment]
I just stumbled upon `ResolveTests21` which comes with two surprises:
* it is not included in the global test suite
* it contains mostly tests for the withdrawn feature string templates
  * not a surprise: one of those tests actually fails on HEAD of BETA_JAVA23

I'm addressing both surprises in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2839 (while adding `ResolveTests23`) :
* add it to the suite
* remove tests for string templates

**Comment by stephan-herrmann** [comment]
> It looks like this issue remains open only due to #2586, correct?

Closing as #2586 turned out to be a red herring.
