### ISSUE TITLE
Disassembler prints "requires protected" 

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2357]
Method `org.eclipse.jdt.internal.core.util.Disassembler.decodeModifiersForModuleRequires()` from [bug 508889](https://bugs.eclipse.org/bugs/show_bug.cgi?id=508889) translates `IModifierConstants.ACC_STATIC_PHASE` into "protected". While concrete syntax may have changed in the early days, I can't recall any mention of "protected" in this position. @mpalat  do you? :)

Should be "static" even though that name has been confusing people more than once.

Other than that the disassembler is very helpful for binary-only modules :+1:

**Comment by mpalat** [comment]
@stephan-herrmann - that was a nice way to put it - yes, after deep thoughts (:)) I agree with you that it should not be `protected` but `static` .  will submit a pr

 yep, I use disassembler very much -very useful.
