### ISSUE TITLE
@NonNull inferred incorrectly when using the ternary operator

### ISSUE THREAD

**Issue by gnikolaidis** [eclipse-jdt/eclipse.jdt.core#236]
Say you have a method somewhere defined as:

`public @NonNull Object getSomeValue() { ... }`

Later in your code, you define a new variable as:

`var a = rainyDay ? getSomeValue() : null;`

The type of a is inferred as `@NonNull Object`, whilst it shall be `@Nullable Object`.

**Comment by stephan-herrmann** [comment]
I can reproduce that a `var a` local is wrongly inferred to `@NonNull` whereas an explicit type avoids inference and then local flow analysis finds the possible null value.

Complete example for comparison:

```
package j11;

import org.eclipse.jdt.annotation.NonNull;

public class Test {
	public @NonNull Test getSomeValue() { return this; }
	
	void test(boolean rainyDay) {
		var a = rainyDay ? getSomeValue() : null;
		a.getSomeValue(); // problem not detected
	}
	void test2(boolean rainyDay) {
		Test a = rainyDay ? getSomeValue() : null;
		a.getSomeValue(); // Potential null pointer access: The variable a may be null at this location
	}
}
```
