### ISSUE TITLE
[Switch Expression] Assertion fails when IDE is launched with JVM option -ea 

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2366]
Code: 

```
public class X {
  public X() {
    super();
  }
  public static void foo() {
    X z;
    while (((z = getObject()) != null))      {
        z.bar();
      }
    System.out.println(switch(42) {
	default -> {
		try {
			yield 42;
		} finally {
			
		}
	}
});
  }
  public void bar() {
  }
  public static X getObject() {
    return null;
  }
  public static void main(String[] args) {
    new X().foo();
  }
}
```
results in `Internal compiler error: java.lang.AssertionError at org.eclipse.jdt.internal.compiler.codegen.CodeStream.pushTypeBinding(CodeStream.java:7723)`

**Comment by jukzi** [comment]
As far as i see "-ea" is enabled during tests:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/9632e30d-cb1f-4ffa-9432-e0f661253f28)
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/184/consoleText

I think "assert"s are fine for conditions that are performance overhead while a runtimexception is ok if there is almost no overhead

**Comment by srikanth-sankaran** [comment]
> As far as i see "-ea" is enabled during tests:

Yes, that adds to its own confusion to see something failing in CI testing but passing locally.

> I think "assert"s are fine for conditions that are performance overhead while a runtimexception is ok if there is almost no overhead

Most of the sanity checks one would want to enforce are trivial in nature I would say.
