### ISSUE TITLE
JavaDoc for binary classes does only work partially

### ISSUE THREAD

**Issue by blasss** [eclipse-jdt/eclipse.jdt.core#2368]
Eclipse IDE 20231201-2043
Eclipse allows to provide a JavaDoc location for libraries in the build path. If no source for such a library is available and the provided JavaDoc has been created with Java 11 the displaying of JavaDoc in a hover does not work for constructors and methods with multiple arguments. If JavaDoc has been created with Java 8 the displaying works and this is most likely no regression as this doesn't work for Eclipse 20211202-1639 as well.

![grafik](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/17325141/38814ddd-6f13-433e-96d3-8392cdb92e3d)

Most likely this is related to the changed format of the individual JavaDoc pages for classes between 8 and 11. For example the anchor for the constructors of a class changed from `Integer.html#Integer-int-` (Java 8) to `Integer.html#<init>(int)` (Java 11).

Some digging into the code of Eclipse shows that there is some basic handling of the differences in `org.eclipse.jdt.internal.core.JavadocContents.getJavadoc8Anchor(char[])`, but this doesn't handle the different naming of constructors (classname vs. `<init>`). `org.eclipse.jdt.internal.core.JavadocContents.computeMethodAnchorPrefixEnd(BinaryMethod)` is used to generate the anchor for a method and it includes spaces between multiple parameters. JavaDoc (generated from Java 11) does not include spaces between parameters.

For the JDK 11 itself this is not relevant, as this works with a source attachement and therefore javadoc is found without problems. But in usual development environments it is quite common to use libraries that don't provide sources and you are required to work with javadoc only.

By the way: I found in `org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.appendMethodReference(IMethod, StringBuffer)` some logic to calculate an external link to javadoc. This considers some of the differences, but it does as well not take care of the changed name of constructors. And what seems to me really nasty is the use of the source-code-compliance-level to determine the right syntax of the generated urls. Especially as this is not documented in any way and why shouldn't be there projects writing Java 8 compliant code that use libraries providing Java 11 JavaDoc?
But maybe this is something for another issue...

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2369
