### ISSUE TITLE
[23] JEP 476: Module Import Declarations (Preview)

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2383]
From the JEP - "Enhance the Java programming language with the ability to succinctly import all of the packages exported by a module."

More details here - https://openjdk.org/jeps/476

**Comment by mpalat** [comment]
JLS changes captured here :https://cr.openjdk.org/~gbierman/jep476/latest/

**Comment by stephan-herrmann** [comment]
Latest spec clarification: https://mail.openjdk.org/pipermail/amber-spec-experts/2024-May/004132.html

**Comment by stephan-herrmann** [comment]
I once more scanned the spec which is now in PR Draft state: https://cr.openjdk.org/~iris/se/23/spec/draft/java-se-23-draft-spec-30/specs/module-import-declarations-jls.html

I also successfully ran ModuleImportTests with `-Drun.javac=enabled -Djdk.root=path_to_jdk-23-ea-30`.

I believe we are done here, indeed.

**Comment by stephan-herrmann** [comment]
Summary of work in this area

JDT/Core:
* https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2550
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2607
   * https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2610
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2823
   * https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2825
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2834
   * https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2836
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2838
   * https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2839

JDT/UI:
* https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1589
