### ISSUE TITLE
[BUG] JDT confuses COBOL files with Java files

### ISSUE THREAD

**Issue by thahnen** [eclipse-jdt/eclipse.jdt.core#2389]
## Summary

When working with a simple project (see the attachment) on an Eclipse installation that has JDT installed and testing our plug-in, I noticed that due to how JDT is magically coming up with the *Java-like extensions*, it treats COBOL files like Java files when we make a check on them.

Simply speaking, we have a filter in place that excludes Java files that are not compiled (wherever they are, they don't have to be in a source folder) because we need the *Java* and its corresponding *Class* file. It should only do so for actual Java projects. Our filter is basically the following implementation (simplified):

```java
public boolean shouldExclude(org.eclipse.core.resources.IFile file) throws org.eclipse.jdt.core.JavaModelException {
  var javaElement = org.eclipse.jdt.core.JavaCore.create(file);
  if (javaElement == null) {
    // not a possible Java file
    return false;
  }

  if (!javaElement.exists()) {
    // some other plug-in-specific magic on our side, ignore this
    return false;
  }

  return !javaElement.getJavaProject().isOnClasspath(javaElement) || javaElement.isStructureKnown();
}
```

This led to COBOL files with the suffix `.cbl` being ignored as Java files - even though they clearly are no Java files. Debugging with `JavaCore.getJavaLikeExtensions()` revealed that `cbl` was in there - no clue how it appeared.

The following issues I observed here:
- `JavaCore.create(IFile file)` should have returned `null` in the first place
- `cbl` shouldn't be in the *Java-like extensions*
- `IJavaElement.getJavaProject()` is returning an instance of `IJavaProject` even though `file.getProject().hasNature(JavaCore.NATURE_ID)` is `false`

I had to change the implementation to this, but I think the bug here is in JDT, and what I implemented is merely a workaround for it:

```java
public boolean shouldExclude(org.eclipse.core.resources.IFile file) throws org.eclipse.core.runtime.CoreException, org.eclipse.jdt.core.JavaModelException {
  var javaElement = org.eclipse.jdt.core.JavaCore.create(file);
  if (javaElement == null) {
    // not a possible Java file
    return false;
  }

  if (!javaElement.exists()) {
    // some other plug-in-specific magic on our side, ignore this
    return false;
  }

  return file.getProject().hasNature(org.eclipse.jdt.core.JavaCore.NATURE_ID) && (!javaElement.getJavaProject().isOnClasspath(javaElement) || javaElement.isStructureKnown());
}
```

## Attachement(s)

[TestProject.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/15131030/TestProject.zip)

**Comment by jukzi** [comment]
if you need changes on jdt please create a Pull Request including JUnit tests that show the impact of the change.

**Comment by thahnen** [comment]
Hi @jukzi,

thanks for replying. I'm not quite sure that we are on the same page, maybe it wasn't clear initially:

As I said, this looks like a bug to me, but I'd rather have a confirmation from a JDT maintainers' perspective. Based on that outcome a decision can be taken on how to handle this. I'm not a JDT maintainer, and therefore, I'm not going to provide a bug fix for that just because I'm not familiar with the JDT source code at all and see this more as an obligation of the JDT maintainers. I sadly don't have the time to get familiar with that enough - not that I want to drop off a load of fixing that to you (or another maintainer) and leave as fast as I came. I can only provide an integration test or, as above, a reproducer.

For me it looks like a bug on JDT with additional, possible improvements on how the *Java-like extensions* are created. Maybe the latter is solved by fixing the initial bug, maybe not. If the improvement is on top, I can eventually provide some input (whether it is code or anything else), but as said above, I'm not (yet) familiar enough with this and maybe won't be anytime soon.

Best,
Tobi

**Comment by jukzi** [comment]
@thahnen i confirm that JavaCore.getJavaLikeExtensions() should normally not contain "cbl". However the implementations seems to be a registry where other plugins can add custom org.eclipse.jdt.core.JavaCore.JAVA_SOURCE_CONTENT_TYPE. So you should doublecheck how your setup registered such file ending. JDT itself does not register such extension.
Any plugin.xml can register such an extension. See for example:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/db6b10d1-b1b6-4d59-aeea-8970e9e24ca6)

Closing as NOT-JDT.
