### ISSUE TITLE
new jdt.internal.compiler.util.Jdk.<init> ()performance problem

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2393]
After updating from ~0418 to I20240428-1800 (auto)rebuild of platform workspace took much longer then usual. I sampled the autobuild and see massive hotspots in JRTUtil .getJrtSystem() -> `Jdk<init>` that i have never seen before
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/64f20181-3bbd-4aa3-b779-5bccaf7d0adb)

```
eclipse.buildId=4.32.0.I20240428-1800
java.version=17.0.10
java.vendor=Eclipse Adoptium
```

**Comment by jukzi** [comment]
@HannesWell @iloveeclipse there where recent refactorings in that area:
f53ffcb035c4194af6a25ea11220f11cd2c56137
523d582e07d4ae1448f179fbbf5f42166da34343
from
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2370

**Comment by jukzi** [comment]
The use of  "path.toRealPath()" in JRTUtil is inaccaptable. It's an expensive IO call not suitable to compute a key on every call. Please fix or revert.

**Comment by iloveeclipse** [comment]
> The use of "path.toRealPath()" in JRTUtil

@HannesWell : could you please remove this from `org.eclipse.jdt.internal.compiler.util.Jdk.Jdk(File)` constructor?

**Comment by HannesWell** [comment]
> > The use of "path.toRealPath()" in JRTUtil
> 
> @HannesWell : could you please remove this from `org.eclipse.jdt.internal.compiler.util.Jdk.Jdk(File)` constructor?

Created https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2394 to use the much cheaper alternative `toAbsolutePath().normalize()`.
