### ISSUE TITLE
Different behaviour between Eclipse and Oracle JDK compilers when using escaped single quote in textblock

### ISSUE THREAD

**Issue by xazap** [eclipse-jdt/eclipse.jdt.core#2395]
I am seeing different behaviour with Eclipse compiler and Oracle compiler when using escaped single quotes in a textblock. 

## Reproduction
```java
public class Reproduction {
        public static void main(String[] args) {

                var testcase1 = """
                         \\M\\\\o\\\'
                         \\M\\q\\\'
                """;
                System.out.println(testcase1.trim().length());

                var testcase2 = """
                         \\M\\q\\\'
                         \\M\\\\o\\\'                                     
                """;
                System.out.println(testcase2.trim().length());

                var testcase3 = """
                        \\M\\q\\'
                        \\M\\\\o\\'                                      
                """;
                System.out.println(testcase3.trim().length());
        }
}
```
When compiling and running in Eclipse the output is:
```
16
15
16
```
When compiling and Running with the Oracle JDK the output is:
```
16
16
16
```

Notice how the  length given for testcase 2 differs between Eclipse and Oracle. Although testcase 3 shows that it is not necessary to escape a single quote in a textblock, it is still valid syntax to use `\'` (source: https://docs.oracle.com/en/java/javase/17/text-blocks/index.html#translation-of-escape-sequences). In any case this seems to produce different results between Eclipse and Oracle compilers.

## Versions used
Oracle JDK:
```
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```
Eclipse:
```
Version: 2024-03 (4.31.0)
Build id: 20240307-1437
```

**Comment by jarthana** [comment]
I simplified the testcase by removing all the leading whitespace in the textblock and compared the output and I don't find any difference between 4.31 eclipse and Javac version 23. Just to be sure, I also printed the literals and this is what get printed in both cases:

**ECJ:**
```
\M\\o\'
\M\q\'

\M\q\'
\M\\o\'

\M\q\'
\M\\o\'
```

**Javac:** 
```
\M\\o\'
\M\q\'

\M\q\'
\M\\o\'

\M\q\'
\M\\o\'
```

Can you please check with the latest ECJ and Javac. It's possible that both compilers went through changes over time.

**Comment by xazap** [comment]
Narrowing it down some more. With latest ECJ `org.eclipse.jdt:ecj:3.37.0` I see that a `\` is dropped on the second line of  testcase 2:
```
\M\\o\'
\M\q\'

\M\q\'
\M\o\'

\M\q\'
\M\\o\'
```
The previous version `org.eclipse.jdt:ecj:3.36.0` produces the same output as the Oracle compiler and does not drop any input:
```
\M\\o\'
\M\q\'

\M\q\'
\M\\o\'

\M\q\'
\M\\o\'
```

**Comment by iloveeclipse** [comment]
Please check ecj from master (you can find latest nightly here: https://download.eclipse.org/eclipse/downloads/drops4/I20240429-1800/), I assume either https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2316 or https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2339 may have fixed this.

**Comment by iloveeclipse** [comment]
> Will Eclipse 2024.03 get an update to replace the affected 3.37 version of the compiler?

No

> or do I have to wait for Eclipse 2024.06?

Yes
