### ISSUE TITLE
Autocomplete with non-existing javadoc crashes eclipse

### ISSUE THREAD

**Issue by ricokritzer** [eclipse-jdt/eclipse.jdt.core#2408]
Using a maven plugin, which itself exists but the javadoc doesn't, makes eclipse crash completely.

In my example the errorlog shows:
```
Could not download javadoc for com.vaadin:vaadin-core-internal:24.3.10
Contains: Missing com.vaadin:vaadin-core-internal:jar:javadoc:24.3.10
```

When I open autocomplete using [Strg] + [Space], eclipse crashes. This could be reproduced.

**Version:** 
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2024-03 (4.31.0)
Build id: 20240307-1437

**Comment by iloveeclipse** [comment]
Please attach Eclipse log and crash logs. Are you using Linux / Wayland?

**Comment by iloveeclipse** [comment]
OK. Please start Eclipse from the console and attach the crash log. I'm pretty sure it's webkit crash and doesn't have any relationship to JDT.
You didn't answered if you are using Wayland or not. This (Wayland) is another source of troubles.
So you can switch to X11 and see if it still crashes.
