### ISSUE TITLE
Please deploy a new version of ecj to maven central

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#241]
There was a serve regression fixed with:

- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/183

I can confirm that building a larger project that fails with the previous version of EJC now runs fine in parallel mode using I20220717

@sravanlakkimsetti any chance to deploy the ecj.jar eg as version 3.30.I20220717 to maven central? This currently prevents parallel builds with Tycho when using Java 17 together with code that is compiled for `--release 11`.

**Comment by sravanlakkimsetti** [comment]
Deploying to repo.eclipse.org help?

**Comment by sravanlakkimsetti** [comment]
Deployed ecj to https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/ecj/3.30.100.v20220717-1600/

**Comment by laeubi** [comment]
> Deploying to repo.eclipse.org help?

I'll try that out, but will most probably require additional repositories added for Tycho users, so a deployment to maven central would be very helpful as well.

**Comment by sravanlakkimsetti** [comment]
We use this 

add this for plugin repository
```
    <pluginRepository>
      <id>cbi-jdt</id>
      <url>https://repo.eclipse.org/content/repositories/eclipse-staging/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </pluginRepository>
```
and in plugin management add 
```
        <plugin>
          <groupId>org.eclipse.tycho</groupId>
          <artifactId>tycho-compiler-plugin</artifactId>
          <version>${tycho.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.eclipse.jdt</groupId>
              <artifactId>ecj</artifactId>
              <version>3.30.100.v20220717-1600</version>
            </dependency>
          </dependencies>
```

**Comment by laeubi** [comment]
> I fear this ecj version could be a bit slower

Slower is better than failing :+1: 

It seems there is another request for an immediate fix: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/148

As @iloveeclipse has suggested, maybe we can at least have M2 release on maven central?

**Comment by akurtakov** [comment]
@sravanlakkimsetti Is there a chance to upload recent ecj to Maven central? We can even name it M2, maven-projects (e.g. surefire do that).

**Comment by sravanlakkimsetti** [comment]
for pushing to maven central, here is the process I used for fixing the issues we had,
1. Backport necessary fixes to R4_24 branch with version increment of +0.0.1
2. Build R4_24
3. then check for signing if unsigned sign the respective artifacts.
4. Deploy the artifacts to maven central.

This is a tedious and painful process. I prefer not to use it unless it is absolutely necessary.

To use 
`mvn deploy:deploy-file -Dfile=<..>/org.eclipse.jdt.core-3.30.100-SNAPSHOT-batch-compiler.jar -DgroupId=org.eclipse.jdt -DartifactId=ecj -Dversion=3.30.100-RC1 -Dpackaging=jar` 
This does require some work and experimentation. 

In the meanwhile we can deploy to repo.eclipse.org on demand. Please let me know the build id from which ECJ needs to be deployed

**Comment by laeubi** [comment]
> 4\. Deploy the artifacts to maven central.

Just to make it clear we do not need *all* artifacts, and we do not need a *full build* we would only need **one single artifact** to be deployed. Also "signing" won'T be needed bejond the usual PGP signing required for central, the whole process could be tested with a local deploy folder, or with `repo.eclipse.org` and i really think it would be crucial to find a less tedious process, as in case of serve regressions, CVEs and alike up to three month delay is just to much given today's release cycles!

**Comment by laeubi** [comment]
This has now become obsolete...
