### ISSUE TITLE
[23] JEP 480: Structured Concurrency (Third Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2475]
ref: https://openjdk.org/jeps/480

Summary
Simplify concurrent programming by introducing an API for structured concurrency. Structured concurrency treats groups of related tasks running in different threads as a single unit of work, thereby streamlining error handling and cancellation, improving reliability, and enhancing observability. This is a [preview API](https://openjdk.org/jeps/12).

Predecessor:  https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1639

**Comment by mpalat** [comment]
@subyssurendran666 can you please investigate this for JAVA23?

**Comment by subyssurendran666** [comment]
@mpalat based on my investigation, it seems that no further action is needed.

**Comment by subyssurendran666** [comment]
> @subyssurendran666 can you please investigate this for JAVA23?

@mpalat could you please assign the ticket to me.

**Comment by mpalat** [comment]
> @mpalat based on my investigation, it seems that no further action is needed.

Thanks @subyssurendran666
