### ISSUE TITLE
Empty stack error compiling project with broken classpath

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2485]
From one of many bugs reported I had a project in my workspace that was meant to be used to reproduce some specific error, however I wasn't able to properly setup the project (seem to need gradle etc), and left it "broken" & closed in my test workspace.

Now while trying to reproduce https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2484 I've opened this project again and got immediately this error:
```
eclipse.buildId=4.32.0.I20240522-1800
java.version=21
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.sdk.ide
Command-line arguments:  -product org.eclipse.sdk.ide -data /data/4x_platform_workspace/../runtime-Java_21 -dev file:/data/4x_platform_workspace/.metadata/.plugins/org.eclipse.pde.core/Java_21/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

org.eclipse.core.resources
Error
Thu May 23 09:35:42 CEST 2024
Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:103)
	at java.base/java.util.Stack.pop(Stack.java:85)
	at org.eclipse.jdt.internal.compiler.codegen.OperandStack.pop(OperandStack.java:57)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.areturn(CodeStream.java:418)
	at org.eclipse.jdt.internal.compiler.codegen.StackMapFrameCodeStream.areturn(StackMapFrameCodeStream.java:409)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.generateReturnBytecode(CodeStream.java:2574)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateReturnBytecode(ReturnStatement.java:276)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateCode(ReturnStatement.java:260)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:388)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:324)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:762)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:832)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
I've zipped the project, it is a part of https://github.com/Glavo/classfile.git 
[empty_stack_error.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/15413369/empty_stack_error.zip)

**Comment by iloveeclipse** [comment]
@srikanth-sankaran : could you please check, it should be reproducible with attached project? 
The code is not compilable, the project setup is clearly broken, but that shouldn't cause internal compiler errors.

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran : could you please check, it should be reproducible with attached project? The code is not compilable, the project setup is clearly broken, but that shouldn't cause internal compiler errors.

Yes, it is reproducible. I am studying it ... stay tuned.

**Comment by srikanth-sankaran** [comment]
Shorter test case: 

```
public class X {
        public static int convertOpcode(int from, int to) { 
        return switch (from) {
            case 42 ->
                    switch (to) {
                        case 42 -> 42;

                        default -> throw new UnsupportedOperationException();
                    };

            default -> throw new UnsupportedOperationException();
        };
    }
}

```

**Comment by srikanth-sankaran** [comment]
Since this code fragment combine exception catching with switch expressions, operand stack tracking is technically not needed. If I disabled that experimentally - the `EmptyStackException` exception goes away (naturally) but we now end up with: 

`Internal inconsistency: Inappropriate operand stack size encountered during translation` 

(stack content tracking is disabled experimentally - not stack size computation - this cannot be disabled, we must record it in the class file)

thereby indicating a problem in code generation

**Comment by srikanth-sankaran** [comment]
Problem arising from optimizing branches to branches:

With optimization of such chained gotos turned off the generated code is

```
  public static int convertOpcode(int, int);
    descriptor: (II)I
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=2, locals=2, args_size=2
         0: iload_0
         1: tableswitch   { // 42 to 42

                      42: 20
                 default: 56
            }
        20: iload_1
        21: tableswitch   { // 42 to 42

                      42: 40
                 default: 45
            }
        40: bipush        42
        42: goto          53
        45: new           #16                 // class java/lang/UnsupportedOperationException
        48: dup
        49: invokespecial #18                 // Method java/lang/UnsupportedOperationException."<init>":()V
        52: athrow
        53: goto          64
        56: new           #16                 // class java/lang/UnsupportedOperationException
        59: dup
        60: invokespecial #18                 // Method java/lang/UnsupportedOperationException."<init>":()V
        63: athrow
        64: ireturn
```

And the operand stack management code is happy with this sequence.

When the `goto` in bci 42 is patches to directly reach the `ireturn` we have a problem

**Comment by srikanth-sankaran** [comment]
> Methinks there are at least two defects here, one new - OperandStack tracking not dealing with chained branch optimization. Two: very old, shouldn't `tableswitch` and `lookupswitch` be considered abruptly completing as in no fall through along with various flavors of `return`s, `athrow` and `goto`s ??! These instructions implement multiway goto with a definite default clause.

I have raised https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2492 for the latter.
