### ISSUE TITLE
[Switch Expression] Switching on sealed interface instance compiles even when the switch expression does not cover all possible input values

### ISSUE THREAD

**Issue by RandomName325398** [eclipse-jdt/eclipse.jdt.core#2503]
Hello,
I came across the following bug in the eclipse jdt build eclipse-SDK-I20240528-1800-win32-x86_64 and was able to reproduce it here
The simple implementation is the following with Java 21:

```
public sealed interface Outer permits Inner, Foo {}
```

```
public sealed interface Inner extends Outer {
	public static record A() implements Inner {}
	public static record B() implements Inner {}
}
```

```
public non-sealed interface Foo extends Outer {}
```

```
public class Main {
	public static void main(String[] args) {
		Outer element = new FooImpl();
		
		String test = switch(element) {
		case Inner.A a -> "a";
		case Inner.B b -> "b";
		};
		
		System.out.println(test);
	}
	
	private static record FooImpl() implements Foo {}
}
```

This compiles currently with eclipse, while the JDK javac.exe fails rightfully with the following message
`Main.java:7: error: the switch expression does not cover all possible input values String test = switch(element) {`
This code then ends up throwing at runtime.

**Comment by srikanth-sankaran** [comment]
Single CU reproducer: 

```
sealed interface Outer permits Inner, Foo {}
sealed interface Inner extends Outer {
	public static record A() implements Inner {}
	public static record B() implements Inner {}
}
non-sealed interface Foo extends Outer {}
public class X {
	public static void main(String[] args) {
		Outer element = new FooImpl();
		
		String test = switch(element) {
		case Inner.A a -> "a";
		case Inner.B b -> "b";
		};
		
		System.out.println(test);
	}
	
	private static record FooImpl() implements Foo {}
}
```

**Comment by srikanth-sankaran** [comment]
Smaller/simpler test case that still throws `MatchException` :

```
sealed interface I permits A, J {}

final class A implements I {}

non-sealed interface J extends I {}

public class X {
	public static void main(String[] args) {		
		System.out.println(switch((I) new J() {}) {
				case A a -> "a";	
		});
	}
}
```

while a variant that fails to compile (as it should)

```
sealed interface I permits A, J {}

final class A implements I {}

final class J implements I {}

public class X {
	public static void main(String[] args) {		
		System.out.println(switch((I) new J()) {
				case A a -> "a";			
		});
	}
}

```

**Comment by srikanth-sankaran** [comment]
See also https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1777

**Comment by srikanth-sankaran** [comment]
**14.11.1.1 Exhaustive Switch Blocks**
The switch block of a switch expression or switch statement is exhaustive for a
selector expression e if one of the following cases applies:
• There is a default label associated with the switch block.
• There is a case null, default label associated with the switch block.
• The set containing all the case constants and case patterns appearing in an
unguarded case label (collectively known as case elements) associated with the
switch block is non-empty and covers the type of the selector expression e.

A set of case elements, P, covers a type T if one of the following cases applies:
...
• The type T names an abstract sealed class or sealed interface C and for
every permitted direct subclass or subinterface D of C, one of the following two
conditions holds:
1. There is no type that both names D and is a subtype of T, or
2. There is a type U that both names D and is a subtype of T, and P covers U.
