### ISSUE TITLE
Regression in Member.areSimilarMethods()

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2507]
PR #2241 improved matching of signature for some use cases while breaking others.

This originally surfaced as a regression in Object Teams tests, but here is a standalone JDT reproducer:
```java
package p1;

class B1 {
	class Inner {}
}
class B2 {}
public class CreateOverride {
	static class A {
		public void foo(B1 b1, B1.Inner inner, B2 b2) {}
	}
	static class B extends A {
		fo
	}
}
```
Invoke completion after "fo", which should create this:
```java
		@Override
		public void foo(B1 b1, Inner inner, B2 b2) {
			// TODO Auto-generated method stub
			super.foo(b1, inner, b2);
		}
```
but now creates:
```java
		@Override
		public void foo(B1 arg0, Inner arg1, B2 arg2) {
			// TODO Auto-generated method stub
			super.foo(arg0, arg1, arg2);
		}
```

Please see that the parameter names from the super method are not used (since not found).

Here's why:

* We have an IMethodBinding `public void foo(p1.B1, p1.B1.Inner, p1.B2)`
* we pass this binding into StubUtility.suggestArgumentNames(IJavaProject, IMethodBinding)
* however, MethodBinding.getJavaElement() will fail:
* we need to match SourceMethod `void foo(B1, B1.Inner, B2)` using areSimilarMethods():
   * params1 = `[Qp1.B1;, Qp1.B1.Inner;, Qp1.B2;]`
   * params2 = `[QB1;, QB1.Inner;, QB2;]`
* when comparing `Qp1.B1.Inner;` vs `QB1.Inner;` the new implementation infers that since both types are "qualified" we need to apply exact comparison. This is wrong.

@mickaelistria  fyi.

**Comment by stephan-herrmann** [comment]
Part of the confusion is caused by invoking Signature.getSignatureQualifier() with `Qp1.B1.Inner;` instead of `Qp1.B1$Inner;`.  This makes `B1` look like part of the package name (see javadoc of getSignatureQualifier()). But as #2240 shows, also outer type names are relevant.

**Comment by mickaelistria** [comment]
Thank for reporting, I'll have a look and will hopefully provide a fix.
