### ISSUE TITLE
[Enhanced switch] Unexpected MatchException thrown at runtime

### ISSUE THREAD

**Issue by pietrobraione** [eclipse-jdt/eclipse.jdt.core#2513]
The following Java 21 code, when compiled with ecj (2024-06 M2), for a suitable input, throws at runtime a `java.lang.MatchException`. This happens when executing the switch expression contained in this code:

	...
	var maybeC = J.syProgramLit().classWithField(f);
	maybeC.ifPresentOrElse(syDeclClass -> {
		switch (syDeclClass) { //raises MatchException
		case SyDeclClassLit C:
			//omit
		}
	}, () -> {
		throw new RuntimeException("No class has field " + f);
	});

`J` is a `SemConfiguration` object, `maybeC` is an `Optional<SyDeclClass>`, therefore `syDeclClass` is a `SyDeclClass`, which has the following declaration:

	public sealed interface SyDeclClass permits SyDeclClassLit { }

While ecj accepts the one-armed switch statement at compile time (possibly because `SyDeclClass` permits only one subclass), it generates a class file that, whenever the switch statement is executed, raises a `MatchException`. When compiled with javac, the code is accepted and the generated classfile does not raise any exception at runtime. 

I include a [bug.zip](https://github.com/user-attachments/files/15526786/bug.zip) file with an Eclipse project (created with 2024-06 M2, but should work with 2024-03) that demonstrates the issue. The JUnit test that triggers the exception is in the `bug.semantics.interpreter.TestInterpreter` class. The incriminated code is in the `bug.semantics.interpreter.Interpreter` class, method `stepRefinementHandlePutfield`.

Things that I did not do:
- Determining whether the fact that the switch expression is nested inside a lambda matters or not;
- Trying to compile the code with 2024-06 RC1.

Sorry about that.

**Comment by srikanth-sankaran** [comment]
Thanks, I can reproduce the problem on master head. Investigating ...

**Comment by srikanth-sankaran** [comment]
We inadvertently fall into the match exception throwing code inserted for binary compatibility as the code associated with the case is empty with no break.

**Comment by srikanth-sankaran** [comment]
Simple test case:

```
sealed interface SyDeclClass permits SyDeclClassLit {

}

record SyDeclClassLit() implements SyDeclClass {}


public class X {
	
	public static void main(String[] args) {
		SyDeclClass sdc = new SyDeclClassLit();
		switch (sdc) {
			case SyDeclClassLit C:
			//omit
		}
	}
	
}


```

**Comment by srikanth-sankaran** [comment]
Here is the code generated by ECJ as of now:

```
        26: aload_1
        27: iload_2
        28: invokedynamic #204,  0            // InvokeDynamic #2:typeSwitch:(Ljava/lang/Object;I)I
        33: tableswitch   { // 0 to 0

                       0: 52
                 default: 57
            }
        52: aload_1
        53: checkcast     #109                // class bug/syntax/SyDeclClassLit
        56: astore_3
        57: new           #86                 // class java/lang/MatchException
        60: dup
        61: aconst_null
        62: aconst_null
        63: invokespecial #93                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
        66: athrow
        67: return
```

While javac generates this:

```
        28: aload_1
        29: iload_2
        30: invokedynamic #175,  0            // InvokeDynamic #3:typeSwitch:(Ljava/lang/Object;I)I
        35: lookupswitch  { // 1
                       0: 62
                 default: 52
            }
        52: new           #72                 // class java/lang/MatchException
        55: dup
        56: aconst_null
        57: aconst_null
        58: invokespecial #77                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
        61: athrow
        62: aload_1
        63: checkcast     #80                 // class bug/syntax/SyDeclClassLit
        66: astore_3
        67: return
```

In the ECJ generated code there is no barrier between bci 56 and bci 57, Hello!
