### ISSUE TITLE
[19] AST Rewrite support for Record Pattern

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.core#252]
AST Rewrite support for Record Pattern

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/85 JEP 405: Record Patterns

**Comment by iloveeclipse** [comment]
@SarikaSinha : please close if fixed or set other milestone, [BETA_JAVA19](https://github.com/eclipse-jdt/eclipse.jdt.core/milestone/13) is not valid anymore.

**Comment by SarikaSinha** [comment]
Missed closing it.
