### ISSUE TITLE
[Switch Expression][Null] Bogus null contract violation diagnostic at yield statements

### ISSUE THREAD

**Issue by agentgt** [eclipse-jdt/eclipse.jdt.core#2522]
Using the code from #2521 as it is related and null analysis turned on Eclipse frequently thinks the result of a pattern matching expression is nullable. @stephan-herrmann 

```java
public sealed interface PatternMatching {
    
    record Stuff() implements PatternMatching {}
    
    static Stuff match(PatternMatching pm) {
        Stuff r = return switch(pm) {
            case Stuff s -> s;
        }; 
        return r; // Eclipse will say "r" is Nullable here.
    }
}
```

Notice even if we pattern match on `null` making it impossible for r to be `null`:

```java
public sealed interface PatternMatching {
    
    record Stuff() implements PatternMatching {}
    
    static Stuff match(PatternMatching pm) {
        Stuff r = return switch(pm) {
            case Stuff s -> s;
            case null -> throw new NullPointerException();
        }; 
        return r; // Eclipse will say "r" is Nullable here.
    }
}
```

It still does not work.

Version I'm using is JDT RC (3.19.500.v20240601-0610)

Happy to help in anyway I can.

**Comment by srikanth-sankaran** [comment]
Much water has flown under the bridge - I don't see a problem with the snippet above (after mending it for the misplaced return)

But on master HEAD - this is the annotated behavior I see and a couple of surprised I have called out:

```
import org.eclipse.jdt.annotation.NonNull;

public sealed interface PatternMatching {
    
    record Stuff() implements PatternMatching {}
    
    @NonNull
    static Stuff match(PatternMatching pm, int v) {
    	if (v == 0) {
			Stuff r = switch (pm) {
			case Stuff s -> s;
			case null -> throw new NullPointerException();
			};
			return r; // no error here - good
    	} else if (v == 1) {
			Stuff r = switch (pm) {
			case Stuff s -> s;
			case null -> throw new NullPointerException();
			};
			return null; // get error here	- good
    	} else if (v == 2) {
			Stuff r = switch (pm) {
			case Stuff s -> s;
			};
			return r; // no error here -- good
    	} else if (v == 3) {
			Stuff r = switch (pm) {
			case Stuff s -> null; // <<<<<---------------------------- Line 28 - error Why ???
			};
			return r; // get error here - good
    	} else if (v == 4) {
			Stuff r = switch (pm) {
			case Stuff s -> s;
			case null -> null;  // <<<-------------------------------- Line 34 - error Why ??
			};
			return new Stuff(); // no error here   // good		
    	}
    	return new Stuff();
    }
}

@stephan-herrmann - what explains those errors marked "Why" ??
```

**Comment by srikanth-sankaran** [comment]
Ok, here is some analysis: `org.eclipse.jdt.internal.compiler.ast.YieldStatement.analyseCode(BlockScope, FlowContext, FlowInfo)` has this code:

```
	if (flowInfo.reachMode() == FlowInfo.REACHABLE && currentScope.compilerOptions().isAnnotationBasedNullAnalysisEnabled)
		checkAgainstNullAnnotation(currentScope, flowContext, flowInfo, this.expression);
```

and `org.eclipse.jdt.internal.compiler.ast.Statement.checkAgainstNullAnnotation(BlockScope, FlowContext, FlowInfo, Expression)` has this:

```
	if (useTypeAnnotations) {
		checkAgainstNullTypeAnnotation(scope, methodBinding.returnType, expr, flowContext, flowInfo);
	} else if (nullStatus != FlowInfo.NON_NULL) {
		// if we can't prove non-null check against declared null-ness of the enclosing method:
		if ((tagBits & TagBits.AnnotationNonNull) != 0) {
			flowContext.recordNullityMismatch(scope, expr, expr.resolvedType, methodBinding.returnType, flowInfo, nullStatus, null);
		}
	}
```

why is the yielded expression typechecked against the method'd return type's nullity constraints ?? That seems to be the problem.

The only other caller of `org.eclipse.jdt.internal.compiler.ast.Statement.checkAgainstNullAnnotation(BlockScope, FlowContext, FlowInfo, Expression)`  is `org.eclipse.jdt.internal.compiler.ast.ReturnStatement.analyseCode(BlockScope, FlowContext, FlowInfo)`
ergo, `yield` statement is getting the same null checks as `return` statement which looks incorrect

**Comment by stephan-herrmann** [comment]
> The only other caller of `org.eclipse.jdt.internal.compiler.ast.Statement.checkAgainstNullAnnotation(BlockScope, FlowContext, FlowInfo, Expression)` is `org.eclipse.jdt.internal.compiler.ast.ReturnStatement.analyseCode(BlockScope, FlowContext, FlowInfo)`
> ergo, `yield` statement is getting the same null checks as `return` statement which looks incorrect

I believe the analogy between return and yield generally makes some sense, both break out from some scope providing a value up the chain, no? Of course, the difference still must be taken into account (see details in the PR).

**Comment by stephan-herrmann** [comment]
> > The only other caller of `org.eclipse.jdt.internal.compiler.ast.Statement.checkAgainstNullAnnotation(BlockScope, FlowContext, FlowInfo, Expression)` is `org.eclipse.jdt.internal.compiler.ast.ReturnStatement.analyseCode(BlockScope, FlowContext, FlowInfo)`
> > ergo, `yield` statement is getting the same null checks as `return` statement which looks incorrect
> 
> I believe the analogy between return and yield generally makes some sense, both break out from some scope providing a value up the chain, no? Of course, the difference still must be taken into account (see details in the PR).

There is a fundamental difference: analysis of a switch statement will be driven from its enclosing expression / statement. For `return` there is no such thing, so it has to trigger the analysis on its own.
