### ISSUE TITLE
Ci became much slower since 2024-05-21

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#2526]
from 38min to 57min :-(
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/e6e35f04-a832-4447-9ef5-c63a0fcf22bc)

**Comment by jukzi** [comment]
also for jdt.ui:
22min -> 40min
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/79e262f8-b738-412f-a213-e954484a709c)

**Comment by akurtakov** [comment]
It's most likely https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4682

**Comment by jukzi** [comment]
almost back to normal
jdt.ui:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/ef759551-cb92-45a0-a755-d0a552750b5f)
jdt.core:
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/3957b360-a59d-4034-b313-50feb69add87)
