### ISSUE TITLE
Track used dependencies during compilation

### ISSUE THREAD

**Issue by guw** [eclipse-jdt/eclipse.jdt.core#2529]
We are using the ECJ to compile Java code with Bazel. One of the interesting features the Bazel Java integration offers is tracking used dependencies during compilation. The goal is to compare this with declared dependencies and compile a list of unused dependencies (classpath entries).

I went with a naive implementation [here](https://github.com/salesforce/bazel-jdt-java-toolchain/commit/20c1eaa4e19362dc94723d2b7366f99b9ad3ffac), which basically extends `NameEnvironmentAnswer` to include the source `public final Classpath source` in the answer. Then I provided an ability to hook a consumer (listener) to the `FileSystem` which gets notified about all the `NameEnvironmentAnswer` objects from the  findType*` methods.

I wonder if this is worth pushing as a PR or if the team has a better idea for collecting the classpath entries used during compilation.

**Comment by iloveeclipse** [comment]
Gunnar, just push your PR and we can discuss on the code :-)

**Comment by jukzi** [comment]
ClasspathAnswer could be better inner class of Classpath to avoid the explicit `this` reference to the constructor;

**Comment by jukzi** [comment]
I wonder why an IDE would need such an listener. Classical if the UI needs such information it would kinda walk the java model and explore all reachable types. However that can get an annoyingly large tree per class and very slow. And i don't know why any user would be interested in such information which is inherently error prone as it misses runtime dependencies introduced by reflection.

**Comment by iloveeclipse** [comment]
> I wonder why an IDE would need such an listener.

As of today this change is only needed for ecj batch compiler used as a command line Java compiler in bazel.

**Comment by guw** [comment]
> As of today this change is only needed for ecj batch compiler used as a command line Java compiler in bazel.

Thats's a fair point. As of today it's only needed to report unnecessary compile dependencies.
