### ISSUE TITLE
testBug434044_comment36 fails with Java 1.7 JLS since I20240606-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2537]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240606-1800/testresults/html/org.eclipse.jdt.core.tests.compiler_ep433I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Note: we probably should drop support for Java < Java 8 now, see https://github.com/eclipse-jdt/eclipse.jdt.core/discussions/820.

I've also created https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2536.

**Comment by stephan-herrmann** [comment]
This difference:
```
 expected:<...or the type capture#[3]-of ? extends Eclips...> but was:<...or the type capture#[2]-of ? extends Eclips...> 
```
is well in the range of acceptable fluctuation across compliance settings.
Creating one capture more or less is not a bug.

@iloveeclipse do you still want me to make the test expectation version dependent, or will we stop testing at 1.7 "immediately"?

**Comment by iloveeclipse** [comment]
If it is eas, fix, fix it, if not, leave it. I hope I can work on removal soon, but this weekend I'm offline.

**Comment by jukzi** [comment]
Still failing. What is the plan for this issue? Disable tests <=1.7 ?

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2536

**Comment by kamilkrzywanski** [comment]
But do capt

> This difference:
> 
> ```
>  expected:<...or the type capture#[3]-of ? extends Eclips...> but was:<...or the type capture#[2]-of ? extends Eclips...> 
> ```
> 
> is well in the range of acceptable fluctuation across compliance settings. Creating one capture more or less is not a bug.
> 
> @iloveeclipse do you still want me to make the test expectation version dependent, or will we stop testing at 1.7 "immediately"?

but it isn't correct behaviour? Its's capture of 2 - 
doFoo(String) in Foo and
doFoo (Integer)in Nasty 

Do enough is just change it to 2 instead of 3?

**Comment by stephan-herrmann** [comment]
> but it isn't correct behaviour? Its's capture of 2 -

Those numbers are not guaranteed, they are a way to visualize different captures of the same wildcard as different. Other than that this number has no meaning.

The point in this specific issue is: compilation at 1.7 vs 1.8 create different numbers of captures so the same capture gets different names.

**Comment by iloveeclipse** [comment]
Closed after Java 8 update.
