### ISSUE TITLE
Incorrect startPosition of a SingleVariableDeclaration in the catch block

### ISSUE THREAD

**Issue by tkravchuk-parasoft** [eclipse-jdt/eclipse.jdt.core#2564]
![AST view](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/154594176/14730d7e-9201-4a71-8efc-1e46bb93f4a0)

Such a problem we have observed only when javadoc comment is placed before a catch keyword.

**Comment by subyssurendran666** [comment]
@mpalat could you please assign it to me ?

**Comment by jarthana** [comment]
Closing this issue.
