### ISSUE TITLE
[Sealed types][selection] Can't navigate in files in 2nd level child

### ISSUE THREAD

**Issue by DamnClin** [eclipse-jdt/eclipse.jdt.core#2574]
Eclipse Version: 2024-06 (4.32.0) on Ubuntu

Create:

```java
public sealed interface Top permits Middle {}
public sealed interface Middle extends Top permits Down {}
public record Down(String foo) implements Middle {}
```

Open `Down` and try ctrl + clic `String`: no action.

When using F3 on String: 

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/59929679/b00a1317-2e26-40eb-9bfd-d7ec525641f7)

("Problems opening an editor. Cannot read the array length because "superPermittedTypes" is null")

Will be the same for any element in this file or any file with a hierarchy looking like this one

**Comment by srikanth-sankaran** [comment]
I think my recent bug fix in this area may already have fixed this. Will check.

**Comment by srikanth-sankaran** [comment]
Yes, I can confirm that this problem is already fixed on master HEAD - problem went away with the fix for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2093
