### ISSUE TITLE
Ant buildfiles export ignores the --release javac option

### ISSUE THREAD

**Issue by jourquin** [eclipse-jdt/eclipse.jdt.core#2576]
The ant builfiles export tool always generates the following code, even if the "Use --release" option is checked in the Java Compiler properties:
```
<target depends="init" name="build-project">
        <echo message="${ant.project.name}: ${ant.file}"/>
        <javac debug="true" debuglevel="${debuglevel}" destdir="classes" includeantruntime="false" source="${source}" target="${target}">
            <src path="src"/>
            <classpath refid="Nodus.classpath"/>
        </javac>
    </target>
```

Expected behavior:
- a "release" property should be set, instead of the "target" and "source" properties. Example: 
```
<property name="release" value="11"/>
```
- The following code should replace the previous one:
```
<target depends="init" name="build-project">
        <echo message="${ant.project.name}: ${ant.file}"/>
        <javac debug="true" debuglevel="${debuglevel}" destdir="classes" includeantruntime="false" release="${release}">
            <src path="src"/>
            <classpath refid="Nodus.classpath"/>
        </javac>
    </target>
```

**Comment by stephan-herrmann** [comment]
This export wizard is provided by org.eclipse.ant.ui. Please re-report at https://github.com/eclipse-platform/eclipse.platform since it is not possible to transfer an issue across organizations.
