### ISSUE TITLE
[sealed types] ECJ accepts a cast from a disjoint interface to a sealed interface

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2595]
Consider the following example that is rejected by Javac:

```
sealed interface Intf permits PermittedA {}
final class PermittedA implements Intf {}
interface Standalone {}
public class X {
    public Intf foo(Standalone st) {
    	return (Intf) st;
    }
}
```

As per the below spec condition, we can deterministically say that Intf and Standalone can't have common instances therefore must be rejected:
```
An interface named I is disjoint from another interface named J if (i) it is not that case that I <: J, and (ii) it is not the case that J <: I, and (iii) one of the following cases applies:

    I is sealed, and all of the permitted direct subclasses and subinterfaces of I are disjoint from J.

    J is sealed, and I is disjoint from all the permitted direct subclasses and subinterfaces of J.
```

**Comment by srikanth-sankaran** [comment]
> Consider the following example that is rejected by Javac:

Is the code snippet correct ? It is rejected by which version of javac ? From 16 - 22 all compile this fine. 

> As per the below spec condition, we can deterministically say that Intf and Standalone can't have common instances therefore must be rejected:
> 
> ```
> An interface named I is disjoint from another interface named J if (i) it is not that case that I <: J, and (ii) it is not the case that J <: I, and (iii) one of the following cases applies:
> 
>     I is sealed, and all of the permitted direct subclasses and subinterfaces of I are disjoint from J.
> 
>     J is sealed, and I is disjoint from all the permitted direct subclasses and subinterfaces of J.
> ```

Neither I nor J is sealed in the example and so it is not clear this spec rule applies at all.

**Comment by srikanth-sankaran** [comment]
Compiles also with JDK 23-ea builds - something wrong with the test case @jarthana

**Comment by jarthana** [comment]
Sorry, there was a goof-up with the testcase. I have fixed it now. There was no need for interface `I`. The cast is to `Intf`.

**Comment by srikanth-sankaran** [comment]
> Sorry, there was a goof-up with the testcase. I have fixed it now. There was no need for interface `I`. The cast is to `Intf`.

Thanks! That makes sense.

Here is a fuller set of JLS for disjoint reference types:

5.1.6 Narrowing Reference Conversion
...
A class or interface is disjoint from another class or interface if it can be determined
statically that they have no instances in common (other than the null value). The
rules for disjointess are as follows:
• A class named C is disjoint from an interface named I if (i) it is not the case that
C <: I, and (ii) one of the following cases applies:
– C is final.
– C is sealed, and all of the permitted direct subclasses of C are disjoint from I.
– C is freely extensible (§8.1.1.2), and I is sealed, and C is disjoint from all of
the permitted direct subclasses and subinterfaces of I.
• An interface named I is disjoint from a class named C if C is disjoint from I.
• A class named C is disjoint from another class named D if (i) it is not the case
that C <: D, and (ii) it is not the case that D <: C.
• An interface named I is disjoint from another interface named J if (i) it is not
that case that I <: J, and (ii) it is not the case that J <: I, and (iii) one of the
following cases applies:
– I is sealed, and all of the permitted direct subclasses and subinterfaces of I
are disjoint from J.
– J is sealed, and I is disjoint from all the permitted direct subclasses and
subinterfaces of J.
