### ISSUE TITLE
JDK 21 preview features and maven

### ISSUE THREAD

**Issue by paulaustin-automutatio** [eclipse-jdt/eclipse.jdt.core#2609]
With the latest 2024-06 release I'm getting the following errors on all my maven projects.

preview features enabled at an invalid source release level 21, preview can only be enabled at source level 22

I decided for my application that the preview features in JDK 21 were good enough for my production use so have enabled them. But with JDK22 they are now full features. But I want to stick with JDK 21 as a long term release.

All my projects are created from maven projects, so all the configuration is created by the maven eclipse integration and not myself. So I can't go and change settings as doing a update project will go and reset those settings.

```
   <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.4.1</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>3.9.5</version>
                </requireMavenVersion>
                <requireJavaVersion>
                  <version>21</version>
                </requireJavaVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
  <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <release>21</release>
          <debug>true</debug>
          <debuglevel>lines,source,vars</debuglevel>
          <parameters>true</parameters>
          <compilerArgs>
            <arg>-parameters</arg>
            <arg>--enable-preview</arg>
          </compilerArgs>
          <testCompilerArgument>-parameters</testCompilerArgument>
          <testCompilerArgument>--enable-preview</testCompilerArgument>
        </configuration>
      </plugin>
```

Please can you make it so that enabling preview features is based on the version of java configured for the project and not the single latest version of Java that eclipse supports.

**Comment by stephan-herrmann** [comment]
> Please can you make it so that enabling preview features is based on the version of java configured for the project and not the single latest version of Java that eclipse supports.

I understand your wish, but that would require that our's would not be _one compiler_ but a matrix of compiler versions, which is not feasible with given resources.

Please see that javac doesn't support several versions of preview features in the same implementation either.

If you are not keen on being on the bleeding edge, perhaps Eclipse 2024-03 is good for a little while still?

BTW: I wasn't aware that anybody would actually consider using preview features in production. You are aware that preview features can actually be withdrawn (which just happened to string templates)?

**Comment by paulaustin-automutatio** [comment]
So what you're saying is that if say I was developing an application (in java 21) that depended on a library that I also developed (in Java 17) that is some circumstances as the eclipse compiler is for Java 22 that I'd have to have 2 versions of eclipse so that I don't get errors in one of them?

Would it not be a good idea to support the LTS version with any features it offers and also whatever the non-LTS version.

Or have a flag in the settings (don't give an error for preview features from older releases).

yes I know there is a risk of having to change code at the next jump to LTS, but there were some features (virtual threads) which work a lot better with ScopedValue and structured concurrency.

**Comment by paulaustin-automutatio** [comment]
One other observation.

This is more of a warning than an error.

I can delete the error and everything else works.

**Comment by stephan-herrmann** [comment]
> So what you're saying is that if say I was developing an application (in java 21) that depended on a library that I also developed (in Java 17) that is some circumstances as the eclipse compiler is for Java 22 that I'd have to have 2 versions of eclipse so that I don't get errors in one of them?

You're locked to a specific JDT version only if you rely on preview features of a specific Java version. In all other scenarios you're free to mix Java versions within the same workspace.
 
> Would it not be a good idea to support the LTS version with any features it offers and also whatever the non-LTS version.

Good idea? Yes. Feasible with current team? Probably not. Maintaining different versions of the same feature is very complex stuff, that costs a lot of effort that would be lacking elsewhere.

I don't even dare to say: feel free to contribute, because it would be asking too much from you, or anybody.

> I can delete the error and everything else works.

don't tell anybody :wink:

**Comment by stephan-herrmann** [comment]
I'm closing this issue. Anybody with a ground-breaking idea how to address the request feel free to re-open.
