### ISSUE TITLE
Compiler complains about missing Class-Path from manifest

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#261]
Initially reported here:

- https://github.com/eclipse/tycho/issues/1197

The problem is that the [org.ow2.sat4j.pb-2.3.6.jar](https://mvnrepository.com/artifact/org.ow2.sat4j/org.ow2.sat4j.pb/2.3.6) has the following manifest:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: Daniel Le Berre
Build-Jdk: 1.8.0_111
Bundle-ManifestVersion: 2
Bundle-Name: %bundleName
Bundle-SymbolicName: org.sat4j.pb
Bundle-Version: 2.3.6.v20201214
Export-Package: org.sat4j.pb;version="2.3.6.v20201214",org.sat4j.pb.co
 nstraints;version="2.3.6.v20201214",org.sat4j.pb.constraints.pb;versi
 on="2.3.6.v20201214",org.sat4j.pb.core;version="2.3.6.v20201214",org.
 sat4j.pb.orders;version="2.3.6.v20201214",org.sat4j.pb.reader;version
 ="2.3.6.v20201214",org.sat4j.pb.tools;version="2.3.6.v20201214"
Bundle-Vendor: %providerName
Bundle-Localization: plugin
Require-Bundle: org.sat4j.core
Main-Class: org.sat4j.pb.LanceurPseudo2007
Specification-Title: SAT4J
Specification-Version: NA
Specification-Vendor: Daniel Le Berre
Implementation-Title: SAT4J
Implementation-Version: 2.3.6.v20201214 
Implementation-Vendor: CRIL CNRS UMR 8188 - Universite d'Artois
Automatic-Module-Name: org.ow2.sat4j.pb
Bundle-RequiredExecutionEnvironment: J2SE-1.5
Class-Path: org.sat4j.core.jar
```

Especially it contains `Class-Path: org.sat4j.core.jar` what can't be found and therefore EJC complains:

```
 Failed to init Classpath for jar file /home/jenkins/agent/workspace/eclipse.pde.ui_master/.m2/repository/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
21:46:43  java.nio.file.NoSuchFileException: /home/jenkins/agent/workspace/eclipse.pde.ui_master/.m2/repository/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
21:46:43  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
21:46:43  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
21:46:43  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
21:46:43  	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
21:46:43  	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
21:46:43  	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
21:46:43  	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
21:46:43  	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
21:46:43  	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
21:46:43  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
21:46:43  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
21:46:43  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:201)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
```

I'm not sure if this should better be a **compiler-warning** instead? And I think it should have an improved message, as it was very hard to guess, so something like:

> Jar-Class-Path-Entry 'org.sat4j.core.jar' declared in 'org.ow2.sat4j.pb-2.3.6.jar' could not be found and will be ignored, compilation classpath might be incomplete.

FYI @iloveeclipse

**Comment by iloveeclipse** [comment]
More generic question is: is the **compiler** supposed to look into `Class-Path:` entries of the jars put on the classpath?
~~I have no idea if there is any spec that defines that.~~
Google says yes: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4212732

**Comment by laeubi** [comment]
> Google says yes

I think a warning might be suitable then or should it be ignored at all?

**Comment by laeubi** [comment]
@iloveeclipse is there any decision yet? Currently this spams the log a bit and if we have fixed these I think I'll try to deploy a recent EJC compiler under the tycho group id so we finally can have a fixed Tycho version...

**Comment by iloveeclipse** [comment]
I guess what do you want is just a warning without stack trace, right?
I think we can add another option to enable stack trace explicitly, as opposed to now where it is always printed.

**Comment by laeubi** [comment]
I think the stack trace are useful, but if we find that they are actually not unsuspected they should be handled, here I think it should be either a warning or simply ignored (I must confess I don't think there are much people calling the compiler by hand these days and would wonder anyways).

**Comment by iloveeclipse** [comment]
This one should be fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/259 already
