### ISSUE TITLE
No results for jdt.core.tests.model and dependent tests in I20240619-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2614]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240619-1800/

I can't spot now whether the tests crashed or something wasn't properly built or whatever.

- org.eclipse.jdt.apt.tests
- org.eclipse.jdt.apt.pluggable.tests
- org.eclipse.jdt.core.tests.builder
- org.eclipse.jdt.core.tests.model
- org.eclipse.pde.api.tools.tests
- org.eclipse.jdt.core.tests.performance

**Comment by akurtakov** [comment]
The console log is at https://download.eclipse.org/eclipse/downloads/drops4/I20240619-1800/testresults/ep433I-unit-mac64-java17_macosx.cocoa.x86_64_17/directorLogs/director-org.eclipse.jdt.apt.pluggable.tests.log

**Comment by iloveeclipse** [comment]
```
Cannot complete the install because one or more required items could not be found.
	Software being installed: Java Annotation Processing Tests 3.6.400.v20240321-1252 (org.eclipse.jdt.apt.pluggable.tests 3.6.400.v20240321-1252)
	Missing requirement: Java Builder Tests 3.12.500.v20240619-0232 (org.eclipse.jdt.core.tests.builder 3.12.500.v20240619-0232) requires 'java.package; org.eclipse.jdt.core.tests.builder.mockcompiler 0.0.0' but it could not be found
	Cannot satisfy dependency:
		From: Java Annotation Processing Tests 3.6.400.v20240321-1252 (org.eclipse.jdt.apt.pluggable.tests 3.6.400.v20240321-1252)
		To: osgi.bundle; org.eclipse.jdt.core.tests.builder 0.0.0
```

**Comment by iloveeclipse** [comment]
The mock project was added in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2497 but that was building fine.
What changed now?

**Comment by jukzi** [comment]
`requires 'java.package; org.eclipse.jdt.core.tests.builder.mockcompiler 0.0.0' but it could not be found`
May be the required version is wrong/missing?

**Comment by iloveeclipse** [comment]
> The mock project was added in #2497 but that was building fine.
> What changed now?

Nothing, I was wrong and this is the first SDK build that "sees" 52b659f8b2ff21058c4f84de303871dd584d2b39.

So I think the project isn't properly hooked up in the build.

**Comment by iloveeclipse** [comment]
Note: the new test bundle `org.eclipse.jdt.core.tests.builder.mockcompiler` is a fragment.

@akurtakov, @mickaelistria : I believe there must be some difference how the target platform is constructed between github PR validation build that uses tycho and SDK build that uses something else? Could it be the new bundle need to be added in some file that is used to construct platform for SDK build?

May be here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml ?

**Comment by iloveeclipse** [comment]
Merged & triggered https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/24/ to see if that works.

**Comment by iloveeclipse** [comment]
Test results are there now: https://download.eclipse.org/eclipse/downloads/drops4/I20240620-0440/testResults.php
