### ISSUE TITLE
Investigation new issues due to the Unnamed Patterns and Variables

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#2623]
Due to Unnamed Patterns and Variables(https://openjdk.org/jeps/443), there are some issues in the DOM AST.  Currently, this is handled through the SingleVariableDeclaration node. We are checking the possibility of a similar situation being handled in the Type Elided Lambda Expression.

**Comment by mpalat** [comment]
Refer:
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2494#issuecomment-2181769555
reproduced here:
@subyssurendran666 - I believe we will have to do a design change here - Neither The changes to SVD (SingleVariableDeclaration) nor the NullType/NoType pattern look like the right approach -
agree that I am also culprit to these proposals, but both do not seem perfect - rather each resonates an afterthought. I believe we should be looking at an approach similar to TypeElided LambdaExpression as we initially planned. Would suggest to create a new issue to investigate such a design change. Specifically the suggestion is to replace SVD in TypePattern with Parameters. Let us go down that path and see whether we get a more appropriate solution. will discuss. Thanks!

**Comment by mpalat** [comment]
Ideally keep the  SVD but add another option - Identifier - that should take care of this

**Comment by subyssurendran666** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2688 is merged with Master. So closing the issue.
