### ISSUE TITLE
Bug 545605 - Adjust ecj to change in JVMS 4.7.18./19.

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2625]
from https://bugs.eclipse.org/545605

The essence: ecj may throw in
```
java.lang.IllegalStateException: Mismatching number of parameter annotations, 2>1 in a(Ljava/util/function/Function;Ljava/lang/Object;J)Z in =
	at org.eclipse.jdt.internal.compiler.classfmt.MethodInfoWithParameterAnnotations.getParameterAnnotations(MethodInfoWithParameterAnnotations.java:46)
	at org.eclipse.jdt.internal.core.ClassFileInfo.generateMethodInfos(ClassFileInfo.java:364)
	at org.eclipse.jdt.internal.core.ClassFileInfo.readBinaryChildren(ClassFileInfo.java:432)
```

this happens when reading a class file with a method of this shape:
```
  // access flags 0xA
  private static a(Ljava/util/function/Function;Ljava/lang/Object;J)Z
    // annotable parameter count: 2 (invisible)
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 1
```

annotatable parameter count 2 looks "wrong", but according to the same spec sentence we are insisting on in #205, ecj should accept that classfile, whether or not we can make sense of that annotation.

**Comment by stephan-herrmann** [comment]
Quite a coincidence that genie reminded me of this bug right after https://mail.openjdk.org/pipermail/compiler-dev/2024-June/026996.html ff :magic_wand: :smile:

**Comment by srikanth-sankaran** [comment]
What genie are you are referring to ??

**Comment by stephan-herrmann** [comment]
> What genie are you are referring to ??

The "author" of https://bugs.eclipse.org/bugs/show_bug.cgi?id=545605#c22, which caused an email notification two days ago.

**Comment by stephan-herrmann** [comment]
The exception observed in the original bug reported was the improved diagnostic from https://bugs.eclipse.org/474081 - at which time this structure was illegal indeed.

**Comment by stephan-herrmann** [comment]
Raising visibility of another link hidden in bugzilla: https://bugs.openjdk.org/browse/JDK-8067975

**Comment by stephan-herrmann** [comment]
### Should anybody suspect that the correlation between parameters and their annotations goes astray define a system property `jdt.reject.parameterAnnotations.countMismatch=true` and recompile.

**Comment by stephan-herrmann** [comment]
To be continued via #2938
