### ISSUE TITLE
[dom ast][rewrite]  org.eclipse.jdt.core.tests.rewrite.describing.ASTRewritingEitherOrMultiPatternNodeTest test failures

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2633]
[ASTRewrite failures](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2610/4/testReport/)

Cannot invoke "java.util.List.iterator()" because "properties" is null
[org.eclipse.jdt.core.tests.rewrite.describing.ASTRewritingEitherOrMultiPatternNodeTest.test0001 - JLS22](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2610/4/testReport/org.eclipse.jdt.core.tests.rewrite.describing/ASTRewritingEitherOrMultiPatternNodeTest/test0001___JLS22/)

**Comment by mpalat** [comment]
@subyssurendran666 - can you please take a look at this?

**Comment by subyssurendran666** [comment]
Sure @mpalat , could you please assign this to me ?

**Comment by subyssurendran666** [comment]
The issue no longer exists; hence, it is being closed.
