### ISSUE TITLE
False Positive Potential Resource Leak Warnings - @NotOwning Not Working Correctly

### ISSUE THREAD

**Issue by geoffblandrbs** [eclipse-jdt/eclipse.jdt.core#2635]
I have installed Eclipse 24.06 as we have a requirement for the new `@Owning` and `@NotOwning` attributes begin supported to correctly flag potential resource leaks - this has been broken since Eclipse 2019.06. See #2129.

Either my understanding of how `@Owning` and `@NotOwning` is meant to work is incorrect - or @NotOwning does not work.

If a resource is owned (marked `@Owning`) in the class responsible for creating and closing that resource it should be possible to pass that resource to other classes where it is not owned (marked `@NotOwning`) and have no warning reported. But a warning is reported  about the `@NotOwning` field needing to be marked `@Owning`.

To show this issue (this example is a bit contrived but shows the issue):

```
package owning_test;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;

import org.eclipse.jdt.annotation.Owning;

public class OwningTest implements AutoCloseable {

	@Owning
	private InputStream fileInputStream;
	
	@SuppressWarnings("unused")
	private NotOwningTest cacheUser;
	
	public void initialise() throws FileNotFoundException {
	  fileInputStream = new FileInputStream("test.txt");
	  cacheUser = new NotOwningTest(fileInputStream);
	}

	@Override
	public void close() throws IOException {
		fileInputStream.close();
	}
	
}
```

```
package owning_test;

import java.io.InputStream;

import org.eclipse.jdt.annotation.NotOwning;

public class NotOwningTest {

	// If get a warning here - "It is recommended to mark resource fields as '@Owning' to ensure proper closing"
	@NotOwning
	private InputStream cacheInputStream;
	
	NotOwningTest(InputStream aCacheInputStream) {
		cacheInputStream = aCacheInputStream;
	}
	
}
```

Also to get `@Owning` and `@NotOwning` to work you need to include the `org.eclipse.jdt.annotation_2.3.0.v20240111-2306.jar` to your project. This is a not intuitive to users having to find and include this obscure JAR.

![Screenshot 2024-06-25 115149](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/6451079/7be05817-58fd-4878-8458-0443b6ae84dc)

![Screenshot 2024-06-25 115347](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/6451079/56f73631-548e-427e-82bc-3af2f53063e0)

![Screenshot 2024-06-25 115503](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/6451079/e868544e-78b0-4ec4-8838-3d5426732f61)

**Comment by geoffblandrbs** [comment]
Adding @stephan-herrmann as he has helped with this in the past.

**Comment by stephan-herrmann** [comment]
Hi @geoffblandrbs 

I'll try to find time to check in detail next week, but some preliminary answers already:

> we have a requirement for the new `@Owning` and `@NotOwning` attributes begin supported to correctly flag potential resource leaks

I'm glad it seems to help.

> If a resource is owned (marked `@Owning`) in the class responsible for creating and closing that resource it should be possible to pass that resource to other classes where it is not owned (marked `@NotOwning`) and have no warning reported. But a warning is reported about the `@NotOwning` field needing to be marked `@Owning`.

The warning "It is recommended to mark resource fields as `@Owning` ..." is different from actual leak warnings. It is controlled by option "Resource not managed with ownership annotations as recommended".  So if it bothers you short-term, that would be the option to dim it down for now.
 
> Also to get `@Owning` and `@NotOwning` to work you need to include the `org.eclipse.jdt.annotation_2.3.0.v20240111-2306.jar` to your project. This is a not intuitive to users having to find and include this obscure JAR.

I don't know what you mean by obscure :). If you have channels where this jar can be advertised more prominently, feel free to do so. I made sure it appears on maven central and time ago we even had a quickfix to add it to the classpath, but that may be limited to the use of null annotations. ...

**Comment by geoffblandrbs** [comment]
> I don't know what you mean by obscure :). 

Apologies, badly worded. I just meant it would be nice if eclipse made it easier for the user. So if you enable this resource analysis it "just worked". So users did not have to go and find out which JAR contained the needed classes and where that JAR file exists in the Eclipse install and then have to add it to the project. 

> some time ago we even had a quickfix to add it to the classpath

That would be nice.
