### ISSUE TITLE
[19] Formatter support for JEP 405: Record Patterns

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.core#264]
Record Patterns will need formatter to be enhanced
@mateusz-matela

**Comment by SarikaSinha** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/85 JEP 405: Record Patterns

**Comment by mateusz-matela** [comment]
#85 points to  http://cr.openjdk.java.net/~gbierman/jep427+405/jep427+405-20220426/specs/patterns-switch-record-patterns-jls.html#jls-6.3.3.2 which doesn't make it easy to understand what changes will be needed, I could use some examples.
Is it something more than #75 ?

**Comment by SarikaSinha** [comment]
There is a  new RecordPattern  node which has nested patterns, which might need a revisit from formatter point of view.

**Comment by winniequinn** [comment]
@mateusz-matela: Formatting for the record patterns introduced in JEP 405 (and iterated upon in JEP 432) does appear to need some work—at least in Eclipse 2022-12 (4.26.0) and in the prerelease version of `redhat.java` for Visual Studio Code (as of December 10th, 2022). In particular, spaces after commas will be removed in code such as the following:

```java
record Foo(int a, int b) {}
record Bar(Foo a, Foo b) {}
int bar(Foo f) {
  return switch (f) {
    // Note the lack of spaces after formatting here.
    case Bar(Foo(var a,bar b),Foo(var c,var d)) -> a + b + c + d;
    // This is what I expected:
    // case Bar(Foo(var a, bar b), Foo(var c, var d)) -> a + b + c + d;
  };
}
```

**Comment by winniequinn** [comment]
@mateusz-matela: Formatting for the record patterns introduced in JEP 405 (and iterated upon in JEP 432) does appear to need some work—at least in Eclipse 2022-12 (4.26.0) and in the prerelease version of `redhat.java` for Visual Studio Code (as of December 10th, 2022). In particular, spaces after commas will be removed in code such as the following:

```java
record Foo(int a, int b) {}
record Bar(Foo a, Foo b) {}
int baz(Bar bar) {
  return switch (bar) {
    // Note the lack of spaces after formatting here.
    case Bar(Foo(var a,var b),Foo(var c,var d)) -> a + b + c + d;
    // This is what I expected:
    // case Bar(Foo(var a, var b), Foo(var c, var d)) -> a + b + c + d;
  };
}
```

**Comment by mateusz-matela** [comment]
OK, I've added support for spaces around commas and parenthesis in record pattern, using the same settings as for record declaration.
I was considering adding line wrapping as well, but if someone's record patterns are long enough to need wrapping, that's probably not the best use for them. So adding new settings for this looks like an overkill. Using the same settings as for record declaration would be simple, but it's easy to imagine someone having a specific formatting for declarations that wouldn't make sense in switch statements.
