### ISSUE TITLE
False positive warning "Potential resource leak" inside "try with resources"

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2642]
Given this example and enabled `org.eclipse.jdt.core.compiler.problem.potentiallyUnclosedCloseable=warning` option in `.settings/org.eclipse.jdt.core.prefs`

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/2d47d904-9fca-4392-9c58-f42513ca6f95)

```
import java.io.FileWriter;
public class DemoNonCloseableWarning {
    public static void main(String[] args) throws Exception {
        try (FileWriter writer = new FileWriter("/dev/null")) {
            writer.append("\n");
        }
    }
}
```

we report false positive warning `Potential resource leak: '<unassigned Closeable value>' may not be closed`.

Of course this is option is not enabled by default, and of course it is **potential**, but here we have undoubtedly closed writer, so not idea where the "potential" warning is coming from.

@stephan-herrmann : FYI.

**Comment by iloveeclipse** [comment]
Fun fact: it worked at least in 3.8.2 Eclipse on Java 1.7 :-)

**Comment by stephan-herrmann** [comment]
This looks spooky on first glance:
```
----------
1. WARNING in /tmp/DemoNonCloseableWarning.java (at line 5)
        writer.append("\n");
        ^^^^^^^^^^^^^^^^^^^
Potential resource leak: '<unassigned Closeable value>' may not be closed
----------
1 problem (1 warning)
```

Not allocating the writer bad calling `append()` triggers the warning. But wait: append *returns* a Writer (which could in theory be a fresh new resource).

We do have provision for this situation, see `org.eclipse.jdt.internal.compiler.lookup.TypeConstants.FLUENT_RESOURCE_CLASSES`.  Something confuses the detection of this "fluent" method.

**Comment by iloveeclipse** [comment]
> But wait: append _returns_ a Writer

OK, I see it now where AI hallucinates :-). Compiler assumes the return value has to be closed...

**Comment by stephan-herrmann** [comment]
> OK, I see it now where AI hallucinates :-). Compiler assumes the return value has to be closed...

Don't worry: with AI in the picture any causalities between input program and warnings would be much more obscure.. ;-P
