### ISSUE TITLE
Prevent excessive creation of intermediate SplitPackageBinding instances

### ISSUE THREAD

**Issue by PPazderski** [eclipse-jdt/eclipse.jdt.core#2646]
I found that in a code base with many Java modules (explicit modules containing a module-info file) and a shared package prefix, the `SplitPackageBinding.combine` produces an unnecessary amount of binding instances.
To make things worse, even if the calling code discards the previous SplitPackageBinding instance which was combined into a new one the old instance will still remain in memory because the old instance is still referenced as a `PackageBinding.wrappingSplitPackageBindings` in all `PlainPackageBinding`s it wraps in addition to the newly combined instance and this is done again and again and again.

In a large code base I encountered `PlainPackageBinding`s which hold references to more than 600,000 SplitPackageBinding instances. You can imagine that my heap memory does not like that and it slows down the compiler code which later iterates over this huge list.

It might be sensible to remove the old SplitPackageBinding from the wrappingSplitPackageBindings when creating a new one but that might require to replace the `ArrayList` with a `(Linked)HashSet` and I have neither tried it nor investigated into the possible consequences and problems of such a change.

Because I found a simpler and from my understanding safe solution for my problem.

I think my main problem is rooted in how `SplitPackageBinding` decides to reuse or create a new instance. I found two code paths which trigger bad behaviour with the current implementation.

First `org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.combineWithPackagesFromOtherRelevantModules(PackageBinding, char[][], char[][])`. This one produces a SplitPackageBinding for a given package with all required modules. Imagine the Eclipse project would be modularized and you got a 'root' module which depends on all others. Now you got a long list of modules which all contain the package `org` (because all Eclipse code is placed in `org.eclipse...` and you also get all external dependencies having `org` packages) and will all be combined into a SplitPackageBinding.

The `SplitPackageBinding.combine` method first tries to reuse one of the bindings however, in this case you can expect that the rank is the same for all (at least for the cases I debugged). Also since we iterate the modules you will never `subsumes` one binding with the other. Therefore each loop iteration will produce a new `SplitPackageBinding` instance.
Each new `SplitPackageBinding` will take over the `PlainPackageBinding` incarnations from its predecessor and will register itself as wrapping binding on the `PlainPackageBinding`.

The seconds one, probably _a lot_ worse, way is through `SplitPackageBinding.getPackage0`, `SplitPackageBinding.getPackage0Any` and `SplitPackageBinding.combineWithSiblings`. If I understand it correctly this might be called to find a sub-package and if not found directly in the `knownPackages` it will check its plain package incarnations. If more than one incarnation contains  the searched sub-package it will produce a new `SplitPackageBinding`, again step by step, and with each step will register the intermediate bindings as wrapping on the plain binding. This grows quite large, quite quickly.

My fix is to extend the logic when to reuse an existing `SplitPackageBinding` and when to create a new one when combing bindings. From my understanding of the code there is no need to create a brand new `SplitPackageBinding` if the `primaryModule` has not changed. In the problematic method `combineWithPackagesFromOtherRelevantModules` I described above the `primaryModule` is always the same and it feels way more natural to have _one_ `SplitPackageBinding` here and add all incarnations and declaring modules one by one to it.

Also for the even more problematic uses of `combine` in `SplitPackageBinding` it would prevent creation of a lot of intermediate `SplitPackageBinding`s.

What might still be problematic is, that `SplitPackageBinding.getPackage0` and `SplitPackageBinding.getPackage0Any` still can produce ephemeral(?) `SplitPackageBinding` which are still referenced as wrapping bindings on the plain bindings for way longer as the split binding might be used by the caller.

**Comment by stephan-herrmann** [comment]
Thanks @PPazderski for your analysis.

In light of the problem discussed in #2647  I gave it a shot by modifying each loop that incrementally creates a SplitPackageBinding, towards collecting the constituents first, and then creating only one SplitPackageBinding in one go. The new test in ModuleCompilationTests went down from 30 instances to 17 (with a bit of fluctuation??). I also instrumented one test in ModuleBuilderTests, where the change is from 175 to 71.

@PPazderski  are you able to test #2730 in your environment, to check if it helps?

**Comment by PPazderski** [comment]
Thank you for your effort. I will give it a try, probably next week.

**Comment by PPazderski** [comment]
The change from #2730 helps, even more than I expected. Where I could get up to 1,500,000 wrapping bindings in the list it is down to ~23,000 after the change.


By accident it also seem to fix the other (non-performance) bug I was investigating around split-packages. I had not made a bug report yet because I always miss some detail to create a reproducing example. But I invested quite some time to understand this bug so I will describe it here anyways.

Before #2730 the compiler sometimes falsely reported one or more packages as not visible or not accessible.
The project has to use the module system. It might require a fully qualified service in a module-info.java (I'm absolutely not sure if this is just the path it triggers the error for me or a requirement for the bug). And I assume it requires an auto-module as dependency with the same root package as the failing project (I'm quite sure the bug has to go through [this code block](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/b03ab84cf9b4d0234a821e49b87afc76b7cd2817/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java#L598) in ModuleBinding).

What I know about this bug: at some point the compiler calls `org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.getPackage0(char[])` for a package which is not yet known in this SplitPackageBinding. In this case all incarnations have caching information, therefore we do not exit early but create a PackageBinding candidate. But somehow I got in a state where each incarnation either returns plain or split-package binding which subsumes the other. In the end it will not create a new `SplitPackageBinding` instance but the candidate is instead the `SplitPackageBinding` object which is cached as known package in one of the incarnations and now will also cached as known in our currently active `SplitPackageBinding`.

This part is important because it is one (maybe the only) path to share the same `SplitPackageBinding` instance in different enclosing modules.

At a later point in the compilation process I came through `org.eclipse.jdt.internal.compiler.lookup.SplitPackageBinding.findPackage(char[], ModuleBinding)` where two or more of the {{declaringModules}} share at some point the same `SplitPackageBinding`. I.e. the first declaring module goes through `getVisiblePackage` and in my case it does not contain this package therefore at the end of `org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getVisiblePackage(PackageBinding, char[])` it will mark this name as not-found package in the parent `SplitPackageBinding`. But in my case this parent binding is shared with another module. Now while `findPackage` continues with the other declaring module the module which does have the searched sub-package happens to have the same `SplitPackageBinding` instance as one of the modules checked before. Now it will falsely report it as not-found from the cache.


As said before this got accidental fixed by #2730. Maybe from the change to `getPackage0` or the change to auto-module handling in `ModuleBinding.getVisiblePackage`.
The bug is also quite hard to trigger because you need the right modules sharing the same packages in the correct order. Simply opening or closing a project, i.e. changing from source module to binary module from Maven, could trigger or prevent the bug.

**Comment by stephan-herrmann** [comment]
> The change from #2730 helps, even more than I expected. Where I could get up to 1,500,000 wrapping bindings in the list it is down to ~23,000 after the change.
> 
> By accident it also seem to fix the other (non-performance) bug I was investigating around split-packages.

There is a chance that "your" bug is the same that caused build failure 2 commits into my PR, such that the modified compiler was no longer able to compile jdt.core itself. I read this as a dormant bug that came to the surface due to different internal representation of the same program model.

Anyway, my 3rd commit https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2730/commits/8d735477bdfefd3ecc8c90b7e721bede4252dbfa was driven more by restoring correctness, rather than performance consideration. 

>  I had not made a bug report yet because I always miss some detail to create a reproducing example. But I invested quite some time to understand this bug so I will describe it here anyways.

without a reproducing example we cannot be 100% sure, but the anomalies you describe sound a bit similar to what I observed and fixed.

In particular, the location you referred to (within `ModuleBinding.getVisiblePackage()`) was among those that could visit the same module more than once. One of the side effects of this: we could create unwanted `SplitPackageBinding` which were in fact not "split" but contained only a single incarnation. This could cause a ripple of other unwanted effects, notably a situation, where a `PlainPackageBinding` could contain a `SplitPackageBinding`, which clearly violates the intended contract.

For now we can hope that #2730 indeed fixed your bug.

Thanks once more for you in-depth analysis.

**Comment by PPazderski** [comment]
> This could cause a ripple of other unwanted effects, notably a situation, where a PlainPackageBinding could contain a SplitPackageBinding, which clearly violates the intended contract.

That is also what I observed when analyzing my issue and what I also assumed is a precondition.

One possible fix I had in mind is to not cache not-found in `ModuleBinding.getVisiblePackge()` if the parent is a `SplitPackageBinding` but only in the incarnation we currently search visible packages for. That would prevent the too early cached "not found" in case the parent binding is shared.
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/b03ab84cf9b4d0234a821e49b87afc76b7cd2817/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java#L618-L623
When I had that idea I thought that there is only one `SplitPackageBinding` for each package and modules are only represented with the `declaredModules` and `incarnations`.

Another odd, but probably intended, detail I noticed is that package bindings form more or less a tree (with parent and knownPackages) but my `SplitPackageBinding`s always have a plain binding as parent.

**Comment by stephan-herrmann** [comment]
> Another odd, but probably intended, detail I noticed is that package bindings form more or less a tree (with parent and knownPackages) but my `SplitPackageBinding`s always have a plain binding as parent.

That's exactly one of the conditions which my change now prevents. Only `SplitPackageBinding`s can have other splits as their children (knownPackages). Once we cross the bridge to `PlainPackageBinding` there should be no way back to `SplitPackageBinding`, and no `SplitPackageBinding` is allowed to have a `PlainPackageBinding` as its `parent`. IOW, if in the future you ever come across that situation again, the we'd know that my fix is incomplete. For now, I'm fairly confident we're good.

**Comment by PPazderski** [comment]
> IOW, if in the future you ever come across that situation again, the we'd know that my fix is incomplete. For now, I'm fairly confident we're good.

I have good and bad news. Bad: I found already a project setup which triggers your newly added assert. Good: this time I can provide a simple reproducing example.

I opened issue #2748 for that.
