### ISSUE TITLE
[Sealed Types] Failure to cast an Object to a generic sealed interface type

### ISSUE THREAD

**Issue by lukeu** [eclipse-jdt/eclipse.jdt.core#2667]
There is a compiler error reported in the 2nd line of the main function of the snippet below, saying "Cannot cast from Object to Either<String, Integer>". 

This differs from executing `java Either.java` in JDK-17 or JDK-21 - which issue only an unchecked-cast warning and still run.

    public sealed interface Either<L,R> {
    
        L getLeft();
        R getRight();
    
        record Left<L, R>(L error) implements Either<L, R> {
            @Override
            public L getLeft() {
                return error;
            }
            @Override
            public R getRight() {
                throw new NoSuchElementException();
            }
        }
    
        record Right<L, R>(R value) implements Either<L, R> {
            @Override
            public L getLeft() {
                throw new NoSuchElementException();
            }
            @Override
            public R getRight() {
                return value;
            }
        }
    
        public static void main(String[] args) {
            Object o = new Left<String, Integer>("boo");
            var either = (Either<String, Integer>) o;
            System.out.println(either.getLeft());
        }
    }

I tested a variant of this class (with generic parameters removed and these types hard-coded) and it did not suffer the same issue.

I believe this is a regression in a recent nightly build of JDT, when compared to the baseline Eclipse SDK 2024-06 (4.32), because to test another JDT issue 1998 I had upgraded just the JDT tools using the following update site:

https://download.eclipse.org/eclipse/updates/4.33-I-builds/I20240628-1800/

I have not seen this error before that JDT upgrade. (With a caveat that the code that detected this was not on my daily development branch, but I believe I have built it recently. If it turns out to not be a regression since Eclipse 4.32, I am sure it would be a regression since Eclipse 4.31.)

**Comment by srikanth-sankaran** [comment]
Thanks for the report, I'll take a look.

**Comment by srikanth-sankaran** [comment]
Indeed. Compiles with 4.32 with an unchecked cast warning, but on HEAD we reject the code.

**Comment by srikanth-sankaran** [comment]
> I believe this is a regression in a recent nightly build of JDT, when compared to the baseline Eclipse SDK 2024-06 (4.32), because to test another JDT issue 1998 I had upgraded just the JDT tools using the following update site:

It is.

I believe the PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2634 merged for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2595 opens up some code paths previously unexercised. In particular some of the code
in `org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.permittedTypes()` look suspicious as they operate
with parameterized (substituted) sealed interface and generic (unsubstituted) permitted types.

I have in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2671 attempted an interim fix that is still correct. I'll review `org.eclipse.jdt.internal.compiler.lookup.ParameterizedTypeBinding.permittedTypes()` in due course and amend it as needed.

**Comment by lukeu** [comment]
Just to say I've updated to 4.33-M1 and and confirm the "interim fix" is now working as described. Also it's nice to see the snippets being added into the test corpus so that they can help with future changes. :-)

**Comment by srikanth-sankaran** [comment]
Thanks a lot @lukeu - appreciate it.
