### ISSUE TITLE
Generic inferral is not correctly performed when using wildcard

### ISSUE THREAD

**Issue by alienisty** [eclipse-jdt/eclipse.jdt.core#2668]
The following code is the smallest reproducing version I could muster. This is happily compiled by ecj:
```java
class IncorrectGenericsDetection {

  static class Test {

    private RestTemplate rest;

    @SuppressWarnings("unchecked")
    void test(Class<?> e) throws Exception {
      when(rest.exchange(any(Class.class))).thenThrow(e);
    }
  }

  public static <T> T any(Class<T> type) {
    return null;
  }

  public static <T> OngoingStubbing<T> when(T methodCall) {
    return null;
  }

  public interface OngoingStubbing<T> {
    OngoingStubbing<T> thenThrow(Class<? extends Throwable> throwableType);
  }

  public class ResponseEntity<T> {
  }

  public static interface RestTemplate {
    public <T> ResponseEntity<T> exchange(Class<T> responseType) throws Exception;
  }
}
```
But when compiled with the JDK I get the following:
```
IncorrectGenericsDetection.java:17: error: incompatible types: Class<CAP#1> cannot be converted to Class<? extends Throwable>
      when(rest.exchange(any(Class.class))).thenThrow(e);
                                                      ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object from capture of ?
```
I believe the JDK error is correct.

Note I'm compiling with open jdk 17

**Comment by srikanth-sankaran** [comment]
@stephan-herrmann - Thanks for taking a look.

**Comment by stephan-herrmann** [comment]
The actual problem is this:
```
    @SuppressWarnings("unchecked")
```
Without suppression you'd see several warnings like this:
```
----------
2. WARNING in /tmp/IncorrectGenericsDetection.java (at line 9)
        when(rest.exchange(any(Class.class))).thenThrow(e);
                           ^^^^^^^^^^^^^^^^
Type safety: The expression of type Class needs unchecked conversion to conform to Class<Object>
----------
```

javac reports similarly.

Due to this unchecked conversion [15.12.2.6](https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-15.12.2.6) applies:
>  If unchecked conversion was necessary for the method to be applicable, then \[...] invocation type's return type and thrown types are given by the erasure of the return type and thrown types of the method's type. 

Ergo `when(..)` returns the raw type `OngoingStubbing#RAW`.

With a raw-type receiver, method `thenThrow(..)` has this signature: `OngoingStubbing#RAW thenThrow(Class#RAW)`

See that there is no requirement to pass a `Class<? extends Throwable>`.

Advice:
* Never use raw types when you want reliable type checking.
* Never accept unchecked conversions when invoking generic methods, because that would result in raw types.

You might consider filing a bug against javac.

**Comment by stephan-herrmann** [comment]
> With a raw-type receiver, method `thenThrow(..)` has this signature: `OngoingStubbing#RAW thenThrow(Class#RAW)`

To fill in intermediate steps:

From [4.8 Raw Types](https://docs.oracle.com/javase/specs/jls/se22/html/jls-4.html#jls-4.8)
> The type of \[...] a\[n] instance method ([§8.4](https://docs.oracle.com/javase/specs/jls/se22/html/jls-8.html#jls-8.4)) of a raw type C that is not inherited from its superclasses or superinterfaces is the erasure of its type in the generic class or interface C.

Where "type of a method" is defined in [8.4](https://docs.oracle.com/javase/specs/jls/se22/html/jls-8.html#jls-8.4) as
> We use the phrase _the type of a member_ to denote:
> \[...]
> * For a method, an ordered 4-tuple (known as a method type) consisting of:
>    * type parameters: the declarations of any type parameters of the method member ([§8.4.4](https://docs.oracle.com/javase/specs/jls/se22/html/jls-8.html#jls-8.4.4)).
>    * parameter types: a list of the types of the formal parameters of the method member ([§8.4.1](https://docs.oracle.com/javase/specs/jls/se22/html/jls-8.html#jls-8.4.1)).
>    * return type: the return type of the method member ([§8.4.5](https://docs.oracle.com/javase/specs/jls/se22/html/jls-8.html#jls-8.4.5)).
>    * throws clause: exception types declared in the throws clause of the method member ([§8.4.6](https://docs.oracle.com/javase/specs/jls/se22/html/jls-8.html#jls-8.4.6)).

Hence all these types will be erased.
