### ISSUE TITLE
Comparator Errors

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2669]
From @MohananRahul  - raised against platform releng -https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2163- found to be jdt.core issue - raising here:

Comparator Error found :
https://download.eclipse.org/eclipse/downloads/drops4/I20240703-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

eclipse.jdt.core/org.eclipse.jdt.core.tests.performance/pom.xml
no-classifier: different
org/eclipse/jdt/core/tests/performance/FullSourceWorkspaceBuildTests.class: different
The main artifact has been replaced with the baseline version.
The following attached artifacts have been replaced with the baseline version: [sources]

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/4507939/de78fcfe-27cf-48e3-b464-232a6560871d)

**Comment by mpalat** [comment]
The issue is in FullSourceWorkspaceBuildTests.scanfile() - this is due to a value change of TerminalTokens.TokenNameEOF which is used in case statements - specifically this change  - https://github.com/eclipse-jdt/eclipse.jdt.core/commit/bf0427a51fa67e9cbe3f2a6ec7c830775468c35f#diff-defeff8a2b5cf674526eec934a508f1a52858f20678cf9631de32d006d35a8c9

An update of baseline would be the right way

**Comment by srikanth-sankaran** [comment]
@mpalat Should this be open anymore ??

**Comment by MohananRahul** [comment]
@srikanth-sankaran issue resolved , please close.
