### ISSUE TITLE
Bug 533327 - [9] Implement JEP 211

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2679]
See https://bugs.eclipse.org/533327 :

> Brought to you via http://openjdk.java.net/jeps/211 is this change in JLS §9.6.4.6:
> A Java compiler must produce a deprecation  warning [...] unless:
> [...]
> •  The use is within an import declaration that imports the ordinarily deprecated
type or member."

**Comment by stephan-herrmann** [comment]
Wondering about "ordinarily" in the above I see the JLS has the same import exception regarding "ordinarily deprecated" and "terminally deprecated"  (causing otherwise a "removal warning").

So, nothing to worry about, in this regard all deprecation is treated the same.

**Comment by jukzi** [comment]
Thanks for implementing this. Should render @SuppressWarnings at class level for the imports unneeded, allowing more fine grained @SuppressWarnings
