### ISSUE TITLE
[Sealed types] ECJ allows a class to be declared as both sealed and non-sealed

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2707]
ECJ compiles this code while javac rejects it with `error: illegal combination of modifiers: sealed and non-sealed`:

```
public sealed class X permits Y {	
}

sealed non-sealed class Y extends X permits K {}

final class K extends Y {}
```

ECJ behavior is faulty.

**Comment by srikanth-sankaran** [comment]
We also accept this:

```
public sealed class X permits Y {	
}

final non-sealed class Y extends X  {}
```

rejected by javac with `error: illegal combination of modifiers: final and non-sealed`

**Comment by srikanth-sankaran** [comment]
And this program elicits 3 errors from ecj of which 2 are bogus:

```
public final sealed class X permits Y {	
}

final non-sealed class Y extends X  {}

```

Description	Resource	Path	Location	Type
A class Y declared as non-sealed should have either a sealed direct superclass or a sealed direct superinterface	X.java	/_pasted_code_/src	line 4	Java Problem
Permitted class Y does not declare X as direct super class	X.java	/_pasted_code_/src	line 1	Java Problem
The type Y cannot subclass the final class X	X.java	/_pasted_code_/src	line 4	Java Problem

javac messages are better:

```
X.java:1: error: illegal combination of modifiers: final and sealed
public final sealed class X permits Y {	
                    ^
X.java:4: error: illegal combination of modifiers: final and non-sealed
final non-sealed class Y extends X  {}
                 ^
X.java:4: error: cannot inherit from final X
final non-sealed class Y extends X  {}
                                 ^
3 errors

```

**Comment by srikanth-sankaran** [comment]
Basically it seems we don't implement this para of JEP 409:

```
It is not possible for a class to be both sealed (implying subclasses) and final (implying no subclasses), or both non-sealed (implying subclasses) and final (implying no subclasses), or both sealed (implying restricted subclasses) and non-sealed (implying unrestricted subclasses).
```

**Comment by iloveeclipse** [comment]
> sealed non-sealed

Cool :-)
