### ISSUE TITLE
 Error in JDT Core during AST creation when using exhaustive switch statement and @NotNull

### ISSUE THREAD

**Issue by ashley-taylor** [eclipse-jdt/eclipse.jdt.core#2708]
## Steps to reproduce

Make sure you have `jakarta.validation` on the classpath

Then, the following code causes a build error

```java
import jakarta.validation.constraints.NotNull;

public class TestSwitch {

	public static void main(@NotNull Animal animal) {
		switch(animal) {
		case Cat c -> {}
        }
	}
	record Cat() implements Animal {}
	sealed interface  Animal permits Cat {}
}
```

## Tested under this environment:
* OS & version: macOS 14.3
* Eclipse IDE/Platform version (as shown in *Help > About*): 2023-12 (4.30.0)

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by srikanth-sankaran** [comment]
What error is reported ? Can you paste the message here please ?

**Comment by srikanth-sankaran** [comment]
If some one has the cycles to spare, please try and see if you are able to extract a standalone test case that can show the problems against plain SDK JDT and against JDT's built in null annotations.

**Comment by srikanth-sankaran** [comment]
This problem is not reproducible. Please reopen with a plain java test case if you have evidence to feel otherwise.
