### ISSUE TITLE
[Sealed types] Disjointness behavior difference vis a vis javac 

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2709]
The following snippet elicits an error from ECJ (`Cannot cast from X.C3 to X.I`) while javac compiles it fine. This difference needs to be investigated:

```
						public class X {
							sealed interface I permits C1 {}
							non-sealed class C1 implements I {}
							class C2 extends C1 {}
							class C3 {}
							{
								I i;
								i = (I) (C1) null;
								i = (I) (C2) null;
								i = (I) (C3) null;
							}
						}
```

**Comment by srikanth-sankaran** [comment]
Relevant JLS wording:

5.1.6

...

A class or interface is disjoint from another class or interface if it can be determined
statically that they have no instances in common (other than the null value). The
rules for disjointness are as follows:
• A class named C is disjoint from an interface named I if (i) it is not the case that
C <: I, and (ii) one of the following cases applies:
...
– C is freely extensible (§8.1.1.2), and I is sealed, and C is disjoint from all of
the permitted direct subclasses and subinterfaces of I.

And 

§8.1.1.2

A class is freely extensible if its direct superclass is not sealed (§8.1.4), and none
of its direct superinterfaces are sealed (§8.1.5), and it is neither sealed nor final
itself.

So ...

The class C3 is free extensible since its direct super class (jlO) is not sealed and none of its super interface (it has no superinterfaces) are sealed and it is neither sealed nor final.

C3 is free extensible and I is sealed and C3 is indeed disjoint from all of
the permitted direct subclasses and subinterfaces of I (which is the singleton set C1) 

So it looks like javac is at fault here.

@stephan-herrmann - May I request you to double check and confirm ? TIA

**Comment by srikanth-sankaran** [comment]
`A class or interface is disjoint from another class or interface if it can be determined
statically that they have no instances in common (other than the null value).'

Given this slightly modified program:

```
public class X {
    sealed interface I permits C1 {}
    non-sealed class C1 implements I {}
    class C2 extends C1 {}
    class C3 {}
    {
        I i;
        i = (I) (C1) null;
        i = (I) (C2) null;
        i = (I) (C3) null;
        i = (I) (C2) (C3) null;
        i = (I) (C1) (C3) null;
    }
}
```

javac 22 complains:

X.java:11: error: incompatible types: X.C3 cannot be converted to X.C2
        i = (I) (C2) (C3) null;
                     ^
X.java:12: error: incompatible types: X.C3 cannot be converted to X.C1
        i = (I) (C1) (C3) null;
                     ^
2 errors


Given I is a sealed interface that permits only C1, for C3 to _NOT TO BE DISJOINT_ from I, C3 must NOT BE DISJOINT from C1 but it is as proved by javac's own rejection of `(C1) (C3) null` 

So straightforward conclusion is that there is a javac bug here.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann - May I request you to double check and confirm ? TIA

Sorry I dropped the ball, the closed issue no longer appeared on any instrument :)
Looking into this now.

**Comment by stephan-herrmann** [comment]
For ease of communication I rephrased the example like this:
```java
public class X1 {
    sealed interface I permits C1 {}
    non-sealed class C1 implements I {}
    class C2 extends C1 {}
    class C3 {}
    I m2(int s, C3 c3) {
        return switch (s) {
            case 0 -> (I) c3;
            case 1 -> (C1) c3;
            case 2 -> (C2) c3;
            default -> null;
        };
    }
}
```

ecj HEAD complains about all three casts, javac still at 24-ea+21 only complains:
```
X1.java:9: error: incompatible types: X1.C3 cannot be converted to X1.C1
            case 1 -> (C1) c3;
                           ^
X1.java:10: error: incompatible types: X1.C3 cannot be converted to X1.C2
            case 2 -> (C2) c3;
                           ^
2 errors
```

case 0 remains silent.

I.e., javac agress that c3 cannot be cast to C1 nor C2, which are the only implementations of I. Still the cast to I is not recognized as impossible.

**Comment by stephan-herrmann** [comment]
Asked here: https://mail.openjdk.org/pipermail/compiler-dev/2024-October/028344.html
