### ISSUE TITLE
[Sealed types + switch expression] Internal inconsistency warning at compile time and verify error at runtime

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-jdt/eclipse.jdt.core#2714]
This sample code produces VerifyError using Eclipse 4.32 with java 21 compilation when running main method :

```
package test;

public interface InterfaceA {

  static <T extends AbstractSealedClass> Integer get(T object) {
    return switch (object) {
      case ClassB ignored -> 5;
    };
  }

  public abstract sealed class AbstractSealedClass permits ClassB {
  }

  public final class ClassB extends AbstractSealedClass {
  }

  public static void main(String[] args) {
    ClassB classB = new ClassB();
    InterfaceA.get(classB);
  }
}
```

**Comment by srikanth-sankaran** [comment]
Running on 4.30, 4.31 and 4.32 we get:

```
Error: Unable to initialize main class test.InterfaceA
Caused by: java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    test/InterfaceA.get(Ltest/InterfaceA$AbstractSealedClass;)Ljava/lang/Integer; @45: areturn
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @45
    flags: { }
    locals: { 'test/InterfaceA$AbstractSealedClass', 'test/InterfaceA$AbstractSealedClass', integer, 'test/InterfaceA$ClassB' }
    stack: { 'java/lang/Integer' }
  Stackmap Frame:
    bci: @45
    flags: { }
    locals: { 'test/InterfaceA$AbstractSealedClass' }
    stack: { }
  Bytecode:
    0000000: 2a59 b800 0a57 4c03 3d2b 1cba 0010 0000
    0000010: aa00 0000 0000 001d 0000 0000 0000 0000
    0000020: 0000 0014 2bc0 0014 4e08 b800 16b0     
  Stackmap Table:
    append_frame(@36,Object[#37],Integer)
    chop_frame(@45,2)


```

BUT on 4.32 we already see the warning: `Internal inconsistency: Inappropriate operand stack size encountered during translation`

@RoiSoleil - I am surprised your report doesn't mention this warning - can you confirm one way or other ?

**Comment by RoiSoleil** [comment]
Yes i get a warning but it is strange that thers is a warning but that the actual code isn't working ...

![image](https://github.com/user-attachments/assets/af57d464-148d-44cb-be0d-807974dc4051)

I see that you linked a PR that solves the issue ;) Thx !!

**Comment by srikanth-sankaran** [comment]
> Yes i get a warning but it is strange that thers is a warning but that the actual code isn't working ...
> 

The compiler was smart enough to detect an internal inconsistency and warned about it. The bad code generation is a direct consequence of the internal inconsistency. The compiler is not smart enough to recover from the internal inconsistency.

**Comment by srikanth-sankaran** [comment]
> 
> I see that you linked a PR that solves the issue ;) Thx !!

You are welcome. That PR will need some tweaks - but yes the crux of the problem has been identified. So hopefully before this weekend the fix will be merged.
