### ISSUE TITLE
[Sealed Types + Enhanced Switch] Incorrect diagnostic about switch not being exhaustive

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#2720]
Reported here by @nlisker : https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2719#issuecomment-2232303720

I've just ran into what seems to be the same problem:

```
sealed interface I {

	enum E implements I {
		A, B, C;
	}
} 

class Test {

	void d(I i) {
		switch (i) { // error: An enhanced switch statement should be exhaustive; a default label expected
			case I.E.A -> {}
			case I.E.B -> {}
			case I.E.C -> {}
		}
	}
}
```
But there are no other valid cases (I must be an E, which must be A, B or C).

Didn't test with javac.

Version: 2024-06 (4.32)
Build id: I20240601-0610

**Comment by nlisker** [comment]
Incorrect behavior with 4.33 as well. This time I tested with javac 22 and compilation passes (correctly).
