### ISSUE TITLE
Switch pattern matching accepts invalid case

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#2722]
```java
class Test {

	interface Inter {}

	class Cls {}

	void test(Inter inter) {
		switch (inter) {
			case Cls s -> {}
			default -> {}
		};
	}
}
```
The case for `Cls` should be rejected as it can't be a match for `Inter`, however, the compiler throws no error. Making the interface sealed (and adding a subtype) doesn't make a difference.

Version: 2024-06 (4.32)
Build id: I20240601-0610

**Comment by srikanth-sankaran** [comment]
Did you check the behavior with javac ? It also compiles the program above. I don't see why there should be an error. While Cls doesn't implement I, a subclass of Cls may ?

For the case where `Making the interface sealed (and adding a subtype) doesn't make a difference.` please provide a test case. That will eliminate guess work. 

ATM I don't see a defect here

**Comment by srikanth-sankaran** [comment]
I recommend always testing against javac.

**Comment by srikanth-sankaran** [comment]
In the parlance of JLS, `Cls` is not disjoint from `Inter`. In the following case where `Cls` has been declared final, `Cls` is indeed disjoint from `Inter` and ECJ issues an error correctly: `Type mismatch: cannot convert from Test.Inter to Test.Cls`

```
class Test {

	interface Inter {}

	final class Cls {}

	void test(Inter inter) {
		switch (inter) {
			case Cls s -> {}
			default -> {}
		};
	}
}
```

**Comment by srikanth-sankaran** [comment]
>  Making the interface sealed (and adding a subtype) doesn't make a difference.

ECJ and javac both reject this:

```
class Test {

	sealed interface Inter permits Klass {}

	final class Klass implements Inter {}
	
	class Cls {}

	void test(Inter inter) {
		switch (inter) {
			case Cls s -> {}
			default -> {}
		};
	}
}
```

I plan to close this with no change, unless you are able to produce a test case that shows ECJ differing from the spec or the reference compiler i.e, javac

**Comment by nlisker** [comment]
> > Making the interface sealed (and adding a subtype) doesn't make a difference.
> 
> ECJ and javac both reject this:
> 
> ```
> class Test {
> 
> 	sealed interface Inter permits Klass {}
> 
> 	final class Klass implements Inter {}
> 	
> 	class Cls {}
> 
> 	void test(Inter inter) {
> 		switch (inter) {
> 			case Cls s -> {}
> 			default -> {}
> 		};
> 	}
> }
> ```

javac rejects this, but ECJ accepts this for me with 2024-06 (4.32). Here is a screenshot:
![image](https://github.com/user-attachments/assets/5c8ef05f-f889-4c37-ac11-11526bec0d95)

Compare with making `Cls` final, where I get the same error as you:
![image](https://github.com/user-attachments/assets/df57ae3a-3eab-47fe-a6ab-1d58f7eb5026)

Perhaps it was fixed after 4.32?

**Comment by srikanth-sankaran** [comment]
I'll check - there have been many fixes in this area in the past month.

**Comment by nlisker** [comment]
I tested with the latest integration build:
Version: 2024-09 (4.33)
Build id: I20240717-1800

The problem is fixed there - ECJ rejects the code.

**Comment by srikanth-sankaran** [comment]
duplicate of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2595
