### ISSUE TITLE
[23] DOM changes for markdown Javadoc comments

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2738]
Follow up discussion on https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2731

DOM API should be updated to differentiate markdown Javadoc nodes with regular Javadoc, so that clients can handle appropriately. Keep the formatter also in mind when updating the APIs.

**Comment by stephan-herrmann** [comment]
@jarthana with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2731 plus `parseMarkdownLinks()` copied to `DocCommentParser`  I see all markdown links handled as `@see` tags, where it would probably be better to mimic `{@link }` tags, to support inline links.

**Comment by jarthana** [comment]
> @jarthana with #2731 plus `parseMarkdownLinks()` copied to `DocCommentParser` I see all markdown links handled as `@see` tags, where it would probably be better to mimic `{@link }` tags, to support inline links.

Thanks, I think I meant to use parseLinkReference() but ended up using parseReference(). Let me try switching it and see what happens.

**Comment by subyssurendran666** [comment]
@jarthana Could you please assign this ticket to me?

**Comment by jarthana** [comment]
In the interest of time and considering the complexity of the issue, I am taking over this.

**Comment by stephan-herrmann** [comment]
@jarthana I think the `DocCommentParser` works pretty good by now. 

What else should we address via this ticket? 
* perhaps the much discussed feature  `Javadoc.isMarkdown()` ? :smile: but we could also defer that until the feature leaves the preview status.

IOW, I wouldn't mind closing this issue for now ...

**Comment by jarthana** [comment]
> @jarthana I think the `DocCommentParser` works pretty good by now.
> 
> What else should we address via this ticket?
> 
>     * perhaps the much discussed feature  `Javadoc.isMarkdown()` ? 😄 but we could also defer that until the feature leaves the preview status.
> 
> 
> IOW, I wouldn't mind closing this issue for now ...

Sounds good to me. isMarkdown() is something we can take up if the drive comes from the UI. Closing this now. Thank you very much for your work on this.
