### ISSUE TITLE
[formatter] single-line comment formatting inconsistent

### ISSUE THREAD

**Issue by lrozenblyum** [eclipse-jdt/eclipse.jdt.core#274]
**Eclipse 2022-03**

Let's have a code like below and execute **Source -> Format**

```
//1. Not formatted with space, even if 'Format line comments on first column' is ON
public class Hello {

//2. Formatted with space if 'Format line comments on first column' is ON
	//3. Always formatted with space
	public static void main(String[] args) {
	}
}
```

EXPECTED:
The comment `//1.` is formatted with a space after slashes `// 1. `

ACTUALLY:
The comment `//1.` is untouched.

It's inconsistent with comments 2 + 3. Modern style guides often require a space after slashes in a single-line comment.

Feature idea: Maybe as an idea: it would be great to make this behavior (whitespace after slashes) actually **configurable** from the formatter settings.

**Comment by mateusz-matela** [comment]
In your example the first comment is actually controlled by the "Enable header comment formatting" setting. If you turn it on, the space is added. Does this solve the problem?

**Comment by lrozenblyum** [comment]
Thank you @mateusz-matela it indeed solved the problem!
