### ISSUE TITLE
[23] Failures in ASTRewritingEitherOrMultiPatternNodeTest after merging

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2743]
After the most recent merge of master into BETA_JAVA23, couple of new tests that were added in master are failing now.

ASTRewritingEitherOrMultiPatternNodeTest.test0007_a()
ASTRewritingEitherOrMultiPatternNodeTest.test0007_b()

This may be something to do with the test projects set up or worse some version related check in code.

@subyssurendran666  can you please take a look. This needs to be fixed in BETA_JAVA23.

**Comment by subyssurendran666** [comment]
@jarthana could you please assign the ticket to me?

**Comment by jarthana** [comment]
Sorry guys, this is blocking all work on BETA branch. I am taking this up.
