### ISSUE TITLE
[23] Code assist changes for markdown Javadoc comments

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2744]
After the compiler support, it would be nice to get the code select and completion working to help users trying to experiment and use the new feature. I see some of the select features already working, but this needs to be tested and more tests should be added if required. Understandably, completion is not at all working and could use some work.

**Comment by stephan-herrmann** [comment]
@jarthana I think from jdt.core perspective this looks good now, so we can close this issue. Or do you have any immediate plans for improvement?

This doesn't touch on any issues mentioned in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1542 (like disabling HTML templates within markdown).
