### ISSUE TITLE
jclMin1.8.jar is not complete for 1.8 JLS target tests

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2756]
Found in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2551

`NullAnnotationModelTests.testBug565246` fails, because `Iterable` class that is present in `jclMin1.7.jar` is missing in `jclMin1.8 jar` and in `jclMin1.8.jar` `Collection` does not extend `Iterable`.

**Comment by stephan-herrmann** [comment]
We probably want to do #2727 first
