### ISSUE TITLE
[19] statement switch with a case null does not compile

### ISSUE THREAD

**Issue by forax** [eclipse-jdt/eclipse.jdt.core#277]
Here is a simple reproducer

```java
public class SwitchNull {
  enum Color { RED, BLACK }

  public static void main(String[] args) {
    Color color = Color.RED;
    switch (color) {
      case null -> throw null;
      case RED -> System.out.println("RED");
      case BLACK -> System.out.println("BLACK");
    }
  }
}
```

This code should compile but i get
"An enhanced switch statement should be exhaustive; a default label expected" at line 6 (on the switch itself).

ecj recognizes that this is an enhanced switch statement, this is true, there is a case "null" but fails to find it exhaustive.
javac has no issue with that code.

**Comment by srikanth-sankaran** [comment]
With project source level set to Java 21, I don't see the problem anymore, but see a different one:

This snippet:

```
public class X {
  enum Color { RED, BLACK }

  public static void main(String[] args) {
    Color color = null;
    switch (color) {
      case null -> System.out.println("Null");
      case RED -> System.out.println("RED");
      case BLACK -> System.out.println("BLACK");
    }
  }
}
```

prints `Null` when compiled with javac and when compiled with ECJ results in:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "X$Color.ordinal()" because "color" is null
	at X.main(X.java:6)
```

**Comment by srikanth-sankaran** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1773 includes fixes and tests for both the snippets here.

**Comment by forax** [comment]
Thanks Srikanth !
