### ISSUE TITLE
[23][IDE Support] JEP 455: Primitive Types in Patterns, instanceof, and switch (Preview) #2298

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2844]
IDE Support 
- DOM AST + Rewrite
- Search
- Selection
- Content Assist
- Formatter

Create issues as required.

**Comment by stephan-herrmann** [comment]
@mpalat  any idea of what should be done here? Any new AST nodes?? New references to be considered for search?

Looking from a distance this issues looks like a no-op.

**Comment by mpalat** [comment]
@stephan-herrmann At this point I also believe that its a no-op.  Will revisit once we have the complete compiler support up to check for nuances and corner cases.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann At this point I also believe that its a no-op. Will revisit once we have the complete compiler support up to check for nuances and corner cases.

As I just closed #2298 be my guest :)

**Comment by mpalat** [comment]
> IDE Support
> 
> * DOM AST + Rewrite
> * Search
> * Selection
> * Content Assist
> * Formatter
> 
> Create issues as required.

I don't see anything that needs to be done for DOM AST/Rewrite, Search, Selection or Formatter. Perhaps we can enhance content assist with the primitives also being listed as options - created https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2886 - not a blocker requirement.

**Comment by mpalat** [comment]
no blocker issue for this milestone - Content assistant issue #2886  may be taken up later if need be.. closing.
