### ISSUE TITLE
[23][IDE Support] JEP 476: Module Import Declarations (Preview) #2383

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2846]
IDE Support

DOM AST + Rewrite
Search
Selection
Content Assist
Formatter
Create issues as required.

**Comment by stephan-herrmann** [comment]
> IDE Support
> 
> * DOM AST + Rewrite

* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2834

> * Search 

* New issue #2852 

> * Selection

* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2838

> * Content Assist

* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2823

> * Formatter

? 

Additionally:
* https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1589
