### ISSUE TITLE
[23][IDE Support] JEP 477: Implicitly Declared Classes and Instance Main Methods (Third Preview) #2474

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2847]
IDE Support for issue #2474 

DOM AST + Rewrite
Search
Selection
Content Assist
Formatter
Create issues as required.

**Comment by mpalat** [comment]
@jarthana can you please take a look whether something is needed here? I am wondering what will be shown in AST DOM for example?

**Comment by jarthana** [comment]
Other than search, of which I don't have much idea, I don't think we need anything here. I can see DOM nodes being added and functioning as expected and code assist in general working. I think some of the list is irrelevant, like the type hierarchy.

I tried some basic things with search that appear to be working. But as an expert in this area, I will let you decide whether something else is required here.

**Comment by stephan-herrmann** [comment]
> Other than search

I don't think that implicit classes are really relevant for search, as no-one outside can see them, right?

Has anyone tried to format an implicit class?

**Comment by mpalat** [comment]
> > Other than search
> 
> I don't think that implicit classes are really relevant for search, as no-one outside can see them, right?
> 
right, search not relevant here.
