### ISSUE TITLE
23][IDE Support] JEP 482: Flexible Constructor Bodies (Second Preview) #2472

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2848]
IDE Support

DOM AST + Rewrite
Search
Selection
Content Assist
Formatter
Create issues as required.

**Comment by stephan-herrmann** [comment]
JEP 482 does not introduce any new constructs, only relaxes existing validity rules.

So from theory, no changes in IDE support would be needed, but I'm sure the community will find some :)

**Comment by stephan-herrmann** [comment]
I don't plan to do anything (until bug reports are coming in ;-P ). Closing.
