### ISSUE TITLE
provide more context in "Could not create the Java Virtual Machine" case

### ISSUE THREAD

**Issue by ralfhauser** [eclipse-jdt/eclipse.jdt.core#285]
Despite https://bugs.eclipse.org/bugs/show_bug.cgi?id=533162 claiming the problem is solved (supposedly also for jdk11 with tomcat9) , the problem still persists with Version: 2022-06 (4.24.0) Build id: 20220609-1112 .

<<Unrecognized VM option 'CMSPermGenSweepingEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.>>

==> please provide more context like

a) which java executable (full path) was attempted to execute

b) environment variables

...

**Comment by ralfhauser** [comment]
Removing the "CMSPermGenSweepingEnabled" out of the "Append to JVM Parameters" of tomcat plugin 9.1.4 "JVM Settings" seems to help

**Comment by iloveeclipse** [comment]
This is not the webtools project.l, sorry.

**Comment by nitind** [comment]
> This is not the webtools project.l, sorry.

Neither is the Tomcat plug-in, whose support tickets are filed at https://sourceforge.net/p/tomcatplugin/tickets/ , not Eclipse Bugzilla.
