### ISSUE TITLE
Eclipse Shows Error "The package javax.xml.parsers is accessible from more than one module" Even when Project is Not a Module

### ISSUE THREAD

**Issue by ingomohr** [eclipse-jdt/eclipse.jdt.core#2863]
## Scenario
Given I have a Maven component project
And that project is not a Java 9+ module
And that project builds successfully via Maven 3.9.6, Java 17
When I open the project in Eclipse (tested on 2024-06)
Then
  actual: I see an ERROR problem marker of "The package javax.xml.parsers is accessible from more than one module"

## Thoughts
(In VSCode with Language Support for Java(TM) by Red Hat v1.33.0 installed, I don't see that error, either).

As far as I understand...
* Eclipse complains because "javax.xml" is a module available in the JDJ17 - and also it's in the Maven dependencies of the project (which is correct).
* Since I don't have a module project, I cannot use the JDK module "javax.xml"
* Also, I wouldn't expect Eclipse to verify any module environment aspects because I don't have a module project, at all.

I assume I could turn the project into a module project to satisfy Eclipse.
Are there other options? Am I understanding something wrong here?

**Comment by stephan-herrmann** [comment]
Please have a look at https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10/53824670#53824670

Does this cover your situation?

A quick response to your assumptions: In Java 9+ there is no such thing as a non-modular mode of compilation. Instead when `module-info.java` is missing your code will be handled as part of the "unnamed module", for which a few special rules exist, but still it is a module.

**Comment by ingomohr** [comment]
Hi @stephan-herrmann, thank you for your answer!
Yes, "limit-modules" in the {{.classpath}} fixed this for me. Thanks also for the explanation! Helped a lot.

**Comment by ingomohr** [comment]
## Works as Specified
The problem has been resolved. As far as I understand, the JDT works as specified for this ticket.

**Comment by stephan-herrmann** [comment]
Thanks, @ingomohr  for confirming.
