### ISSUE TITLE
[23] JEP 455 - subtask - Handling the cases of testing contexts

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2868]
All cases under https://cr.openjdk.org/~abimpoudis/instanceof/jep455-20240424/specs/instanceof-jls.html#jls-5.7.2

**Comment by stephan-herrmann** [comment]
Actually, I needed to implement §5.7.2 as part of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2878
