### ISSUE TITLE
[23] JEP 455 - Exhaustiveness of Switch

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2869]
Ref -https://cr.openjdk.org/~abimpoudis/instanceof/jep455-20240424/specs/instanceof-jls.html#jls-14.11

Since primitives can also make a switch enhanced the exhaustiveness rules have changes in conjunction with https://cr.openjdk.org/~abimpoudis/instanceof/jep455-20240424/specs/instanceof-jls.html#jls-5.7.2 - the unconditionally exact

**Comment by stephan-herrmann** [comment]
According to 14.11.1.1 a switch is exhaustive when (only listing cases relevant for primitives, my numbering):
> 1. CE contains a pattern that is unconditional ([14.30.3](https://cr.openjdk.org/~iris/se/23/spec/fr/java-se-23-fr-spec-01/specs/instanceof-jls.html#jls-14.30.3)) for T.
> 2. The type T is boolean or Boolean and CE contains both the constant true and the constant false.
> 3. CE contains a type pattern with a primitive type P, and T is the wrapper class for the primitive type W, and the conversion from type W to type P is unconditionally exact ([5.7.2](https://cr.openjdk.org/~iris/se/23/spec/fr/java-se-23-fr-spec-01/specs/instanceof-jls.html#jls-5.7.2)).

Most directly, (2) is implemented in `SwitchStatement.resolve()` in the `check` lambda:
* we are comparing two `ResolvedCase`s: `c` and `otherResolvedCase`
* when their constants are not equal (`con.equals(c2)`) 
* and when the type is boolean, then they must be one `true` and one `false` constant
* at this point we set `this.switchBits |= Exhaustive` :heavy_check_mark: 

Next, (3) is implemented in `Pattern.coversType()`, when the conversion route is one of
* UNBOXING_CONVERSION: conversion is `T -> W`, where `W -> P` is identity
* UNBOXING_AND_WIDENING_PRIMITIVE_CONVERSION: here both conversions are explicit / non-trivial
   * in this case we additionally need to check if `W -> P` is unconditionally exact
   * this is delegated to `BaseTypeBinding.isExactWidening()`
     * in this method 16 conversions are enumerated, which correspond to the 16 ɛ entries in the table in https://bugs.openjdk.org/browse/JDK-8288476
     * to double-check the slightly tricky correlation to JLS:
        * the quoted paragraph delegates to §5.7.2 ("Unconditionally Exact Testing Conversions") which further delegates to   "exact widening primitive conversion", which in §5.1.2 is defined enumerating 4 cases:
           * from an integral type to another integral type
               * byte -> short, byte -> int, byte -> long
               * char -> int, char -> long
               * short -> int, short -> long
               * int -> long
           * from byte, short, or char to a floating-point type
               * byte -> float, byte -> double
               * short -> float, short -> double
               * char -> float, char -> double
           * from int to double
           * from float to double -- TOTAL: 16
       * the listing concerning integral types furthermore relies on:
          * the definition of "integral types": byte, short, int, long, and char (see intro of §4):
          * the fact that char and byte are in no widening relation either way (see first listing in §5.1.2).
* q.e.d. :heavy_check_mark:

**Comment by stephan-herrmann** [comment]
Resolved with #2878
