### ISSUE TITLE
eclipse can't build when error in switch

### ISSUE THREAD

**Issue by thomas2123** [eclipse-jdt/eclipse.jdt.core#2870]
Hi,
As I am a junior developper, I sometime make silly mistakes, sorry for that ^^'.
As @stephan-herrmann suggested, I'll create a new issue for this one. 
I got this error in building with 2024-06 :
![image](https://github.com/user-attachments/assets/b1cf67b6-31c2-4c08-8840-34c2903e1ddf)
I tried to revert to 2024-03, but I got this error : 
![362346452-baa85cb4-d79a-44bb-bfc5-7bf2201e024c](https://github.com/user-attachments/assets/a95848e0-6668-48e8-97c3-513f8c71c778)
But when I reverted back to 2023-12, I did not have the error in building anymore. As I went through the error, I found that it was linked to this error :
![image](https://github.com/user-attachments/assets/80fb17a7-6c8d-4683-8a9d-d8ca82606394)
It's a mistake I often make, to use an enum as a Constant in a switch.

When the enum is replaced by a Constant, the error goes away and the building works again.
I hope I made this clear, sorry if I didn't.
Good luck and thank you for the beautiful software you make.

**Comment by thomas2123** [comment]
![image](https://github.com/user-attachments/assets/f994471c-0718-422a-8f24-7f6b04431360)
proof I used eclipse 2024-06

**Comment by srikanth-sankaran** [comment]
Are you able to provide a small and self contained example to reproduce the problem ?? Screen shots are not very useful. 

Can you try and attach a fuller stack trace when the problem shows up ?? Thanks.

**Comment by stephan-herrmann** [comment]
> As I am a junior developper, I sometime make silly mistakes, sorry for that ^^'.

Every developer makes mistakes, and still the tool should not throw exceptions.

So, if you provide the code that triggered this as text, not picture, then your mistake will help us fix the tool for the benefit of others running into a similar mistake :)

**Comment by srikanth-sankaran** [comment]
Reproduced. Thanks @thomas2123 for the test case.

**Comment by srikanth-sankaran** [comment]
Simplified test case:

```
public class X {
	
	enum EnumError {
		TEST(0);
		
		private int value;
		
		private EnumError(int value) {
			this.value = value;
		}
		
		public int getValue() {
			return this.value;
		}
	}

	public static void main(String[] args) {
		int bouh = 0;
		switch(bouh) {
		case EnumError.TEST.getValue() : 
			break;
		}
	}

}
```

JDK-22 reports:

```
X.java:20: error: cannot find symbol
		case EnumError.TEST.getValue() : 
		              ^
  symbol:   class TEST
  location: class EnumError
X.java:20: error: deconstruction patterns can only be applied to records, getValue is not a record
		case EnumError.TEST.getValue() : 
		     ^
2 errors

```

**Comment by thomas2123** [comment]
thanks for the fix ^^

**Comment by srikanth-sankaran** [comment]
The fix is not merged in - master is not open for development of 4.34 work. Reopening. 

In any case, the ticket will be closed automatically when the fix is integrated.
