### ISSUE TITLE
Test or remove code block in SwitchStatement.generateCode()

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2879]
For #2298 I measured code coverage and due to high coverage in classes relevant for that issue, the remaining untested code blocks stick out clearly.

One example is in `SwitchStatement.generateCode()`:
```java
			// generate the switch block statements
			...
			if (this.statements != null) {
				for (Statement statement : this.statements) {
					CaseStatement caseStatement = null;
					if ((caseIndex < constantCount) && (statement == this.cases[caseIndex])) { // statements[i] is a case
						...
					} else {
						if (statement == this.defaultCase) { // statements[i] is a case or a default case
							...
						} else if (statement instanceof CaseStatement) {
							caseStatement = (CaseStatement) statement;
							caseStatement.typeSwitchIndex = typeSwitchIndex;
							typeSwitchIndex += caseStatement.constantExpressions.length;
						}
					}
					statementGenerateCode(currentScope, codeStream, statement);
```
In our entire compiler regression suite, no test evaluates `statement instanceof CaseStatement` to true.

I think, all `CaseStatement`s should be covered by `if ( ... statement == this.cases[caseIndex])`.

@mpalat as you added the block in question via 5876f7acb83ddc09b28de8d546830eff6b9ef3c8 for [Bug 579355](https://bugs.eclipse.org/579355) you should be given a chance to either
* write a test case that exercises this block, or
* confirm that it is dead code :smile:

**Comment by srikanth-sankaran** [comment]
I will follow up on this - I am working on cleaning up the switch implementation. Phase 1 of that already is in master. I will revisit this after some more work on sealed types clean up that is underway

**Comment by mpalat** [comment]
@srikanth-sankaran noted.

**Comment by srikanth-sankaran** [comment]
Compare the suspect block with the equivalent code in `org.eclipse.jdt.internal.compiler.ast.SwitchStatement.generateCodeForStringSwitch(BlockScope, CodeStream)` in which an arm of the form `else if (statement instanceof CaseStatement) {` is conspicuously absent.

**Comment by srikanth-sankaran** [comment]
```
if ((caseIndex < this.caseCount) && (statement == this.cases[caseIndex])) { // statement is a case 
...
} else if (statement == this.defaultCase) { // statement is the default case
```

features in `org.eclipse.jdt.internal.compiler.ast.SwitchStatement.analyseCode(BlockScope, FlowContext, FlowInfo)` too.

is allocated by `org.eclipse.jdt.internal.compiler.ast.SwitchStatement.resolve(BlockScope)` and populated by `org.eclipse.jdt.internal.compiler.ast.CaseStatement.resolveCase(BlockScope, TypeBinding, SwitchStatement)` with the understanding that "// collection of cases is too big but we will only iterate until caseCount"
