### ISSUE TITLE
Unnamed record pattern matching causes compilation errors

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#2898]
```java
public class SwitchBug {

	sealed interface Source {
	
		record I() implements Source {}
		record S(int id) implements Source {}
		record E(int id1, int id2) implements Source {}
	}

	private void f(Source source) {
		switch (source) {
			case Source.I() -> {}
			case Source.S(int id) -> {}
			case Source.E(int id1, _) -> {}
		};
	}
}
```

On Eclipse Version: 2024-06 (4.32) with Java 22 support:
Eclipse JDT (Java Development Tools) Patch with Java 22 support for 2024-03 development stream	1.2.300.v20240320-0518_BETA_JAVA22	org.eclipse.jdt.java22patch.feature.group	Eclipse.org

Two types of errors occur.
In the UI:
![image](https://github.com/user-attachments/assets/8fefc17b-a67b-427b-84e8-c3a3929fe61a)

 In the log:

!ENTRY org.eclipse.jdt.core.manipulation 4 2 2024-09-04 06:37:07.799
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.core.manipulation".
!STACK 0
java.lang.NullPointerException

!ENTRY org.eclipse.jdt.core.manipulation 4 0 2024-09-04 06:37:07.801
!MESSAGE Error in JDT Core during AST creation
!STACK 0
java.lang.NullPointerException

Perhaps it's fixed in 4.33, but I didn't test it there.

**Comment by srikanth-sankaran** [comment]
Using `Version: 2024-09 (4.33) Build id: I20240828-1820` - I don't see any errors. I will see if I can track it down to a problem fixed in the past.

**Comment by srikanth-sankaran** [comment]
Same as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2494

4.33 will have the fix.
