### ISSUE TITLE
[24] Create Java 24 constants and test framework changes

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2905]
Ref issue #2268 for a similar issue for Java 23

also, to raise once the issue #2212 gets closed - https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4497

**Comment by jarthana** [comment]
Closing.

**Comment by stephan-herrmann** [comment]
> Ref issue #2268 for a similar issue for Java 23
> 
> also, to raise once the issue #2212 gets closed - https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4497

As all these links were for Java 23, I was wondering about the status of jenkins (PR) builds, but it looks like this can be easily fixed, see #3197
