### ISSUE TITLE
Spring @RequestBody with required default is ignored in null checks

### ISSUE THREAD

**Issue by dnapoletanoexp** [eclipse-jdt/eclipse.jdt.core#2908]
If a Spring RestController has a method with a parameter marked with Spring _@RequestBody_ annotation, which has _required = true_ as a default (so its value is never null), null checks in the method ignore it:

- An "if ... == null" check is not reported as "Null comparison always yields false"
- Attribute access is reported as "Potential null pointer access"

Example class with both wrong behaviours:

```
package example;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/examplecontroller")
public class ExampleController {
	
   @PostMapping(value = "/examplemethod")
   public ResponseEntity<?> exampleMethod(@RequestBody InputObj data) {
      //@RequestBody has required = true as default, so data is never null
		
      if (data == null) {   //Should be reported as "Null comparison always yields false" but it isn't
         System.out.println("Input is null");
      }
		
      String attribute = data.getAttribute();   //It's reported as "Potential null pointer access" but it shouldn't
      System.out.println("Attribute: " + attribute);
      return null;
   }
}

class InputObj {
   private String attribute;
   public String getAttribute() {
      return attribute;
   }
   public void setAttribute(String attribute) {
      this.attribute = attribute;
   }
}
```

**Comment by jukzi** [comment]
jdt is only java aware it does not know about spring/RequestBody. it is totally possible in java to call that method by hand with a null argument. -> closing as invalid

**Comment by stephan-herrmann** [comment]
> jdt is only java aware it does not know about spring/RequestBody. it is totally possible in java to call that method by hand with a null argument. -> closing as invalid

Thanks, @jukzi for assessment.

Let me just add that null analysis in jdt has over time been taught to "understand" a few custom annotations and methods. Such additions have a few prerequisites:
* the library must in wide spread use 
* the semantics of the library must be specified in sufficient clarity that we have no doubt about where null can / cannot occur.
* the semantics should be simple enough not to introduce complex analysis into our implementation
* there should be some kind of enforcement that the library semantics cannot be bypassed.

It's the last item that is violated by explicit calls to such a method, which, OTOH, JDT cannot prohibit. Hence I agree with closure of this issue.
