### ISSUE TITLE
Potential null pointer access on 2 variables despite two-step null check

### ISSUE THREAD

**Issue by dnapoletanoexp** [eclipse-jdt/eclipse.jdt.core#2909]
In this example class, a "Potential null pointer access" warning is shown on two variables, despite a two-step null check is present for both of them.
For comparison, I added another method which performs a one-step null check on both variables, and the warning is not shown.

```
package example;

public class Example {

   public static boolean npaTest1(String s1, String s2) {
      if (s1 == null && s2 == null) {
         return true;
      }
      
      if ((s1 == null && s2 != null) || (s1 != null && s2 == null)) {
         return false;
      }
      
      s1 = s1.trim();     //Potential null pointer access - Wrong
      s2 = s2.trim();     //Potential null pointer access - Wrong
      
      return s1.equals(s2);
   }
   
   
   
   public static boolean npaTest2(String s1, String s2) {
      if (s1 == null || s2 == null) {
         return true;
      }
      
      s1 = s1.trim();     //No Potential null pointer access - Right
      s2 = s2.trim();     //No Potential null pointer access - Right
      
      return s1.equals(s2);
   }
}
```

**Comment by jukzi** [comment]
The example to be an academic example of no real usecase -> closing as not planned

**Comment by stephan-herrmann** [comment]
I agree with closing, but I disagree with the reason given.

I've seen similar requests with real world examples, so I _would_ be willing to improve null analysis in this direction, but this would require an entirely new kind of analysis, where the fundamental design of our implementation would need to be changed with unknown implications on tool performance etc.

What's so hard here? Understanding (im)possible flows of `null` in such code would require to reason about correlation between nullness of different variables. In JDT, however, null analysis for each variable is performed separately with no knowledge whatsoever about nullness of other variables. As a result, both if-statements are understood as possibly letting a `null` in either variable pass without branching to one of the early returns.

Changing the basic design of null analysis in this direction is way beyond the available resource.


While some people prefer the symmetry of the shown code pattern, I think the following style would be easier to understand not only by the tool but also by most human readers:

```java
	public static boolean npaTest1(String s1, String s2) {
		if (s1 == null) {
			return s2 == null;
		} else if (s2 == null) {
			return s1 == null; // redundant but symmetric :)
		}

		s1 = s1.trim(); // no warning :)
		s2 = s2.trim(); // no warning :)

		return s1.equals(s2);
	}
```

Search existing bug reports on https://bugs.eclipse.org for "[null][correlation]" for previous discussions in this field.
