### ISSUE TITLE
[23] ECJ accepts both boolean values and a default case in a switch

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#2916]
Consider this code:
```
public class X {
	public void foo(Boolean b) {
		final boolean TRUE = true;
		final boolean FALSE = false;
		switch (b) {
			case TRUE -> { break;}
			case FALSE -> { break;}
			default -> { break;}
		}
	}
}
```

ECJ accepts this but Javac rejects this with error:
`X.java:8: error: switch has both boolean values and a default label`

I haven't checked with the spec on this, though.

**Comment by stephan-herrmann** [comment]
Thanks, @jarthana  this is a good one. Keep'em coming! :)

**Comment by stephan-herrmann** [comment]
Fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2919

**Comment by jarthana** [comment]
> > FWIW, when I remove any of the three case statements, Javac crashes. I have a raised a defect with Oracle for this.
> 
> This one: https://bugs.openjdk.org/browse/JDK-8339602 ? Wow that was fast.

The JDK issue has been closed as  "not an issue". Don't know what to make of it :)
