### ISSUE TITLE
[23] NPE after PR #2935

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2939]
After updating with changes from #2935 new code from that PR causes NPE:
```
Caused by: java.lang.NullPointerException: Cannot read field "id" because "expressionType" is null
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.checkAndSetEnhanced(SwitchStatement.java:1401)
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.resolve(SwitchStatement.java:1120)
	at org.eclipse.jdt.internal.compiler.ast.Statement.resolveWithBindings(Statement.java:496)
```

It happened with this file
```
<T extends Short> void typeVariableSingle(T single) {
    int i1 = single;
    System.out.print(i1);
    if (single instanceof int i)
        System.out.print(i);
    else
        System.out.print('-');
    switch (single) {
        case int i -> System.out.print(i);
        default -> System.out.print('-');
    }
    System.out.println();
}
<T extends Short> void typeVariableList(List<T> list) {
    int i1 = list.get(0);
    System.out.print(i1);
    if (list.get(0) instanceof int i)
        System.out.print(i);
    else
        System.out.print('-');
    switch (list.get(0)) {
        case int i -> System.out.print(i);
        default -> System.out.print('-');
    }
    System.out.println();
}
void wildcard(List<? extends Short> list) {
    int i1 = list.get(0);
    System.out.print(i1);
    if (list.get(0) instanceof int i)
        System.out.print(i);
    else
        System.out.print('-');
    switch (list.get(0)) {
        case int i -> System.out.print(i);
        default -> System.out.print('-');
    }
    System.out.println();
}
void main() {
    Short s = 1;
    typeVariableSingle(s);
    typeVariableList(Collections.singletonList(s));
    wildcard(Collections.singletonList(s));
}
```

Right now I'm seeing new resolve errors on that file: `List` cannot be found, although this should be covered by the default `import module java.base`.

@mpalat  the NPE goes to you.

@jarthana do you have an idea what broke the module import for this implicitly declared class?

**Comment by jarthana** [comment]
> @jarthana do you have an idea what broke the module import for this implicitly declared class?

Found something strange. The same code works if I add a specific JDK to the build path. The error comes back when I use a JavaSE-23 mapped to the same specific JDK. Will investigate.

**Comment by jarthana** [comment]
> > @jarthana do you have an idea what broke the module import for this implicitly declared class?
> 
> Found something strange. The same code works if I add a specific JDK to the build path. The error comes back when I use a JavaSE-23 mapped to the same specific JDK. Will investigate.

Raised #2945 and assigned to @noopur2507 

@stephan-herrmann  can you confirm that the same is happening in your setup too?

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann can you confirm that the same is happening in your setup too?

While the workflows of changing compliance settings is certainly worth some more review, unfortunately, there's more to the problem. Right now I'm looking at a project, where in an explicit class a module import works, whereas an implicitly declared class in the same project cannot resolved `List` and `Collections`.

I'll take another look...

**Comment by stephan-herrmann** [comment]
OK, the module import thing is #2952.

Closing since the NPE has been fixed already.
