### ISSUE TITLE
NullPointerException when resolving lambda types

### ISSUE THREAD

**Issue by ADarko22** [eclipse-jdt/eclipse.jdt.core#2940]
When parsing the code below, and other variants, a NullPointerException is thrown in [LambdaExpression#isCompatibleWith](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/f32a0771c56c3ffadcef27bd33901a9f6e91396b/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/LambdaExpression.java#L915):

```
import java.util.function.Supplier;

public class Reproducer {

  public void configureBeanContext(final Object bean) {
    Context context = new Context();
    context.registerBean((Class<Object>) bean.getClass(), () -> bean);
  }

  class Context {
    private <T> void registerBean(Class<T> beanClass, Object... constructorArgs) {
      // not relevant
    }

    private <T> void registerBean(Class<T> beanClass, Supplier<T> supplier, Object... customizers) {
      // not relevant
    }
  }
}
```

It seems that passing a lambda, i.e., `() -> bean,` to a generic and overloaded method of a class, i.e., `Context#registerBean,` causes the NPE when the lambda target type is being resolved.

Please have a look at the [ecj-npe-in-sonar-java](https://community.sonarsource.com/t/ecj-npe-in-sonar-java-8-0-1-36337/124291) thread in the SonarSource Community forum for details about the original code snippet, which uses the Spring framework.

**Comment by stephan-herrmann** [comment]
Compiling the reproducer on the command line raises 2 warnings, but then succeeds.

Ergo we'll need more information about the context in which this is compiled. Version of ecj, compliance settings etc.

**Comment by jukzi** [comment]
The stacktrace given in https://community.sonarsource.com/t/ecj-npe-in-sonar-java-8-0-1-36337/124291 does not match the current version. Please test with newest eclipse version and post a up-to-date stacktrace here.

**Comment by ADarko22** [comment]
We are using [eclipse.jdt.core](https://github.com/eclipse-jdt/eclipse.jdt.core) version 3.37.0; unfortunately, we couldn't update to version 3.38.0 because there seem to be errors with parsing some cases of _unnamed variable & patterns_ specified in https://openjdk.org/jeps/456. I tested it with 3.38.0, and the issue is still present.

I just noticed that two days ago [version 3.39.0](https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core/3.39.0), did you use this new version to verify the absence of the reported error?

**Comment by srikanth-sankaran** [comment]
> We are using [eclipse.jdt.core](https://github.com/eclipse-jdt/eclipse.jdt.core) version 3.37.0; unfortunately, we couldn't update to version 3.38.0 because there seem to be errors with parsing some cases of _unnamed variable & patterns_ specified in https://openjdk.org/jeps/456. I tested it with 3.38.0, and the issue is still present.
> 

Has a defect been raised for this? If so do you have a reference ??

Thanks in advance. 


> 
> I just noticed that two days ago [version 3.39.0](https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core/3.39.0), did you use this new version to verify the absence of the reported error?

**Comment by ADarko22** [comment]
> Has a defect been raised for this? If so do you have a reference ??

No, we noticed that there was an implementation on master addressing some of those issues and so we decided to wait for the next release :)
