### ISSUE TITLE
Conflicting javadoc for TryStatement.resources() vs ASTConverter9Test.testBug497719_0002

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#2946]
Javadoc on TryStatement.resources() says "A resource is either a VariableDeclarationExpression or (since JLS9) a Name".
ASTConverter9Test.testBug497719_0002 tries to cast an item of the `resources()` list into a SuperFieldAccess and passes.

This is inconsistent; maybe the javadoc should be change to clarify "In a well-formed Java code, a resource is either a VariableDeclarationExpression or (since JLS9) a Name."

**Comment by noopur2507** [comment]
Moved to JDT Core as the involved classes/javadocs are from Core.

**Comment by mpalat** [comment]
@subyssurendran666 could you pleas pick this up once you are back from vacation?

**Comment by subyssurendran666** [comment]
@mpalat Could you please assign this ticket to me?

**Comment by subyssurendran666** [comment]
As per the [Language spec](https://docs.oracle.com/javase/specs/jls/se23/html/jls-14.html#jls-14.20.1), the resources must be AutoCloseable interfaces. 

Here, `try (y3; super.yz; this.y2; Y _ = new Y()) {`

`super.yz` & `this.y2` should not be acceptable.  The respective nodes are showing in the AST as well(see the screenshot). 

<img width="1298" alt="Screenshot 2024-10-14 at 7 02 53 PM" src="https://github.com/user-attachments/assets/f63b6634-b592-4f42-b80c-1861f4c31674">


Question: I believe this should be handled by the compiler, as it is not throwing any errors.

@mpalat @srikanth-sankaran could you please share you ideas ?

**Comment by mpalat** [comment]
> As per the [Language spec](https://docs.oracle.com/javase/specs/jls/se23/html/jls-14.html#jls-14.20.1), the resources must be AutoCloseable interfaces.
> 
> Here, `try (y3; super.yz; this.y2; Y _ = new Y()) {`

> 
> @mpalat @srikanth-sankaran could you please share you ideas ?

@subyssurendran666 resources defined inside the the try statement should be Autocloseable 

eg: try (Y y) - I don't see an issue with this code.

**Comment by subyssurendran666** [comment]
> > As per the [Language spec](https://docs.oracle.com/javase/specs/jls/se23/html/jls-14.html#jls-14.20.1), the resources must be AutoCloseable interfaces.
> > Here, `try (y3; super.yz; this.y2; Y _ = new Y()) {`
> 
> > @mpalat @srikanth-sankaran could you please share you ideas ?
> 
> @subyssurendran666 resources defined inside the the try statement should be Autocloseable
> 
> eg: try (Y y) - I don't see an issue with this code. - all the types are Y and is Autocloseable

Finally concluded that, this required JavaDoc modifications only. Thanks @mpalat
