### ISSUE TITLE
[23] Formatter Support for Implicit classes - investigate

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2977]
ref - https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2847#issuecomment-2323056290

**Comment by mpalat** [comment]
@mateusz-matela will you be able to take a look at this?

**Comment by mateusz-matela** [comment]
Yes, I should have some time to spare by the end of the month.

**Comment by mpalat** [comment]
Thanks @mateusz-matela !

**Comment by mateusz-matela** [comment]
Looks like no changes were needed, I just added a test confirming that it works.
