### ISSUE TITLE
[23] Markdown doc comments with codeblock don't parse  Javadoc tags afterwards

### ISSUE THREAD

**Issue by danthe1st** [eclipse-jdt/eclipse.jdt.core#2980]
If a JDK 23 Markdown documentation comment is using a Javadoc tag like `@param` after a codeblock, this parameter is not parsed.

For example, take a doc comment like this:
```java
/// This is a test Javadoc
/// ```java
/// test(42);
/// ```
/// @param a some parameter
```
and it results in the `@param a some parameter` not being parsed:
![image](https://github.com/user-attachments/assets/6b114f70-1e0d-4d0b-87ce-e3bc7a238f4c)

### Steps to reproduce
- Download Eclipse IDE for Java Developers 2024-09
- Install Java 23 support [from the Marketplace](https://marketplace.eclipse.org/content/java-23-support-eclipse-2024-09-433) (I used the Marketplace client)
- Set up a JDK 23 JDK in the `Installed JREs` menu
- Create a project with JDK 23
![image](https://github.com/user-attachments/assets/6cd3f93c-9260-4178-a027-510d759e9de0)
- Create the following class:
```java
package test;

public class Test {
	/// This is a test Javadoc
	/// ```java
	/// test(42);
	/// ```
	/// @param a some parameter
	void test(int a) {
		
	}
}
```
- Hover over the `test` method or open the `Javadoc` view and click on the said method:
![image](https://github.com/user-attachments/assets/5ecf1fc1-eccc-478e-ac6e-8139c496cac1)
![image](https://github.com/user-attachments/assets/bb1f64a8-4955-4441-aae7-766197ae0688)

From my testing, this seems to happen with any Javadoc tags after a codeblock. This does not happen with inline codeblocks. Normal markdown formatting (like `**bold**` text) seems to work after codeblocks.

**Comment by jarthana** [comment]
Reproduced and working on it.
