### ISSUE TITLE
SwitchPatternTests failing in I-builds

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.core#2982]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240918-0950/testresults/html/org.eclipse.jdt.core.tests.compiler_ep434I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html and

**Comment by jarthana** [comment]
I did a quick comparison between R4_33_maintenance and master (post merge) and I find some difference in .class output of the typeSwitch signature:

Here's at 22:
```
         8: invokedynamic #16,  0             // InvokeDynamic #0:typeSwitch:(Ljava/lang/Object;I)I
...
...
  #16 = InvokeDynamic      #0:#17         // #0:typeSwitch:(Ljava/lang/Object;I)I
  #17 = NameAndType        #18:#19        // typeSwitch:(Ljava/lang/Object;I)I
  #18 = Utf8               typeSwitch
  #19 = Utf8               (Ljava/lang/Object;I)I
```

And what's produced at 23:
 ```
        8: invokedynamic #16,  0             // InvokeDynamic #0:typeSwitch:(Ljava/lang/Integer;I)I
...
...
  #16 = InvokeDynamic      #0:#17         // #0:typeSwitch:(Ljava/lang/Integer;I)I
  #17 = NameAndType        #18:#19        // typeSwitch:(Ljava/lang/Integer;I)I
  #18 = Utf8               typeSwitch
  #19 = Utf8               (Ljava/lang/Integer;I)I
```

I don't yet know what causing this and if this is expected or not.

**Comment by jarthana** [comment]
Here's another interesting fact: The same code compiled with the post-merge compiler at compliance 22, runs OK with JRE 23. This explains why they were passing in Y builds and our setup.

**Comment by jarthana** [comment]
I believe this is related to the recent work in the BETA branch wrt to the primitive pattern, even though the code itself doesn't contain any primitive patterns. Re-assigning to @mpalat

**Comment by mpalat** [comment]
will take a look @jarthana

**Comment by stephan-herrmann** [comment]
This seems to be a corner case where a switch was legal already in Java 22, but in 23 ecj "re-classifies" it as applying JEP 455.

In my work concerning JEP 455 I assumed that it suffices to reject at 22- any switches that **need** JEP 455. Looks like we need additional checks for switches that swing both ways, in order to generate code that is compatible with the target JRE.

Here's what `SwitchBootstraps.typeSwitch()` has to say at 22 about that signature
> The type of the returned CallSite's method handle will have a return type of int. It has two parameters: the first argument will be an Object instance (target) and the second will be int (restart).

In 23ea this paragraph has not been updated, but from javac we learned that indeed other signatures are accepted.

**Comment by mpalat** [comment]
The current I build at the time of writing this comment is I20240919-1230 - Please note that this doesn't contain this fix.  Keeping this issue open until we confirm that the I Build has the tests fixed. 

re-opening to keep it open for such time

@MohananRahul meanwhile can you please trigger an I build once the current one finishes to get early results.

**Comment by srikanth-sankaran** [comment]
Is this still open ?

**Comment by jarthana** [comment]
I don't see the failure anymore. Can be closed.
