### ISSUE TITLE
[19] Revisit code generation for record patterns

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#300]
There  are couple of issues with the current implementation of record patterns in the area of code generation.

1. Explore the idea of using proxy methods to retrieve pattern variables from record/components. At the moment, we simply generate the code for this flatly. Using a proxy method might help us avoid lot of stack management issues. Also, I see match exception being thrown inside the proxy methods for pattern not matching. The spec doesn't specify anything about this, but this might be a worthwhile to consider.
2. In the case instanceof expression containing a record pattern, both the InstanceOfExpression and TypePattern produce and use a secret variable, so as to avoid stack issues. It might be possible to get rid of the secrete variables in the former. This way, we can get rid of some of the code that is doing similar things in both places.

This can be taken up during the next revision of this language feature.

**Comment by srikanth-sankaran** [comment]
@jarthana as discussed, I am studying this area and so I offer to work on this.
