### ISSUE TITLE
NON-NLS tag ignored for specific method references targeting a string literal

### ISSUE THREAD

**Issue by HannesWell** [eclipse-jdt/eclipse.jdt.core#3025]
In the following code the compiler issues a warning in the second line and does not consider NON-NLS tag.
`Non-externalized string literal; it should be followed by //$NON-NLS-<n>$`
```
List<String> list = List.<String>of();
list.removeIf("."::equals); //$NON-NLS-1$
list.removeIf(e -> ".".equals(e)); //$NON-NLS-1$
list.removeIf((Predicate<String>) "."::equals); //$NON-NLS-1$
```
In the third and fourth line no such warnings are emitted.

**Comment by srikanth-sankaran** [comment]
Please always supply full class that can be pasted - the committers will thank you :)

**Comment by srikanth-sankaran** [comment]
I'll take a look.

**Comment by HannesWell** [comment]
> Please always supply full class that can be pasted (with class headers, method headers, imports etc) - the committers will thank you :)

Sure, no problem. Assumed you would prefer a minimal snippet, but can of course also make it complete.

> I'll take a look.

Thanks.

**Comment by srikanth-sankaran** [comment]
> > Please always supply full class that can be pasted (with class headers, method headers, imports etc) - the committers will thank you :)
> 
> 
> 
> Sure, no problem. Assumed you would prefer a minimal snippet, but can of course also make it complete.
> 

A minimal snippet is minimal not only in terms of amount of code in it - but also minimal in how much work is needed in addition to reproduce the problem or write a junit test. So in that sense a complete but minimal snippet is best. Thanks. 

> 
> 
> > I'll take a look.
> 
> 
> 
> Thanks.

**Comment by srikanth-sankaran** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=443456 - Unfortunately that considered only lambda expressions and the bug has stayed dormant in the case of reference expressions for some ten years !!!

**Comment by HannesWell** [comment]
> See https://bugs.eclipse.org/bugs/show_bug.cgi?id=443456 - Unfortunately that considered only lambda expressions and the bug has stayed dormant in the case of reference expressions for some ten years !!!

Some issues stay long :O
Thanks a lot for fixing this now. I'll check tomorrows I-build to verify it works.
