### ISSUE TITLE
[Switch][Sealed types] Incorrect exhaustiveness check leads to MatchException at runtime

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#3031]
The following program compiles fine with ECJ while it should not, but crashes at runtime with a `MatchException`:

```
abstract sealed class J<T1, T2> permits X.S, A {}

final class A extends J<Integer, String> {}

public class X<T> {

	final class S<U> extends J<T, U> {}

 int testExhaustive(J<Integer, String> ji) {
   return switch (ji) { // Exhaustive!
     case A a -> 42;
   //case X<Integer>.S<String> e -> 42;
   };
 }
 public static void main(String[] args) {
   X<Integer>.S<String> xs = null;
   System.out.println(new X<Integer>().testExhaustive(new X<Integer>().new S<String>()));
 }
}
```

When run:

```
Exception in thread "main" java.lang.MatchException
	at X.testExhaustive(X.java:10)
	at X.main(X.java:17)
```

javac OTOH rejects the program with: `X.java:10: error: the switch expression does not cover all possible input values`

**Comment by srikanth-sankaran** [comment]
But this program, compiles and runs fine with ECJ but javac fails to compile it (javac behavior is incorrect)

```
abstract sealed class J<T1, T2> permits X.S, A {}

final class A extends J<Integer, String> {}

public class X<T> {

	final class S<U> extends J<T, U> {}

 int testExhaustive(J<Integer, String> ji) {
   return switch (ji) { // Exhaustive!
     case A a -> 42;
  case X<Integer>.S<String> e -> 42;
   };
 }
 public static void main(String[] args) {
   X<Integer>.S<String> xs = null;
   System.out.println(new X<Integer>().testExhaustive(new X<Integer>().new S<String>()));
 }
}
```

javac complains: `X.java:12: error: illegal start of type` at the `case X<Integer>.S<String> e -> 42;` line.
See that we are allowed to declare `X<Integer>.S<String> xs = null;` inside `main`

**Comment by srikanth-sankaran** [comment]
@stephan-herrmann - a second opinion that this is javac to failure to accept a valid program would be useful. TIA

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann - a second opinion that this is javac to failure to accept a valid program would be useful. TIA

I finally posted https://mail.openjdk.org/pipermail/compiler-dev/2024-November/028464.html
