### ISSUE TITLE
java.util.EmptyStackException: null when invoking a static method on a null string literal in a ternary operator

### ISSUE THREAD

**Issue by ADarko22** [eclipse-jdt/eclipse.jdt.core#3042]
Static methods invoked on a `null` string literal, returned from the second expression in a ternary operator, cause a  `java.util.EmptyStackException` during the AST creation. The following code reproduces the error:
```
public class Reproducer {
  
  void parseFailure(Reproducer o) {
    (o != null ? o : null).bar();
  }
  
  static void bar() { }
}
```

Note that this is a particular corner case that happens only in the scenario reported above. There is no failure in the following cases:

```
public class Reproducer {
  
  void parseSuccess(Reproducer o) {
    (o == null ? null : o).bar();
    ((Reproducer) null).bar();
    null.bar();
  }

  static void bar() { }
}
```

**Comment by srikanth-sankaran** [comment]
Any reason you must access the static method in a non-static way ??
