### ISSUE TITLE
[Enhancement] Add warnings for unused patterns

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#3051]
```java
public class Unused {

    public static void main(String[] args) {
        record R(int i, long l) {}
        
        R r = new R(1, 1);
        switch (r) {
        	case R(_, long l) -> {}
        	case R r2 -> {}
        }
    }
}
```
In the above example, `l` and `r2` are unused. Java 22 allows to use `_` for unnamed patterns. It would be useful to add a warning option for unused patterns with a quickfix to renamed them to `_`, similar to other "unused" warnings.

**Comment by srikanth-sankaran** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/567 which seems to have restricted itself only with type test patterns

**Comment by nlisker** [comment]
Thanks again for the fast fix!

Is a quick-fix (ctrl+1) option to "rename variable to _" available, or should I file a separate issue (and is it in jdt.core or jdt.ui)?

**Comment by srikanth-sankaran** [comment]
> Thanks again for the fast fix!
> 
> 
> 
> Is a quick-fix (ctrl+1 or on hover) option to "rename variable to _" available, or should I file a separate issue (and is it in jdt.core or jdt.ui)?

You are welcome! 

Yes, please - file a ticket against jdt.ui.

**Comment by nlisker** [comment]
Created https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1701.

By the way, are unused lamba variables also covered in this fix? They are also part of JEP 456, but I didn't mention them in my initial comment.

**Comment by srikanth-sankaran** [comment]
> Created [eclipse-jdt/eclipse.jdt.ui#1701](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1701).
> 
> By the way, are unused lamba variables also covered in this fix? They are also part of JEP 456, but I didn't mention them in my initial comment.

So, your fault ;-)

JEP 456 allows _ in multiple contexts - not all of it is covered by the fix:

```
The following kinds of declarations can introduce either a named variable (denoted by an identifier) or an unnamed variable (denoted by an underscore):

A local variable declaration statement in a block (JLS 14.4.2),
A resource specification of a try-with-resources statement (JLS 14.20.3),
The header of a basic for statement (JLS 14.14.1),
The header of an enhanced for loop (JLS 14.14.2),
An exception parameter of a catch block (JLS 14.20), and
A formal parameter of a lambda expression (JLS 15.27.1).
```

I'll raise a follow up ticket.

**Comment by srikanth-sankaran** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3054

**Comment by srikanth-sankaran** [comment]
> https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3054

This is integrated into master. 

Did I overlook anything ??

**Comment by nlisker** [comment]
Until jdt.ui adds support for it I wouldn't be able to test all of it. If all the cases in the JEP are covered, I assume that's all.
