### ISSUE TITLE
"Regression" in 3.39.0

### ISSUE THREAD

**Issue by I-Al-Istannen** [eclipse-jdt/eclipse.jdt.core#3064]
Hey,

feel free to close this issue if it is too ludicrous :D It is a bit of a long shot, but I find the behaviour a bit odd. Consider the following code (this is *all* JDT gets):
```java
public class Action<Request extends BroadcastRequest<Request>, ShardRequest> {
    private final Request request;

    protected ShardRequest newShardRequest(Request request) {return null;} // can also be omitted

    protected void performOperation(final int shardIndex) {
        ShardRequest shardRequest = newShardRequest(request);
        shardRequest.setParentTask(foobar);
    }
}
```

There are a few things to consider here, namely:
- `Request` is a recursive generic
- `request` is passed to `newShardRequest`
- The input of `setParentTask` is an undefined variable (otherwise the declaring type resolves to null even in older JDT versions)

In 3.38.0 and older versions of JDT, JDT was able to associate the receiver of the `shardRequest.setParentTask` MessageSend with the `shardRequest` variable (notice the `binding` there):
<img width="435" alt="grafik" src="https://github.com/user-attachments/assets/48df6721-f160-4fa5-a371-666f32faf8ca">

In 3.39.0 JDT instead produces the following (notice there no longer is a `binding`):
<img width="409" alt="grafik" src="https://github.com/user-attachments/assets/40798d08-214a-446a-bcb9-76258b916544">

It is a bit weird that JDT is no longer able to associate the method call with the variable defined above it. Is this something you are willing to look at or fix? Everything works correctly when all dependencies exist and JDT can resolve the correct methods. It only breaks with an incomplete classpath.

----

This is a reduction from https://github.com/INRIA/spoon/pull/5977, but we would also be fine with adjusting the test.

**Comment by iloveeclipse** [comment]
Could you please provide a simple self contained test showing the problem?

**Comment by I-Al-Istannen** [comment]
Am I allowed to show a 3 line spoon program or do I have to peel out the relatively complicated JDT scaffolding?
The relevant breakpoint would be `spoon/support/compiler/jdt/JDTTreeBuilder.java:1443`.

```java
import org.junit.jupiter.api.Test;
import spoon.Launcher;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.reference.CtExecutableReference;
import spoon.reflect.reference.CtTypeParameterReference;
import spoon.reflect.visitor.filter.TypeFilter;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;

public class Test {

	@Test
	public void testMWE() {
		CtClass<?> ctClass = Launcher.parseClass("""
			public class Action<Request extends BroadcastRequest<Request>, ShardRequest> {
			    private final Request request;
			
			    protected ShardRequest newShardRequest(Request request) {return null;} // can also be omitted
			
			    protected void performOperation(final int shardIndex) {
			        ShardRequest shardRequest = newShardRequest(request);
			        shardRequest.setParentTask(foobar);
			    }
			}
			""");
		for (var ref : ctClass.getElements(new TypeFilter<>(CtExecutableReference.class))) {
			if(ref.getSimpleName().equals("setParentTask")) {
				var typeRef = ref.getDeclaringType();
				assertInstanceOf(CtTypeParameterReference.class, typeRef);
				assertEquals("ShardRequest", typeRef.getSimpleName());
			}
		}
	}
}

```

**Comment by iloveeclipse** [comment]
Ideally it would be self contained test that uses no extra dependencies except JDT and JUnit :) 
This would increase a chance that this bug would be investigated & fixed.

**Comment by I-Al-Istannen** [comment]
Then I am out, I think. There is not really a chance I can rebuild the scaffolding for extracting JDTs internal API in a readable test case (and I have absolutely zero clue how it works).

**Comment by srikanth-sankaran** [comment]
You can alternately describe how one may see the problem starting with a plain SDK downloadble from [here](https://download.eclipse.org/eclipse/downloads/) - I paste the test case from above into a project and then what ? How do I resolve any build errors for imports etc ? Is it just a matter of downloading some jar files from somewhere and adding them to the build path ?

**Comment by stephan-herrmann** [comment]
I don't quite understand the expectation to begin with.

It looks like some of your code passes the content of one source file into the compiler, but that source code depends on several other classes which are nowhere in the picture.

To me this would imply that the source can be parsed OK, but resolving will inevitably fail, no matter which JDT version.

What am I missing?

**Comment by stephan-herrmann** [comment]
Shortcutting the invoking code I made the following experiment:
```
$ cat > Action.java
public class Action<Request extends BroadcastRequest<Request>, ShardRequest> {
                            private final Request request;

                            protected ShardRequest newShardRequest(Request request) {return null;} // can also be omitted

                            protected void performOperation(final int shardIndex) {
                                ShardRequest shardRequest = newShardRequest(request);
                                shardRequest.setParentTask(foobar);
                            }
                        }
$ ecj-HEAD.sh -23 Action.java 
----------
1. ERROR in /tmp/Action.java (at line 1)
        public class Action<Request extends BroadcastRequest<Request>, ShardRequest> {
                                            ^^^^^^^^^^^^^^^^
BroadcastRequest cannot be resolved to a type
----------
2. ERROR in /tmp/Action.java (at line 7)
        ShardRequest shardRequest = newShardRequest(request);
                                                    ^^^^^^^
Missing code implementation in the compiler
----------
2 problems (2 errors)
``` 

So, it does indeed trigger a bug :)

**Comment by I-Al-Istannen** [comment]
> To me this would imply that the source can be parsed OK, but resolving will inevitably fail, no matter which JDT version.

Yes, but it could still resolve the receiver of the method call `shardRequest.setParentTask(foobar);` to the local variable `shardRequest`. That does not need any knowledge about surrounding missing types and worked in 3.38.0.

> So, it does indeed trigger a bug :)
Neat! Maybe even the one causing the difference then :)

**Comment by stephan-herrmann** [comment]
@I-Al-Istannen in case there might be a "next time" reporting a similar issue: please have a look at https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3167/files#diff-22a10cb3aa942ca99d4b438d23446bfd91e802b55dfa4ba6030a8c92148f11ad for the kind of test that enables JDT devs to work on your issue without having to guess any setup.

**Comment by I-Al-Istannen** [comment]
Thank you! That looks useful :)
