### ISSUE TITLE
[Patterns] Inappropriate diagnostic with type test patterns

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#3074]
The following program generates a diagnostic: `Type String cannot be safely cast to Example<String>` that is misleading. This is not a situation that involves unsafe generic cast. This is a patent type incompatibility error. Javac reports: `error: incompatible types: String cannot be converted to Example<String>`.

```
class Example<T> {
	private void foo(String x) {
		if (x instanceof Example<String> es) {
			
		}
	}
}
```

**Comment by srikanth-sankaran** [comment]
If I add this statement to the snippet above:

`Example<String> es = x;`

I get: `Type mismatch: cannot convert from String to Example<String>` which is bang on.

**Comment by stephan-herrmann** [comment]
I added this test case in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3069/commits/f45e77e7e3d2c4f86bdf99d778752a3cfcde6f58 of #3069
