### ISSUE TITLE
[Patterns] Suspect classification of when as a modifier

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#3091]
The definitions of `org.eclipse.jdt.core.dom.Modifier.WHEN` and `org.eclipse.jdt.core.dom.Modifier.ModifierKeyword.WHEN_KEYWORD` look suspect. It seems DOM APIs treat `when` as a modifier.

This block of code in `org.eclipse.jdt.core.dom.ASTConverter.setModifiers(List, Annotation[], int)`:

```
					case TerminalTokens.TokenNameRestrictedIdentifierWhen:
						modifier = createModifier(Modifier.ModifierKeyword.WHEN_KEYWORD);
						break;
```

looks unreachable.

Are we stuck with these since these are APIs - @jarthana ??

**Comment by jarthana** [comment]
I see them when @noreference. So, they were out of bounds for clients. We can still remove or modify them, I suppose with api filters.
