### ISSUE TITLE
[Switch][Primitive type patterns] Unexpected operand error with switch pattern and widening unboxing conversion

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#3113]
Compiler throws an exception during codegen for the following code:

```
record Record<T extends Integer>(T t) {}
public class X {
	public static <T extends Integer> double convert(Record<T> r) {
		return switch (r) {
		case Record(double d) -> d;
		default -> 2;
		};
	}
}
```

The stack thrown:
java.lang.AssertionError: Unexpected operand at stack top
	at org.eclipse.jdt.internal.compiler.codegen.OperandStack.pop(OperandStack.java:110)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.d2i(CodeStream.java:719)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.generateImplicitConversion(CodeStream.java:2207)
	at org.eclipse.jdt.internal.compiler.ast.TypePattern.generateTestingConversion(TypePattern.java:149)
	at org.eclipse.jdt.internal.compiler.ast.TypePattern.generateCode(TypePattern.java:89)
	at org.eclipse.jdt.internal.compiler.ast.RecordPattern.generateCode(RecordPattern.java:279)
	at org.eclipse.jdt.internal.compiler.ast.CaseStatement.generateCode(CaseStatement.java:435)
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.statementGenerateCode(SwitchStatement.java:1048)
	at org.eclipse.jdt.internal.compiler.ast.SwitchExpression.statementGenerateCode(SwitchExpression.java:223)

**Comment by srikanth-sankaran** [comment]
Thanks @jarthana, I will follow up.

**Comment by srikanth-sankaran** [comment]
Hmm. Is this the right test case ? 

On master HEAD, I get `Record component with type T is not compatible with type double` (javac 23 compiles with preview enabled)

**Comment by srikanth-sankaran** [comment]
OK, reproduced, I needed to enable preview at project level. Not just workspace level.

**Comment by srikanth-sankaran** [comment]
This modified program compiles at 23 with preview enabled with javac and print 2.0 when run.

With ECJ master head, we get `Internal inconsistency: Inappropriate operand stack size encountered during translation` and then `java.lang.AssertionError: Unexpected operand at stack top`

```
record Record<T extends Integer>(T t) {
}

public class X {
	public static <T extends Integer> double convert(Record<T> r) {
		return switch (r) {
		case Record(double d) -> d;
		default -> 2;
		};
	}

	public static void main(String[] args) {
		System.out.print(convert(new Record(2)));
	}
}
```

**Comment by srikanth-sankaran** [comment]
Generated code:

```
  public static <T extends java.lang.Integer> double convert(Record<T>);
    descriptor: (LRecord;)D
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Signature: #17                          // <T:Ljava/lang/Integer;>(LRecord<TT;>;)D
    Code:
      stack=4, locals=5, args_size=1
         0: aload_0
         1: dup
         2: invokestatic  #18                 // Method java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
         5: pop
         6: astore_1
         7: iconst_0
         8: istore_2
         9: aload_1
        10: iload_2
        11: invokedynamic #24,  0             // InvokeDynamic #0:typeSwitch:(Ljava/lang/Object;I)I
        16: tableswitch   { // 0 to 0

                       0: 36
                 default: 60
            }
        36: aload_1
        37: checkcast     #28                 // class Record
        40: invokevirtual #30                 // Method Record.t:()Ljava/lang/Integer;
        43: invokevirtual #34                 // Method java/lang/Integer.intValue:()I
        46: d2i
        47: dstore_3
        48: goto          56
        51: iconst_1
        52: istore_2
        53: goto          9
        56: dload_3
        57: goto          63
        60: ldc2_w        #40                 // double 2.0d
        63: dreturn
        64: new           #42                 // class java/lang/MatchException
        67: dup_x1
        68: swap
        69: dup
        70: invokevirtual #44                 // Method java/lang/Throwable.toString:()Ljava/lang/String;
        73: swap
        74: invokespecial #50                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
        77: athrow
```

**Comment by srikanth-sankaran** [comment]
@bci 46 - we emit a d2i - hello! Shouldn't it be a i2d ??

**Comment by srikanth-sankaran** [comment]
@stephan-herrmann - can you take a look ? 

Here is a test that can be added to org.eclipse.jdt.core.tests.compiler.regression.PrimitiveInPatternsTest


```

   // https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3113
   // [Switch][Record patterns] Unexpected operand error with switch pattern and widening unboxing conversion
   public void testIssue3113() {
	   runConformTest(new String[] {
				"X.java",
				"""
				record Record<T extends Integer>(T t) {}
				public class X {
					public static <T extends Integer> double convert(Record<T> r) {
						return switch (r) {
						case Record(double d) -> d;
						default -> 2;
						};
					}
					public static void main(String[] args) {
						System.out.print(convert(new Record(2)));
					}
				}
				"""
			},
			"2.0");
   }
```

**Comment by srikanth-sankaran** [comment]
Debugging tip: To produce the class file, you can edit `org.eclipse.jdt.internal.compiler.codegen.CodeStream.createOperandStack(CompilerOptions)` and make it use the `NullStack`

**Comment by stephan-herrmann** [comment]
> What is the difference between `PrimitiveInPatternsTest.java` and `PrimitiveInPatternsTestSH.java` BTW ??

The first difference is in authorship :)

When I proposed a variant that loops over relevant types to increase test coverage, the other author was not quite happy with this (I assume for reasons of debugging), so we kept our tests apart. If you have an idea to improve this, I don't expect my initials to remain part of the class name :)

**Comment by mpalat** [comment]
> > What is the difference between `PrimitiveInPatternsTest.java` and `PrimitiveInPatternsTestSH.java` BTW ??
> 
> The first difference is in authorship :)
> 
> When I proposed a variant that loops over relevant types to increase test coverage, the other author was not quite happy with this (I assume for reasons of debugging), so we kept our tests apart. If you have an idea to improve this, I don't expect my initials to remain part of the class name :)

The other author is now fine with anything that works, neither does the other wants to retain his name - may the third author have it :)

**Comment by stephan-herrmann** [comment]
The existing test PrimitiveInPatternsTestSH.testInstanceof_widenUnbox() was "lucky" to use a conversion that doesn't require a bytecode conversion (short2int). This hid another instance of confused direction of conversion, by your's truly this time. :-/
