### ISSUE TITLE
Newly added tests fail in I-Builds while passing in CI test runs

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.core#3118]
The newly added tests:

org.eclipse.jdt.core.tests.compiler.regression.BatchCompilerTest_17.testGHI1774_Expression()
org.eclipse.jdt.core.tests.builder.IncrementalTests.testExhaustiveness()

fail in https://download.eclipse.org/eclipse/downloads/drops4/I20241019-0120/testResults.php

These don't fail in CI runs nor locally. Perhaps a specific version of JDK is required to see the problem,

**Comment by srikanth-sankaran** [comment]
@mpalat  - FYI. I am working on this.

**Comment by srikanth-sankaran** [comment]
And they pass locally too. @mpalat can you review these two tests to see if anything is amiss - I may need another pair of eyes looking over them

**Comment by HannesWell** [comment]
I have no idea about these tests, but in general the difference between CI builds an I-builds are that
- in I-builds the bundles and therefore the class-files and resources are usually packed into jars, in CI and loclal tests the bundles are usually directories
- in I-builds more bundles are potentially available in the application, in CI-builds usually only the minimal dependency closure is present.

Maybe this helps you.

**Comment by srikanth-sankaran** [comment]
Thanks @HannesWell - That unfortunately doesn't shed any light at least for me.

Let me ask @jarthana @mpalat and @stephan-herrmann to take a look to see what I am missing

**Comment by mpalat** [comment]
> And they pass locally too. @mpalat can you review these two tests to see if anything is amiss - I may need another pair of eyes looking over them

sure @srikanth-sankaran

**Comment by mpalat** [comment]
@srikanth-sankaran - very easily reproducible locally by running it on a Java 17 JDK. I could reproduce it on my machine.

**Comment by srikanth-sankaran** [comment]
Duh! Thanks. I'll follow up.

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran - testExhaustiveness() and testGHI1774_Expression() fail by running on a Java 17 JDK. I could reproduce the failures on my machine. I believe the minimum required. version for these is 18. Of course, with a 21 both pass. can you try with a 17 JDK?
> 
> [note: why did I use 17? - because the failures were in org.eclipse.jdt.ui.tests_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html and org.eclipse.jdt.core.tests.builder_ep434I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

Thanks a lot Manoj.
