### ISSUE TITLE
[24] JEP 493: Linking Run-Time Images without JMODs

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#3139]
Ref: https://openjdk.org/jeps/493

Summary
Reduce the size of the JDK by approximately 25% by enabling the jlink tool to create custom run-time images without using the JDK's JMOD files. This feature must be enabled when the JDK is built; it will not be enabled by default, and some JDK vendors may choose not to enable it.

**Comment by jarthana** [comment]
OK, the way I see it, this is for the JDK. However, this also has some impact for the compiler, in the sense that this will pave way for getting rid of the JMOD libraries at some point. We will keep the code that supports for the time being but at some point, when there are no JDKs with JMOD, we can remove them. I am closing this for now.
