### ISSUE TITLE
ecj: The import org.eclipse.jdt.core.Signature cannot be resolved

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#314]
![image](https://user-images.githubusercontent.com/51790620/184825762-e646de90-1786-4482-ba42-24f4f7804959.png)
Bug 513880 - [null][external] JDT null analysis "Illegal format in annotation" exception is ambiguous and unhelpful (#310)
@stephan-herrmann

**Comment by iloveeclipse** [comment]
@stephan-herrmann : would you be able to fix that till M3 (this Thursday)?

**Comment by stephan-herrmann** [comment]
Thanks for catching this. I'll attend to this later today.

**Comment by iloveeclipse** [comment]
We should really try to make https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181 in 4.26.

**Comment by merks** [comment]
I noticed this too just now.  But others are even faster!  🚤

**Comment by jukzi** [comment]
Und das auf dem selben Längengrad ;-)

**Comment by stephan-herrmann** [comment]
> We should really try to make https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181 in 4.26.

sounds good.

For the time being I'm happy that people actually check out the validation project, and pay more attention to it than I did myself ;p

**Comment by merks** [comment]
All clean again.  Thanks.   😄
