### ISSUE TITLE
Wrong error line for "No enclosing instance of type ___ is accessible" when using method reference

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#3207]
I looked at #3194 and #3153, but I don't think they fix the following in Eclipse 4.33:
```java
package eclipse;

import java.util.List;

public final class EnclosedInstance {

	private static Runnable c = () -> {
//		new Indicator("s");
		List.of("a", "a").forEach(Indicator::new);
	};
	
	private class Indicator  {
		
		Indicator(String s) {}
	}
}
```
The compiler complains (correctly) that "No enclosing instance of type EnclosedInstance is accessible. Must qualify the allocation with an enclosing instance of type EnclosedInstance (e.g. x.new A() where x is an instance of EnclosedInstance)." However, it puts the error on line 1 and underlines the `p` in `package`:
![image](https://github.com/user-attachments/assets/6f49caf2-7404-4a14-b8ed-915c7b9ac580)

javac correctly identifies the line:
```
EnclosedInstance.java:9: error: invalid constructor reference
		List.of("a", "a").forEach(Indicator::new);
		                          ^
  cannot access constructor Indicator()
    an enclosing instance of type EnclosedInstance is not in scope
1 error
```

Note that if you uncomment the normal constructor call then the erroneous line (and the red squiggly) are displayed correctly, so I surmised that the problem is the method reference.

**Comment by stephan-herrmann** [comment]
> However, it puts the error on line 1 and underlines the `p` in `package`

Simple cause: when `ReferenceExpression.generateImplicitLambda(BlockScope, CodeStream, boolean)` generates an `AllocationExpression` it fails to set source positions.
