### ISSUE TITLE
org.eclipse.jdt.core.tests.builder requires a version bump

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-jdt/eclipse.jdt.core#322]
<html>
<body>

org.eclipse.jdt.core.tests.builder | 3.11.200.v20220405-0748 | 3.11.200.v20220719-0906
-- | -- | --

</body>
</html>

**Comment by srikanth-sankaran** [comment]
@jarthana - Does this have to stay open ??!

**Comment by jarthana** [comment]
> @jarthana - Does this have to stay open ??!

Not at all.
