### ISSUE TITLE
[24] JEP 450: Compact Object Headers (Experimental)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#3236]
ref: https://openjdk.org/jeps/450

Summary
Reduce the size of object headers in the HotSpot JVM from between 96 and 128 bits down to 64 bits on 64-bit architectures. This will reduce heap size, improve deployment density, and increase data locality.

**Comment by srikanth-sankaran** [comment]
@mpalat you are just cluttering/polluting our defect database with these Hotspot VM specific work :)

**Comment by mpalat** [comment]
> @mpalat you are just cluttering/polluting our defect database with these Hotspot VM specific work :)

@srikanth-sankaran - That's one way of looking at the world :) - Idea is that we take a look at each and every feature exhaustively so that we don't "miss" any related work -We took this decision sometime back.

**Comment by srikanth-sankaran** [comment]
> > @mpalat you are just cluttering/polluting our defect database with these Hotspot VM specific work :)
> 
> @srikanth-sankaran - That's one way of looking at the world :) - Idea is that we take a look at each and every feature exhaustively so that we don't "miss" any related work -We took this decision sometime back.

Ok, so far as there is method behind it :)

**Comment by mpalat** [comment]
Closing
