### ISSUE TITLE
[24] JEP 478: Key Derivation Function API (Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#3238]
ref: https://openjdk.org/jeps/478
Summary
Introduce an API for Key Derivation Functions (KDFs), which are cryptographic algorithms for deriving additional keys from a secret key and other data. This is a [preview API](https://openjdk.org/jeps/12).

**Comment by mpalat** [comment]
Note: Need to reconfirm this check with ecj before closing -

Compile the program with javac --release 24 --enable-preview Main.java and run it with java --enable-preview Main; or,

When using the [source code launcher](https://openjdk.org/jeps/330), run the program with java --enable-preview Main.java; or,

**Comment by stephan-herrmann** [comment]
> Note: Need to reconfirm this check with ecj before closing -
> 
> Compile the program with javac --release 24 --enable-preview Main.java and run it with java --enable-preview Main; or,
> 
> When using the [source code launcher](https://openjdk.org/jeps/330), run the program with java --enable-preview Main.java; or,

I have no idea what you are planning to check here ...

**Comment by mpalat** [comment]
> 
> I have no idea what you are planning to check here ...

neither do I at this point :) - it seemed a little strange that this was mentioned explicitly for this JEP and hence I thought it's better to make note of this comment.

**Comment by mpalat** [comment]
Not affecting JDT - closing
