### ISSUE TITLE
Default tick for 'public static void main(String[] args) {}' when creating a new Java class

### ISSUE THREAD

**Issue by arunvel-01** [eclipse-jdt/eclipse.jdt.core#3271]
I would like to request a feature enhancement for the Eclipse IDE. Currently, when creating a new Java class, there’s an option to automatically generate a public static void main(String[] args) {} method via a checkbox. It would be convenient if this checkbox could be ticked by default, as many Java classes require a main method, especially for beginner programmers and small projects.

When creating a new Java class, the checkbox for generating public static void main(String[] args) {} is selected by default.

**Comment by stephan-herrmann** [comment]
> [...] many Java classes require a main method, especially for beginner programmers and small projects.

That last part is essential. In large projects there can be many thousands of classes without a single main method.

With this, your proposal could be reshaped to create a beginners' or playground mode. Do you have more ideas what might be suitable settings for such a mode?

On a different note, recent Java version have an option (currently as a preview feature) to create main methods with less ceremony, so having it pre-generated from the wizard will lose importance, see e.g., https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2902

**Comment by arunvel-01** [comment]
Thanks for the suggestion! I agree that a beginner or playground mode would be very helpful for newcomers to Java. To add to that, perhaps we could introduce a project or package-level setting in the setup wizard. For example, if a user opts to create a simple project, the wizard could automatically check a box to include a basic main method, reducing the initial setup steps. For more complex projects, the user could uncheck this option, allowing for more advanced structures without needing a main method. This would provide flexibility and a smoother transition for users as they move from smaller projects to larger, modular ones. With recent Java updates simplifying main methods, having a tailored setup experience could help accommodate both beginner and advanced needs.

**Comment by venkateshkona3456-oss** [comment]
Hello,
I am a beginner and interested in working on this issue.
Can you please guide me on how to start?

Thank you!

**Comment by trancexpress** [comment]
Hi, the contribution guide for JDT is here: https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md
