### ISSUE TITLE
Annotation-based analysis breaks when annotations are not on the build path

### ISSUE THREAD

**Issue by basilevs** [eclipse-jdt/eclipse.jdt.core#3278]
# Test steps
Create a class in an Eclipse plugin:

```
import java.io.Closeable;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.eclipse.jdt.annotation.NotOwning;
import org.eclipse.jdt.annotation.Owning;

public class TestNotOwning implements Closeable {
    private final List<Closeable> toClose = new ArrayList<>();

    @NotOwning
    public <T extends Closeable> T register(@Owning
    T closeable) throws IOException {
        closeable.close();
        return closeable;
    }

    @Override
    public void close() throws IOException {
        for (Closeable closeable : toClose.reversed()) {
            closeable.close(); // Ignore error handling for this demonstration
        }
    }

}
```
Enable annotation analysis and ensure that:
```
try (TestNotOwning t = new TestNotOwning()) {
    var a = new Closeable() {} ; // produces warning
    var b = t.register(new Closeable() {} ); // produces no warning
}
```

Create a fragment of the same plugin. Enable annotation analysis. Try same sample:
```
try (TestNotOwning t = new TestNotOwning()) {
    var a = new Closeable() {} ; // produces warning
    var b = t.register(new Closeable() {} ); // produces warning
}
```
## Expected result
no warnings for line `var b = ...` or a warning requesting a missing dependency

Workaround: add an explicit dependency on `org.eclipse.jdt.annotation` in the fragment.

For some reason annotation analysis ignores implicit dependency on `org.eclipse.jdt.annotation` from host plugin.

**Comment by stephan-herrmann** [comment]
I'll try to have a look during the next release cycle.

If there is a bug indeed, it will likely be an issue of PDE, because JDT knows nothing of bundles, fragments and all that. All that JDT works on is a readily resolved classpath.

**Comment by basilevs** [comment]
JDT annotations are absent from classpath (as they are not used in the fragment).

**Comment by stephan-herrmann** [comment]
> JDT annotations are absent from classpath (as they are not used in the fragment).

We'll have to check: shouldn't PDE implicitly put them on the classpath? Do you see them when you expand "Plug-in Dependencies" in the Package Explorer?

**Comment by basilevs** [comment]
Attached is a reproducer for pure JDT. A "client" project has no direct dependency on annotations package, but still produces the potential resource leak warning.
[notowning_reproducer.zip](https://github.com/user-attachments/files/17692420/notowning_reproducer.zip)

**Comment by stephan-herrmann** [comment]
> Attached is a reproducer for pure JDT. A "client" project has no direct dependency on annotations package, but still produces the potential resource leak warning. [notowning_reproducer.zip](https://github.com/user-attachments/files/17692420/notowning_reproducer.zip)
> 
> To reproduce, import the whole ZIP (three projects) into workspace, compile, check problem view.
> 
> Adding a dependency makes little sense (as annotations are not used in this project) but fixes the issue.

I'm no longer sure which exact bug you are concerned about.

From the initial description I understood you had problems with a fragment that didn't see the dependency of its host.

The latest comment seems to point in a different direction, viz. that you expect compilation of a client to understand the semantics of `@NotOwning` without having access to that annotation.

Which issue(s) do  you want to report? If it's two issues let's capture them in separate issues please.

**Comment by basilevs** [comment]
These are same issues - I did not realize, that any kind of "access" to annotations is required if these annotations are not referenced anywhere in a project.
I think, it would be nice for compiler to output a warning if annotations analysis is enabled, but annotations are not available.

**Comment by stephan-herrmann** [comment]
> Additional confusion exists, if class TestNotOwning is resolved to a `SourceTypeBinding` (as it may happen during reconcile), where the `UnresolvedReferenceBinding` does **not** have it's fully qualified name.

This actually seems to be the main problem. At least this is the only recipe by which I could create a failing test.

@basilevs may I assume that you, too, had both projects open in your workspace, rather than depending on TestNotOwning from a jar / class file?

**Comment by stephan-herrmann** [comment]
I still believe that a client should "see" all parts of an API which it uses.
If you call a method with this signature:
```
@Owning Bar doit(@NonNull Foo input) 
```
then all types `Owning`, `Bar`, `NonNull` and `Foo` contribute to the contract. If any of the types is not visible to the client you cannot be sure if the contract is fulfilled. I regularly recommend that a plug-in using annotations to specify its contracts should simply re-export the annotation artifact and all clients will be happy.

In this light the changes in #3355 should be seen as band-aids to help working with an incomplete setup. I cannot guarantee that this band-aid is complete, as there could be other paths where annotations enter compilation.

**Comment by stephan-herrmann** [comment]
One more issue is involved: when trying to resolve `org.eclipse.jdt.annotation.NotOwning` we detect that the current **module** has no package `org.*` among the packages it can access. I'm not sure if handling all this is worth it.

The module thing can be resolved by adding
```
	requires static org.eclipse.jdt.annotation;
```

**Comment by basilevs** [comment]
> @basilevs may I assume that you, too, had both projects open in your workspace, rather than depending on TestNotOwning from a jar / class file?

There were no JAR files in workspace. Compilation necessarily produces class files, but that process is opaque to the user. From user's POV, they just create projects, link some of them, compile and see the warning, no class files or JARs involved.

**Comment by basilevs** [comment]
> I regularly recommend that a plug-in using annotations to specify its contracts should simply re-export the annotation artifact and all clients will be happy.

In my codebase reexports are forbidden, as they are a source of redundant implicit dependencies. While in this case one might argue, that dependendency is no redundant, it actually is, especially for projects without leak analysis.

**Comment by stephan-herrmann** [comment]
The experiment #3355 is incomplete, and I don't see a clean solution to evaluate an annotation that cannot be resolved. Indeed this affects only dependencies between workspace projects, dependencies referenced in binary form are not affected. 

Instead of working with phantom annotation types I'll revisit the options to raise an error when annotation based resource analysis is enabled, but no such annotations are on the build path.

I'm sure we discussed this already for null-annotations, so I'll have to search that prior art.

In the end it's a project's decision, either: fully ignore `@Owning` and `@NotOwning` or: enable this analysis and supply the necessary annotation types on the build path, one way or other.

**Comment by stephan-herrmann** [comment]
> Instead of working with phantom annotation types I'll revisit the options to raise an error when annotation based resource analysis is enabled, but no such annotations are on the build path.
> 
> I'm sure we discussed this already for null-annotations, so I'll have to search that prior art.

At the project level we only show an error when a user configures the annotation names and when those names cannot be resolved. Errors are shown in that dialog only.

I was thinking of raising a build path problem, but the compiler cannot do this (it doesn't know about things like projects etc.). And the builder, OTOH, shouldn't handle such specific problems on its own.

Instead #3374 implements a new warning that will be raised at the usage site, when an element (method or field) is referenced, that has an unresolved annotation, and judging by the simple name this could possibly be one of the configured owning annotations.

**Comment by stephan-herrmann** [comment]
One more comment which I wrote some days ago but forgot to submit, doing so now for posterity:

-------------
For the related case of null annotations it was https://bugs.eclipse.org/483566 which
1. clarified that annotations need not be present when consuming API **in binary form**
2. implemented the preference dialog for annotation names, where indeed an error is raised when a required annotation type cannot be found.

Both items have been copied to the case of owning-annotations. Unfortunately, the error in the dialog is shown only when the user clicks the "Configure ..." link. If names are left untouched at their defaults, no such error is shown.
