### ISSUE TITLE
[DOM] Via "Double-Checked Locking" idiom lazy initialized fields have to be "volatile"

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-jdt/eclipse.jdt.core#3322]
In "org.eclipse.jdt.core.dom", the "Double-Checked Locking" idiom is used multiple times, but without the corresponding lazy initialized fields being "volatile".

A field that is lazy initialized via the "Double-Checked Locking" idiom has to be "volatile" to be multithreaded-safe. Otherwise, another thread may get a partial initialized field since the initialization of a non-volatile non-primitiv field is not guaranteed to be atomic.

The double-check idiom wasn't guaranteed to work until Java 1.5. Since Java 1.5 the "volatile" keyword ensures that multiple threads handle the singleton instance correctly. In "org.eclipse.jdt.core.dom", at least some of the via the double-check idiom lazy initialized fields have been introduced before Java 1.5.

See:
- https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java
- http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

For example, org.eclipse.jdt.core.dom.ForStatement:

```
public class ForStatement extends Statement {
	// ...
	private Statement body = null;
	// ...
	public Statement getBody() {
		if (this.body == null) {
			// lazy init must be thread-safe for readers
			synchronized (this) {
				if (this.body == null) {
					preLazyInit();
					this.body = new Block(this.ast);
					postLazyInit(this.body, BODY_PROPERTY);
				}
			}
		}
		return this.body;
	}
	// ...
}
```

... has to be (with "volatile" and with "localRef" to access the "volatile" field only once for better performance):

```
public class ForStatement extends Statement {
	// ...
	private volatile Statement body = null;
	// ...
	public Statement getBody() {
		Statement localRef = this.body;
		if (localRef == null) {
			// lazy init must be thread-safe for readers
			synchronized (this) {
				localRef = this.body;
				if (localRef == null) {
					preLazyInit();
					this.body = localRef = new Block(this.ast);
					postLazyInit(this.body, BODY_PROPERTY);
				}
			}
		}
		return localRef;
	}
	// ...
}
```

Ref: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573404

**Comment by subyssurendran666** [comment]
@mpalat @jarthana could you please share your insights on this?

**Comment by carstenartur** [comment]
Here you see a list of affected classes in jdt.core

https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/171945

**Comment by subyssurendran666** [comment]
> Here you see a list of affected classes in jdt.core
> 
> https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/171945


Thanks, @carstenartur . I came across your earlier comment on Bugzilla. First, I would like to confirm whether this is required or not.

**Comment by jukzi** [comment]
see javadoc in 
https://github.com/eclipse-jdt/eclipse.jdt.core/blame/6b53bf4250c8412380003f04f4035f05a38f3554/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/ASTNode.java#L2855
how it has to be used.

**Comment by jarthana** [comment]
> @mpalat @jarthana could you please share your insights on this?

I don't yet know. But I think Sarika's question from here is still valid and needs to be answered:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=573404#c4

**Comment by carstenartur** [comment]
While I agree that Sarika's question is valid and the answer would shed some light on important consequences I can only think of two different outcomes:

1) the double locking idiome used here never has been needed and should be removed. It does not work this way anyway.

2) the double locking idiome used here is broken and fails to lock in multithreading situations. It needs a fix. This might cause difficult to find issues.

There is no option 3) to have advantages to keep it like it is, imho.

**Comment by jukzi** [comment]
I don't what is unclear or why this issue is filed.

> question from here is still valid

see bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=58314 for a bug report where it AST was used from different threads and it did throw a NPE and therefore they added the (wrong) double checking idiom. 
The examples given in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3322#issue-2667800002 are not valid. Both - neither the one with or without volatile. I already fixed the ForStatement with a8bb9ad04a8363e60b2badb7b2f14499302ce8ca and if you find any wrong usage just fix it. But i am not aware of any left over. org.eclipse.jdt.core.dom.ForStatement.body is already volatile since 8f4278164ada650f34550627f48a2d9b4cf66d36!

**Comment by jarthana** [comment]
> I don't what is unclear or why this issue is filed.
> 
> > question from here is still valid
> 
> see bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=58314 for a bug report where it AST was used from different threads and it did throw a NPE and therefore they added the (wrong) double checking idiom. The examples given in [#3322 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3322#issue-2667800002) are not valid. Both - neither the one with or without volatile. I already fixed the ForStatement with [a8bb9ad](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/a8bb9ad04a8363e60b2badb7b2f14499302ce8ca) and if you find any wrong usage just fix it. But i am not aware of any left over. org.eclipse.jdt.core.dom.ForStatement.body is already volatile since [8f42781](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/8f4278164ada650f34550627f48a2d9b4cf66d36)!

OK, I just checked the code (and thanks) and looks like indeed this is fixed. @subyssurendran666 if you still can find any such cases without volatile, then you can raise a PR for those.

**Comment by carstenartur** [comment]
So do you think 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=573404#c4
should be kept open?

**Comment by jukzi** [comment]
> So do you think
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=573404#c4
> should be kept open?

The task is done. I don't know if anybody cares about the status of bugzilla anymore, i treat it as read only since we moved to github.

**Comment by jarthana** [comment]
OK, just for the record, I have marked the aforementioned bug as resolved.
