### ISSUE TITLE
[24] JEP 496: Quantum-Resistant Module-Lattice-Based Key Encapsulation Mechanism

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#3362]
ref: [JEP 496
](https://openjdk.org/jeps/496)
Summary
Enhance the security of Java applications by providing an implementation of the quantum-resistant Module-Lattice-Based Key-Encapsulation Mechanism (ML-KEM). Key encapsulation mechanisms (KEMs) are used to secure symmetric keys over insecure communication channels using public key cryptography. ML-KEM is designed to be secure against future quantum computing attacks. It has been standardized by the United States National Institute of Standards and Technology (NIST) in [FIPS 203](https://csrc.nist.gov/pubs/fips/203/final).

**Comment by mpalat** [comment]
Does not affect JDT - resolving.

**Comment by srikanth-sankaran** [comment]
"Quantum-Resistant Module-Lattice-Based Key Encapsulation Mechanism" ?? This sounds like something Sheldon Cooper would reel off 😆
