### ISSUE TITLE
Incorrect control flow analysis causes statement subsequent to a switch statement to be flagged unreachable under some circumstances

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#3376]
javac from Java 21 compiles the code below fine.
ecj starting from a589ad26776cdcc6ed940def15e7591b6e7e67ba reports "Unreachable code" compilation error on return.

```
public class SwitchTest {
    String unreachableCode(String arg) {
        String result;
        switch (arg) {
            case "a" -> {
                result = "A";
            }
            default -> throw new RuntimeException(arg);
        }
        return result;      // <- ecj reports "Unreachable code"
    }
}
```

Both compiler agree that the code below is fine:
```
public class SwitchTest {
    String unreachableCode(String arg) {
        String result;
        switch (arg) {
            case "a" -> {
                result = "A";
                break;       // <- this makes ecj happy
            }
            default -> throw new RuntimeException(arg);
        }
        return result;
    }
}
```

For the "old style" switch both ecj and javac agree that the return is unreachable:

```
public class SwitchTest {
    String unreachableCode(String arg) {
        String result;
        switch (arg) {
            case "a" : {
                result = "A";
            }
            default : throw new RuntimeException(arg);
        }
        return result;
    }
}
```

I assume ecj has a regression with a589ad26776cdcc6ed940def15e7591b6e7e67ba, but I haven't checked what JLS says here.
@srikanth-sankaran : please check.

**Comment by srikanth-sankaran** [comment]
Thanks for the report. I can see where the problem originates from. The commit comment says: `Eliminate the hack to inject synthetic `BreakStatement` in label rule switch blocks. Enhance the code generator to handle these explicitly.` 

To remove the earlier kludgy implementation, it is not enough to _code generator is enhanced to handle these explicitly_ - we should also make flow analysis's dependence on the earlier kludge is delinked. 

PR will follow shortly.
