### ISSUE TITLE
Retire org.eclipse.jdt.annotation_v1 from Github repo

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.core#3399]
I have been asked by @akurtakov to open this issue. org.eclipse.jdt.annotation_v1 is not part of the build anymore and now also require Java 8 similar to org.eclipse.jdt.annotation.

So maybe also retire this code from master?

**Comment by vogella** [comment]
@akurtakov please review

**Comment by jarthana** [comment]
This should be OK since we removed support for < 1.8 in compiler. But would like to hear from @stephan-herrmann .

**Comment by stephan-herrmann** [comment]
> This should be OK since we removed support for < 1.8 in compiler. 

That alone doesn't make o.e.j.annotation_v1 useless :), but retiring was mostly completed already before ... see also https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3400#issuecomment-2549185836
