### ISSUE TITLE
Completion broken after switch-case-reduce

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#341]
There is no completion proposal anymore in some cases.

minimal reproducer i found:
```
import java.util.stream.IntStream;

public class CompletionBug  {	
	//completion here OK
	public void a() {
		switch (1) {
		case 1:
		}
	}
	//completion here NOK
	public void b() {
		Object o = IntStream.of(2).reduce((c, d) -> 3);
		o.toString();
	}
	//completion here NOK	
}
```
![image](https://user-images.githubusercontent.com/51790620/186697212-9a965070-0102-40f8-8aa3-400a930fbf58.png)
![image](https://user-images.githubusercontent.com/51790620/186697372-39055d60-f3d0-48ad-b79c-0885caafb338.png)

delete any code inside the methods=> completion in the class body cured:
![image](https://user-images.githubusercontent.com/51790620/186697984-beaaa578-08f1-4b5a-bd46-3fa3c473aa3c.png)

**Comment by jarthana** [comment]
@vik-chand Can you please take a look at this?

**Comment by lukeu** [comment]
I had also logged a regression with code-assist in `switch`, in bugzilla:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=576934

Due to the migration, should I perhaps include the details here as an additional test case? (Or is that link sufficient?)

**Comment by jukzi** [comment]
seems to be fixed - can not reproduce anymore
