### ISSUE TITLE
[null analysis]  `animal instanceof Dog dog` fails to assume dog as @NonNull

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#350]
named instance of (eg `animal instanceof Dog dog`) do not assume the new variable (`dog` here) is `@NonNull`. It leads to false warning reports with null analysis.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : do you have some time/interest?

**Comment by stephan-herrmann** [comment]
Interest? Sure. Time? Let's see. 
Might also be a good learning issue for someone new to this aspect of the code :)

BTW, we already have two bugs for this: 
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=571933
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=577181

**Comment by stephan-herrmann** [comment]
GitHub forgot to close this issue, when #351 got merged
