### ISSUE TITLE
@NonNull is not assumed for instanceof variable

### ISSUE THREAD

**Issue by frankbenoit** [eclipse-jdt/eclipse.jdt.core#360]
In that snippet:

````java
    private void func( Object o ) {
        if (o instanceof @NonNull String text) {
            // text is not evaluated as non-null if the @NonNull is missing
        }        
    }
````

The annotation shall not be needed, because instanceof is a null check as well.

**Comment by frankbenoit** [comment]
(https://github.com/eclipse-jdt/eclipse.jdt.core/blob/7eeb9b4342d4d83f3a5a1d078a4e4dff0ab83bb2/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/InstanceOfExpression.java#L94)

Should it be `markAsDefinitelyNonNull` in this location?

**Comment by frankbenoit** [comment]
@stephan-herrmann can you tell, would this be the right way?

**Comment by stephan-herrmann** [comment]
That looks amazingly similar to #351  :)
