### ISSUE TITLE
[19] Pattern variable declared in a guard containing instanceof expression is not visible in the case block

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#371]
Consider this code:

		switch (r) {
			case Rectangle r1 when (r instanceof (Rectangle(ColoredPoint upperLeft2, ColoredPoint lowerRight) r2)):
			System.out.println(r2); // error reported here
			break;
			default :
				break;
		} 

This code should be allowed but ecj reports an error. Looks like the pattern variable doesn't make it to the case statement and hence to the block.

**Comment by srikanth-sankaran** [comment]
@jarthana - is this still open ? Looks like it is fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/372 ??

**Comment by jarthana** [comment]
Yes, this should be closed.
