### ISSUE TITLE
[switch-expression] Invalid compiler error with switch expression

### ISSUE THREAD

**Issue by pykmalion** [eclipse-jdt/eclipse.jdt.core#377]
Looks like there may be a JDT bug related to processing java 12 switch expressions. 
JDT is showing a cryptic error whenever there is a call to a throwing method in the finally block inside a switch case.
`javac` does not seem to have an issue with it.

Here's a simplified example that reproduces this error:
```java
public class BugTest {

  enum TestEnum {
    A, B;
  }

  @SuppressWarnings("unused")
  private int switcher(final TestEnum e) throws Exception {
    return switch (e) {
      case A -> 0;
      case B -> {
        try {
          yield 1;
        } finally {
          throwingFn();
        }
      }
    };
  }

  private void throwingFn() throws Exception {}
}
```

This results in:
```
[ERROR] COMPILATION ERROR : 
[ERROR] .../BugTest.java:[28] 
        private int switcher(final TestEnum e) throws Exception {
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SANITY CHECK: Invalid attribute for exception attribute for switcher
```

**Comment by stephan-herrmann** [comment]
As the string "SANITY CHECK" indicates, an internal assertion of the compiler implementation was violated.

The immediate cause are imbalanced invocations of `ExceptionLabel.placeStart()` and `placeEnd()`. 

If I may hazard a guess the following invocation looks fishy:
```
ExceptionLabel.placeEnd() line: 53	
TryStatement(SubRoutineStatement).exitAnyExceptionHandler() line: 54	
TryStatement.exitAnyExceptionHandler() line: 485	
TryStatement.generateSubRoutineInvocation(BlockScope, CodeStream, Object, int, LocalVariableBinding) line: 1048	
YieldStatement.generateExpressionResultCodeExpanded(BlockScope, CodeStream) line: 154	
YieldStatement.generateCode(BlockScope, CodeStream) line: 187	
Block.generateCode(BlockScope, CodeStream) line: 88	
TryStatement.generateCode(BlockScope, CodeStream) line: 586	
```

There is some funny ping pong from the TryStatement delegating to the contained YieldStatement delegating back to the same TryStatement. If we'd skip this `placeEnd()` compilation would complete, but I can't say if the result would be correct.

I'm not an expert concerning the `yield` construct, though. Let's see if @mpalat has a minute to look into this :)

**Comment by srikanth-sankaran** [comment]
I am able to verify that this problem is fixed on master, the problem being addressed by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1744 made for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1686 - I will release the snippet from here as a regression test and close this.
