### ISSUE TITLE
OOM and memory leak again in gerrit

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#381]
We have again OOM error reported in gerrit, see

- https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-340/4/
- https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-380/2/

There were no changes on master except https://github.com/eclipse-jdt/eclipse.jdt.core/pull/325, which is unlikely the root cause.

The https://github.com/eclipse-jdt/eclipse.jdt.core/pull/380 only bumps bundle version.

Search in the console for `Memory usage reported by JVM`.
We see that memory constantly grows between test suites, despite the fact that we call gc and finalization.

The total memory given is 1 GB, the tests start with `22.987.912 bytes used heap` and end with multiple OOM's with this picture:
```
[2022-09-09 12:20:18 +0000] org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test#test0400()
14:20:19  
14:20:19  ########### Memory usage reported by JVM ########
14:20:19     1.073.741.824 bytes max heap
14:20:19     1.073.741.824 bytes heap allocated
14:20:19        47.580.488 bytes free heap
14:20:19     1.026.161.336 bytes used heap
14:20:19  #################################################
```

So there is some memory leak now. it is either coming from some other platform changes on 4.26 or from external changes like tycho, surefire or whatever else.

This reminds me on https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2 that was caused by Tycho leak: https://github.com/eclipse-tycho/tycho/issues/879

Similar to Tycho bug, we have a constant memory growing with every test.

**Comment by iloveeclipse** [comment]
@laeubi : was there any change on Tycho side similar to https://github.com/eclipse-tycho/tycho/issues/879 that could again cause OOM's?

@sravanlakkimsetti : did we changed anything related in the aggregator poms? I don't see any tycho version change, is is still `3.0.0-SNAPSHOT`:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/82e840b16f4f0714360357b31e903b9d60d91b06/eclipse-platform-parent/pom.xml#L70

**Comment by mickaelistria** [comment]
Yes most likely. I was expecting some improvement on that topic, but the Maven issue about the memory leak is still open, so nothing concrete happened apparently. I'm reverting that in Tycho.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-tycho/tycho/pull/1321

**Comment by iloveeclipse** [comment]
I've temporarily bumped memory to see how far we get, and we are close to 1.5 GB: `1.562.672.088 bytes used heap` short before test end...

If fixed Tycho is there, we should revert https://github.com/iloveeclipse/eclipse.jdt.core/commit/be594c221f34a323522254e1de599dbc3e4a840b

**Comment by iloveeclipse** [comment]
Fixed in Tychon, so reverted the temporary workaround via #467
