### ISSUE TITLE
Selectively revive run.javac test mode

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#386]
### Background

See https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/ECJ-Testing#runjavac

### Current status

None of the build jobs associated to this topic perform any real work since the migration to github (they still try to pull from the abandoned repo).

### Code involved

A non-trivial amount of code in / around org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.JavacTestOptions currently serves no purpose as it is never exercised.

Specific tests contain more that 1300 specific references to this class.

### Options

1. Revive the builds and continuously invest in analyzing & capturing compiler differences.
2. Do nothing, let the existing code rot.
3. Remove the unused code (either only the code in test infra are also the 1300+ references in tests)
 
Despite the issue title, I should like not to vote in this issue, but I believe whatever is done should be the result of a conscious decision, not an accident.

**Comment by mickaelistria** [comment]
If JDT committers seems that solution 1 is preferred, I think I or some colleague can invest some time to revive the exisiting jobs ( https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-12/ , isn't it?); and if those tests can run relatively fast, hook them to PR builds so people are made aware of possible regressions immediately

**Comment by laeubi** [comment]
> they still try to pull from the abandoned repo

Why not adjust the job to pull from the new location? I can't edit the job config because I'm not a JDT committer but it seems obvious to do so ...
![grafik](https://user-images.githubusercontent.com/1331477/189541151-bc5015c1-8ff8-46cf-8318-b645cb988347.png)

**Comment by gayanper** [comment]
I think we can change the repo and also switch to Java17 right ? If there are not objects we can change the job and try.

**Comment by stephan-herrmann** [comment]
Thanks for all offers to fix the build jobs.

The other, implicit question is: would running those jobs again create any benefit? If you scan the bugs in bugzilla that mention run.javac you'll see that the last relevant activity lies more than 2 years in the past. In plain words: who is willing to invest substantial efforts in monitoring test results and investigating the underlying differences between compilers. 

I mentioned the defunct jobs mainly as an indication that perhaps nobody even noticed their broken state, and by extension: nobody really cares. If that's the case, i.e., if nobody cares, what conclusions do we draw from that? Is it OK? Should we actively search for someone to look after these tests and their implications?

Btw, #339 shows an instance where more work would be needed when the old strategy should be continued.

**Comment by mickaelistria** [comment]
> who is willing to invest substantial efforts in monitoring test results and investigating the underlying differences between compilers

Monitoring is something that requires someone to make an effort and commit to it. It's asking a lot. A better alternative is to automate reporting (via CI vote, or by sending mails to the mailing-list) so they become notifications that multiple people would receive, and interested parties would react upon.
CI Jobs can be configured to achieve that.

> I mentioned the defunct jobs mainly as an indication that perhaps nobody even noticed their broken state, and by extension: nobody really cares.

It can also be the case that some people might care but have never known about those jobs and the value they can produce.
So one question to help establishing the probability of one interpretation over the other is what is the value this jobs do provide? Would having those jobs turned on noticeably improve the quality of JDT or the productivity of its contributors?

In any case, with already 2 people who have offered help to revive the jobs if it's consider profitable, so it doesn't seem to be a resource issue any more.

**Comment by stephan-herrmann** [comment]
The resource problem is: who is able and willing to make use of the test results?

Anyone interested is invited to look at these bugs: https://bugs.eclipse.org/bugs/buglist.cgi?classification=Eclipse%20Project&component=Core&list_id=21298875&longdesc=run.javac&longdesc_type=allwordssubstr&product=JDT&query_format=advanced&resolution=---

[bug 550032](https://bugs.eclipse.org/bugs/show_bug.cgi?id=550032) in particular looks like a good way of explaining: At that point comparison of javac 11 vs. ecj with target 11 exhibited 235 differences that had not been catalogued yet. When switching to target 12 we identified additional tests showing differences between javac and ecj, so either javac changed behavior, or when ecj makes a distinction between 11 and 12 this is not in accordance with javac. After two of those cases had been resolved, we still have a list of 7 tests with newly detected differences between javac and ecj, which have never been analyzed (as of 2019).

To address any of these cases, very good knowledge about ecj and JLS is required. Of course much of this can be acquired on the job.

So what's the effect either way?
* If we abandon these tests, we forgo systematic data points about changes in the comparison between compilers. In this matter we'd very much rely on bug reports from users who by chance detect one such difference (which happens, but just not systematically). The languages handled by javac and ecj will drift further apart. 
* If we pay attention to the results of the tests, it should improve our chances to at least avoid further drift, perhaps we can even manage some convergence. In a relevant number of cases this will involve challenging whether a difference might be due to a bug in javac, not ecj. Perhaps discussing this with Oracle, digging through their bug database and such (one possible outcome of analysis: we add an Oracle bug number to our list in JavacTestOptions, thusly documenting the reason for the difference). In some cases it may be impossible to judge using only JLS which of the compilers is right vs wrong.

In the first case, the drift can be safely predicted.  In the latter case, it's unclear what balance can be reasonably achieved? Drift only at a smaller rate? No drift, i.e., maintaining roughly the status quo? Some degree of convergence, i.e., improvement? I'm unable to predict.

How does all this effect users of Eclipse? Every now and then we get bug reports, where a program accepted in Eclipse does not compile in maven (i.e., using javac) and vice versa. Each occurrence will make users question whether they can afford to continue using Eclipse. The special test mode is designed to catch some of these cases before they hit the fan, pardon my french.

Related posts:
* https://objectteams.wordpress.com/2017/04/02/several-languages-java-8/
* https://objectteams.wordpress.com/2020/01/16/oracle-made-me-a-stackoverflow-guru/

**Comment by stephan-herrmann** [comment]
[TestAll_javac22.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14945270/TestAll_javac22.zip)

Snapshot of tests run against javac 22.
* 1 error
* 889 failures

For comparison: a [comment from 2019](https://bugs.eclipse.org/bugs/show_bug.cgi?id=539053#c7) documented (comparing javac10 vs javac11):
> At this point it shows 256 failures vs. the approx. 230 failures against javac10 (with a little fluctuation between builds).

**Comment by stephan-herrmann** [comment]
Status: I seem to be the only person interested in this testing mode. For new language features I'm using this test mode locally (and sporadically). Just for this it is definitely very useful still, but applying it to the entire suite is losing value by the day, due to accumulation of differences that have never been analysed.

Closing this issue.

**Comment by stephan-herrmann** [comment]
Discussion in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3204 did show some interest in running at least some tests in run.javac mode.

-> re-opening

**Comment by stephan-herrmann** [comment]
I resurrected one of the defunct build jobs: https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-12

[Result](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-12/319/testReport/): 3,889 failures

Tests that are relevant for current feature work fare much better, see
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2212#issuecomment-2323293285
* https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3204#issuecomment-2448688333

**Comment by stephan-herrmann** [comment]
Once #3204 is merged individual test classes can opt in for javac comparison.

The global mode is then selected like this:
* `-Drun.javac=enabled` -> enable javac comparison for entire suite
* `-Drun.javac=optin` -> enable only for test classes opting in via `AbstractCompilerTest.runJavacOptIn`
    (will use equalsIgnoreCase() so nobody has to remember OptIn vs. opIn vs. optin :) ).

The additional property `-Djdk.root=` is becoming optional. If unset the jdk running the tests will be used (at its specific compliance level).

I will then use https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-23 to monitor the comparison for some fresh and relevant test classes.

**Comment by stephan-herrmann** [comment]
With #3218 merged some first few classes opt in to run.javac mode, and in https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-23 exactly these classes are compared against javac. I plan to keep that build 100% green (i.e., classes not yet cleaned-up in this regard, will not be allowed to opt in :)).

If the next build looks good, I'm planning to set a weekly timer for that job.

Detail work on addressing actual differences between javac & ecj will continue in #2959

**Comment by stephan-herrmann** [comment]
Moved the feature description to a more permanent location: https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/ECJ-Testing#runjavac
