### ISSUE TITLE
Formatter: programmatically not handling "pre" tags correctly

### ISSUE THREAD

**Issue by rob-stoecklein** [eclipse-jdt/eclipse.jdt.core#393]
We're writing a program to format our Java source code, using the org.eclipse.jdt.core v3.30.0 library.
Most of the formatting works as expected, however "pre" tags in JavaDoc blocks get turned into a *single* line.

For example, this:
```
/**
 * <pre>
 * All    | of   | this | should | be   | aligned
 * but    | it   | is   | merged | into | a
 * single | line |
 * </pre>
 */
public class MyClass {
}
```

gets turned into this:
```
/** 
 * <pre> All    | of   | this | should | be   | aligned but    | it   | is   | merged | into | a single | line | </pre>
 */
public class MyClass {
}
```

The test code is:
```
public static void main(final String[] args) {
    String data = """
            /**
             * <pre>
             * All    | of   | this | should | be   | aligned
             * but    | it   | is   | merged | into | a
             * single | line |
             * </pre>
             */
            public class MyClass {
            }
            """;

    ASTParser parser = ASTParser.newParser(AST.getJLSLatest());
    parser.setKind(ASTParser.K_COMPILATION_UNIT);
    parser.setSource(data.toCharArray());
    ASTNode ast = parser.createAST(null);
    System.out.println(ast);
}
```

Is there something we're doing wrong?
Is there an option that needs to be set?
Thanks!

**Comment by mateusz-matela** [comment]
`ASTNode` is not designed for code formatting.
You should use `org.eclipse.jdt.internal.formatter.DefaultCodeFormatter`.
`CodeFormatterApplication` has a usage example. Actually, it may just be the implementation you need, as it can be invoked from command line to reformat a whole folder: https://www.beyondjava.net/run-eclipse-formatter-command-line
