### ISSUE TITLE
[19] PatternInstanceofExpression has its right operand as SingleVariableDeclaration instead of Pattern

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#396]
Patterns in an instanceof expression can also be record patterns. So, what we have now in PatternInstanceofExpression as right operand doesn't cover record patterns. We should change it to Pattern and all the relevant code.

Also noticed that the pattern property in Pattern is of type Javadoc, but I am not sure this is correct.

@SarikaSinha Can you please take a look?

**Comment by SarikaSinha** [comment]
RightOperand for PatternInstance of needs to handle the case of simple "String S" also, how will it work if changed the Right operand to Pattern?

JavaDoc thing looks wrong, it should be Pattern itself.

**Comment by jarthana** [comment]
> RightOperand for PatternInstance of needs to handle the case of simple "String S" also, how will it work if changed the Right operand to Pattern?
> 
> JavaDoc thing looks wrong, it should be Pattern itself.

I thought a TypePattern covers "String s" case, which in turn will convert this to a SingleVariableDeclaration?

**Comment by SarikaSinha** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/85 JEP 405: Record Patterns

**Comment by srikanth-sankaran** [comment]
@jarthana - this looks like a stale bug ??

**Comment by srikanth-sankaran** [comment]
> @jarthana - this looks like a stale bug ??

FWIW, I just closed https://github.com/eclipse-jdt/eclipse.jdt.core/issues/399 which was a precursor/originator to this as not reprodicible.

**Comment by jarthana** [comment]
> @jarthana - this looks like a stale bug ??

Yes, closing it now.
