### ISSUE TITLE
[19] ECJ reports switch with total record pattern as not exhaustive

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#398]
Try this testcase:
```
public class VarPattern {
  record Person(String name, int age) {}
  public static void main(String[] args) {
    Person person = new Person("Bob", 12);
    switch (person) {
      case Person(var name, var age) -> System.out.println(name +  " " + age);
    }
  }
}
```
ECJ reports the switch to be not exhaustive and suggest adding a default case. But it's not required as we already have a total pattern in the record pattern Person(var name, var age). I suspect this is due to the unimplemented isTotalForType() in RecordPattern.

**Comment by jarthana** [comment]
I thought we can fix this simply by computing and storing isTotalTypeNode for a record pattern rather. But this had issues in code generation where we were using the same flag to mean whether the pattern is a subtype or not. So, we will have to make some changes in how we store and use this flag. I have a working patch, but needs more testing and considering how late we are in the game, would like to test it bit more. There's a chance this will only make it after the GA.

**Comment by kriegaex** [comment]
Hello @jarthana, how much more testing and refinement is this issue going to take? Could this be fixed together with #455 anytime soon?

**Comment by jarthana** [comment]
> Hello @jarthana, how much more testing and refinement is this issue going to take? Could this be fixed together with #455 anytime soon?

Sorry, I should have updated. The earlier patch wasn't good enough. So, I left it at that. I believe this is same as #587 , which Manoj is looking at.

Copying @mpalat

**Comment by iloveeclipse** [comment]
@jarthana : please close if fixed or set other milestone, [BETA_JAVA19](https://github.com/eclipse-jdt/eclipse.jdt.core/milestone/13) is not valid anymore.

**Comment by mpalat** [comment]
yes, this is a duplicate - #1244 (along with #587  for further variations) fixes this.
