### ISSUE TITLE
Can not build Java 17 based projects with the openjdk version of openSUSE Leap

### ISSUE THREAD

**Issue by weberhofer** [eclipse-jdt/eclipse.jdt.core#405]
I have filed a bug at [openSUSE Bugzilla](https://bugzilla.opensuse.org/show_bug.cgi?id=1203476) too. Maybe the fix should be made in Eclipse, too. I'm quite sure, another ticket is related to this issue, too: microsoft/vscode-java-debug/issues/1212

BUG DESCRIPTION:
Whenever the latest version of Eclipse tries to build a Java 11 or Java 17 based project using Leap's openjdk-11 or openjdk-17 it throws errors with the following message:
```
Errors occurred during the build.
Errors running builder 'Java Builder' on project 'test'.
Cannot invoke org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(org.eclipse.jdt.internal.compiler.util.JRTUtil$JrtFileVisitor, int)"
because the return value of org.eclipse.jdt.internal.compiler.util.JRTUtil.getJrtSystem(java.io.File, String)" is null
```

The reason for this issue is, that Eclipse expects a file /usr/lib64/jvm/java-17-openjdk-17/release holding some version information. The file included in the Java installation included in Eclipse contains the following two lines:

```
JAVA_VERSION="17.0.4.1"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.internal.le jdk.internal.opt jdk.internal.vm.ci jdk.internal.vm.compiler jdk.internal.vm.compiler.management jdk.jartool jdk.javadoc jdk.jcmd jdk.management jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.random jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"
```
Copying this file into /usr/lib64/jvm/java-17-openjdk-17/release solves that issue for me.

STEPS TO REPRODUCE THE ISSUE:
* Start Eclipse 2022-09 on openSUSE Leap
* Add a new JRE pointing to /lib64/jvm/java-17-openjdk-17
* Switch the JavaSE-17 execution environment to use Leap's openjdk instead of the version coming with Eclipse
* Create/Open a Java 17 based project, using the JavaSE-17 execution environment
* Whenever Eclipse tries to build the project you should see errors.

**Comment by weberhofer** [comment]
To make openJDK 11 usable I have executed
```bash
sudo sh -c 'echo "JAVA_VERSION=\"11.0.16.0\"" > /usr/lib64/jvm/java-11-openjdk-11/release'
```

**Comment by iloveeclipse** [comment]
> Install a JDK 11 in local machine, and manually remove release file under jdk home.

Is this a valid use case? Or are there "regular" JDK builds without `release` file?

**Comment by testforstephen** [comment]
> Is this a valid use case? Or are there "regular" JDK builds without release file?

We have seen multiple (5+) users reporting this issue on the JDT language server side recently, and it looks like there are some JDK distributions that don't carry `release` file. I suspect that these JDK distributions are not from the official JDK vendors.

**Comment by iloveeclipse** [comment]
> it looks like there are some JDK distributions that don't carry release file

Would be nice to know which distributions are affected.

**Comment by testforstephen** [comment]
As this issue author @weberhofer mentioned, openSUSE Leap's openjdk doesn't provide `release` file.

**Comment by iloveeclipse** [comment]
> openSUSE Leap's openjdk

Where one can get this, and which exact version is affected?

**Comment by weberhofer** [comment]
openSUSE is currently packaging those files in "java-XX-openjdk-jmods", but the packages will be updated to move the fle to the "headless" package. 

This is the packagers response:
"It is really surpising that they depend on this file that is of no use to the jdk/jre unless you want to create a custom JDK. In our packages, the file is part of *-jmods. It is enough to install java-11-openjdk-jmods and/or java-17-openjdk-jmods and all will work as expected."

**Comment by iloveeclipse** [comment]
Well, there are many surprising things in universe, the compiler dependency to the release file is just one of them.
I hesitate to fix this, because it looks the particular Java SDK wasn't fully installed and there are few workarounds available.

**Comment by fridrich** [comment]
> Well, there are many surprising things in universe, the compiler dependency to the release file is just one of them. I hesitate to fix this, because it looks the particular Java SDK wasn't fully installed and there are few workarounds available.

"Wasn't fully installed" is pretty misleading. I made an arrangement for people that were hit by poorly thought-through design. There are different ways of getting version from a JRE. Reading the release file is not the canonical one. But never mind, I modified openSUSE/SUSE packages accordingly just to make users happy.

**Comment by fbricon** [comment]
@iloveeclipse you closed this issue as completed, but latest Eclipse still fails to compile the projects if that release file is missing. So, is it supposed to be fixed or closed as won't fix?

**Comment by iloveeclipse** [comment]
> you closed this issue as completed, but latest Eclipse still fails to compile the projects if that release file is missing. So, is it supposed to be fixed or closed as won't fix?

It is supposed to be closed as won't fix.

Of course if anyone plans ro contribute an improved solution to validate JDK version, feel free to reopen this & provide a PR.
