### ISSUE TITLE
[19] Create Wiki Examples Page for Java 19 Support

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.core#406]
Create https://wiki.eclipse.org/Java19/Examples
similar to https://wiki.eclipse.org/Java18/Examples

Following References might help:
- https://openjdk.java.net/projects/jdk/19/ - for list of features

JEP 405:	[Record Patterns (Preview)](https://openjdk.org/jeps/405)
JEP 427: [Pattern Matching for switch (Third Preview)](https://openjdk.org/jeps/427)
JEP 425: [Virtual Threads (Preview)](https://openjdk.org/jeps/425)
JEP 428: [Structured Concurrency (Incubator)](https://openjdk.org/jeps/428)

**Comment by SarikaSinha** [comment]
@niraj-modi

**Comment by niraj-modi** [comment]
Initial Java19 Examples wiki is ready:
https://wiki.eclipse.org/Java19/Examples
