### ISSUE TITLE
[19] Release Activities

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.core#407]
Top Level for bug general release activities:

- Increase the bundle service version 
	This must not use the same version as the base. As always, we increase the service segment by 50 for the beta work ==> 3.x. 50. Tracked in #409 

(e.g. 0 -> 50, 1 -> 50, 100 -> 150).

Tasks:
1. Disclaimers to be removed in Beta Branch 
2. Y build after Disclaimer removal
3. Merge Beta to master
4. Updating Marketplace Entry
5. Sending mail to community with MPE

**Comment by SarikaSinha** [comment]
@jarthana @noopur2507 @ktatavarthi

**Comment by noopur2507** [comment]
JDT UI beta and disclaimers removal to be done via
- https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/268
