### ISSUE TITLE
[19] Increase the bundle service version

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-jdt/eclipse.jdt.core#409]
Increase the bundle service version
This must not use the same version as the base. As always, we increase the service segment by 50 for the beta work ==> 3.x. 50
(e.g. 0 -> 50, 1 -> 50, 100 -> 150).

**Comment by sravanlakkimsetti** [comment]
Here is the list that require an update


IU id | Reference (old) version | Current (new) version
-- | -- | --
org.eclipse.jdt.core | 3.31.0.v20220831-1439 | 3.31.0.v20220912-1350
org.eclipse.jdt.core.compiler.batch | 3.31.0.v20220831-1439 | 3.31.0.v20220912-1350
org.eclipse.jdt.core.manipulation | 1.16.200.v20220824-0551 | 1.16.200.v20220913-0643
org.eclipse.jdt.core.manipulation.source | 1.16.200.v20220824-0551 | 1.16.200.v20220913-0643
org.eclipse.jdt.core.source | 3.31.0.v20220831-1439 | 3.31.0.v20220912-1350
org.eclipse.jdt.core.tests.compiler | 3.12.2000.v20220831-1439 | 3.12.2000.v20220910-2058
org.eclipse.jdt.core.tests.model | 3.11.300.v20220831-1439 | 3.11.300.v20220916-0220
org.eclipse.jdt.debug.tests | 3.11.1800.v20220730-1850 | 3.11.1800.v20220809-0554
org.eclipse.jdt.launching | 3.19.700.v20220730-1850 | 3.19.700.v20220809-0554
org.eclipse.jdt.launching.source | 3.19.700.v20220730-1850 | 3.19.700.v20220809-0554
org.eclipse.jdt.ui | 3.27.0.v20220824-0714 | 3.27.0.v20220912-1023
org.eclipse.jdt.ui.source | 3.27.0.v20220824-0714 | 3.27.0.v20220912-1023

**Comment by noopur2507** [comment]
JDT UI bundle version updates are done via
- https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/270
