### ISSUE TITLE
ASTRewriteFlattener inserts unnecessary semicolon

### ISSUE THREAD

**Issue by RaphaelJenni** [eclipse-jdt/eclipse.jdt.core#434]
When creating a record manually and adding it to the AST, the rewrite adds a semicolon to the start of the body declaration block.

Example:
```java
record Point(int x, int y) {
    ; // <-- this one
    private static final int staticField = 16;
    ...
 ````

I tracked the issue down to the `ASTRewriteFlattener`.

For TypeDeclaration the call looks like follows:
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/5fd28398cc7aba72f9f05a9b777c8daa5a2cfc41/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteFlattener.java#L1231
the same code but for records looks like this:
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/5fd28398cc7aba72f9f05a9b777c8daa5a2cfc41/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteFlattener.java#L917

The issue lies in the `String.valueOf(';')` representing the `lead` in the list (`ASTRewriteFlattener.java:212`).

The Java SE Specification (JLS18) (https://docs.oracle.com/javase/specs/jls/se18/html/jls-8.html#jls-RecordBodyDeclaration) has records listed as follows:
```
RecordBody:
  { {RecordBodyDeclaration} }
  
RecordBodyDeclaration:
  ClassBodyDeclaration
  CompactConstructorDeclaration

ClassBodyDeclaration:
  ClassMemberDeclaration
  InstanceInitializer
  StaticInitializer
  ConstructorDeclaration

ClassMemberDeclaration:
  FieldDeclaration
  MethodDeclaration
  ClassDeclaration
  InterfaceDeclaration
  ;
```

Is this intended or a bug? Any help is appreciated.

References:
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=553154
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=550504
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=553155

**Comment by Shee43** [comment]
I am looking to this issue
