### ISSUE TITLE
Formatter incorrect when using type parameters in records

### ISSUE THREAD

**Issue by victornoel** [eclipse-jdt/eclipse.jdt.core#443]
Hi,

I am using:
Version: 2022-09 (4.25.0)
Build id: 20220908-1902

Starting with the following code (this would be the expected formatting after applying the formatter):
```java
record MyRecord<A>() {}
class MyClass<A> extends AnotherClass {}
```

If I format using `org.eclipse.jdt.core.formatter.insert_space_after_closing_angle_bracket_in_type_parameters` do `insert`, notice the extra space between `<A>` and `()`:
```java
record MyRecord<A> () {}
class MyClass<A> extends AnotherClass {}
```

And if I format using `do not insert`, notice the missing space between `<A>` and `extends`:
```java
record MyRecord<A>() {}
class MyClass<A>extends AnotherClass {}
```

**Comment by PyvesB** [comment]
This issue was impacting my team, thanks for fixing @mateusz-matela!
