### ISSUE TITLE
[20] JEP 433: Pattern Matching for switch (Fourth Preview)

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#482]
Pattern matching for switch will continue to be a preview feature in Java 20 and being detailed here:

https://openjdk.org/jeps/433

**Comment by mpalat** [comment]
Task identified so far
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/556
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/557
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/558

**Comment by mpalat** [comment]
Remaining issues will be addressed by separate issues. Resolving
