### ISSUE TITLE
Q: Compile errors in org.eclipse.jdt.core.tests.model (problem getting started with jdt source)

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.core#502]
I wanted to take a look at the content assist code (I might try to fix some completion bugs). So I cloned eclipse.jdt.core and set the target platform to the currently running Eclipse. The projects have no compilation errors, but test projects like org.eclipse.jdt.core.tests.model show me various errors (like, for example, "The hierarchy of the type CompletionTests18 is 
inconsistent" for CompletionTest18.

Is there something obviously wrong in my setup? Maybe I need to clone other repositories besides eclipse.jdt.core?

Thanks you

**Comment by stephan-herrmann** [comment]
My quick guess is that you are lacking bundles like org.eclipse.test.performance, but actually you shouldn't need to hunt them down individually. Have you seen https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md#create-an-eclipse-development-environment ? 

Yes, this probably should be linked from the jdt.core repo, too ...
