### ISSUE TITLE
Code auto complete for methods and "organize imports" functionality is not working from classes from jdk.* modules

### ISSUE THREAD

**Issue by sveryovka** [eclipse-jdt/eclipse.jdt.core#518]
Example module jdk.jshell
You can add it to module-info.java - "requires jdk.jshell;"
You can instantiate class from this module in your code:
```
import jdk.jshell.JShell;
...          
JShell state = JShell.create();
```
but when you type `state.` and click `Ctrl+Space` you will get auto completion window with suggestion of methods. But it is not complete. It does include only methods inherited from Object. But there are no methods which are defined in JShell itself.

The resulting code compiles and runs. It is a problem with Eclipse smart features only.

And it is not only about jshell. I've tried  `jdk.nio.Channels` class from `jdk.net` module. Same problem. 

It seems like it is because these are "jdk.*" modules. But if you can compile and run application content assistant and other smart features should also work

**Comment by iloveeclipse** [comment]
Please remove type filters here: 
![image](https://user-images.githubusercontent.com/964108/204481507-c5f0c86f-0fd5-477d-b738-2f010da7b43c.png)
