### ISSUE TITLE
Enable Discussions?

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.core#521]
Github Discussions are a good way to interact with the community on Github as it allows feature rich linking of code, issues and/or other discussions: https://docs.github.com/en/discussions

I therefore like to suggest to enable it for this repository.

**Comment by iloveeclipse** [comment]
Feel free to discuss whatever you want here, but only if it is related to JDT core :-)

**Comment by laeubi** [comment]
@iloveeclipse even if it is named "discussions" it also offers other types like Announcements, Ideas, Questions, ... you might want to take a look at https://github.com/eclipse-tycho/tycho/discussions how it might be used.

So I think the usual "issues" are not very well suited for such kind of things, so probably you still like to consider this a a usefull feature, you just need to enable it in the repository settings :-)

**Comment by laeubi** [comment]
Just as an example:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/516

might be more suitable for the discussions feature as it is a usage/question and not (yet) an issue. Still if one thinks there need something be done, you can easily create issues out of discussions.

**Comment by iloveeclipse** [comment]
I have no idea what are you talking about. You wanted discussions, I enabled that, so feel free to discuss: https://github.com/eclipse-jdt/eclipse.jdt.core/discussions

**Comment by laeubi** [comment]
@iloveeclipse sorry it seems my browser tricked me and showing an old page without the discussions link and thus I misread your response :-\

But you probably still want to go to this issue:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/516

and click "transfer to discussion" :-)
