### ISSUE TITLE
`continue` without label is incorrectly handled in a switch expression

### ISSUE THREAD

**Issue by Haspamelodica** [eclipse-jdt/eclipse.jdt.core#53]
Tested on Eclipse 2022-03; jdt.core version 3.29.0.v20220214-1307.

The JDT compiler allows a `continue` statement inside a (case of a) switch expression to continue to a loop declared outside of the switch expression, iff that `continue` doesn't target an explicit label.
The JLS clearly forbids this: "It is a compile-time error if the continue target contains any [...] switch expression that encloses the continue statement. That is, there are no non-local jumps." in https://docs.oracle.com/javase/specs/jls/se17/html/jls-14.html#jls-14.16 / https://docs.oracle.com/javase/specs/jls/se18/html/jls-14.html#jls-14.16

MWE:
```java
public class ContinueFromSwitchExpression
{
    public static String string = "a";

    public static void main(String[] args)
    {
        loop: for(;;)
        {
            System.out.println("In loop before switch");
            int result = 123 + switch(string)
            {
                case "a" ->
                {
                    continue; // incorrectly compiles in JDT
                    //continue loop; // correctly flagged as error ("Continue out of switch expressions not permitted")
                    // javac (correctly) outputs "error: attempt to continue out of a switch expression" for both continue statements
                }
                default -> 456;
            };
            System.out.println("After switch. result: " + result);
        }
    }
}
```

Resulting classfile:
```
public class ContinueFromSwitchExpression {
  public static java.lang.String string;

[... default constructor and <clinit> ...]

  public static void main(java.lang.String[]);
    Code:
       0: getstatic     #23                 // Field java/lang/System.out:Ljava/io/PrintStream;
       3: ldc           #29                 // String In loop before switch
       5: invokevirtual #31                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
       8: bipush        123
      10: getstatic     #12                 // Field string:Ljava/lang/String;
      13: dup
      14: astore_2
      15: invokevirtual #37                 // Method java/lang/String.hashCode:()I
      18: lookupswitch  { // 1
                    97: 36
               default: 45
          }
      36: aload_2
      37: ldc           #10                 // String a
      39: invokevirtual #43                 // Method java/lang/String.equals:(Ljava/lang/Object;)Z
      42: ifne          0
      45: sipush        456
      48: iadd
      49: istore_1
      50: getstatic     #23                 // Field java/lang/System.out:Ljava/io/PrintStream;
      53: new           #47                 // class java/lang/StringBuilder
      56: dup
      57: ldc           #49                 // String After switch. result:
      59: invokespecial #51                 // Method java/lang/StringBuilder."<init>":(Ljava/lang/String;)V
      62: iload_1
      63: invokevirtual #53                 // Method java/lang/StringBuilder.append:(I)Ljava/lang/StringBuilder;
      66: invokevirtual #57                 // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
      69: invokevirtual #31                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
      72: goto          0
}
```

Trying to run the resulting classfile throws a verification error because of the value 123 remaining on the stack when the `continue` jumps to the loop beginning. Removing `123 + ` causes the JVM to not throw any errors; it then prints "In loop before switch" repeatedly and indefinitely as expected (but still incorrectly).

**Comment by Haspamelodica** [comment]
After a bit debugging, the problem seems to be in [`SwitchExpression.OOBLFlagger`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/SwitchExpression.java#L389): it only considers `ContinueStatement`s with an explicit label for out-of-bounds detection: [`OOBLFlagger#visit(ContinueStatement, ...)`, l.433](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/SwitchExpression.java#L433), [`OOBLFlagger#checkForOutofBoundLabels`, l. 411](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/SwitchExpression.java#L411)

**Comment by iloveeclipse** [comment]
@Haspamelodica : do you want to provide a fix? If yes, ideally that should go along with new test case.

**Comment by Haspamelodica** [comment]
I'll try, but so far I haven't been able to compile and run the test cases.

Also, currently this error (for explicitly labeled `continue`s) will be found [in `resolveType`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/SwitchExpression.java#L495); however, the current solution is rather hacky and isn't easy to extend for implicitly labeled `continue`s. I think it would be easier to find this error [in `analyseCode`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/SwitchExpression.java#L689), where the `FlowContext` is known. Will this work or is `analyseCode` "too late" to catch such errors?

**Comment by Haspamelodica** [comment]
If there is no reason this error shouldn't be detected in `analyseCode`, I think the best solution would be to move detecting this error into [`FlowContext#getTargetContextForDefaultContinue`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/e939427920a4695e714c6bcf7b2b3ea5bdd9717b/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/flow/FlowContext.java#L641) / [`FlowContext#getTargetContextForContinueLabel`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/e939427920a4695e714c6bcf7b2b3ea5bdd9717b/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/flow/FlowContext.java#L567), which are the methods [`ContinueStatement#analyseCode`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/ContinueStatement.java#L29) uses to find the target context.

**Comment by srikanth-sankaran** [comment]
I'll take a look at this one.

**Comment by srikanth-sankaran** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1056 is still work in progress and needs a bit of polish and lot more testing. But as flow analysis of Switch expressions is not integrated well into the canonical infrastructure for flow analysis and this PR attempts to do that (by completely getting rid of the abstraction SwitchExpression.OOBLFlagger
