### ISSUE TITLE
MetaIndex values for type references are wrong

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#533]
Based on the https://github.com/eclipse-jdt/eclipse.jdt.core/blob/7eeb9b4342d4d83f3a5a1d078a4e4dff0ab83bb2/org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/indexing/AbstractIndexer.java#L256

It cause all type references which doesn't have a enclosing type to prefix with the '$' which cause metaindex hits to fail.

Once this is fixed the metaindex needs to rebuilt which means the a full index rebuilt must be done.

**Comment by iloveeclipse** [comment]
I assume this can be closed now.
