### ISSUE TITLE
release option 9 make compiler break when using JDK 11

### ISSUE THREAD

**Issue by CsCherrYY** [eclipse-jdt/eclipse.jdt.core#539]
original post can be found here: https://github.com/eclipse-m2e/m2e-core/issues/1065

If we have JDK 11 as environment and release option enabled with source level 9, then we will get the error: 
```
The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files
```

The issue can also be reproduced in JDK 10 with release 9, but disappear with 

- release 10+
- release 9-
- JDK 12+

Although we have a warning provided since https://bugs.eclipse.org/bugs/show_bug.cgi?id=544674, m2e will automatically add the release tag from pom.xml and the warning message has no opportunity to be found.

I found there was a patch to fix this issue in release 10: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/8cf64302cf48ebc8b9e15908bc66f2358cbcccb9. Since the issue can be observed in release 9 as well, we should make a similar patch for this.

**Comment by stephan-herrmann** [comment]
@iloveeclipse this expands your fix from [Bug 562727](https://bugs.eclipse.org/562727), so perhaps you want to review / merge (for the next M1 I guess)?

**Comment by iloveeclipse** [comment]
@CsCherrYY : thanks for the patch!
