### ISSUE TITLE
Java 20 support preliminary steps

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.core#542]
PRs here will be for steps done before getting into compiler supporting new constructs and producing new bytecode.

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt/issues/40 for relevant Java 20 features.

**Comment by jarthana** [comment]
I have added a new wiki page that lists all changes we usually make for new language version/feature support:

[Adding support for new Java version and Features in JDT](https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/Adding-support-for-new-Java-version-and-Features-in-JDT)

**Comment by akurtakov** [comment]
I'm closing this one as the constants are in and further work seems to happen in other issues.
