### ISSUE TITLE
[19] JEP 427: Pattern Matching for switch Enhancements

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#55]
JEP 427: Pattern Matching for switch - referred by 
(1) https://openjdk.java.net/jeps/427
(2) tracked via : https://bugs.openjdk.java.net/browse/JDK-8282272

- [x] #56
- [ ] Search Changes

**Comment by srikanth-sankaran** [comment]
@mpalat - Should this stay open ?

**Comment by jarthana** [comment]
> @mpalat - Should this stay open ?

No reason. Closing.
