### ISSUE TITLE
Switch with a case null should be treated as an enhanced switch

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#554]
public class X {
	public static void main(String[] args) {
	    String obj = null;
		var a = switch (obj) {
	        case null, default -> 1;
	    }; 
	}  
}  

Follow-up from #449 
This gives a run time error NPE 
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "obj" is null
	at X.main(X.java:4)

Issue is that this is treated as a String switch but not as an enhanced switch.

**Comment by mpalat** [comment]
This should be applied after #449

**Comment by PatrickHechler** [comment]
the same bug occurs, when using a switch case with a enum and a null case (NullPointer at runtime)

    Exception in thread "main" java.lang.NullPointerException: Cannot invoke "MyEnum.ordinal()" because "val" is null
        at X.main(X.java:4)


    public class X {
        public static void main(String[] args) {
            MyEnum val = null;
            switch (val) {
            case null:
                System.out.println("val is null");
                break;
            }
        }
    }
    enum MyEnum {
        a
    }

**Comment by iloveeclipse** [comment]
@srikanth-sankaran : something for you?

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran : something for you?

Will take a look

**Comment by srikanth-sankaran** [comment]
The original defect snippet seems to have been fixed by @mpalat via commit 4fe460b7c184e51203ad929d6aac97d95c01a6af.

The PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1773 fixes and includes a test for the additional scenario reported by @PatrickHechler
