### ISSUE TITLE
[Patterns] Report `unused variable` for variables declared in instanceof pattern

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.core#567]
Example
```java
  if (animal instanceof Dog dog) {
      System.err.println(animal.toString());
  }
```
should show a warning about unused variable `dog`. This will allow to more easily ensure correct code as it can happen that ones defines a typed variable after the instanceof expecting it to be used; but may forget about it.

**Comment by srikanth-sankaran** [comment]
I don't think this is a beginner issue - appearances can be deceptive :)

**Comment by iloveeclipse** [comment]
Thanks Srikanth!

**Comment by mickaelistria** [comment]
Thank you, that will be very useful when modernizing old code.
