### ISSUE TITLE
[19] JEP 427 Switch Pattern Third Preview Grammar Changes

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#57]
<Placeholder for more inf>

Ref: http://cr.openjdk.java.net/~gbierman/jep427+405/jep427+405-20220426/specs/patterns-switch-record-patterns-jls.html

**Comment by srikanth-sankaran** [comment]
@mpalat - Should this stay open ?

**Comment by jarthana** [comment]
> @mpalat - Should this stay open ?

No reason. Closing.
