### ISSUE TITLE
Merge https://github.com/eclipse-jdt/eclipse.jdt into https://github.com/eclipse-jdt/eclipse.jdt.core

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#571]
I have **no idea** why there is a dedicated https://github.com/eclipse-jdt/eclipse.jdt repository next to https://github.com/eclipse-jdt/eclipse.jdt.core.
It contains only three projects, one from them is jdt feature which is then separated from the bundles it refers to.

We probably should merge eclipse.jdt into https://github.com/eclipse-jdt/eclipse.jdt.core.

**Comment by akurtakov** [comment]
Note that this feature includes o.e.jdt.ui, o.e.jdt.debug.ui and etc. so it will create yet another circular dependency between jdt.core and jdt.ui git repos if merged into jdt.core repo.

**Comment by iloveeclipse** [comment]
Arrgh.

**Comment by akurtakov** [comment]
Technically jdt.ui is the only place where it can be merged without creating additional circular dependency between repos.
