### ISSUE TITLE
Sealed classes permits clause

### ISSUE THREAD

**Issue by uhoefel** [eclipse-jdt/eclipse.jdt.core#581]
Currently, there is a warning if a sealed class permits a generic subclass and does not specify the type parameter:
![image](https://user-images.githubusercontent.com/4885222/205446980-21f2e372-5e3f-4189-8c70-638637df873c.png)
However, it seems that specifiying the type parameter is not liked by java (at least by jshell). Also, in the JLS, only the TypeName is listed there:
[JLS 8.1.6](https://docs.oracle.com/javase/specs/jls/se19/html/jls-8.html#jls-8.1.6)
My guess would be that there should be no warning in the permits clause.

**Comment by uhoefel** [comment]
Any chance this is getting fixed for 2023-03?

**Comment by iloveeclipse** [comment]
> Any chance this is getting fixed for 2023-03?

Yes, if someone would take time to contribute a fix.

**Comment by uhoefel** [comment]
I may be able to spend some time on it, but where would I best start?

**Comment by jarthana** [comment]
Copying @mpalat

**Comment by mpalat** [comment]
Agree - 8.1.6 says
 ClassPermits:
permits TypeName {, TypeName}
- not parameterized.

Suby Surendran is currently looking into this and will post a patch soon

**Comment by srikanth-sankaran** [comment]
This was fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1159

**Comment by srikanth-sankaran** [comment]
> Agree - 8.1.6 says ClassPermits: permits TypeName {, TypeName}
> 
> * not parameterized.
> 
> Suby Surendran is currently looking into this and will post a patch soon

Could you please inform Suby so he doesn't waste time on this ? Sorry, I came to this from bugzilla (https://bugs.eclipse.org/bugs/show_bug.cgi?id=576378)
