### ISSUE TITLE
Compiler warnings in I-builds

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.core#590]
At https://download.eclipse.org/eclipse/downloads/drops4/I20221205-1800/testResults.php#PluginsErrors there is:

Compile Logs (Jar Files) | Errors | Warnings
-- | -- | --
jdt.core.compiler.batch | 0 | 2

Compile Logs (Jar Files) 	Errors 	Warnings
[jdt.core.compiler.batch](https://download.eclipse.org/eclipse/downloads/drops4/I20221205-1800/compilelogs/plugins/org.eclipse.jdt.core.compiler.batch_3.33.0.v20221205-1735/@dot.html) 	[0](https://download.eclipse.org/eclipse/downloads/drops4/I20221205-1800/compilelogs/plugins/org.eclipse.jdt.core.compiler.batch_3.33.0.v20221205-1735/@dot.html#ERRORS) 	[2](https://download.eclipse.org/eclipse/downloads/drops4/I20221205-1800/compilelogs/plugins/org.eclipse.jdt.core.compiler.batch_3.33.0.v20221205-1735/@dot.html#OTHER_WARNINGS)

**Comment by akurtakov** [comment]
@iloveeclipse This seems to be side effect of the batch compiler bundle move.

**Comment by iloveeclipse** [comment]
> @iloveeclipse This seems to be side effect of the batch compiler bundle move.

Sure, from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181 / https://github.com/eclipse-jdt/eclipse.jdt.core/pull/182 .

I have troubles right now to understand which hack allowed p2 to run ant tasks with compiler taken from jdt.core runtime, https://github.com/eclipse-pde/eclipse.pde/issues/419.

Once I will be done there, I will look here.
