### ISSUE TITLE
Rebase BETA_JAVA20 branch on master

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.core#591]
Needed to get the https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181 refactoring before Java 20 changes.

**Comment by akurtakov** [comment]
This is prereq for rebasing https://github.com/eclipse-jdt/eclipse.jdt.core/pull/541

**Comment by akurtakov** [comment]
@iloveeclipse maybe you can do it?

**Comment by akurtakov** [comment]
I've provided a PR to make it single click for committer to push it.

**Comment by iloveeclipse** [comment]
I'm looking at it.

**Comment by brychcy** [comment]
Shouldn't there be an explicit "merge" commit from the master into the BETA_JAVA20 branch, so git knows it can ignore all earlier commits when doing future merges?

**Comment by iloveeclipse** [comment]
Since there is no documentation what is expected, we just did something we've assumed should be OK.
But as there are no changes on the branch yet, we can do whatever we need to do.

Any **concrete** proposals what is needed?

**Comment by brychcy** [comment]
I'll just do it.

**Comment by brychcy** [comment]
done
