### ISSUE TITLE
Missing error message for generics on var

### ISSUE THREAD

**Issue by joeseibel** [eclipse-jdt/eclipse.jdt.core#600]
An error should be reported when there are generics on `var`, but the JDT compiler does not complain and compiles anyway. The following class currently compiles and runs, but an error should be reported:
```java
package test;

import java.util.ArrayList;

public class Test {
    public static void main(String[] args) {
        var<String> list = new ArrayList<String>();
        System.out.println(list.size());
    }
}
```
When I run this class through `javac`, the following error is produced:
```
Test.java:7: error: illegal reference to restricted type 'var'
		var<String> list = new ArrayList<String>();
		^
```

**Comment by iloveeclipse** [comment]
Cool. Looks like ecj ignores the generic part completely, which leads to such code to be accepted too:
`var<Number> list = new ArrayList<String>();`
