### ISSUE TITLE
Eclipse compiled classes reference JDK12+ classes with JDK11 target compatibility set

### ISSUE THREAD

**Issue by ssadedin** [eclipse-jdt/eclipse.jdt.core#632]
After migrating to Eclipse 2022-09 and then observed again with 2022-12, I have found that one of my projects produces class files that cannot be executed using JDK11, even though JDK11 compatiblity has been set.

The class file emitted reference the `java.lang.constant.Constable` interface, even though this interface is not present in JDK11. 

An example stack trace that occurs when trying to execute the code is:

```
Caused by: java.lang.NoClassDefFoundError: java/lang/constant/Constable
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
at java.base/java.security.AccessController.doPrivileged(Native Method)
...
```
In this case there is no JDK/JRE configured that contains the Constable class (added in JDK12):

<img width="620" alt="image" src="https://user-images.githubusercontent.com/138868/211302916-be22e2f3-c70e-48a6-862a-32878a5319e7.png">

All the Java Compile options are set to JDK11:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/138868/211303120-11b4ef60-9c72-4f56-ae2b-bc1590a07cf0.png">

If I remove the bundled Java 17 JRE from the eclipse.ini and replace it with JDK11 VM, this error does not occur.

So it seems  like it would have to be a bug that Eclipse outputs a class referencing the Constable class?

**Comment by iloveeclipse** [comment]
Are there any related errors reported in Error log view? 
Could you please attach simple standalone project (including .settings directory) that shows the issue?

Could you please also check with 4.27 M1 from https://download.eclipse.org/eclipse/downloads/?

**Comment by ssadedin** [comment]
Followup: after digging some more I think I have identified that this may be due to the groovy-eclipse compiler rather than core JDT. I will follow up with that project first.

**Comment by ssadedin** [comment]
> Are there any related errors reported in Error log view? Could you please attach simple standalone project (including .settings directory) that shows the issue?
> 
> Could you please also check with 4.27 M1 from https://download.eclipse.org/eclipse/downloads/?

thanks for the followup!  I'll check if this is due to groovy-eclipse first and if I can reproduce stand alone will come back and reopen here. Thanks!
