### ISSUE TITLE
Prevent imports/package from being moved above first comments

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdt/eclipse.jdt.core#649]
this is a follow up on https://github.com/redhat-developer/vscode-java/issues/1993.

JBang scripts use directives in java files taking the form of single line comments. eg:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?

public class hello {

  public static void main(String[] args) {
    if (args != null) {
      Arrays.stream(args).forEach(System.out::println);
    } else {
      System.out.println("no args");
    }
  }
}
```

here, the `///usr/bin/env jbang "$0" "$@" ; exit $?` needs to stay on the 1st line, as it's interpreted by bash/shell when invoked from CLI (see https://www.jbang.dev/documentation/guide/latest/faq.html).

When you organize imports or use autocompletion for `Arrays`, `import java.utils.Arrays` is added on the 1st line, instead of keeping the JBang directive there.

```java
import java.util.Arrays;
///usr/bin/env jbang "$0" "$@" ; exit $?


public class hello {

  public static void main(String[] args) {
    if (args != null) {
      Arrays.stream(args).forEach(System.out::println);
    } else {
      System.out.println("no args");
    }
  }
}
``` 

So, it'd be nice if the JDT formatter didn't touch those 1st comments. @rgrunber proposed the following patch, that might fix this issue:

> I think the entry point to fix this (or add an option to change the behaviour) should be at https://github.com/eclipse-jdt/eclipse.jdt.core/blob/c58f581d8cef2c38a339b8056b3f48f1d5365731/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java#L317 .
> 
> If there's no existing import region (no imports), and no existing package declaration (default package), then find the offset of the first non-comment node and begin from there.
>
> This pretty basic patch seems to do the job.

```diff
diff --git a/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java b/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java
index 200be49a4f..cd29dfcc5e 100644
--- a/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java
+++ b/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java
@@ -28,6 +28,7 @@ import java.util.Map.Entry;
 import java.util.NavigableMap;
 import java.util.Set;
 import java.util.TreeMap;
+
 import org.eclipse.core.runtime.IProgressMonitor;
 import org.eclipse.core.runtime.IStatus;
 import org.eclipse.core.runtime.Status;
@@ -315,6 +316,16 @@ public final class ImportRewriteAnalyzer {
            }
            else {
                surroundingStart = 0;
+               ASTNode topNode = nodesTreeMap.firstEntry().getValue();
+               if (topNode instanceof Comment) {
+                   for (ASTNode node : nodesTreeMap.values()) {
+                       if (!(node instanceof Comment)) {
+                           break;
+                       } else {
+                           surroundingStart = node.getStartPosition() + node.getLength();
+                       }
+                   }
+               }
            }

            positionAfterImports = surroundingStart;

```

The same care should be taken when moving the file from the default to a random package, so the package statement stays under the 1st comment.

**Comment by jjohnstn** [comment]
The aforementioned patch might move a Javadoc comment for a class above the imports.

Do the comments always begin with /// ?  If so, a check could be made for this specifically to avoid all other comments or for // to avoid the Javadoc issue.

**Comment by rgrunber** [comment]
> The aforementioned patch might move a Javadoc comment for a class above the imports.
> 
> Do the comments always begin with /// ? If so, a check could be made for this specifically to avoid all other comments or for // to avoid the Javadoc issue.

It can become `LineComment`. I intentionally made it `Comment` to include `BlockComment` & `Javadoc`. I guess my thinking was to make it more general to increase likelihood of acceptance.

For example, imports go below the package statement, and often there's some kind of comment-based header (eg. copyright) at the top of the file. However for jbang, since we're usually talking about a singe file, it's likely there's no package declaration (default package) at all. In this case, the imports go to the top of the file, causing the issue. It could very easily be argued that the imports should always go after the set of comment statements from the top of the file.

**Comment by maxandersen** [comment]
Fwiw this is not jbang specific. 

Same happens with plain single file java files.

**Comment by jjohnstn** [comment]
I have taken Roland's patch and added a fix for the case where the class is moved from default package to another package.  I have JDT UI tests which I can add if/once the PR is merged. 

It should be noted that Javadoc comments are special and can be connected to their subsequent elements and not treated as header comments.  For example:

```
/**
 * Copyright 2023
 *
 */
/**
 * 
 * @author jjohnstn
 *
 */
public class TestImport {
	
	public void foo() {
		Date d = new Date();
	}

}
```
In this example, CTRL+SHIFT+O will put the import statement between the 2 Javadoc comments.  The 2nd Javadoc comment will continue to describe the TestImport class.  This behavior would only cause a problem for the JBang directives if they were to use Javadoc comments which I would not anticipate.  A class with a single Javadoc comment (e.g. just the copyright comment above) would end up putting any added package statement or import statement at the top of the file.
