### ISSUE TITLE
No completions for records header first components

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#667]
```
public record Person(|) {}
```

At the position | there are no type completion suggestions are made. Neither after typing a Type like

```
public record Person(String n|) {}
```

No variable name completions or any.

But things start to work after completing the first component

```
public record Person(String name, |) {}
```

Eclipse version: 2022-12
Project Runtime: Java 17

**Comment by gayanper** [comment]
@mickaelistria @testforstephen I started to look into this code and it seems to be a issue in the completion parser. What i fear is trying to fix this will open up a pandora box of issues. Should we wait or start trying to replace the completion parser with javac parser as a experimental feature ? WDYT

**Comment by mickaelistria** [comment]
> Should we wait or start trying to replace the completion parser with javac parser as a experimental feature ?

This is not yet certain this is possible, not certain it can be done everywhere in JDT, not certain it is actually better... I think no decision should be made at the moment assuming that changing the parser is something is something that will be complete anytime soon, if ever.

**Comment by gayanper** [comment]
@stephan-herrmann I debugged the scanerio, seem like once after processing the `consumeRecordHeaderName1` parser fails to see the compact constructor or the record components. None of the consume methods are called, I don't see the action values computed for those rules either.

Could it be a issue with the parser files ?

**Comment by stephan-herrmann** [comment]
@gayanper You don't have a junit for this ready for debugging, do you?

First thing that comes to mind: is the restricted identifier `record` recognized by the Scanner on incomplete source? See `Scanner.disambiguatedRestrictedIdentifierrecord(int)`.

**Comment by gayanper** [comment]
@stephan-herrmann I have one without proper assertions which I'm using to debug

```
	public void testGH667() throws JavaModelException {
		this.workingCopies = new ICompilationUnit[1];
		this.workingCopies[0] = getWorkingCopy(
				"/Completion/src/Person.java",
				"public record Person (Strin) {\n"
						+ "}");
		this.workingCopies[0].getJavaProject();
		CompletionTestsRequestor2 requestor = new CompletionTestsRequestor2(true);
		requestor.allowAllRequiredProposals();
		String str = this.workingCopies[0].getSource();
		String completeBehind = "Person (Strin";
		int cursorLocation = str.lastIndexOf(completeBehind) + completeBehind.length();
		this.workingCopies[0].codeComplete(cursorLocation, requestor, this.wcOwner);
		assertNotEquals("", requestor.getResults());
	}
```

**Comment by gayanper** [comment]
I check the `Scanner.disambiguatedRestrictedIdentifierrecord(int)` and it seems to identify the record token correctly. Following the the debug output.

```
-- ENTER INSIDE PARSE METHOD --
EnterCompilationUnit ::=
InternalCompilationUnit ::=
CompilationUnit ::= EnterCompilationUnit...
-- EXIT FROM PARSE METHOD --
-- ENTER INSIDE PARSE METHOD --
EnterCompilationUnit ::=
Modifiersopt ::= Modifiers
RecordHeaderName1 ::= Modifiersopt...
Modifiersopt ::=
Name ::= SimpleName
ClassOrInterface ::= Name
ReferenceType ::= ClassOrInterfaceType
PushZeroTypeAnnotations ::=
Modifiersopt ::= Modifiers
RecordHeaderName1 ::= Modifiersopt...
Modifiersopt ::=
Name ::= SimpleName
ClassOrInterface ::= Name
ReferenceType ::= ClassOrInterfaceType
PushZeroTypeAnnotations ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
Name ::= SimpleName
ClassOrInterface ::= Name
ReferenceType ::= ClassOrInterfaceType
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
-- EXIT FROM PARSE METHOD --
-- ENTER INSIDE PARSE METHOD --
BlockStatementsopt ::=
-- EXIT FROM PARSE METHOD --
-- ENTER INSIDE PARSE METHOD --
EnterCompilationUnit ::=
Modifiersopt ::= Modifiers
RecordHeaderName1 ::= Modifiersopt...
Modifiersopt ::=
Name ::= SimpleName
ClassOrInterface ::= Name
ReferenceType ::= ClassOrInterfaceType
PushZeroTypeAnnotations ::=
Modifiersopt ::= Modifiers
RecordHeaderName1 ::= Modifiersopt...
Modifiersopt ::=
Name ::= SimpleName
ClassOrInterface ::= Name
ReferenceType ::= ClassOrInterfaceType
PushZeroTypeAnnotations ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
Name ::= SimpleName
ClassOrInterface ::= Name
ReferenceType ::= ClassOrInterfaceType
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
Modifiersopt ::=
TypeAnnotationsopt ::=
-- EXIT FROM PARSE METHOD --
```

**Comment by gayanper** [comment]
When record type is correctly written we get this debug output

```
-- ENTER INSIDE PARSE METHOD --
EnterCompilationUnit ::=
Modifiersopt ::= Modifiers
RecordHeaderName1 ::= Modifiersopt...
Modifiersopt ::=
Name ::= SimpleName
ClassOrInterface ::= Name
ReferenceType ::= ClassOrInterfaceType
Dimsopt ::=
RecordComponent ::= Modifiersopt Type...
RecordComponentHeaderRightParen ::= RPAREN
RecordHeader ::= LPAREN RecordComponentsopt...
RecordHeaderPart ::= RecordHeaderName RecordHeader...
RecordBodyDeclarationopt ::=
RecordBody ::= LBRACE RecordBodyDeclarationopt RBRACE
RecordDeclaration ::= RecordHeaderPart RecordBody
InternalCompilationUnit ::= TypeDeclarations
CompilationUnit ::= EnterCompilationUnit...
-- EXIT FROM PARSE METHOD --
```

**Comment by gayanper** [comment]
@stephan-herrmann I did look at the `java.g` while I get some answers from you. I found this

For constructors we define the FormalParamater like follows
```
FormalParameter ::= Modifiersopt Type VariableDeclaratorIdOrThis
/.$putCase consumeFormalParameter(false); $break ./
FormalParameter ::= Modifiersopt Type PushZeroTypeAnnotations '...' VariableDeclaratorIdOrThis
/.$putCase consumeFormalParameter(true); $break ./
/:$compliance 1.5:/
FormalParameter ::= Modifiersopt Type @308... TypeAnnotations '...' VariableDeclaratorIdOrThis
/.$putCase consumeFormalParameter(true); $break ./
/:$readableName FormalParameter:/
/:$compliance 1.8:/
/:$recovery_template Identifier Identifier:/
```

For RecordComponent

```
RecordComponent -> VariableArityRecordComponent
RecordComponent ::= Modifiersopt Type VariableDeclaratorId
/.$putCase consumeRecordComponent(false); $break ./
/:$readableName RecordComponent:/
/:$compliance 14:/

VariableArityRecordComponent ::= Modifiersopt Type PushZeroTypeAnnotations '...' VariableDeclaratorId
/.$putCase consumeRecordComponent(true); $break ./
/:$readableName VariableArityRecordComponent:/
/:$compliance 14:/

VariableArityRecordComponent ::= Modifiersopt Type @308... TypeAnnotations '...' VariableDeclaratorId
/.$putCase consumeRecordComponent(true); $break ./
/:$readableName VariableArityRecordComponent:/
/:$compliance 14:/
/:$recovery_template Identifier Identifier:/
```

Now if i try to understand the grammar from my limited knowledge in it, I see a small difference (I might be wrong as well)

Parameter are define in this order

```
FormalParameter ::= Modifiersopt Type VariableDeclaratorIdOrThis
FormalParameter ::= Modifiersopt Type PushZeroTypeAnnotations '...' VariableDeclaratorIdOrThis
```

But record components are in this order

```
RecordComponent -> VariableArityRecordComponent
RecordComponent ::= Modifiersopt Type VariableDeclaratorId
```

rather than

```
RecordComponent ::= Modifiersopt Type VariableDeclaratorId
RecordComponent -> VariableArityRecordComponent
```

The the line ordering has anything to do with how the parser and scanner works ?

**Comment by gayanper** [comment]
I couldn't try to above my self since i couldn't get hold of Jikes which can run on aarch64

**Comment by stephan-herrmann** [comment]
> The the line ordering has anything to do with how the parser and scanner works ?

The order of parser rules _should_ not have any impact.

**Comment by stephan-herrmann** [comment]
> I couldn't try to above my self since i couldn't get hold of Jikes which can run on aarch64

You saw https://github.com/jikespg/jikespg/tree/fixes-combined ? I have no idea if the sources are ready for aarch64, but that's what I use, i.e., a self-compiled jikespg. You'd only need `gcc`, the makefile doesn't mention anything special. But I can't rule out that some of the includes need special massaging towards aarch64, never tried.

But unless you're curious to try it anywhy, don't waste your time building jikespg. I'll promise to look into this soonish.

**Comment by stephan-herrmann** [comment]
From first experiments in the  debugger I don't see reasons to blame the parser. Construction of RecordComponents can only start with either `,` or a `)` is seen in the expected position, i.e., after type and name of a component. Since the name is missing, we have to rely on recover to provide what CompletionEngine needs.

Let's compare this to completion of method parameters: in that case the `assistNode` will be created in `CompletionParser.checkRecoveredMethod()`, The type name would sit on the `identifierStack` and `getTypeReference()` would wrap the identifier in a `CompletionOnSingleTypeReference`.

But in the record case, that `currentElement` is not a `RecoveredMethod` but a `RecoveredType`, so we would need to do the required work in `CompletionParser.checkRecoveredType()`. In that method only two situations are handled:
* any orphaned node after `{`
* a type references after `extends`.

For an experiment I added this in `checkRecoveredType` (stolen from checkRecoveredMethod, added towards the end):
```
			if (this.lastIgnoredToken == -1) {
				//if (rParenPos < lParenPos){ // inside arguments
				this.assistNode = this.getTypeReference(0);
				this.lastCheckPoint = this.assistNode.sourceEnd + 1;
				this.isOrphanCompletionNode = true;
				return true;
			}
```
This already achieves that in `CompletionParser.endParse()` we will see `<CompleteOnType:Strin>` as our `assistNode`. How is that? :)

(The above snippet must be guarded with a check whether the type is actually a record.)

Next we "only" need to find a way, how to attached the orphaned assistNode into the typeDeclaration...

**Comment by gayanper** [comment]
I did change the code and try to attache the node we found as a local field type into the recovered type. I will test more why my test is failing. I used `CompletionTests14` and for some reason I don't get type ref proposals, Even if I try to change test to complete on the field type on class. I will check more tomorrow.

**Comment by gayanper** [comment]
Did test the code change in Eclipse seems the Type completions are working, Not need to work on the name completions for record components. But first I need to find the problem with the UnitTest.

**Comment by gayanper** [comment]
@stephan-herrmann All issues solved, I will take bit more time to see if I can easily fix the name suggestions as well since that will complete the record component completions.

**Comment by srikanth-sankaran** [comment]
This fix causes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1095 - Working on it.
