### ISSUE TITLE
Content assist not working inside lambda expression

### ISSUE THREAD

**Issue by NathanSweet** [eclipse-jdt/eclipse.jdt.core#708]
I found that Open Declaration fails on the code below, likely due to switch expressions.

```java
public class Test {
	public void test (Type type, String string) {
		switch (type) {
		case openDeclarationFails -> {
			switch (string) {
			// Open Declaration on "openDeclarationFails" does nothing except making an error sound.
			// Open Declaration on "Type" opens the "Open" dialog to search for an element to open.
			// Ctrl+click on "Type" opens com.sun.tools.javac.code.Type, a seemingly random class with the same same.
			case "Test" -> method(Type.openDeclarationFails);
			}
		}
		case anotherValue -> { // Open Declaration on "anotherValue" fails.
			switch (string) { // Open Declaration on "string" fails.
			case "Test" -> method(Type.anotherValue); // The above works as expected here.
			}
		}
		}
	}

	private void method (Type relay) {
	}

	static public enum Type {
		openDeclarationFails, anotherValue;
	}
}
```

I'm posting this issue here as suggested in an [older issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=562551#c17).

**Comment by jarthana** [comment]
I found this to be due to the `->` being considered as lambda by the assist parser. And this is because, when we know we are dealing with a switch expression, we should push a `K_SWITCH_EXPRESSION_DELIMITTER `into the element kind stack. Thanks to our parser, I can simply do this when I find the `TokenNameBeginCaseExpr `inside `consumeToken()`.

**Comment by jarthana** [comment]
Nathan, I just released a fix which should be available in tomorrow's build. If possible, please try it out and let me know.

**Comment by jarthana** [comment]
For the records, we found one test failing (#715) with this patch, which has since been fixed.

**Comment by NathanSweet** [comment]
Confirmed, it seems to be working well. Cheers!

**Comment by trancexpress** [comment]
Looks like this caused a regression: #968
