### ISSUE TITLE
[20][pattern switch] Dominance on Erasure Types - no error reported

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#711]
Ref: https://cr.openjdk.java.net/~gbierman/jep432%2b433/jep432+433-20221115/specs/patterns-switch-record-patterns-jls.html
Section: 14.11.1 - example on erasure type dominance
A self contained test case below:

import java.util.ArrayList;
import java.util.List;

public class X {

	@SuppressWarnings("preview")
	public static void foo(List<Number> l) {
		switch (l) {
		    case ArrayList<Number> al -> 
		        System.out.println("An ArrayList of Number");
		    case ArrayList<? extends Number> aln -> // Error - dominated case label
		        System.out.println("An ArrayList of Number");
		    default -> 
		        System.out.println("A List");
		}
	}

}

**Comment by jarthana** [comment]
Fix and tests released via #732
