### ISSUE TITLE
Provide "Convert to Text Block" quick fix

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdt/eclipse.jdt.core#718]
Legacy codebases are littered with string concatenations like:

```
var foo = "package java;\n\n" +
			"public class Completion {\n" +
			"	void foo() {\n" +
			"		String str = new String(\"hello\");\n" +
			"		str.starts" +
			"	}\n" +
			"}\n");
```

If the project compiles against Java 17 or more recent, we should have a refactoring option to convert those string concatenations to text blocks, like IntelliJ IDEA does

![Feb-09-2023 16-51-38](https://user-images.githubusercontent.com/148698/217865362-a21ecd5c-fb97-4543-9a31-50731b754140.gif)

Bonus points for doing the same when a StringBuffer or StringBuilder is used for concatenation.
```
StringBuilder bufC = new StringBuilder();
bufC.append("package bar;\n");
bufC.append("public class Bar {\n");
bufC.append(" int v = BaseFoo.VAL;\n");
bufC.append("}");
```

This need to be implemented in jdt.core so that jdt.ls can reuse it.

**Comment by fbricon** [comment]
Previously opened as https://bugs.eclipse.org/bugs/show_bug.cgi?id=559763

**Comment by iloveeclipse** [comment]
Interestingly, I see there a custom "Cleanup" already available - just not present as a "Refactor" or "Ctrl+1 -> Convert to Text Block": 
![image](https://user-images.githubusercontent.com/964108/217878054-7ffbfcfa-990f-40c1-885a-93a1e858d895.png)

@jjohnstn : do you have an idea if that would be difficult to re-use this cleanup code and provide a **quick fix** "Convert to a Text Block"?
That would be really handy.

**Comment by jjohnstn** [comment]
@iloveeclipse We've converted cleanups to quick fixes before so should be straightforward.  I'll start looking at it.  I'll also be sure to make sure that the quick fix is accessible by jdt.ls.

**Comment by jjohnstn** [comment]
@fbricon @iloveeclipse Sorry for the delay but I finally took a look at this in detail and found out it is already a quick assist in QuickAssistProcessor.  Works for the sample code above and if the light bulb option is on, it shows it.  There is no current support for StringBuffer/StringBuilder concatenation but I can certainly work on it.  There is already a StringConcatToTextBlockFixCore class which is in jdt.core.manipulation but there is also some code in QuickAssistProcessor that wraps the fix in a FixCorrectionProposal which is jdt.ui.  I will leave it to jdt.ls folks to say what they have done with existing assists in the QuickAssistProcessor (in jdt.ui) that are also supported in jdt.ls.  If it is not straightforward, perhaps we can find a more generic method to use that eases the burden.

**Comment by iloveeclipse** [comment]
Strange, looks like it is not activated in all cases where String concatenation is used?

**Comment by fbricon** [comment]
Sorry, I was actually not seeing the option in the Refactoring menu (my initial request), but it's absolutely found when popping up quickfixes. 
![Feb-10-2023 10-10-12](https://user-images.githubusercontent.com/148698/218050832-dc9e3d3f-5408-4697-bb61-ce121753fc27.gif)

@jjohnstn thanks for the pointer, I got it working in jdt.ls (and vscode-java) in a few minutes: 
![Feb-10-2023 10-02-47](https://user-images.githubusercontent.com/148698/218049327-022ca94b-807f-4c32-8506-3509bb71404c.gif).

Unless @iloveeclipse want to turn this ticket into a bug report, because the fix is not available in some cases, I'm OK to close this.  https://bugs.eclipse.org/bugs/show_bug.cgi?id=559763 should be closed too.

**Comment by iloveeclipse** [comment]
Hmm, today it works. Not sure what is different except new (+1 day) SDK build. Sorry Jeff for noise.

**Comment by jjohnstn** [comment]
I have created https://github.com/eclipse-jdt/eclipse.jdt.core/issues/725
