### ISSUE TITLE
ambigious call for jdk >=13

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#722]
in org.eclipse.jdt.internal.compiler.util.Util.getZipEntryClassFile(String, String)
![image](https://user-images.githubusercontent.com/51790620/218073019-36100b68-519d-4ee2-8058-5e8cf27a2eca.png)
@jarthana 
you can use `FileSystems.newFileSystem(zipfile, (ClassLoader) null)`

java.nio.file.FileSystems.newFileSystem(Path, Map<String, ?>) was added in 13

**Comment by jarthana** [comment]
This happens when BREE 11 is mapped to a newer JDK. Now, if I change the code to make it work with JDK > 13, we might get a warning about an unused type cast. May be we can take this up when we move up to Java 11, eventually.

**Comment by jarthana** [comment]
> This happens when BREE 11 is mapped to a newer JDK. Now, if I change the code to make it work with JDK > 13, we might get a warning about an unused type cast. May be we can take this up when we move up to Java 11, eventually.

OK, I was wrong about the warning part. I don't see a warning about the cast. I will fix this for M3.

**Comment by iloveeclipse** [comment]
> I will fix this for M3.

Jay, that is already fixed.
