### ISSUE TITLE
[20] Implement type inference for Record patterns

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#737]
This section describes type inference in record patterns:

https://cr.openjdk.java.net/~gbierman/jep432%2b433/jep432+433-20221115/specs/patterns-switch-record-patterns-jls.html#jls-18.5.5

At this point, we don't know what it takes to complete this, but first we should remove the code we added that rejects raw types in record patterns. That was done just to mimic Javac during the Java 19 work.

**Comment by mpalat** [comment]
This was taken care by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/829
