### ISSUE TITLE
[critical] No references are found for methods used inside lambda

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#754]
No references are found for methods used inside lambda expressions in pre-release

##### Environment
- Operating System: All
- JDK version: 17
- Visual Studio Code version: 1.75.1 
- Java extension version: v1.15.2023021503

##### Steps To Reproduce
1. Search for method references of the method that is used inside lambda expressions or blocks

##### Current Result
No references are found

##### Expected Result
Lambda usage references must be counted as well.

Suspected regression of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/432

**Comment by gayanper** [comment]
@iloveeclipse we probably need to include this in 4.27.  @trancexpress will you be able to have a look at this if its a regression?

**Comment by iloveeclipse** [comment]
@gayanper : 
1) Could you please provide a simple snippet showing what is not found? 
2) Which Eclipse build do you use?

**Comment by trancexpress** [comment]
I don't see how this can be a regression from #432. The change was: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/94bf6fbdefa8c09e4cd1c7547bcc36ca90987cb8#diff-89a90ed8e05661ffcc6ede6ca9d3268e3d7a771155fde46f8cb3ff82e8626569

At most we are pruning less, not more. Maybe a regression from something else though. Recently we did a lot of changes to the search related to modules.

**Comment by iloveeclipse** [comment]
I can't reproduce, please provide a snippet.

**Comment by iloveeclipse** [comment]
May be you see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/740? That should be fixed already.

**Comment by gayanper** [comment]
Will test with lastest i build soon. Found in pre-release vscode-java. Will use the latest jdt core modules and test out soon and update here

**Comment by gayanper** [comment]
seems like the problem existed in I20230212-1800, but with the latest build the problem is not there. Therefore closing the issue

**Comment by trancexpress** [comment]
Must be #740 then. We introduced the bug around that time.
