### ISSUE TITLE
Eclipse JDT produces bytecode that can't be indexed by Jandex

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-jdt/eclipse.jdt.core#756]
Eclipse JDT produces bytecode that can't be indexed by Jandex. 
There is an issue in Jandex about that (https://github.com/smallrye/jandex/issues/32) but i think it's a JDT bug.
Example :

```
package test;

import java.util.*;

public class A {

  public static void main(String[] args) {
    EList<Object> requireNonNullElseGet = Objects.requireNonNullElseGet(null, EList<Object>::new);
    System.out.println(requireNonNullElseGet);
  }

  static class EList<T> implements Iterable<T> {

    public EList(T... varArgs) { // This is the varatgs that produces the "bad" bytecode
    }

    @Override
    public Iterator<T> iterator() {
      return null;
    }

  }
}
```

When trying to index the class generated by Eclipse with the above code, we get this :

Exception in thread "main" java.lang.IllegalArgumentException: Expected character '^' at position 2
	at org.jboss.jandex.GenericSignatureParser.expect(GenericSignatureParser.java:262)
	at org.jboss.jandex.GenericSignatureParser.parseMethodSignature(GenericSignatureParser.java:298)
	at org.jboss.jandex.Indexer.parseMethodSignature(Indexer.java:1440)
	at org.jboss.jandex.Indexer.applySignatures(Indexer.java:1427)
	at org.jboss.jandex.Indexer.index(Indexer.java:1987)
	at test.Main.main(Main.java:10)

There is no problem with the class generated by Javac.

My Main to test :
```
package test;

import java.io.*;

import org.jboss.jandex.*;

public class Main {

  public static void main(String[] args) throws FileNotFoundException, IOException {
    new Indexer().index(new FileInputStream(new File("A.class")));
  }
}
```

**Comment by iloveeclipse** [comment]
@RoiSoleil : could you please attach a self contained project that has all required libraries to reproduce the problem?

Why do you think if the 3rd party library can't parse bytecode, it is a bug in JDT and not in the 3rd party bytecode parser?

**Comment by iloveeclipse** [comment]
Actually I can reproduce without the "Indexer" from Jandex.
Just have Bytecode Outline view opened in 4.27 master and get this error:
```
Cannot decompile: [Working copy] A.java [in test [in src [in A2]]]
  package test
  import java.util.*
  class A
    static void main(String[])
    class EList
      EList(T ...)
      Iterator<T> iterator() null

java.lang.IllegalArgumentException
	at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:249)
	at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:114)
	at org.objectweb.asm.util.Textifier.appendJavaDeclaration(Textifier.java:1349)
	at org.objectweb.asm.util.Textifier.visitMethod(Textifier.java:418)
	at org.eclipse.jdt.bcoview.asm.CommentedClassVisitor.visitMethod(CommentedClassVisitor.java:164)
	at org.eclipse.jdt.bcoview.asm.CommentedClassVisitor.visitMethod(CommentedClassVisitor.java:1)
	at org.objectweb.asm.util.TraceClassVisitor.visitMethod(TraceClassVisitor.java:230)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:645)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:468)
	at org.eclipse.jdt.bcoview.asm.DecompilerHelper.getDecompiledClass(DecompilerHelper.java:44)
	at org.eclipse.jdt.bcoview.views.BytecodeOutlineView.decompileBytecode(BytecodeOutlineView.java:1458)
	at org.eclipse.jdt.bcoview.views.BytecodeOutlineView.refreshView(BytecodeOutlineView.java:1054)
	at org.eclipse.jdt.bcoview.views.BytecodeOutlineView.handlePartVisible(BytecodeOutlineView.java:951)
	at org.eclipse.jdt.bcoview.views.EditorListener.partOpened(EditorListener.java:121)
	at org.eclipse.ui.internal.PartService$10.run(PartService.java:193)
```

**Comment by Ladicek** [comment]
Hi, Jandex maintainer here (the bytecode parsing library in question).

Here's a minimal reproducer:

```java
import java.util.function.Supplier;
  
public class MyList<T> {
    public MyList(T... elements) {
    }

    public static Supplier<? extends MyList<Object>> supplier() {
        return MyList<Object>::new;
    }
}
```

Compile with ECJ like this:

```bash
java -jar ecj-4.26.jar -17 MyList.java
```

And inspect the generated bytecode using `javap`:

```bash
javap -v -p MyList.class
```

You'll notice that the generated signature for the synthetic lambda method is `()+LMyList<Ljava/lang/Object;>;`. That doesn't conform to the grammar in the JVMS, [chapter 4.7.9.1](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.7.9.1).

**Comment by iloveeclipse** [comment]
- [ecj_421_dump.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10757638/ecj_421_dump.txt)
- [ecj_dump.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/10757639/ecj_dump.txt)

ECJ generates this (4.21 and 4.27 master are generating same code):
```
  private static ? extends MyList<java.lang.Object> lambda$1();
    descriptor: ()LMyList;
    flags: (0x100a) ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Signature: #29                          // ()+LMyList<Ljava/lang/Object;>;
    Code:
      stack=3, locals=0, args_size=0
         0: new           #1                  // class MyList
         3: dup
         4: iconst_0
         5: anewarray     #3                  // class java/lang/Object
         8: invokespecial #30                 // Method "<init>":([Ljava/lang/Object;)V
        11: areturn
      LineNumberTable:
        line 1: 0
```

javac generates this
```
  private static MyList lambda$supplier$0();
    descriptor: ()LMyList;
    flags: (0x100a) ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=3, locals=0, args_size=0
         0: new           #3                  // class MyList
         3: dup
         4: iconst_0
         5: anewarray     #4                  // class java/lang/Object
         8: invokespecial #5                  // Method "<init>":([Ljava/lang/Object;)V
        11: areturn
      LineNumberTable:
        line 8: 0
```

**Comment by Ladicek** [comment]
Aside: one funny thing is that `javap` doesn't hesitate to print `private static ? extends MyList<java.lang.Object> lambda$1();`, which clearly contains an invalid return type :-)

**Comment by iloveeclipse** [comment]
`? extends MyList<java.lang.Object>` as return type for synthetic `lambda$1` method seem to be strange, differs from simple `MyList` of javac.

**Comment by Ladicek** [comment]
Because javac doesn't emit the signature. (And hence `javap` prints a return type based on the descriptor.)

**Comment by iloveeclipse** [comment]
@othomann, @stephan-herrmann : could you please look at the lambda generation above? It is not a recent regression, so is not something I can easily spot.

**Comment by RoiSoleil** [comment]
Nice to see that it's quickly handled ;) Thx

**Comment by stephan-herrmann** [comment]
> `? extends MyList<java.lang.Object>` as return type for synthetic `lambda$1` method seem to be strange, differs from simple `MyList` of javac.

I think from a type inference p.o.v. that return type is correct (modulo wildcard capture), since the method implements `Supplier<? extends MyList<Object>>`.  Simple `MyList`, OTOH, is correct from a JVM p.o.v. 

Without having debugged the sample, my guess is: ecj sees good reason to generate a signature attribute (not needed by the JVM, but useful for tools and reflection), but then JVMS doesn't specify syntax for this type. In other similar bugs we learned that the compiler should simply refuse generating the signature, reasoning that even if the compiler should normally generate this attribute, we should rather err on the side of missing information in the byte code, rather than emitting illegal signatures. We probably need to implement more heuristics, which signatures should be avoided.

This could be further complicated if it's the same implementation where internally JDT expects some signature _always_, and now for code generation it must refuse to compute a signature.

**Comment by RoiSoleil** [comment]
Any news about that ?

**Comment by srikanth-sankaran** [comment]
See https://mail.openjdk.org/pipermail/compiler-dev/2015-January/009268.html - javac never generates Signature attributes for synthetic lambda body methods. 

See also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=449063

I'll investigate

**Comment by srikanth-sankaran** [comment]
I have raised a PR that is undergoing test - apart from the code freeze period coming in the way, there is also some problems with my old and new eclipse identities colliding in various manner. So, this will take a while to get integrated into mainline, but if someone wants to test against their tooling/library environments, then the patch can be grabbed (after Jenkins blesses it)

**Comment by stephan-herrmann** [comment]
More prior art FYI: https://bugs.eclipse.org/bugs/show_bug.cgi?id=494198 where we approximate by erasure rather than dropping the signature.

**Comment by srikanth-sankaran** [comment]
Thanks, for good or bad, I will try aligning with this prior strategy.

**Comment by srikanth-sankaran** [comment]
Food for thought: This fix ought to leave in us a better place but I wonder if "approximate by erasure" results in coarseness. I wonder if we should reach for the bounds suitably instead in the case of wildcards.

**Comment by stephan-herrmann** [comment]
> Food for thought: This fix ought to leave in us a better place but I wonder if "approximate by erasure" results in coarseness. I wonder if we should reach for the bounds suitably instead in the case of wildcards.

When asking which strategy would be 'better', do we have any metric for this, i.e., what would be our goals (in which priority):
* don't crash
* don't let tools reading our class files crash
* don't violate JVMS
* mimic (exactly?) what javac does
* use our own judgement which strategy (roughly within JVMS) might provide most value to tools and reflection

**Comment by srikanth-sankaran** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1048 - while the GFE goes away. encoding the generic signature as ()Ljava/util/stream/Stream<TT;>;  appears problematic - I am yet to fully analyze.

**Comment by srikanth-sankaran** [comment]
> > Food for thought: This fix ought to leave in us a better place but I wonder if "approximate by erasure" results in coarseness. I wonder if we should reach for the bounds suitably instead in the case of wildcards.
> 
> When asking which strategy would be 'better', do we have any metric for this, i.e., what would be our goals (in which priority):
> 
> * don't crash
> * don't let tools reading our class files crash
> * don't violate JVMS
> * mimic (exactly?) what javac does
> * use our own judgement which strategy (roughly within JVMS) might provide most value to tools and reflection

We are using the "use our own approach ..." here to accomplish some of the earlier bullets. Javac doesn't emit generic signature for synthetic methods at all - I think we should in the cases where the signature is non denotable do exactly that.

Lengthy discussion here: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/414

**Comment by srikanth-sankaran** [comment]
FTR, pursuant to discussion at https://github.com/eclipse-jdt/eclipse.jdt.core/pull/414, the PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1070 replaces the approximate-by-erasure strategy implemented for this ticket with "skip generic signature emission for synthetic methods if non denotable types are involved" strategy.
