### ISSUE TITLE
[20][pattern switch] unnecessary code generated

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#773]
check:
public class X {
	
	public static void main(String[] args) {
		Object o = null;
		foo(new R());
	}
	@SuppressWarnings("preview")
	public static void foo(Object o) {
		switch (o) {
	    case R():                         // Multiple case labels!
	        System.out.println("R Only");
	    case S():                         // Multiple case labels!
	        System.out.println("Either S or an R");
	        break;
	    default:
	}      
	}
} 
 
record R() {}  
record S() {}              

see :
  // Method descriptor #22 (Ljava/lang/Object;)V
  // Stack: 2, Locals: 3
  public static void foo(java.lang.Object o);
     0  aload_0 [o]
     1  dup
     2  invokestatic java.util.Objects.requireNonNull(java.lang.Object) : java.lang.Object [27]
     5  pop
     6  astore_1
     7  iconst_0
     8  istore_2
     9  aload_1
    10  iload_2
    11  invokedynamic 0 typeSwitch(java.lang.Object, int) : int [33]
    16  tableswitch default: 72
          case 0: 40
          case 1: 56
    40  goto 48
    43  iconst_1
    44  istore_2
    45  goto 9
    48  getstatic java.lang.System.out : java.io.PrintStream [37]
    51  ldc <String "R Only"> [43]
    53  invokevirtual java.io.PrintStream.println(java.lang.String) : void [45]
    56  goto 64
    59  iconst_2
    60  istore_2
    61  goto 9
    64  getstatic java.lang.System.out : java.io.PrintStream [37]
    67  ldc <String "Either S or an R"> [51]
    69  invokevirtual java.io.PrintStream.println(java.lang.String) : void [45]
    72  return

Line numbers 43-45 [and consequently goto at 40) and similarly 56-61 are unnecessary. To check

**Comment by iloveeclipse** [comment]
@srikanth-sankaran : something for you?

**Comment by srikanth-sankaran** [comment]
With https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2011, we now generate:

```
  // Method descriptor #22 (Ljava/lang/Object;)V\n
  // Stack: 2, Locals: 3\n
  public static void foo(java.lang.Object o);\n
     0  aload_0 [o]\n
     1  dup\n
     2  invokestatic java.util.Objects.requireNonNull(java.lang.Object) : java.lang.Object [27]\n
     5  pop\n
     6  astore_1\n
     7  iconst_0\n
     8  istore_2\n
     9  aload_1\n
    10  iload_2\n
    11  invokedynamic 0 typeSwitch(java.lang.Object, int) : int [33]\n
    16  tableswitch default: 56\n
          case 0: 40\n
          case 1: 48\n
    40  getstatic java.lang.System.out : java.io.PrintStream [37]\n
    43  ldc <String "R Only"> [43]\n
    45  invokevirtual java.io.PrintStream.println(java.lang.String) : void [45]\n
    48  getstatic java.lang.System.out : java.io.PrintStream [37]\n
    51  ldc <String "Either S or an R"> [51]\n
    53  invokevirtual java.io.PrintStream.println(java.lang.String) : void [45]\n
    56  return\n
```

**Comment by srikanth-sankaran** [comment]
PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2011 fixes this problem, but is this a "real problem" ? Will anyone declare records with no components ? The very idea of records is that they are data carriers - to declare a record class with no data seems pointless - no ? Did I miss something ?
