### ISSUE TITLE
Full Java indexing on large project with many jar dependies takes a lot of time

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-jdt/eclipse.jdt.core#78]
Full Java indexing on large project with many jar dependies takes a lot of time
Creation of JavaSearchEnvironment for every SourceIndexer#resolveDocument is time a consuming. We need to share the JavaSearchEnvironment between compatible SourceIndexer request.

**Comment by jukzi** [comment]
closing due to lack of information provided.
