### ISSUE TITLE
[20][record pattern][dom ast] DOM changes

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#784]
Implement the changes in DOM for record patterns - create more issues as deemed necessary
- enable [org.eclipse.jdt.core.tests.rewrite.describing.ASTRewritingRecordPatternTest.testModifyRecordSwitchPattern - JLS20] once this is done

**Comment by mpalat** [comment]
ref https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/494
and https://github.com/eclipse-jdt/eclipse.jdt.core/issues/884

**Comment by jarthana** [comment]
The reported issues have been fixed and a new DOM AST node has been added to support record patterns in foreach. This can be closed now.
