### ISSUE TITLE
[20][record pattern][search] - Make changes to search support for record patterns

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#785]
org.eclipse.jdt.core.tests.model.JavaSearchBugs19Tests.testIssue215_001
org.eclipse.jdt.core.tests.model.JavaSearchBugs19Tests.testIssue215_003
org.eclipse.jdt.core.tests.model.JavaSearchBugs19Tests.testIssue215_004
org.eclipse.jdt.core.tests.model.JavaSearchBugs19Tests.testIssue215_005
org.eclipse.jdt.core.tests.model.JavaSearchBugs19Tests.testIssue215_006
org.eclipse.jdt.core.tests.model.JavaSearchBugs19Tests.testIssue215_007
org.eclipse.jdt.core.tests.model.JavaSearchBugs19Tests.testIssue215_011

**Comment by akurtakov** [comment]
Are these tests failing right now ? I just run them and they finished properly so it's unclear to me what's needed here.

**Comment by rgrunber** [comment]
Looks to me like https://github.com/eclipse-jdt/eclipse.jdt.core/pull/231 supported this.

**Comment by mpalat** [comment]
Nothing more needed on search. resolving
