### ISSUE TITLE
[20][record pattern][test] RecordPatternTests - test25 and test28 failure with javac

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#786]
RecordPatternTests - test25 and test28  with the following additional VM args:
-Drun.javac=enabled -Djdk.root=<path>JDKs/20/ea34/jdk-20.jdk/Contents/Home --enable-preview

fail with Error: LinkageError occurred while loading main class p.X\n
	java.lang.UnsupportedClassVersionError: p/X has been compiled by a more recent version of the Java Runtime (class file version 64.65535), this version of the Java Runtime only recognizes class file versions up to 61.0\n
Investigate

**Comment by jarthana** [comment]
The solution is to skip the tests since Javac fails those tests.
