### ISSUE TITLE
[20] Record pattern in foreach leaks the secret recordPatternVar in UI

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#833]
Having a record pattern in foreach like below brings up a warning about preview features being used.  This is expected, However, one of the quick fixes offered is "Add @SuppressWarning to recordPatternVar".

```
        for (R(int x) : recArray) {
            ret = true;
        }
```

This variable should not be exposed to the user at all.
Copying @mpalat

**Comment by srikanth-sankaran** [comment]
PR https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1909 gets rid of this secret variable and all traces of support for record pattern as element variable type in foreach loop

**Comment by srikanth-sankaran** [comment]
In any case this can be closed since this feature is withdrawn by JEP 440
