### ISSUE TITLE
Bad selection for method call with nested instanceof argument

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#848]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=575150

Navigate to the call to `CompletionEngine.findMethods()` in `CompletionEngine.completionOnMessageSend()`, try computing a call hierarchy or using F3, observe nothing meaningful is shown.

The method is:

```
org.eclipse.jdt.internal.codeassist.CompletionEngine.findMethods(char[], TypeBinding[], TypeBinding[], ReferenceBinding, Scope, ObjectVector, boolean, boolean, InvocationSite, Scope, boolean, boolean, boolean, Binding[], int[], int[], boolean, char[], int, int)
```

Reproducible also with:

```
public class Test {

	public static class X {
		public Object o = new Object();
	}

	public static void main(String[] args) {
		X x = new X();
		foo(
			x.o instanceof Object
		);
	}

	private static void foo(boolean b) {
	}
}
```

Select the call to `foo()` in `main()` and use F3, see the status error text in the bottom left (the left part of the status line).

**Comment by trancexpress** [comment]
If I remove `SelectionParser.consumeInstanceOfExpression()`, which was added for https://bugs.eclipse.org/bugs/show_bug.cgi?id=577508, the bug is gone. Oddly, Stephan reported the bug against 4.21 and supposedly the change was done for 4.22+...

**Comment by iloveeclipse** [comment]
Just another manifestation of same issue from #853 :
```
import java.util.concurrent.CompletableFuture;

public class F3NotWorking {
    public CompletableFuture<String> readOutStream() {
        return CompletableFuture.supplyAsync(() -> { // <-- F3 to open supplyAsync() declaration doesn't work
        	try {
                return "";
            } catch (Throwable e) {
                String message = "";
                if (e instanceof Exception) { // replace with message == "" and F3 will work again
                    message = "This instanceof breaks F3 above!!!";
                }
                throw new RuntimeException(message, e);
            }
        });
    }
}
```

**Comment by mpalat** [comment]
Moving this out of M1

**Comment by srikanth-sankaran** [comment]
I can review this candidate fix early next week.

**Comment by trancexpress** [comment]
I checked, this is fixed with: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1028
