### ISSUE TITLE
Invalid code not rejected by compiler

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.core#859]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=481133

Snippet:

```
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * CFSXXX
 * 
 * @author connors
 */
public class CFSXXX {

    public static void main(String[] args) {
        boolean mybool_XXXWhoopsGotTheWrongNameHereXXX = true;
        if (mybool) {
            System.out.println("within if - true part");
            setSupplier(() -> x -> System.out.println("x" + x); );
        } else {
            System.out.println("within if - false part");
        }
    }
    
    public static void setSupplier(Supplier<Consumer<String>> supplier) {
        System.out.println("setSupplier called: " + supplier);
    }
}
```

This code should not compile, but does with Eclipse. E.g. `javac` reports errors:

```
CFSXXX.java:16: error: ')' expected
            setSupplier(() -> x -> System.out.println("x" + x); );
                                                              ^
CFSXXX.java:16: error: illegal start of expression
            setSupplier(() -> x -> System.out.println("x" + x); );
                                                                ^
2 errors
```

**Comment by trancexpress** [comment]
First `ecj` version that supports `-source 1.8` is 4.4, the bug already exists there. So not a regression.

**Comment by trancexpress** [comment]
I don't really understand the comment above in the fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=383046 ...

```
https://bugs.eclipse.org/bugs/show_bug.cgi?id=383046, we should never ever report the diagnostic, "Syntax error, insert ElidedSemicolonAndRightBraceto complete LambdaBody"
```

For this snippet:

```
public class X {
	public interface S<T> {
	    T s(T t);
	}
    public void f() {
    	S<?> s = v -> v ) ;
    	{} // empty block to force scope handling for the lambda line
    }
}
```

`ecj` reports:

```
----------
1. ERROR in /data/workspaces/runtime-Eclipse/TestBug481133/src/X.java (at line 6)
        S<?> s = v -> v ) ;
                        ^
Syntax error on token ")", ElidedSemicolonAndRightBrace expected
----------
1 problem (1 error)
```

Here the `SUBSTITUTION_CODE` branch is taken (value of `SecondaryRepairInfo.code`)... Unlike `SCOPE_CODE` it apparently doesn't care about `ElidedSemicolonAndRightBrace`?

Also is text like this expected in an error message from a compiler? And is the error above much different to the one from the comment?

**Comment by trancexpress** [comment]
@srikanth-sankaran , first and foremost, great to see you are working again on JDT!

If you have time in future, it would be great if you can take a look here, as well as #125, #367 and #904. I believe those issues are all closely related, if not one and the same bug.

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran , first and foremost, great to see you are working again on JDT!
> 
> If you have time in future, it would be great if you can take a look here, as well as #125, #367 and #904. I believe those issues are all closely related, if not one and the same bug.

Yes, @trancexpress, I will take a look at these in due course. Thanks for the pointers

**Comment by srikanth-sankaran** [comment]
This is the same issue as https://github.com/eclipse-jdt/eclipse.jdt.core/issues/367 - My candidate fix for that ticket handles the code snippets here correctly - as in rejects them. I will include the test case from here in my patch for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/367 and add my observations there.

**Comment by srikanth-sankaran** [comment]
@trancexpress, some explanations:

(1) "we should never ever report the diagnostic, "Syntax error, insert ElidedSemicolonAndRightBrace to complete LambdaBody""

There are two reasons for this comment:

(i) ElidedSemicolonAndRightBrace is an internal synthetic token. A programmer can do NOTHING on his/her accord to insert these tokens at the indicated place. So including such tokens in messages addressed to the users is wasteful, confusing, not actionable and needlessly exposing internal implementation details.

(2) The above is also entirely true of the synthetic tokens handled by ProblemReporter.replaceIfSynthetic(String) but ElidedSemicolonAndRightBrace  is special for one crucial difference: ElidedSemicolonAndRightBrace is synthesized and inserted right after a non-block lambda, on the fly by the Parser in *normal parsing itself* - OIOW, normal parsing itself does some amount of "repair" of the input stream to reduce a lambda expression. The other synthetic tokens are inserted into the stream by the scanner but ElidedSemicolonAndRightBrace is not returned by the scanner  (See point 4 in https://bugs.eclipse.org/bugs/show_bug.cgi?id=380194#c15) 

When the DiagnoseParser is coming up with a recommendation to  " insert ElidedSemicolonAndRightBrace to complete LambdaBody" - it is likely mimicking the Parser's own repair of the input stream done at

org.eclipse.jdt.internal.compiler.parser.Parser.consumeElidedLeftBraceAndReturn() and
org.eclipse.jdt.internal.compiler.parser.Parser.consumeExpression()

If that is all there is to it (the assumption when I short circuited that error emission with a break), things would be fine. I think what I overlooked is that DiagnoseParser has its own complicated repair mechanism which can sometimes skip ahead past several tokens until it reaches a certain point of predictability. This skipping past subsequent tokens results in subsequent errors to be not reported and with my code short circuiting the initial error ( insert ElidedSemicolonAndRightBrace to ...) no error shows up leading to the impression that the code is compiled fine.

I am testing a candidate fix that would (a) not expose internal non-actionable synthetic tokens but (b) will still surface a generic/bland error message that is "quite correct"

First order business being to reject invalid programs correctly, quality of diagnostics being secondary to correctness.

I'll wait until https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1045 to make any improvements to quality of diagnostics.
Some of these parsing magic may be gotten rid of - who knows.

**Comment by srikanth-sankaran** [comment]
So in summary, injection of ElidedSemicolonAndRightBrace to reduce a lambda expression is normal part of business. So it makes sense to not show that in an error message.

What was a complete surprise (and hence resulted in this cluster of bugs) was that after thus repairing the input stream, the DiagnoseParser  would have been expected to report "some" additional error as it chewed the input stream further. That it skipped further input was something (I and my) the code was not prepared for.

**Comment by trancexpress** [comment]
Alright, thank you for the explanations.

**Comment by srikanth-sankaran** [comment]
Here is an experiment that sheds light on how insertion of ElidedSemicolonAndRightBrace is "normal" part of business of parsing lambda expressions, be it by Parser or DiagnoseParser.

(1) Comment out the code:
```
if (insertedToken == TokenNameElidedSemicolonAndRightBrace) {
    /* https://bugs.eclipse.org/bugs/show_bug.cgi?id=383046, we should never ever report the diagnostic, "Syntax error, insert ElidedSemicolonAndRightBraceto complete LambdaBody"
	as it is a synthetic token. Instead we should simply repair and move on. See how the regular Parser behaves at Parser.consumeElidedLeftBraceAndReturn and Parser.consumeExpression.
        See also: point (4) in https://bugs.eclipse.org/bugs/show_bug.cgi?id=380194#c15
  */
	break;
}
``` 

(2) Now compiling this code: 
```
interface IX {
    public void foo();
}
public class X {
    IX i = () -> 42;
    int x
}
```

results in the perfectly (syntactically) valid lambda being rejected:

```
1. ERROR in X.java (at line 5)
	IX i = () -> 42;
	             ^^
Syntax error, insert "ElidedSemicolonAndRightBrace" to complete LambdaBody

2. ERROR in X.java (at line 5)
	IX i = () -> 42;
	             ^^
Void methods cannot return a value
----------
3. ERROR in X.java (at line 6)
	int x
	    ^
Syntax error, insert ";" to complete FieldDeclaration
``` 

(It is worth investigating why the DiagnoseParser skips past several tokens resulting in no further error at all in the test cases for this cluster of duplicate defects)
