### ISSUE TITLE
getAttachedJavadoc() returns null if method has more than one argument [Java 11]

### ISSUE THREAD

**Issue by kem41k** [eclipse-jdt/eclipse.jdt.core#865]
Hi, I'm using the following Eclipse 
Version: 2022-09 (4.25)
Build id: I20220831-1800

I faced a problem with getting Javadoc after migration from Java 8 to Java 11. `getAttachedJavadoc()` returns null if the method has more than one argument. 

I started to delve into the problem and realized following:
1. Imagine that javadoc-style comment is written to `myMethod(int arg0, double arg1, boolean arg2)` method
2. Javadoc anchor generated by Java 8 has dashes: `myMethod-int-double-boolean-`
3. At the same time, javadoc anchor generated by Java 11 looks like: `myMethod(int,double,boolean)`

The problem is that under the hood `getAttachedJavadoc()` is looking for `myMethod(int, double, boolean)` (**extra space after each comma!**), then it looks for `myMethod-int-double-boolean-` (see `org.eclipse.jdt.internal.core.JavadocContents.getJavadoc8Anchor(char[])`) and only after that returns null if there is no match. That is why `getAttachedJavadoc()` works with Javadoc 8, but fails with Javadoc 11.

Can you please fix it?

**Comment by iloveeclipse** [comment]
Should be fixed for Java >= 17 via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2369.
