### ISSUE TITLE
An enum within a record will lead to "unfixable" import warnings

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.core#869]
If you have the record
```
public record EclipseEnumWithinRecord(long id, MyEnum type) {

    public enum MyEnum {
	A, B;
    }
}
```
then Eclipse will automatically add the import statement
```
import EclipseEnumWithinRecord.MyEnum;

public record EclipseEnumWithinRecord(long id, MyEnum type) {

    public enum MyEnum {
	A, B;
    }
}
```
This will be shown as a warning ("The import 'EclipseEnumWithinRecord.MyEnum' is never used"). This is true, but when I remove the import then "Organize imports" will re-add the import.

=> I'm forced to add a `@SuppressWarnings("unused")` to the class.

**Comment by srikanth-sankaran** [comment]
You need a package declaration to see the problem I think:

```
package p;

record A( int v, B b ){
    record B( String n ){}
}
```

Now organize imports will introduce the unused import with a warning.

**Comment by srikanth-sankaran** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/869
