### ISSUE TITLE
OutOfMemory during building workspace after upgrade to 2023-03

### ISSUE THREAD

**Issue by AlBundy33** [eclipse-jdt/eclipse.jdt.core#871]
Today I've upgraded my installation vom 2022-06 (4.24) to 2023-03 (4.27)

After the upgrade a full build was started and after some time my complete system did not respond anymore becuase eclipse used 100% of my cpu

After killing eclipse I've seen an "OutOfMemoryError: Java heap space" in the logs so maybe my system was unresponsive because of the garbage collector.
-> There where no exceptions before if I remember correctly but a lot after the OutOfMemory (but I think those where subsequent errors due to the OOM)

Eclipse was started with -Xmx3G and with 2022-06 I had no issues with that.

For now I've restored trhe previous version and the workspace.
Feel free to ask if you need more informations - then I'll try to setup a dedicated workspace.

**Comment by trancexpress** [comment]
Are you able to take memory snapshots with 2022-06 and 2023-03, compare and list the differences? If not, making the workspace available as an archive somewhere would help with analysis.

**Comment by AlBundy33** [comment]
"Unfortunately" these are only internal projects.
But the good news are that I can reproduce it with an attached JProfiler.
With 2023-03, a fresh workspace and an imported mid-size-project it looks like this.
![image](https://user-images.githubusercontent.com/6294586/226412962-c25cac49-4ed3-4712-a502-d684f5858e56.png)

In the screenshot the GC Activity goes down after some time - this does not happen in my large workspace (or at least I didn't wait that long).

I've also added `-XX:+HeapDumpOnOutOfMemoryError` to my eclipse.ini - the file is over 5GB.
I can check with MAT what are the leak suspects.

**Comment by AlBundy33** [comment]
the instance is currently showing this messages:
![image](https://user-images.githubusercontent.com/6294586/226414381-39377cb7-7007-4d01-8c31-965f9b5b2a16.png)

this is the end of the logfile
```
!ENTRY org.eclipse.lsp4e 4 0 2023-03-20 17:55:13.980
!MESSAGE TimeoutException
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$10(LanguageServerWrapper.java:519)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

!ENTRY org.eclipse.core.jobs 4 2 2023-03-20 17:55:15.312
!MESSAGE An internal error occurred during: "Initialize Language Servers for MANIFEST.MF".
!STACK 0
java.lang.OutOfMemoryError: Java heap space

!ENTRY org.eclipse.ui.monitoring 4 0 2023-03-20 17:55:15.315
!MESSAGE UI freeze of 1,6s at 17:52:05.653
(no stack samples were collected because the monitoring thread starved for CPU)

!ENTRY org.eclipse.ui.monitoring 4 0 2023-03-20 17:55:15.702
!MESSAGE UI freeze of 1,5s at 17:52:55.461

!ENTRY org.eclipse.core.jobs 4 2 2023-03-20 17:55:16.403
!MESSAGE An internal error occurred during: "Building".
!STACK 0
java.lang.OutOfMemoryError: Java heap space

!ENTRY org.eclipse.lsp4e 4 0 2023-03-20 17:55:23.650
!MESSAGE TimeoutException
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$10(LanguageServerWrapper.java:519)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

My project has also a lot of errors and warnings
![image](https://user-images.githubusercontent.com/6294586/226414836-1d7fd603-dcc6-4831-bf56-b618dd040bd0.png)
but this is fine because Errors came from a wrong target platform (test-project is a rcp-application) and warnings a because of missing generics, deprecated methods and so on (because the application exists since java 7)

**Comment by trancexpress** [comment]
It would be great if you can diff 2 dumps (when the build still worked with 3GB heap and now), that should show where consumption increased.

**Comment by AlBundy33** [comment]
Tested with this version https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2023-03/R/eclipse-rcp-2023-03-R-win32-x86_64.zip and fresh workspace

**Comment by AlBundy33** [comment]
I've loaded the heapdump into MAT and the leak-suspects are
```
The class "org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant", loaded by "org.eclipse.lsp4e", occupies 1.678.750.376 (52,42 %) bytes. The memory is accumulated in one instance of "java.util.HashMap$Node[]", loaded by "<system class loader>", which occupies 1.678.750.184 (52,42 %) bytes.

Keywords
org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant
org.eclipse.lsp4e
java.util.HashMap$Node[]
```
and
```
The thread org.eclipse.core.internal.jobs.Worker @ 0x7498a6f18 Worker-3: Building keeps local variables with total size 1.202.832.664 (37,56 %) bytes.

The memory is accumulated in one instance of "org.eclipse.jdt.internal.compiler.Compiler", loaded by "org.eclipse.jdt.core.compiler.batch", which occupies 1.178.283.192 (36,79 %) bytes.
The stacktrace of this Thread is available. [See stacktrace](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/pages/41.html). [See stacktrace with involved local variables](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/pages/42.html).



Keywords
org.eclipse.jdt.internal.compiler.Compiler
org.eclipse.jdt.core.compiler.batch
org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.cleanUp()V
AbstractImageBuilder.java:276
org.eclipse.jdt.internal.core.builder.BatchImageBuilder.cleanUp()V
BatchImageBuilder.java:207
org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build()V
BatchImageBuilder.java:95
org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll()V
JavaBuilder.java:273
[Details »](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/pages/35.html)
```


I did also a leak suspect analysis with the 2022-06  but created the heapdump "somewhere" during build.
In this dump the first leak suspects are
```
One instance of "org.eclipse.core.internal.dtree.DeltaDataTree" loaded by "org.eclipse.core.resources" occupies 533.999.000 (33,54 %) bytes. The memory is accumulated in one instance of "org.eclipse.core.internal.dtree.AbstractDataTreeNode[]", loaded by "org.eclipse.core.resources", which occupies 533.998.952 (33,54 %) bytes.

Keywords
org.eclipse.core.internal.dtree.DeltaDataTree
org.eclipse.core.resources
org.eclipse.core.internal.dtree.AbstractDataTreeNode[]

[Details »](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/pages/21.html)
```
and
```
One instance of "org.eclipse.jdt.internal.core.search.indexing.IndexManager" loaded by "org.eclipse.jdt.core" occupies 165.611.792 (10,40 %) bytes. The memory is accumulated in one instance of "java.lang.Object[]", loaded by "<system class loader>", which occupies 155.021.032 (9,74 %) bytes.

Keywords
org.eclipse.jdt.internal.core.search.indexing.IndexManager
org.eclipse.jdt.core
java.lang.Object[]

[Details »](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/pages/37.html)
```
But bot with much less memory.

**Comment by AlBundy33** [comment]
and JProfiler shows this
![image](https://user-images.githubusercontent.com/6294586/226421241-f2c1ebab-92a2-45fd-979e-27652d4a2549.png)

old.hprof is from my default-workspace with all projects and eclipse 2022-06 where I've started a full build for my test-project

eclipse.bin is the heapdump of eclipse 2023-03 after the OutOfMemoryError.
-> The imported projects is the same as in the step above

**Comment by trancexpress** [comment]
Does JProfiler show which classes are holding the top 6 in this list?

**Comment by AlBundy33** [comment]
JProfiler unfortunetely not but EclipseMemoryAnalyzer

Class Name | Shallow Heap | Retained Heap
-- | -- | --
java.util.HashMap$Node[4096] @ 0x7c2b771d0 | 16.400 | 1.678.750.184
table java.util.HashMap @ 0x7c743c380 | 48 | 1.678.750.232
map java.util.HashSet @ 0x7c743c370 | 16 | 1.678.750.248
SUBMITTED_JOBS class org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant @ 0x7c743c2f8 | 8 | 1.678.750.376
<class> org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant @ 0x7c7c14c88 | 16 | 144
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7fe6db8b8 | 112 | 288
<Java Local>, currentJob org.eclipse.core.internal.jobs.Worker @ 0x74f2c0940 Worker-4: Initialize Language Servers for plugin.xml Thread | 120 | 6.384
job org.eclipse.ui.internal.progress.ProgressManager$JobMonitor @ 0x7fe6db638 » | 32 | 32
Total: 2 entries |   |  
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7fe9f79d8 » | 112 | 288
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7fee8fd60 » | 112 | 288
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7ff5fa718 » | 112 | 288
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7ff988ec8 » | 112 | 288
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7ffb9a920 » | 112 | 376
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7ffbb7a50 » | 112 | 288
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7ffc1b298 » | 112 | 288
this$0 org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2 @ 0x7ffebeae8 » | 112 | 288
Total: 9 entries |   |  
[0] java.lang.Object[49] @ 0x793fdbbe0 » | 216 | 5.976

**Comment by trancexpress** [comment]
Its odd that the diff shows an increase in `TreeMap` objects and `TreeMap` nodes... not the `HashMap` nodes as seen in the dump from the newer Eclipse version. Just to be sure both versions are the same type of IDE, can you paste the "header" contents of the about dialog? Main menu -> Help -> About ...

E.g. for the SDK this is e.g.:

```
Eclipse SDK
Version: 2023-03 (4.27)
Build id: I20230211-0330
```

Anyway, @gayanper are you aware of any changes in `lsp4e` that could lead to more memory consumption?

**Comment by trancexpress** [comment]
Seems like this commit fits the time frame: https://github.com/eclipse/lsp4e/commit/8775fa82e5fc440772363b242b78202ea0d1ba35#diff-8e21697c4a1f40f67124b21910baf0e9e3729e144bca3215c7e8732cfa34f0e2

That code is now reworked, but I assume the respective commit has not made it in 2023-03 (somehow): [8f9220cc9211dc15e0c9a73e03d238e12284454a](https://github.com/eclipse/lsp4e/commit/8f9220cc9211dc15e0c9a73e03d238e12284454a#diff-8e21697c4a1f40f67124b21910baf0e9e3729e144bca3215c7e8732cfa34f0e2)

**Comment by AlBundy33** [comment]
![image_20230320202331](https://user-images.githubusercontent.com/6294586/226444939-108fd3de-0bd6-4632-a25d-8bad3cc83718.png)
![image_20230320202256](https://user-images.githubusercontent.com/6294586/226444946-f5e5a7d0-3b0a-43e6-89d8-b8fe5beade41.png)
Luckily I did some screenshots for a colleague today 😄 

I can test a nightly build if you think this is already fixed.
-> but I would need a link where I can find the downloads

**Comment by AlBundy33** [comment]
Downloaded eclipse-SDK-I20230320-1800-win32-x86_64.zip from here
https://download.eclipse.org/eclipse/downloads/index.html

added this at the beginning of the eclipse.ini
-data
home\workspace
-configuration
home\configuration

this at the end
-Duser.home=C:\temp\home

and change Xmx to -Xmx3G

After that I've startet Eclipse and installed lsp4e from this update site
https://download.eclipse.org/lsp4e/releases/latest/


Now I've imported my test-project -> compiled without OutOfMemory
Added another large project -> compiled without OutOfMemory

![image](https://user-images.githubusercontent.com/6294586/226546476-ec4fff68-ad89-4f81-9949-414413551b28.png)

Next I'll try 2023-03 mit updated lsp4e

**Comment by AlBundy33** [comment]
At first I've used a clean eclipse again (without updating lsp4e)
![image](https://user-images.githubusercontent.com/6294586/226554498-2172b46e-6a14-4f99-90da-d2ed0193e133.png)

**Comment by AlBundy33** [comment]
Updated lsp4e looks promising...
![image](https://user-images.githubusercontent.com/6294586/226558106-b0ebd59e-9e62-4b67-be04-69b229a16804.png)
![image](https://user-images.githubusercontent.com/6294586/226558164-4387760f-e6ac-47d5-8b29-14e66e401fa0.png)
-> Here I've already added two large projects

I think I'll try to update my main installation again now...

**Comment by AlBundy33** [comment]
I didn't switch because all other informations are already here and I hope that this issue is solved and I can just add success-message in some minutes.

If there is still an issue I would move to lsp4e

**Comment by AlBundy33** [comment]
But the diff would explain why the build didn't finish on a colleagues PC.
-> he has more RAM and works on Linux so instead of getting an OutOfMemory his builds may wait for the submitted jobs.

**Comment by AlBundy33** [comment]
Updating lsp4e seems to fix the OutOfMemory
![image](https://user-images.githubusercontent.com/6294586/226582307-bd771c2e-fb93-4adf-a2ad-91ef8c2cb6b6.png)
-> This is the workspace with all of my projects

Thanks for your help and sorry for blaming jdt 😄

**Comment by trancexpress** [comment]
Alright, thanks for also opening https://github.com/eclipse/lsp4e/issues/563.
