### ISSUE TITLE
Update bundles to Java 17

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#883]
There are many bundles in platform which require now Java 17 and so we have bundles that depend on those but still running with Java 11 settings.

We should change that and bump bundle settings / versions etc.

I plan to provide changes, once BETA_JAVA20 branch is merged to master.

**Comment by iloveeclipse** [comment]
@mpalat, @jarthana : I assume you plan to merge BETA_JAVA20 branch soon? Do you have concrete plans when you want merge it?

**Comment by jarthana** [comment]
Yes, it's planned. But unlikely to happen today. Possibly tomorrow. We don't have people who can do it for jdt.debug and jdt.ui.
If there are anyone who's interested in doing the merge, that's fine with me.

**Comment by iloveeclipse** [comment]
This is actually an good example of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/597.
I would like to help but have no idea where to start because I have no clue about "special" handling of BETA_JAVA branches.

**Comment by jarthana** [comment]
> This is actually an good example of #597. I would like to help but have no idea where to start because I have no clue about "special" handling of BETA_JAVA branches.

Nothing special here. This is just another merge followed by bundle version changes if any on master. Just that it's easier if someone who understand the code in respective repository does it. 

We don't have to do anything on the beta branch anymore. It was already merged from R4_7. And we had the last build off that branch with mostly successful test runs.
https://download.eclipse.org/eclipse/downloads/drops4/Y20230321-1000/testResults.php

**Comment by iloveeclipse** [comment]
> Nothing special here. 

For those who knows the (unwritten) process, yes.

> We don't have to do anything on the beta branch anymore. 

OK, so the plan would be:

- (not needed) update BETA_JAVA20 from master on all jdt.ui / jdt.debug / jdt.core
- merge each repo back to master
- fix bundle versions in manifest/pom files
- set PR's, merge & run I build to see any issues

I will try to do this today.

**Comment by jarthana** [comment]
> > Nothing special here.
> 
> For those who knows the (unwritten) process, yes.

A merge is a merge. I don't see much to document there :) 

> > We don't have to do anything on the beta branch anymore.
> 
> OK, so the plan would be:
> 
>     * (not needed) update BETA_JAVA20 from master on all jdt.ui / jdt.debug / jdt.core
> 
>     * merge each repo back to master
> 
>     * fix bundle versions in manifest/pom files
> 
>     * set PR's, merge & run I build to see any issues
>
> I will try to do this today.

Sounds about right. We just need to make sure we do all these three repos together before the build, lest causing the build to fail due to missing dependencies between Core and Debug/UI. So, go for it. If you can't spare time for it today, I will try to pick this up my morning tomorrow.
