### ISSUE TITLE
Incorrect behavior of the possible static method check for generic parameters

### ISSUE THREAD

**Issue by sflorczy** [eclipse-jdt/eclipse.jdt.core#89]
Overview:
![image](https://user-images.githubusercontent.com/93647744/169048532-5dca1093-3cac-4968-a7b3-cb36a442d3bd.png)
![image](https://user-images.githubusercontent.com/93647744/169047557-1dd72fa1-f5a1-4086-9f1d-a7b1d7052ba3.png)

Correct:
![image](https://user-images.githubusercontent.com/93647744/169047913-dfac6ed2-4150-408c-b7ea-9173b69eed93.png)

Incorrect (suppress warning should not be reported):
![image](https://user-images.githubusercontent.com/93647744/169047243-5feab5fb-e916-4b12-8df8-a2c9cd9c4c98.png)

Incorrect (possible static warning should be reported):
![image](https://user-images.githubusercontent.com/93647744/169047817-74003d85-183e-44bf-9dfd-007065a2fc00.png)

**Comment by jarthana** [comment]
This is result of our recent work via https://bugs.eclipse.org/bugs/show_bug.cgi?id=413873

Will take a look.

**Comment by iloveeclipse** [comment]
> This is result of our recent work via https://bugs.eclipse.org/bugs/show_bug.cgi?id=413873

Sorry for that, it looked simple enough :-)

> Will take a look.

Thank you.

**Comment by iloveeclipse** [comment]
@jarthana : I assume this issue can be closed now after #90 is merged ?

**Comment by jarthana** [comment]
@sflorczy when you have a moment, could you please grab the latest build and verify the fix? TIA!

**Comment by sflorczy** [comment]
![image](https://user-images.githubusercontent.com/93647744/169979545-44c7f1a5-ea67-4324-b6fa-e1b2f2080b35.png)

![image](https://user-images.githubusercontent.com/93647744/169979725-8bd9b294-cfd7-4049-bb21-eb30aaa74a97.png)

Thank you. Looks good.
