### ISSUE TITLE
references search can't find StackWalker

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#902]
Using I20230323-0850 build.

- have `org.eclipse.ui.editors` bundle imported as source in the workspace
- Go to `org.eclipse.ui.texteditor.MarkerAnnotationPreferences.checkAccess()`.
- Right click on `StackWalker` -> search for references
- Bug: nothing found in `org.eclipse.ui.editors`
- Right click one line below on `.getInstance()` -> search for references
- Correct: match found in `org.eclipse.ui.editors`

**Comment by iloveeclipse** [comment]
@trancexpress : FYI

**Comment by trancexpress** [comment]
@iloveeclipse there is no `StackWalker` use in `MarkerAnnotationPreferences`? Were you reviewing some PR maybe?

**Comment by trancexpress** [comment]
Snippet to reproduce with:

```
public class Test {
	public static void main(String[] args) {
		StackWalker.getInstance().forEach(s -> System.out.println(s));
	}
}
```

Works with:

```
Eclipse SDK
Version: 2022-12 (4.26)
Build id: I20221123-1800
```

Doesn't work with:

```
Eclipse SDK
Version: 2023-03 (4.27)
Build id: I20230211-0330
```

Probably one of the recent search  fixes broke this.

**Comment by trancexpress** [comment]
Bisection leads to: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/8844381127d65995e0c01ae2ce1d91ca0bdc6707

Reverting the commit on top of current `master` "fixes" the bug.

So this is a regression from #532.

**Comment by iloveeclipse** [comment]
Thanks Simeon for bisecting.
@gayanper : could you please check this regression?

**Comment by gayanper** [comment]
I can have a look at it this weekend. Meanwhile @trancexpress could try with switching off the metaindex ? Then we can be sure that its because of missing information in metaindex rather than a logic issue in the new code.

**Comment by gayanper** [comment]
> > I can have a look at it this weekend. Meanwhile @trancexpress could try with switching off the metaindex ? Then we can be sure that its because of missing information in metaindex rather than a logic issue in the new code.
> 
> 
> 
> I assume you mean running Eclipse with `-Dorg.eclipse.jdt.disableMetaIndex=true`. In that case, yes, the bug is gone with this system property.

Have you also tried reindexing the workspace ?

Because prior to the fix you found, there was a improvement for metaindex to include some missing type information for reference search. That improvement actually increment the index version so that when that change is deployed we should have a workspace reindex happening, may be that didn't worked.

**Comment by trancexpress** [comment]
> Have you also tried reindexing the workspace ?

I'm reproducing the bug with a clean workspace, a new Java project and copy-pasted snippet. There shouldn't be any index to rebuild.

**Comment by gayanper** [comment]
@testforstephen @iloveeclipse please check the PR and let me know if you find any issues.

**Comment by iloveeclipse** [comment]
Fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/907
