### ISSUE TITLE
Autocomplete does not work for java.lang.reflect.ParameterizedType when using instanceof pattern matching.

### ISSUE THREAD

**Issue by yeah-boi** [eclipse-jdt/eclipse.jdt.core#906]
See image below:

![image](https://user-images.githubusercontent.com/30007588/227707023-c4c7db91-7525-4046-9008-7fd2465114cc.png)

**Comment by yeah-boi** [comment]
I'm using:

Version: 2022-12 (4.26.0)
Build id: 20221201-1913

**Comment by srikanth-sankaran** [comment]
This works on master. Closing as not reproducible.
