### ISSUE TITLE
Class 'ElementsImpl9' uses @Override for methods not present in base class

### ISSUE THREAD

**Issue by kriegaex** [eclipse-jdt/eclipse.jdt.core#908]
@jarthana: After merging in the Java 20 upstream changes into AspectJ and trying to compile them, I get the following errors: 

```text
[ERROR] error at public javax.tools.JavaFileObject getFileObjectOf(Element element) {
[ERROR]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.eclipse.jdt.core.compiler.batch\src\org\eclipse\jdt\internal\compiler\apt\model\ElementsImpl9.java:210:0::0 The method getFileObjectOf(Element) of type ElementsImpl9 must override or implement a supertype method
[ERROR] error at TypeElementImpl outer = (TypeElementImpl) getOutermostTypeElement(element);
[ERROR]                                                    ^^^^^^^^^^^^^^^^^
[ERROR] org.eclipse.jdt.core.compiler.batch\src\org\eclipse\jdt\internal\compiler\apt\model\ElementsImpl9.java:220:0::0 The method getOutermostTypeElement(Element) is undefined for the type ElementsImpl9
[ERROR] error at public boolean isCanonicalConstructor(ExecutableElement e) {
[ERROR]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.eclipse.jdt.core.compiler.batch\src\org\eclipse\jdt\internal\compiler\apt\model\ElementsImpl9.java:296:0::0 The method isCanonicalConstructor(ExecutableElement) of type ElementsImpl9 must override or implement a supertype method
[ERROR] error at public boolean isCompactConstructor(ExecutableElement e) {
[ERROR]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.eclipse.jdt.core.compiler.batch\src\org\eclipse\jdt\internal\compiler\apt\model\ElementsImpl9.java:301:0::0 The method isCompactConstructor(ExecutableElement) of type ElementsImpl9 must override or implement a supertype method
```
Inspecting class `ElementsImpl9` and its base class `ElementsImpl`, I see that those alleged super methods simply do not exist. Are they supposed to, or should the `@Override` annotations simply be removed? Maybe you compiled with a setting that ignores problems like that, but with my compiler settings, I am seeing them.

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/8fd34a894917855e2780c786a402f90785336d29/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/apt/model/ElementsImpl9.java#L209-L210

---

Furthermore, one compilation error says that the method called here does not exist:

https://github.com/eclipse-jdt/eclipse.jdt.core/blob/802a7b27b14c2b4356d9181a469906a7d428c570/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/apt/model/ElementsImpl9.java#L220

Where is it hiding?

**Comment by jarthana** [comment]
Those methods were introduced in Java 20, which we included in the javax20api.jar. Hence the compilation went through. In hindsight, I understand that outside this build set up, the compilation will fail. I can remove this if you can confirm this to be your case.

**Comment by kriegaex** [comment]
Actually compiling the module using a JDK 20 instead of a JDK 17 solved both problems mentioned in this issue. Thanks for your input concerning javax20api. That was the clue I needed - stupid me! Feel free to mark this issue as invalid.
