### ISSUE TITLE
Error while compiling modular application

### ISSUE THREAD

**Issue by roman-kitko** [eclipse-jdt/eclipse.jdt.core#921]
Hello, 
I am facing strange error while trying to compiler modularized project (module-info) in eclipse.
I have pushed the code to reproduce with into github repo : https://github.com/roman-kitko/vpda-eclipse-bug

How to reproduce :
1. git clone https://github.com/roman-kitko/vpda-eclipse-bug.git
2. In eclipse new workspace import all projects as existing maven project
3. Press Alt + F5 (select all)to refresh and reload
4. Go to class org.vpda.common.launcher.jetty.JettyLauncher
5. Here you can see strange compiler errors 
Description	Resource	Path	Location	Type

The method execute(CommandExecutor, CommandExecutionEnv, CommandEvent) of type new Command<Object>(){} must override or implement a supertype method	JettyLauncher.java	/vpda-common-launcher-jetty/src/main/java/org/vpda/common/launcher/jetty	line 177	Java Problem

6. When you are in class and you just add few empty spaces and press CTRL+S for compile(repeat more times), now the error disappears.
7. Can Again do full maven reload and the error will be there again

In maven command line, all can compile well

My eclipse detail :

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2023-03 (4.27.0)
Build id: 20230309-1520
OS: Linux, v.5.10.0-21-amd64, x86_64 / gtk 3.24.24, WebKit 2.38.5
Java vendor: Debian
Java runtime version: 17.0.6+10-Debian-1deb11u1
Java version: 17.0.6

Thx for help
Roman

**Comment by iloveeclipse** [comment]
Could you please try to reduce your problem to a small self contained project? 
This would greatly speedup bug analysis.

Common approach to do so is to start removing all the unneeded dependencies and code around as long as error remains.

**Comment by roman-kitko** [comment]
The repository  I have created is only subset of the project. 
I can try to remove unneeded modules. 
But still do not expect like 2 modules.
Will do that Tomorrow, push changes and let you know

**Comment by roman-kitko** [comment]
I reduced number of modules to 16. 
What I also found, the problem is only in 
JettyLauncher.registerShutdown method. If I clean  its body (and java imports), the the error is gone.
Also when you do full maven reload and then you do several CTRL+S with dummy changes, you can get different  compiler errors.

**Comment by roman-kitko** [comment]
![Screenshot from 2023-03-29 21-44-31](https://user-images.githubusercontent.com/10545043/228650518-714f9303-9c38-4bff-8bc3-a9d702bfcd85.png)

**Comment by roman-kitko** [comment]
I am closing the issue.
I found workaround here.
The error occurs when using inner class or lamda expression, then type is not accessible. When using normal class, it works.

There is still some bug in compiler and 'build process is in-deterministic here, but it is pretty hard to simulate on smaller project.
