### ISSUE TITLE
[20] foreach template not proposed for completion after a foreach with record pattern

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.core#923]
The following code demonstrates this problem:

public static void foo(List<R> rList) {
	forea|   // template proposed here
	for (R(Integer abcs) : rList) { // incorrect source range
		System.out.println(abcs); 
	}  
	forea|  // template not proposed
} 

I suspect this is because we fail to clean up elements pushed to the element kind stack in presence of the foreach. This results in CompletionContext.TL_STATEMENT_START not being used for the context and eventually, we figure this is not the right place to propose foreach template.

**Comment by srikanth-sankaran** [comment]
Closing this as not planned - use of record patterns in foreach was withdrawn by JEP 440
