### ISSUE TITLE
[20][pattern switch] SwitchPatternTest.testBug575571_1 failure

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#933]
Ref: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/635 - left over test failure - 
Issue: no warning for default even after the option is on
testBug575571_1

This one particular test failure was overlooked while fixing the rest. 
Enable this after this is fixed

**Comment by srikanth-sankaran** [comment]
@mpalat - is this still open ? Which file is test from ? I don't get any hits for a search

**Comment by srikanth-sankaran** [comment]
> @mpalat - is this still open ? Which file is test from ? I don't get any hits for a search

@mpalat - could you answer this for me please ?? TIA

**Comment by mpalat** [comment]
onto this now..
