### ISSUE TITLE
Regression: call hierarchy has zero results for JARs with module-info

### ISSUE THREAD

**Issue by rdicroce** [eclipse-jdt/eclipse.jdt.core#935]
Steps to reproduce:
1. Create a project that has sqlite-jdbc 3.41.2.1 on its classpath. I used a Maven project but presumably this will happen regardless of the project type.
2. Set the project's JRE to Java 8.
3. Open the SQLiteConfig class.
4. Open the call hierarchy for the isExplicitReadOnly() method. Note that there are several results.
5. Switch the project's JRE to Java 11. (Also seen on 17. Presumably any version >= 9 will cause this.)
6. Open the call hierarchy again. Note that now, there are zero results.

The same thing happens with the latest HikariCP JAR. I'm guessing the common factor is that both of them have module-info in the root of the JAR.

This is a regression in Eclipse 2023-03. It works fine in 2022-12.

**Comment by trancexpress** [comment]
Still works in:

```
Eclipse SDK
Version: 2023-03 (4.27)
Build id: I20230207-1800
```

**Comment by dmatej** [comment]
Hmm, that is probably the issue I am experiencing now in 4.28. I am looking forward to 4.29, thank you!
