### ISSUE TITLE
[XX]  Primitive types in patterns, instanceof, and switch (First Preview)

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#942]
Ref : https://openjdk.org/jeps/8288476
Enhance pattern matching by allowing primitive type patterns to be used in all pattern contexts. Align the semantics of primitive type patterns with instanceof. Extend switch to allow primitive constants as case labels. This is a [preview language feature](https://openjdk.org/jeps/12).
Also ref: https://bugs.openjdk.org/browse/JDK-8288476 to check the target periodically

**Comment by srikanth-sankaran** [comment]
Does this need to stay open ? @mpalat ??

**Comment by mpalat** [comment]
closed. thanks @srikanth-sankaran
