### ISSUE TITLE
ASTRewriteFlattener generaing invalid code: extra "yield" in enhanced switch statement

### ISSUE THREAD

**Issue by thanhminhmr** [eclipse-jdt/eclipse.jdt.core#949]
ASTRewriteFlattener introduces an additional `yield` in the enhanced switch statement during the process of flattening the ASTNode, causing the generated code to become invalid.

For example, this code:
```java
switch (string) {
	case "1" -> System.out.println("This returns void!");
	case "2" -> System.out.println("This also returns void!");
	default -> throw new AssertionError();
}
```
Will become this:
```java
switch (string) {
	case "1" -> yield System.out.println("This returns void!");
	case "2" -> yield System.out.println("This also returns void!");
	default -> throw new AssertionError();
}
```

**Comment by thanhminhmr** [comment]
I've submitted a patch to address this bug, and according to Jenkins, all tests have passed. Would someone kindly review it?

**Comment by mpalat** [comment]
@thanhminhmr : I see multiple commits - can you raise a PR -  will review the same. Thanks

**Comment by thanhminhmr** [comment]
> @thanhminhmr : I see multiple commits - can you raise a PR - will review the same. Thanks

There is currently PR #950, I've already commited the fix and tests necessary. Can you review it? Thanks.

**Comment by subyssurendran666** [comment]
@thanhminhmr I have reviewed your PR and added a few additional lines of code. However, I noticed that your forked branch is behind the master branch. Could you please rebase the "thanhminhmr" branch with the master branch?

**Comment by thanhminhmr** [comment]
> @thanhminhmr I have reviewed your PR and added a few additional lines of code. However, I noticed that your forked branch is behind the master branch. Could you please rebase the "thanhminhmr" branch with the master branch?

I've rebased my branch with the current master branch. Could you check it out? Thanks.
