### ISSUE TITLE
org.eclipse.jdt.core.dom.AST class is not updated for jdk20

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#953]
When trying to construct a AST object with java source level of 20, it fails with NPE. When looking at the source it seems the `getApiLevelMapTable` is not updated for java 20

**Comment by srikanth-sankaran** [comment]
@jarthana - Should this stay open ??

**Comment by jarthana** [comment]
> @jarthana - Should this stay open ??

I guess not.
