### ISSUE TITLE
Bug: module binding error message does not render correctly in diagnostics

### ISSUE THREAD

**Issue by ascopes** [eclipse-jdt/eclipse.jdt.core#954]
```
8389908 - Cannot bind message for problem (id: 1300) "{0} cannot be resolved to a module" with arguments: {}
```

Appears that https://sourcegraph.com/github.com/eclipse-jdt/eclipse.jdt.core@17d644ffc8a0fc262a20baaac0e390b55076a088/-/blob/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/problem/ProblemReporter.java#L11448 is not passing an array of problem arguments into the handler, despite one parameter being required.

I'll put a PR up to fix this.

**Comment by iloveeclipse** [comment]
The new test fails: https://download.eclipse.org/eclipse/downloads/drops4/I20230412-0120/testresults/html/org.eclipse.jdt.compiler.tool.tests_ep428I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
