### ISSUE TITLE
Nightly/weekly/snapshot releases

### ISSUE THREAD

**Issue by MartinWitt** [eclipse-jdt/eclipse.jdt.core#967]
Hey,

Have you considered offering nightly, weekly, or snapshot releases? You now deliver a release every several months. The option to start implementing new java features early will be beneficial for developing spoon. Even though the code is already there and usable for eclipse IDE, there is a wait between a JDK release and the JDT release for a new Java version. The development of Java 20 features in Spoon is now halted by this bug (https://github.com/eclipse-jdt/eclipse.jdt.core/pull/956).

Due to the parent pom's inability to be resolved, using jitpack for your git tags is not possible. It appears that there is a long-standing problem with building this project using Maven (https://bugs.eclipse.org/bugs/show_bug.cgi?id=540756).

**Comment by iloveeclipse** [comment]
You probably mean "offering **on maven central**"?

Note that there is always latest nightly build of SDK/ECJ compiler available at https://download.eclipse.org/eclipse/downloads/ as well as milestone builds, same also on the update site which is https://download.eclipse.org/eclipse/updates/4.28-I-builds/ as of today (during 4.28 development).

So we (Advantest) run all of our internal product tests that build on SDK every week using latest nightly SDK sources/binaries and are able to find/report/fix any regression we discover latest in a week time frame.

And yes, there were some discussions about providing snapshot versions of SDK packages on maven but the main issue is the manpower we don't have.

I believe @merks & @laeubi are more familiar with the current state of the maven publishing for Platform artifacts in general, so maybe they could give here some pointers how one could contribute to this process.

**Comment by merks** [comment]
Snapshots are published here daily:

https://repo.eclipse.org/content/repositories/eclipse-snapshots/

**Comment by iloveeclipse** [comment]
Thanks Ed!
I've updated jdt core readme: https://github.com/eclipse-jdt/eclipse.jdt.core#snapshot-builds

**Comment by iloveeclipse** [comment]
And releng readme too: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator
