### ISSUE TITLE
Expected type of the first parameter is not populated in context for constructors

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.core#979]
Expected type of the first parameter is not populated in context for constructors.

```
public class App {
      public App(List<String> names) {}

     public static void foo() {
     App a = new App(|);  
     }

}
```

completions on `App(|` must populate `List<String>` as a expected type like it does for method invocations.

**Comment by trancexpress** [comment]
@gayanper can you explain what completion is expected to do here, but doesn't? Some short screen recording with and without the fix would be great. I tried invoking completion with/without the change but I don't see a difference, I assume I'm doing something wrong.

**Comment by gayanper** [comment]
Without the fix completions at constructor first argument

https://user-images.githubusercontent.com/7471994/235503331-fa21c1ac-0f6f-44f0-8bc8-20b440a07ac3.mp4

**Comment by gayanper** [comment]
With the fix at the same position

https://user-images.githubusercontent.com/7471994/235503397-cd62bed3-48bd-472f-9d2a-90984d14ca2c.mp4
