### ISSUE TITLE
Wayland support in experimental state despite being introduced in stable releases

### ISSUE THREAD

**Issue by Ricky-Tigg** [eclipse-jdt/eclipse.jdt.core#990]
_Eclipse IDE for Java Developers_ | **v.:** 2023-03 (4.27.0) | **Build ID:** 20230309-1520 | **Linux kernel v.:** 6.2 | **Gnome v.:** 44.0

Hello. What can be learned from a **first** usage? Well. The Wayland support appears to be so low that it is reasonable to interpret it as being still in **experimental** state. What did you think that could be most likely to happen with a fair quality software seeking user. The first use shall also be the last. That is what an experience as bad as it is can do.

Observations:
- Some windows part of the operation covered by the _Eclipse installer_ are **missing their title bar**.
- Those windows **cannot be moved nor resized according to any axe**. As a result, with my current screen resolutions, the whole content of some windows could not be exhibited; for instance the _Install_ element which then prevented the installation of this application. I had to switch to _Gnome on X.org_ in order to get it installed.

Once installed, switching back to _Wayland_ in order to figure out whether the experience can go worse. And guess; it can.
```
$ ./eclipse/java-2023-032/eclipse/eclipse
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
13:55:11.879 [main] DEBUG org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob - Queued refresh request: []
```
- Unlike applications Firefox, LibreOffice and many others that are able to fill the **whole screen's surface**, this application is not yet. Despite the capability of optimization of the workspace is one of the key requirement of modern software in order to provide professional user experience.. 

Since there is no choice but to learn this application in bad working-condition, then let's keep on testing so.

In _Help_ menu
- Select _Check for update_ | Resultant window displayed has a title bar. Attempts to move that window invariably fails; Eventually it moves the main window instead, which triigers in terminal:

`(Eclipse:22582): Gdk-WARNING **: 12:17:37.509: Tried to unmap the parent of a popup`

- Select _Eclipse Marketplace_ | Resultant window, which has a title bar, can be moved. This selection triggers in terminal multiple iterations of this message:
```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```
- Open the rolling-menu containing the option _All markets_ and click somewhere outside the area listing the options. | **No effect**; the rolling menu remains open. Pressing <kbd>esc</kbd> does close it.

- Enlarge that window by double-clicking its title bar so it fills the available workspace. Within it, select _Help_ | That results in moving the window to the right side, while the _Help_ panel is out of screen.
- Once the panel has been made visible, double-click the window's title bar | That triggers the **disappearance** of that _Help_ panel.

At last, one more test before switching to X11.
- **Next attempts** to get that panel exhibited in that session invariably fail. 

 Obviously there is no need to be endowed with any talent to guess that this augurs an incalculable number of issues with those functionalities not tested here, and for reason. Best practices and guideline in regard to software release do exist for a reason; **to be observed**.  Now since this aspect was ignored by developers, all those issues that should have been resolved while the software was in experimental state, have finally reached stable releases. Be sure from now to take it into account.

**Comment by trancexpress** [comment]
JDT core is responsible for Java language support, such as compilation, searching, content assist and so on.

If you want you can report the issue at https://github.com/eclipse-platform/eclipse.platform.swt, where X11/Wayland support is done.

Keep in mind that SWT support on Linux doesn't have many maintainers at this point. Though this can be discussed in the SWT ticket, if you'll create one.

**Comment by Ricky-Tigg** [comment]
Wasn't in mind, until now.
