### ISSUE TITLE
12 compiler fails since Java 20 is used / I20230419-0650

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#992]
See 
https://download.eclipse.org/eclipse/downloads/drops4/I20230419-0650/testresults/html/org.eclipse.jdt.core.tests.compiler_ep428I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html

There are 12 new test fails in org.eclipse.jdt.core.tests.compiler [after the build started to use Java 20](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1033).

- NullAnnotationTests18.testBug576329
```
junit.framework.ComparisonFailure: Unexpected error running resulting class file for Main.java:
--[START]--
Error: LinkageError occurred while loading main class Main
java.lang.UnsupportedClassVersionError: Main (class file version 63.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 64.65535
---[END]---
.
----------- Expected ------------

------------ but was ------------
Error: LinkageError occurred while loading main class Main\n
java.lang.UnsupportedClassVersionError: Main (class file version 63.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 64.65535\n

--------- Difference is ----------
expected:<[]> but was:<[Error: LinkageError occurred while loading main class Main\n
java.lang.UnsupportedClassVersionError: Main (class file version 63.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 64.65535\n
]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:266)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3605)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3371)
at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest$Runner.runConformTest(AbstractRegressionTest.java:142)
at org.eclipse.jdt.core.tests.compiler.regression.NullAnnotationTests18.testBug576329(NullAnnotationTests18.java:545)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

**Comment by iloveeclipse** [comment]
Local execution works with I20230420-1800.
So test setup must be wrong.

**Comment by iloveeclipse** [comment]
OK, `UnsupportedClassVersionError: Main (class file version 63.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 64.65535`

While it sounds weird that Java 20 won't work with Java 19 class files, but exact that seem to be the case.

See 
![image](https://user-images.githubusercontent.com/964108/233599280-4102957a-cf33-41a8-8392-60d58064b85b.png)

**Comment by iloveeclipse** [comment]
Test seem to run compiler with Java 19 level (locally with 20)!
@jarthana : I guess some defaults are not updated somewhere (the test doesn't set target level, so ECJ uses some default and that seem to be still at 19, even if running on Java 20).

Any idea where?

**Comment by iloveeclipse** [comment]
Similar to #994 the tests do not fail on Jenkins because Jenkins runs tests on Java 17.
I wonder if we should switch Jenkins to run on Java 20...

**Comment by iloveeclipse** [comment]
OK, looking on https://download.eclipse.org/eclipse/downloads/drops4/I20230420-1800/testresults/consolelogs/ep428I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20_consolelog.txt I see following:

```
java-test:
     [echo] Running org.eclipse.jdt.core.tests.compiler.regression.TestAll. Result file: /home/jenkins/agent/workspace/AutomatedTests/ep428I-unit-cen64-gtk3-java20/workarea/I20230420-1800/eclipse-testing/results/ep428I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20/org.eclipse.jdt.core.tests.compiler.regression.TestAll.xml
     [echo] timout property: 7200000
     [echo] frameworkvmargs:  -Xms256m -Xmx2048m  -Djava.io.tmpdir=/home/jenkins/agent/workspace/AutomatedTests/ep428I-unit-cen64-gtk3-java20/tmp -Djava.security.manager=allow
     [echo] vmargs: -Dcompliance.jre.11=1.8,9,10,11 -Dcompliance.jre.16=1.8,11,15,16 -Dcompliance.jre.17=1.8,11,16,17
```
This matches the line I see in https://github.com/eclipse-jdt/eclipse.jdt.core/blob/ffa923ceaffa1ca90288169b610326d43e9b66db/org.eclipse.jdt.core.tests.compiler/test.xml#L60

And that is different to what we set in https://github.com/eclipse-jdt/eclipse.jdt.core/blob/ffa923ceaffa1ca90288169b610326d43e9b66db/Jenkinsfile#L35
and in https://github.com/eclipse-jdt/eclipse.jdt.core/blob/ffa923ceaffa1ca90288169b610326d43e9b66db/org.eclipse.jdt.core.tests.compiler/pom.xml#L299

So for SDK build we specify compliance for Java 11, 16 and 17 only. 

I assume if we don't specify compliance for Java 20, it looks all possible versions are tested. This explains also why do we test with Java 19 compliance on Java 20.

So the test should be disabled for 19 on 20.

**Comment by jarthana** [comment]
> I assume if we don't specify compliance for Java 20, it looks all possible versions are tested. This explains also why do we test with Java 19 compliance on Java 20.

I just tried locally to run with JRE 20 with compliances 17,18,19 and I don't see the failures. As expected, tests are not run in any compliance.
