### ISSUE TITLE
[21][pattern switch] Selector type delta

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#997]
Ref changes between last preview and this at 14.11 
The type of the selector expression must be char, byte, short, int or a reference type, or a compile-time error occurs.

**Comment by mpalat** [comment]
need to reconfirm this.

**Comment by srikanth-sankaran** [comment]
@mpalat - Should this stay open ??

**Comment by srikanth-sankaran** [comment]
> @mpalat - Should this stay open ??

@mpalat - Could you answer this please ? TIA

**Comment by mpalat** [comment]
@srikanth-sankaran - this can be closed as this is taken care.
